### ISSUE TITLE
plots are not eps ready

### ISSUE THREAD

**Issue by yipcma** [mtennekes/tmap#101]

**Comment by mtennekes** [comment]
Could you elaborate a little bit more?
This works for me:

    data(World)
    tm <- qtm(World)
    save_tmap(tm, filename = "test.eps")

**Comment by yipcma** [comment]
i'm using tm_raster and ploting in-line in an rmarkdown. When i use an eps device, it does not give proper vector output, all blurred up.

**Comment by mtennekes** [comment]
Do you have the same problems when using leaflet or mapview to draw raster map? Could you provide a reproducible working example?

**Comment by yipcma** [comment]
the issue is for print/postscript export with rasters.

**Comment by mtennekes** [comment]
This also works:

    data(land)
    tm <- qtm(land)
    save_tmap(tm, filename = "test.eps")

Please provide an example that does not work.

**Comment by yipcma** [comment]
ah i see. so save_tmap would work. right now i'm using rmarkdown with "postscript"device for figures. the in-line ones would render really poorly.

**Comment by mtennekes** [comment]
Maybe there are some rendering settings you can set for the ps device in markdown?
