### ISSUE TITLE
legend formatting by single value, without the <lower> to <higher>

### ISSUE THREAD

**Issue by yipcma** [mtennekes/tmap#102]
am curious if we can get away without the to, it's space consuming and publication unfriendly. It would be great if we can customize how the whole legend would look; in addition to customizing the <lower> and <higher> which i don't want in the first place.

**Comment by sjewo** [comment]
You can adjust the legend format with `tm_layout`:
```
tm_layout(legend.format = list(text.separator = "", text.less.than = "", text.or.more = "")
```
Additionally you can use your own formating function with `tm_layout(legend.format = list(fun=myfunction)`

For detailed information you may want to take a look at the documentation for tm_layout.

**Comment by yipcma** [comment]
thanks for the reply. wouldn't your code snippet create a doubled-cloumn of values with low and high on each row in the middle of the category, while i want boundrary values sitting at category boundary.

**Comment by mtennekes** [comment]
Ah, now I understand, I think. Do you mean https://canvas.uw.edu/courses/952982/files/28799814 ?

**Comment by yipcma** [comment]
yes indeed.

**Comment by yipcma** [comment]
@mtennekes would love to follow up on how to make it work quickly. Much appreciated.

**Comment by mtennekes** [comment]
Not easy. If we decide to implement it, we could use the continuous legend format, which is quite similar:

    data(World)
    tm_shape(World) +
    	tm_polygons("HPI", style="cont")

I'm not sure how to let users set this option: with another argument, like "legend.labels.at.breaks"? I'm not sure if it doesn't get too complicated... If you have any ideas how to tackle it, let me know.
