### ISSUE TITLE
MAP_COLORING vs MAP_COLORS

### ISSUE THREAD

**Issue by sjewo** [mtennekes/tmap#103]
I tried to use the option `col=MAP_COLORING` in `tm_fill` and got an error:
```
data(Europe)
tm_shape(Europe) + tm_fill("MAP_COLORING")
Error: Fill argument neither colors nor valid variable name(s)
```
While `col=MAP_COLORS` works:
```
data(Europe)
tm_shape(Europe) + tm_fill("MAP_COLORS")
```
Maybe just the documentation needs an update.

**Comment by mtennekes** [comment]
Thanks. Yes, it is "MAP_COLORS", but the underlying function is tmaptools::map_coloring.
