### ISSUE TITLE
install on macOS sierra

### ISSUE THREAD

**Issue by academikuser** [mtennekes/tmap#107]
install.packages("tmap")  fails due to V8 dependency
fix:
1. install old version of v8

    brew tap homebrew/versions
    brew install v8-315

2. download the tmap archive
3. install with flags

    R CMD INSTALL tmap_1.8-1.tgz --configure-args='INCLUDE_DIR=/usr/local/opt/v8-315/include LIB_DIR=/usr/local/opt/v8-315/lib'

**Comment by mtennekes** [comment]
See #149
