### ISSUE TITLE
World data plotting error

### ISSUE THREAD

**Issue by Nowosad** [mtennekes/tmap#108]
I've tried to plot a world data from the  `rnaturalearth` package. While it works great for borders, it fail for polygons. Later, I found out that I can make a plot when I remove Antarctica from the dataset. 
Is it a problem with `tmap` or it's a dataset problem?

```R
library(tmap)
library(rnaturalearth)

world_sf <- ne_countries(returnclass = 'sf')

qtm(world_sf) #works

tm_shape(world_sf) + tm_polygons(c("pop_est")) #error

world_sf2<- subset(world_sf, name!='Antarctica')
tm_shape(world_sf2) + tm_polygons(c("pop_est")) #works
```

**Comment by Robinlovelace** [comment]
I also hit the same issues and pulled lots of hair out. Probably should have reported it. Note it works in other plotting systems, making me think it's a **tmap** issue:

```r
plot(world_sf["pop_est"])
mapview::mapview(world_sf["pop_est"])
```

**Comment by sjewo** [comment]
Maybe a projection is needed for area calculation. Defining a projection removes the warning:
```{r}
library(tmap)
library(rnaturalearth)

world_sf <- ne_countries(returnclass = 'sf')
tm_shape(world_sf, projection="eck4") + tm_polygons(c("pop_est"))
```
But I have no idea, why removing Antarctica stops the warning too.

**Comment by mtennekes** [comment]
Ah, Antarctica again:-) The area size of Antarctica cannot be determined when unprojected. However, this should only matters when area sizes are used, e.g. when converting to population densities.

It's fixed now! This works:

    tm_shape(world_sf) + tm_fill("pop_est")

and this also works, but shows the population density of Antarctica as missing (unless you project it):

    tm_shape(world_sf) + tm_fill("pop_est", convert2density = TRUE)

**Comment by Robinlovelace** [comment]
Fantastic work - this will feed into our work. More soon.
