### ISSUE TITLE
Size legend is removed tmap_leaflet

### ISSUE THREAD

**Issue by ghost** [mtennekes/tmap#111]
Is there a way to keep the dot size legend when using the tmap_leaflet function? Great package!

**Comment by mtennekes** [comment]
As far as I known, only the legend with squares is supported by the leaflet package (and by the JS leaflet library). So the other legends types (for instance bubble size) are removed in the view mode.

If there is a way to show such legend directly with the leaflet package, I can easily implement it in tmap.
