### ISSUE TITLE
Make some layers default to off on tmap_leaflet load

### ISSUE THREAD

**Issue by ghost** [mtennekes/tmap#113]
I was wondering if there is a way in tmap to have the leaflet map default to selected layers turned off, instead of showing all element in the map? Thanks again for your help!

**Comment by mtennekes** [comment]
Not yet. There is a leaflet function `hideGroup` which could be used. However, I noticed that I used the shape are group. E.g. 

    tm_shape(World) + tm_polygons("HPI") + tm_dots("economy")

Will create only one clickable layer, while it makes more sense there would be two.

**Comment by tim-salabim** [comment]
maybe [this](https://github.com/r-spatial/mapview/blob/master/R/leafletControls.R#L74-L80) can be of help here?

**Comment by behrica** [comment]
I just discovered that it is possible to achieve the "hiding" of layers by combining functions from "tmap" and "leaflet" package.



```
tmap::tm_shape(...) %>%
  tmap::tm_fill(group=  ....) %>%   
  tmap::tmap_leaflet(tmap) %>% 
    leaflet::hideGroup("sumDetected") %>% 
    leaflet::hideGroup("sumBelowLOQ") %>% 
   ... hide more groups
 htmlwidgets::saveWidget("out.html")

```

The default group names are set to the variables shown by tmap, but can be overridden.

**Comment by francisbarton** [comment]
Hi, is it ok to reopen this as a feature request please?
The solution from @behrica is good, but it would be great to have an option for hideGroup built into tmap itself if possible. I had a look through various code files to see if I could work out where to make the necessary changes but I could not work out where this would be, sorry.
