### ISSUE TITLE
rotate y labes in tm_grid

### ISSUE THREAD

**Issue by malacandon** [mtennekes/tmap#114]
Hi,
I was wondering whether there is options for rotate the labels when they are inside the frame.

Many thanks in advance
Miguel

**Comment by mtennekes** [comment]
Not yet, but it certainly should be possible.

**Comment by mtennekes** [comment]
Done! Was quite easy to implement:-) I've added to argument to `tm_grid`: `labels.rot` and `labels.format`. Please let me know if it works as expected.
