### ISSUE TITLE
troubles when updated map to the latest version (ver 1.10)

### ISSUE THREAD

**Issue by malacandon** [mtennekes/tmap#115]
I used tmap and everything goes OK, but I updated tmap to the latest version and now I get this error:
**Error in grid.Call(L_convert, x, as.integer(whatfrom), as.integer(whatto),  : 
  Viewport has zero dimension(s)**

I tried several change in my script and found that  everything it's OK with: **_labels.inside.frame = TRUE_** 
tm_grid(col = "black", lwd = 0.5, labels.size = 0.002, labels.inside.frame = FALSE, alpha = 0.2,
          n.x = 5, n.y = 5)

Please could you help me to solve this.

Many thanks

Miguel

**Comment by mtennekes** [comment]
Could you provide a reproducible example that produces this error? What is the device that you are using (e.g. plotting window in RStudio, png file, pdf, ...)?

That's a very tiny label size btw ;-)

**Comment by Nowosad** [comment]
Inactive, close?
