### ISSUE TITLE
Error in tm_shape when attempting to plot RasterLayer Google image

### ISSUE THREAD

**Issue by andreaskiermeier** [mtennekes/tmap#117]
I get the following error when plotting *some* RasterLayer objects obtained from the gmap() function.
```
Error in `levels<-`(`*tmp*`, value = l) : 
  factor level [255] is duplicated
```
A minimal example is as follows - the first two maps (Camden and Adelaide) from google work, while the third (Melbourne ) fails. Note also that the image for Melbourne is downloaded as expected, but something goes wrong when running tm_shape.
```
library(tmap)
library(raster)
library(dismo)
google.map1 <- gmap("Camden, London", type = "roadmap", filename="Google1.gmap")
tm_shape(google.map1) + tm_raster()
google.map2 <- gmap("Adelaide, Australia", type="roadmap", filename="Google2.gmap")
tm_shape(google.map2) + tm_raster()
google.map3 <- gmap("Melbourne, Australia", type="roadmap", filename="Google3.gmap")
tm_shape(google.map3) + `tm_raster()
```
Any thoughts?
Thanks in advance.

**Comment by mtennekes** [comment]
Fixed now. Thanks for the bug report and the nice example using Google Maps!

**Comment by andreaskiermeier** [comment]
Thanks for the quick fix!
