### ISSUE TITLE
qtm: Error in `levels<-`(`*tmp*`, value = l) : factor level [2] is duplicated

### ISSUE THREAD

**Issue by MatthieuStigler** [mtennekes/tmap#119]
Hi

It seems `qtm` does not handle raster data with a colour legend that have repeated colour "labels" for different values? I think this arises with the recent update (1.10), and did not happened before? Try:

    library(raster)
    library(tmap)

    ##
    a <- raster(nrow=5, ncol=5)
    a[] <- rep(1:5, each=5)
    attr(a, "legend")@colortable <- rep(c("#FF6666", "#FF6666", "#FF8EAA", "#334933", "#E57026"), each=5)

    qtm(a)

Gives error: **Error in `levels<-`(`*tmp*`, value = l) : factor level [2] is duplicated**. While it works if one were to use instead: 

    attr(a, "legend")@colortable <- rep(c("#FF6666", "#FF8EAA", "#334933", "#E57026", "#267000"), each=5)
    qtm(a)

Repeated colour "labels" happen for example with the rasters from the Cropland Data layer, USDA NASS.

**Comment by mtennekes** [comment]
Thanks! This was already solved in #119, but there was still a bug in it, which is now solved.

    library(raster)
    library(tmap)

    a <- raster(nrow=5, ncol=5)
    a[] <- rep(0:4, each=5)
    attr(a, "legend")@colortable <- c("#FF6600", "#FF6600", "#FF8EAA", "#334933", "#E57026")

    # plot using raster's plot function
    plot(a)

    qtm(a) 
    # qtm uses interpolate=TRUE by default, which is useful for baselayers
    # qtm(a) is identical to tm_shape(a) + tm_rgb()
    # for tm_raster, interpolate is set to FALSE by default:
    tm_shape(a) + tm_raster()
