### ISSUE TITLE
legend.format - override for "Missing"

### ISSUE THREAD

**Issue by jlacko** [mtennekes/tmap#121]
First of all: this is a fantastic package, I really love it. Respect!

Would it be possible to add a string override for the "_Missing_" label in legend? 
Similarly as text.separator overrides the "_to_" part of the legend?

Not a major problem, but it would make localized charts a bit easier...

Thanks!

![leyenda](https://user-images.githubusercontent.com/29260421/27519576-25e2af40-59f7-11e7-82e2-f3586dd45182.png)

**Comment by mtennekes** [comment]
Thanks for your question. It can be adjusted by the `textNA` argument:

    tm_shape(World) +
    tm_polygons("HPI", textNA="Text for missing values")

**Comment by jlacko** [comment]
My bad. Thanks for making it clear.
