### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by solrepresa** [mtennekes/tmap#124]
I had some error messages:
ERROR: dependency ‘rmapshaper’ is not available for package ‘tmaptools’
* removing ‘/home/usuario/R/x86_64-pc-linux-gnu-library/3.2/tmaptools’
Warning in install.packages :
  installation of package ‘tmaptools’ had non-zero exit status
ERROR: dependency ‘sf’ is not available for package ‘mapview’
* removing ‘/home/usuario/R/x86_64-pc-linux-gnu-library/3.2/mapview’
Warning in install.packages :
  installation of package ‘mapview’ had non-zero exit status
ERROR: dependencies ‘tmaptools’, ‘mapview’ are not available for package ‘tmap’
* removing ‘/home/usuario/R/x86_64-pc-linux-gnu-library/3.2/tmap’
Warning in install.packages :
  installation of package ‘tmap’ had non-zero exit status

**Comment by Nowosad** [comment]
@solrepresa Have you tried to install the rmapshaper package? 

`install.packages("rmapshaper")
`
