### ISSUE TITLE
Classes below 0 are plotted with same color

### ISSUE THREAD

**Issue by PKullberg** [mtennekes/tmap#130]
Hi,

thanks for this great package. I think that there is a bug in the way negative values are handled. When I plot a thematic map using variables with negative values all classes below 0 area plotted with the same color.

Here is an example: 

```
library(tmap)
library(sp)

pg1 <- Polygons(srl = list(Polygon(matrix(c(0,0, 1,0, 1,1, 0,1, 0,0), ncol = 2, byrow = T))), ID = 1)
pg2 <- Polygons(srl = list(Polygon(matrix(c(0,0, 1,0, 1,1, 0,1, 0,0) + 1, ncol = 2, byrow = T))), ID = 2)
pg3 <- Polygons(srl = list(Polygon(matrix(c(0,0, 1,0, 1,1, 0,1, 0,0) + 2, ncol = 2, byrow = T))), ID = 3)
pg4 <- Polygons(srl = list(Polygon(matrix(c(0,0, 1,0, 1,1, 0,1, 0,0) + 3, ncol = 2, byrow = T))), ID = 4)
spo <- SpatialPolygons(Srl = list(pg1, pg2, pg3, pg4))
spd <- SpatialPolygonsDataFrame(spo, data.frame(val = c(-2:1)))

tm_shape(spd) + 
  tm_polygons("val", style = "equal", palette = "Blues")
```

My session info:
R version 3.3.3 (2017-03-06)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.2 LTS

**Comment by PKullberg** [comment]
I just realized that with diverging scale everything works perfectly:

tm_shape(spd) + 
  tm_polygons("val", style = "equal", palette = "BrBG")

Nevertheless, I think that it would be good to be able to select non-diverging scales.

**Comment by mtennekes** [comment]
Thanks for the feedback. This works as expected: by default `auto.palette.mapping` is set to `TRUE`, so for sequential palettes (such as "Blues"), 0 is mapped to the left-hand side of the palette, and the highest absolute value to the right-hand side. This value may be either positive or negative, so the mapped value range is either [-10, 0] or [0, 10] when -10 respectively 10 is the highest absolute value. In case of both negative and positive values, the mapping of a sequential palette does not work. Maybe an error or warning should be thrown here.

So, in other to map a sequential palette anyway, you'll have to set `auto.palette.mapping = FALSE`:

    tm_shape(spd) + 
      tm_polygons("val", style = "equal", palette = "Blues", auto.palette.mapping = FALSE)

I also use this option in this example:

    data(World)
    tm_shape(World) +
      tm_polygons("HPI", palette="RdYlGn", style="cont", n=8, auto.palette.mapping=FALSE,
        title="Happy Planet Index", id="name") +
      tm_text("iso_a3", size="AREA", scale=1.5) +
    tm_format_World() + 
    tm_style_grey()

**Comment by paulito-bandito** [comment]
Hi all, firstly, create library. It's been excellent to work with.

Secondly, in 2022 it looks like `auto.palette.mapping` is being depricated. I'm seeing this warning "Please use midpoint for numeric data and stretch.palette". Was curious if someone could link me to an example of how either of those options is being used?

**Comment by mtennekes** [comment]
Thanks. For numerical data, only `midpoint` is relevant. For instance:

```r
data(World)
tm_shape(World) +
	tm_polygons("HPI", palette="RdYlGn", style="cont", n=8,
				title="Happy Planet Index", id="name")

tm_shape(World) +
	tm_polygons("HPI", palette="RdYlGn", style="cont", n=8,
				title="Happy Planet Index", id="name", midpoint = 35)
```

`stretch.palette` is only used for categorical data/palettes.

If you have some old examples that use `auto.palette.mapping` and need to update, please let me know. Otherwise, I'll close this issue.

**Comment by paulito-bandito** [comment]
Ahhh, @mtennekes Thank you! That's what i was looking for!

**Comment by paulito-bandito** [comment]
Check it out! Mission Successful: I an finally visually indicating which of my T-values are unacceptable (and the dots are my overlaid p-values). Thanks again!

![image](https://user-images.githubusercontent.com/5655808/154607608-60db50fa-50c0-4bc9-8f66-473bd8aa7e95.png)
