### ISSUE TITLE
 tmap_icons and add_legend

### ISSUE THREAD

**Issue by sjewo** [mtennekes/tmap#131]
Hi Martijn!

I failed to add a legend for a `tm_markers()` layer manually using a symbol loaded by `tmap_icons()`. 
As there is no type "markers" for `tm_add_legend()`, I assume this is not implented yet.

Could I add a legend by a different method?

**Comment by mtennekes** [comment]
I think it should work now. The `shape` argument of `tm_add_legend` can take the same options as the `shape` argument of `tm_symbols` (except variable names of course).

E.g.

    airplane <- tmap_icons(paste0("http://cdn.mysitemyway.com/etc-mysitemyway/icons/",
        "legacy-previews/icons-256/retro-green-floral-icons-transport-travel/",
        "040553-retro-green-floral-icon-transport-travel-transportation-airplane22.png"))

    qtm(metro) + tm_add_legend("symbol", labels=1:3, size=c(.2, .6, 1), shape = list(airplane))

Let me know if this is what you aim for.

**Comment by sjewo** [comment]
Thanks! That's exactly what I was looking for!
