### ISSUE TITLE
Horizontal alignement of numbers in legend text

### ISSUE THREAD

**Issue by sjewo** [mtennekes/tmap#132]
Hi Martijn,
 
it would be great, if we could fix the alignment of the legend labels. 
At the moment a legend looks like this:

```
1.2 to 1.8
1.8 to 10.1
10.1 to 12.1
12.1 to 14.1
14.1 or greater
```
The readability could be increased by aligning the number in columns:
```
1.2  to 1.8
1.8  to 10.1
10.1 to 12.1
12.1 to 14.1
14.1 or greater
```
I tried to get these result by adding a tab (`\t`) into the legend text, but the horizontal space is to large.

I tried to understand the code for legend creation, and as far I understand the legend text is pasted into one string at some point. Would it be a great effort to keep the lower and upper bounds separate and plot them in individual text grobs? Maybe this approach could be useful to create more flexible legend layouts, as described in issue #102 .

I'm willing to contribute code to this issue, but I need some tips where I should start.

**Comment by yipcma** [comment]
I'm interested in this as well, in addition, i wonder if there's a way to have the ordering of values customizable, for example, i would like to have 

```
10.1 to 12.1
1.8  to 10.1
1.2  to 1.8
```

**Comment by mtennekes** [comment]
legend.format now has two extra options, text.align and text.to.columns

The only minor thing that does not work (yet) is that the "text.less.than" and "text.or.more" are now treated as values. In other words, the "than" and the "or" words are not placed in the middle column.

Feel free to improve this.

**Comment by sjewo** [comment]
Thanks for adding this options! This works great for closed intervals. I see the problem with "less than" - I'll look into the code...

**Comment by mtennekes** [comment]
Actually, it should be easier then I thought:-) I'll fix it.

**Comment by mtennekes** [comment]
Done! text.less.than and text.or.more are now character vectors of size two, such that the middle-column-word can be extracted.

Please reopen this issue if there are bugs, or if the spacing is not right (always a struggle to get it right).
