### ISSUE TITLE
Symbols does not show in the legend when tm_facets is implemented

### ISSUE THREAD

**Issue by sigmafelix** [mtennekes/tmap#133]
I'm very grateful to you for making the great package `tmap`.
I've just found that there is an issue on making legend when I used `tm_facets` and `tm_dots` simultaneously. I'm using a factor variable `ERRORCLS1` to make it as symbol color. Additionally I'm also using `tm_facets` to visualize the points by their own regions. Here's an example code:

```
# the factor variable ERRORCLS1
unique(slsp1@data$ERRORCLS1)
[1] (0,10]      (-10,0]     (10,20]     (20,30]     (-20,-10]   (30,247]    (-79.2,-30] (-30,-20]  
Levels: (-79.2,-30] (-30,-20] (-20,-10] (-10,0] (0,10] (10,20] (20,30] (30,247]
# slsp1 is a SpatialPointsDataFrame object
# This is the main code; the variable SIDO indicates names of regions where the points are
tm_shape(slsp1)+
    tm_dots(col='ERRORCLS1', size=0.1) + 
    tm_facets('SIDO',free.coords = TRUE, free.scales.symbol.size = TRUE, free.scales.symbol.shape = TRUE, free.scales.fill = TRUE) + 
   
tm_layout(legend.outside = TRUE, legend.outside.position = 0.12)
```
It throws the plot as below:

![rplot](https://user-images.githubusercontent.com/25448786/29616112-574dbade-884b-11e7-9ddf-f79a0a08d001.png)

I can't figure out why symbols in the legend do not show. Even though I've changed every parameter shown in the help page of `tm_facets` or `tm_dots`, the problem was not solved.
Is this a bug or just by my fault?
Thanks in advance.

**Comment by AndySouth** [comment]
I've just come across the same thing.

A short reproducible example :

With facets gives no symbols in legend.
```
data(Europe)
  tm_shape(Europe) +
       tm_bubbles(size=1, col="continent") +
       tm_facets("part")
```
![image](https://user-images.githubusercontent.com/3042629/30018862-6e5b0ff6-9156-11e7-85d6-a767d72a61b2.png)

Without facets the symbols appear fine in the legend.
```
  tm_shape(Europe) +
      tm_bubbles(size=1, col="continent")
```
![image](https://user-images.githubusercontent.com/3042629/30019045-1e0de20c-9157-11e7-9b3b-1401eed3a128.png)

**Comment by mtennekes** [comment]
Thanks @sigmafelix and @AndySouth for reporting this bug!
