### ISSUE TITLE
Misspelled arguments not generating any warnings

### ISSUE THREAD

**Issue by DataDataEverywhere** [mtennekes/tmap#135]
I am not sure if this is a minor issue or an intended feature but I am not getting any warnings if I misspell any arguments in tm_polygons. In this below example I have misspelled the 'palette' argument:

```
library(tmap)

data(Europe)

tm_shape(Europe) +
      tm_polygons( "gdp_cap_est", 
                 style= "kmeans",
                 pallette= "Blues",
                 auto.palette.mapping=FALSE,
                 title= "GDP per capita") +
tm_format_Europe() + 
tm_style_grey()
```

This is does not throw and error or warning and just ignores the argument and uses default colour palette. If the lack of error is intended it would be nice to have a warning message saying argument x is ignored.

**Comment by mtennekes** [comment]
Thanks for your feedback. It would indeed be better to have some kind of warning. The problem is that tje arguments of functions like these are (can be) passed on to other functions, but there should be a workaround possible.

**Comment by Nowosad** [comment]
Close?
