### ISSUE TITLE
Wish: small multiples with list of shape lists

### ISSUE THREAD

**Issue by ugroempi** [mtennekes/tmap#139]
Hi Martijn,
it would be really nice if I could create a small multiple by giving a list of shape lists to tm_symbols, e.g. 

`bothMap <- tm_shape(geo) +`
`    tm_polygons(col = "grey", alpha=0, border.col ="grey20") +`
`    tm_symbols(shape=c("NAMEshort","NAMEshort"),`
`             shapes=list(tmap_icons(gns[sort(geo$NAMEshort)], width=96, height=48),`
`                      tmap_icons(fns[sort(geo$NAMEshort)], width=96, height=48)))`

I would like to show png files resulting from analyzing two different aspects for each county. I suppose that I can use tm_arrange, but the result looks pretty poor, and I was hoping that the built-in small multiples split into two graphs makes it look better. Giving `tm_symbols` two identical shape variable names and the list of two icon specs, as in the code above, creates a chart that only uses the first icon of each list. If I give tm_symbols two different shape variable names, I get a mix of shapes from both types on both plots, with the first two shapes from each list used and recycled. I have played with a few guessed arrangements to no avail. 

Is this not possible? (It would be nice if it were ... but I know we all have too little time for everything ...)

Best, Ulrike

**Comment by mtennekes** [comment]
Hi Ulrike, could you provide a reproducible example of what you want to achieve (including the icon files)?

**Comment by ugroempi** [comment]
Hi Martijn,

what I wanted to achieve is to put the following two graphs as small multiples onto a single page:
[Failure percentages in Abitur in German Counties](http://prof.beuth-hochschule.de/fileadmin/prof/groemp/downloads/AbiturAverageGrades.html)
[Average grades in Abitur in German Counties](http://prof.beuth-hochschule.de/fileadmin/prof/groemp/downloads/AbiturAverageGrades.html). 

I could not make this work by using the specification of separate shapes for triggering a small multiples display.

The png-files are available by downloading the complete websites. Is this sufficient, or do you need more info?

Best, Ulrike

**Comment by mtennekes** [comment]
It should be working now. The shapes can now be assigned by name (rather than order), see #137 Also, small multiples are supported.

I've created a test script, see https://github.com/mtennekes/tmap/blob/master/test/test_shapes.R 
Let me know if it still doesn't work as expected.

**Comment by ugroempi** [comment]
Thank you also for this one, it's very useful for me!
