### ISSUE TITLE
tmap_save for html files looses titles

### ISSUE THREAD

**Issue by ugroempi** [mtennekes/tmap#141]
Hi Martijn,

I find that saving an interactive map with tmap_save looses the title that is saved OK when exporting from the viewer in an RStudio window. That viewer gave me a lot of slowness and unreliable behavior with my maps otherwise, so that I switched to working with the browser and using `tmap_save`. However, the titles were consistently gone, when using `tmap_save` (simple reproducible example below).

Simple reproducible example:

`data(World, metro, rivers)`

`exampLooseTitle <- tm_shape(World, projection="longlat") + 
    tm_polygons() +` 
`tm_layout("Long lat coordinates (WGS84)", 
    inner.margins=c(0,0,.1,0), title.size=.8)`

`save_tmap(exampLooseTitle, "LooseTitle.html")`

Best regards,
Ulrike

**Comment by tim-salabim** [comment]
FWIW you can set `options(viewer = NULL)` to render your maps in the browser rather than RStudio viewer.

**Comment by mtennekes** [comment]
Fixed, thanks for the bug report!
