### ISSUE TITLE
qtm doesn't work with vectors with "units" 

### ISSUE THREAD

**Issue by barryrowlingson** [mtennekes/tmap#143]
`st_distance` returns vectors with distance units.

```
> d[1:10,]
Units: m
 [1]  11.651255  73.925251 332.152476 266.152978  93.110727  22.169747
 [7]   8.139602  63.514804  72.877887  11.221053
```

If I try and make a map with a column in my sf object that has units, `qtm` fails:

```
> populated$road_min = d[,1]
> qtm(populated, symbols.col="road_min")
Error in Ops.units(x, 0) : 
  both operands of the expression should be "units" objects
```

This looks like its trying to do something like adding 0 to the unitted vector. I can get the same error message this way:

```
> library(units)
> a <- set_units(1:2,  m)
> a
Units: m
[1] 1 2
> a+0
Error in Ops.units(a, 0) : 
  both operands of the expression should be "units" objects
```

Converting to an un-unitted vector fixes it:

```
> populated$road_min = as.vector(d[,1])
> qtm(populated, symbols.col="road_min") # a map appears!
```

**Comment by mtennekes** [comment]
Currently, tmap expects numeric or categorical (factor or character) data for the aesthetic arguments. It would indeed be useful to support units as well. They can be treated as numeric, but with extra information, namely the unit, which can be shown in the legend title. I'll come back to this when the sf branch is ready.

**Comment by Robinlovelace** [comment]
I raised a similar issue in dplyr and a less friendly response. Great that you're will to support this, will be a great addition to an already awesome space-aged map making pkg.

**Comment by mtennekes** [comment]
Implemented. See https://github.com/mtennekes/tmap/blob/master/tests/testthat/test_units.R for some tests/examples
