### ISSUE TITLE
tm_raster fails if colortable has duplicated colours

### ISSUE THREAD

**Issue by barryrowlingson** [mtennekes/tmap#144]
If I try and plot a raster with a colortable that has duplicated colours then tmap fails. Depending on your version of R, this will be a warning or an error. Version 3.3 will warn, but 3.4 errors. Reproducible example - this creates a 2x2 matrix with initially a rainbow palette of four colours, but then setting the first colour as the same as the second causes (in this case) a warning:

```
 r = raster(matrix(0:3,2,2))
 projection(r)="+init=epsg:4326"
 plot(r)
 n = new(".RasterLegend")
 n@colortable = rainbow(4)
 r@legend = n
 plot(r)
 tm_shape(r) + tm_raster() # works fine
 r@legend@colortable[1] = r@legend@colortable[2]
 tm_shape(r) + tm_raster()

## Warning message:
## In `levels<-`(`*tmp*`, value = c("#80FF00FF", "#80FF00FF", "#00FFFFFF",  :
##  duplicated levels in factors are deprecated
```

In R 3.4 the deprecation is now an error, and the map fails completely.

It looks like something in tmap is trying to make a factor from the colours...

tmap version is 1.10

**Comment by mtennekes** [comment]
Thanks for reporting. This has already been fixed (https://github.com/mtennekes/tmap/issues/117), so in the latest development version, it works.
