### ISSUE TITLE
Can not use tm_text with tm_facet.

### ISSUE THREAD

**Issue by pbdanny** [mtennekes/tmap#148]
Running this command

`data(Europe)
tm_shape(Europe) +
+ tm_polygons("well_being", title="Well-Being Index") +
+ tm_facets("part") +
+ tm_text(text = "well_being", size = "well_being")`
Yield this error massage
`Error in cols[, i] : incorrect number of dimensions`

But when remove tm_text(), output are ok.

Is there any parameter needed for tm_text() to work with tm_facets?
Thank you.

**Comment by mtennekes** [comment]
Seems to work with the latest development version. Let me know if not.
