### ISSUE TITLE
pipe or `+` ?

### ISSUE THREAD

**Issue by joelgombin** [mtennekes/tmap#15]
I don't know how much thaught you've given to this, and if you have specific views on this, but there is a heated debate going on about interfaces relying on `+` (ggplot2 style) and those pipeable (ggvis style). See for example: https://twitter.com/cpsievert/status/606192726883704832

**Comment by Robinlovelace** [comment]
%>% seems to be the future; also used in leaflet: https://github.com/rstudio/leaflet

**Comment by joelgombin** [comment]
I tend to agree, but I can also see the logic of building by adding components (nouns). Plus I think switching to the pipe would involve a significant amount of rewriting.

**Comment by mtennekes** [comment]
Interesting topic. I have to admit I didn't work with any pipeline packages (dplyr, ggvis) yet.
It seems that the nouns pretty much correspond one to one to the verbs. I mean, component1+component2 is not very different from draw_component1 %>% draw_component1.

To make thinks more practical: what code would you get in the pipeline approach that reproduces the following example?

```{r}
data(World)
data(metro)

# Choropleth and bubblemap
metro$growth <- (metro$pop2020 - metro$pop2010) / (metro$pop2010 * 10) * 100
tm_shape(World) +
    tm_polygons("income_grp", style="kmeans", palette="-Blues", title="Income class") +
    tm_text("iso_a3", size="AREA", scale=1.5) +
tm_shape(metro) +
    tm_bubbles("pop2010", col = "growth", border.col = "black", 
        border.alpha = .5, style="fixed", 
        breaks=c(-Inf, seq(0, 6, by=2), Inf),
        palette="-RdYlGn", contrast=1, 
        title.size="Metro population (2010)", 
        title.col="Annual growth rate (%)") + 
tm_layout_World(title="Income and\nurbanization")
```

**Comment by joelgombin** [comment]
I guess that would look something like this (assuming we allow non-standard evaluation):

```r
library(dplyr)
data(World)
data(metro)

# Choropleth and bubblemap

World %>%
  map() %>%
    add_ layer_polygons(income_grp, style="kmeans", palette="-Blues", title="Income class") %>%
    add_layer_text(iso_a3,  size=AREA, scale=1.5) %>%
    add_layer_bubbles(shape = metro %>%
                                          mutate(growth = (pop2020 - pop2010) / (pop2010 *10) * 100,
                          pop2010, col= growth, bordel.col = "black", 
                          border.alpha = .5, style="fixed", 
                          breaks=c(-Inf, seq(0, 6, by=2), Inf),
                          palette="-RdYlGn", contrast=1, 
                          title.size="Metro population (2010)", 
                          title.col="Annual growth rate (%)") %>% 
    add_layout_World(title="Income and\nurbanization")
  
```

**Comment by mtennekes** [comment]
As I understand, one of the main advantages of the pipeline approach is that temporarily (modified) variables do not need to be assigned explicitly, making the global workspace much cleaner.

One thing that annoys me in our case, is that the pipe starts with one (i.e., the first) shape object, while the other shape objects are tucked away in the add_layer functions. This is not a problem if the first layer is also the most important one, but often, the first layer is only served as a background layer.

So you understand that implementation of this approach does not have my biggest priority. But if any of you wants to, please feel free to have it a go!

**Comment by Robinlovelace** [comment]
I agree with this - adding pipes is not a priority, especially while `+` works so well.
