### ISSUE TITLE
Add leaflet's Marker Cluster option for interactive mapping

### ISSUE THREAD

**Issue by ccamara** [mtennekes/tmap#151]
Since Leaflet allows using marker clusters (visit documentation here: https://rstudio.github.io/leaflet/markers.html) and tmap uses leaflet for interactive maps, I was wondering if it is possible to add a Marker Cluster in tmap.

**Comment by mtennekes** [comment]
Sure, why not?

What kind of interface do you want? One option is to add an argument `clustering` to `tm_symbols` (and therefore `tm_dots`, `tm_markers` etc.), which can be set to TRUE, FALSE, or to a list created by leaflet::markerClusterOptions. What do you think?

**Comment by ccamara** [comment]
Glad to hear that! 

Honestly, my only (and limited) experience with clustering and leaflet is simply adding the parameter `clusterOptions = markerClusterOptions()` to `addMarkers()` (or `addCircleMarkers()` or any type of marker) calls which, in turn, uses [Leaflet.markercluster](https://github.com/Leaflet/Leaflet.markercluster) plugin. For that reason I would love to use a solution similar to default's leaflet behaviour:

```
leaflet(quakes) %>% 
  addTiles() %>% 
  addMarkers(clusterOptions = markerClusterOptions())
```

Unfortunately I can't provide any more feedback than that, although your approach (or the part I understood -before TRUE, FALSE) seems to be aligned to that.

**Comment by mtennekes** [comment]
Ah, so the part you didn't understand: `markerClusterOptions()` returns a list. Without options, the default settings are set, but you can change its parameters, e.g. `markerClusterOptions(freezeAtZoom = 5)`.

Therefore I thought about these options:

   tm_shape(quakes) + tm_markers(clustering = FALSE)
   tm_shape(quakes) + tm_markers(clustering = TRUE) 
   tm_shape(quakes) + tm_markers(clustering = markerClusterOptions()) # most flexible

**Comment by ccamara** [comment]
That would be great! (especially the last option)
Thanks for considering it and for taking your time sharing your approach.

**Comment by mtennekes** [comment]
Done, let me know if it doesn't work as expected.
