### ISSUE TITLE
Misleading color legend based on palettes and breaks

### ISSUE THREAD

**Issue by rubemd** [mtennekes/tmap#153]
Hello,

Maybe my doubt/question is too dumb because I am new on R. I beg your pardon if that is indeed the case.

Well... I have a `tm_lines` that I wanted to make 5 breaks with fisher `style`. I did it successfully. I am used to adopt the RdYlGn `palette`, however, using the minus sign before it to establish that red color is stronger.

I would expect that the legend would bring: dark green, light green, yellow, orange and red (as ArcGIS does). Nevertheless I got yellow, light orange, orange, light red, red (and I got those distinguishable using `contrast` from 0 to 1). An analogous pattern happens if I remove the minus, but the problem is that instead of reds, I get greens.

So, my question is: am I doing something wrong or this is a real issue?

The code for this specific line:

``` tm_shape(KDE_ERM, unit = "km") +
        tm_lines(col = "Str_Dens2",
                 lwd = 3, 
                 style = "fisher",
                 n = 5, 
                 palette = "-RdYlGn",
                 contrast = c(0, 1),
                 scale = 1.5,
                 title.col = "Intensidade de agregação", 
                 legend.col.is.portrait = T,
                 labels = c("Muito baixa", "Baixa", "Média", "Alta", "Muito alta"))
```

and the result:

![imagem1](https://user-images.githubusercontent.com/25906665/32874959-7f38eca8-ca7c-11e7-9d9a-cdcf0fce4812.png)

Thank you very much indeed for your attention!

Best regards!

Rubem.

**Comment by mtennekes** [comment]
Hi Rubem,

Good question! By default diverging palettes are mapped in such a way that 0 corresponds to the middle color. You can turn this off by setting `auto.palette.mapping` to `FALSE`.

Martijn
