### ISSUE TITLE
Bug in `labels` argument of `tm_polygons()`/`tm_fill()`

### ISSUE THREAD

**Issue by philmikejones** [mtennekes/tmap#155]
First, thank you for such a useful package. I've used it to create thematic maps throughout my thesis and was complemented on the quality of the finished maps by my examiner.

I think a bug has been introduced into tmap since the latest CRAN release. I've tested on version 1.10 (using `devtools::install_version()`) and version 1.11 and reproduce the error with the latest version but can plot with version 1.10.

The problem seems to be with the `labels` argument of `tm_polygons()`/`tm_fill()`. Attached is a MRE using a small shapefile.

When you run the code with the `labels` argument I receive the following error:

```
> Error in if (is.na(align) || align == "left") { : 
>   missing value where TRUE/FALSE needed
> In addition: Warning message:
> In is.na(align) : is.na() applied to non-(list or vector) of type 'NULL'
```

Removing the `labels` produces the plot without error. Rolling back to version 1.10 with `devtools::install_version("tmap", version = "1.10")` and re-inserting the labels also produces the plot without error.

Apologies if this is a change in syntax or a new feature, but I couldn't find any documentation suggesting it has been updated.
[tmap_labels_bug.zip](https://github.com/mtennekes/tmap/files/1528179/tmap_labels_bug.zip)

**Comment by philmikejones** [comment]
FWIW I tried the development version but got this error message whatever I tried to do:

```
> Error in get_proj4(x[[shape.id[masterID]]]$projection, output = "crs") : 
>   unused argument (output = "crs")
```

**Comment by mtennekes** [comment]
Thx, Phil! The bug has been fixed now. 

Regarding your last error message: tmap is undergoing a major transformation under the hood (from sp to sf).

The master branch is the sf branch and requires the master branch of tmaptools. The current version is stored in the "old_sp" branch.

**Comment by philmikejones** [comment]
Thanks, that did the trick!
