### ISSUE TITLE
Syncing and border problem in "view" mode

### ISSUE THREAD

**Issue by wkedziora** [mtennekes/tmap#157]
I am trying to get two maps syncing in "view" mode but I cannot achieve this. 
Additionally when setting `border.lwd = NA' it works in plotting mode but not in a viewing one.

Reproducible example:
library(tmap)
data(metro)
map1 <- tm_shape(metro) + tm_bubbles(size = "pop1970", border.lwd = NA)
map2 <- tm_shape(metro) + tm_bubbles(size = "pop2020", border.lwd = NA) 
tmap_arrange(map1, map2, sync = TRUE)

R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

**Comment by mtennekes** [comment]
Thx! Syncing is fixed now. I'll check why the borders still appear in view mode. For now, you can remove them by `border.col = NULL`.
