### ISSUE TITLE
Different colors for different variables in facets

### ISSUE THREAD

**Issue by Robinlovelace** [mtennekes/tmap#16]
Is this possible?

E.g. is it possible to make the right-hand map have a "Reds" colourscheme?

![selection_242](https://cloud.githubusercontent.com/assets/1825120/8046821/04e8e9da-0e36-11e5-83ba-ce9ccdc8d919.png)

Will add to my Creating-maps-in-R tutorial if so!
https://github.com/Robinlovelace/Creating-maps-in-R

**Comment by mtennekes** [comment]
Not possible yet, but would be very welcome indeed. I'll have a look at it this week! 

There are other arguments that determine the palette, like contrast. I'll have to see whether they should also accept a value for each variable. 

By the way, it's also possible to assign a vector of colors values to the palette argument, but somehow I forgot to mention it in the docs. In the different-colors-per-facet-variable setting this could be made possible by a list of color value vectors.

**Comment by Robinlovelace** [comment]
Thanks @mtennekes. I can work on the documentation of the vector-based palette. Should I add it to the main 'nutshell' vignette? Which function should I use to describe it in the help docs?

**Comment by mtennekes** [comment]
@Robinlovelace Thanks for your input. I'll update the docs myself, they have to be changed anyway when the above idea has been implemented. Please feel free to join with the further development of this package.

**Comment by mtennekes** [comment]
Done! If there are any bugs, or doc typos, please let me know.

**Comment by Robinlovelace** [comment]
Great work on this @mtennekes and many thanks for your hard work on this fantastic mapping package.
