### ISSUE TITLE
can't specify two sets of labels when using small mulitples

### ISSUE THREAD

**Issue by christinabrady** [mtennekes/tmap#160]
The following code throw an error: Labels should be a character vector. 

tm_shape(Europe) +
    tm_fill(c("HPI", "gdp_cap_est"), 
        palette=list("RdYlGn", "Purples"),
        auto.palette.mapping=FALSE,
        title=c("Happy Planet Index", "GDP per capita"), 
        labels = list(Europe$HPI, prettyNum(Europe$gdp_cap_est, big.mark = ","))) +
tm_format_Europe() + 
tm_style_grey()

**Comment by mtennekes** [comment]
Labels should indeed be a character value vector. For small multiples, every list item should be a character vector (so this error was not very clear).

This works:

    tm_shape(Europe) +
	tm_fill(c("HPI", "gdp_cap_est"),
			palette=list("RdYlGn", "Purples"),
			auto.palette.mapping=FALSE,
			title=c("Happy Planet Index", "GDP per capita"),
			labels = list(letters[1:6], LETTERS[1:5])) +
	tm_format_Europe() +
	tm_style_grey()

I think this is not what you wanted to achieve, isn't it? If you just want the formatting of the legend labels to be different, you can use 

    tm_shape(Europe) +
	tm_fill(c("HPI", "gdp_cap_est"),
			palette=list("RdYlGn", "Purples"),
			auto.palette.mapping=FALSE,
			title=c("Happy Planet Index", "GDP per capita"),
			legend.format = list(list(), list(big.mark = ","))) +
	tm_format_Europe() +
	tm_style_grey()

If you want the popup values in different formats (for view mode only), you can use `popup.format` in the same way.

**Comment by Nowosad** [comment]
Inactive, close?
