### ISSUE TITLE
how to save the result of tmap_arrange?

### ISSUE THREAD

**Issue by microly** [mtennekes/tmap#162]
thanks for this amazing package!

tmap_arrange() is a very useful tool, which can combine any maps.
but i find it only "print" the combined map, but cannot save it to a file such as png.

could you please tell me how to save the result of  tmap_arrange, which is really often needed?
thank you~

**Comment by mtennekes** [comment]
Good point. You can always go the standard way, e.g. with png(...) tmap_arrange(...) dev.off()

**Comment by microly** [comment]
Thank you so much！

**Comment by statnmap** [comment]
Could you maybe add this information in the documentation ? At least in `tmap_arrange` help file ?  
I spent some time trying to figure this out. Some others may find this useful.  
Thanks
