### ISSUE TITLE
another mac install problem

### ISSUE THREAD

**Issue by GeraldCNelson** [mtennekes/tmap#163]
Here's another Mac installation problem.

> install_github("mtennekes/tmaptools")
Downloading GitHub repo mtennekes/tmaptools@master
from URL https://api.github.com/repos/mtennekes/tmaptools/zipball/master
Installing tmaptools
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/bv/881_rsvd2kv83c13yywwc_xh0000gn/T/RtmpOuHJqy/devtools1701159e059e4/mtennekes-tmaptools-2f9870e'  \
  --library='/Users/gcn/Library/R/3.4/library' --install-tests 

* installing *source* package ‘tmaptools’ ...
** R
** preparing package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Users/gcn/Library/R/3.4/library/classInt/libs/classInt.so':
  dlopen(/Users/gcn/Library/R/3.4/library/classInt/libs/classInt.so, 6): Symbol not found: ___addtf3
  Referenced from: /usr/local/lib/libquadmath.0.dylib
  Expected in: /usr/local/lib/libgcc_s.1.dylib
 in /usr/local/lib/libquadmath.0.dylib
ERROR: lazy loading failed for package ‘tmaptools’
* removing ‘/Users/gcn/Library/R/3.4/library/tmaptools’
* restoring previous ‘/Users/gcn/Library/R/3.4/library/tmaptools’
Installation failed: Command failed (1)
I'm using R 3.4.3, on Mac OS High Sierra

**Comment by microly** [comment]
you can try the old_sp branches.
it works well for me, but on win10.
good luck~

**Comment by vhertzb** [comment]
Any luck in solving this issue? I am running R 3.4.3 on Mac OS X Sierra 10.12.6

**Comment by vhertzb** [comment]
Oh, and I am not trying to run this package, but have the same problem with upgrading another package. Thanks!

**Comment by Nowosad** [comment]
Inactive, close?
