### ISSUE TITLE
Different labels for tm_facet

### ISSUE THREAD

**Issue by claudiofronterre** [mtennekes/tmap#166]
Hello Martijn,

First of all thanks for this wonderful package. It is by far the best R package to visualise spatial data.

I am struggling to solve the following problem. I am using tm_facets to plot spatial points for different years and I want to assign different labels for the legend for each facet. I have created a list with the labels and set the argument `free.scales = TRUE` but as you can see from the plot below it visualise the points only in the last legend. 
![image](https://user-images.githubusercontent.com/25867244/35693690-d32792ec-0776-11e8-9d6c-d144d6c4e470.png)
How can I sort this out? Here is the code:
``` r
map_prev <- tm_shape(ethy, is.master = T) +
  tm_borders() +
  tm_fill("white") +
  tm_shape(onco_sp) +
  tm_facets(by = "surveyyear", ncol = 3, free.coords = F, free.scales = T) +
  tm_symbols(col = "prev_map", size = .2, alpha = 1, style = "fixed", contrast = c(0, 1),
             breaks = c(0, .05, .2, .4, .6, .8, 1), title.col = "Prevalence - Counts",
             interval.closure = "left", labels = list(label1, label2, label3), 
             palette = "YlOrRd", auto.palette.mapping = F) +
  tm_compass(position = "left") +
  tm_layout(legend.outside = F, scale = 1.5, asp = 1, legend.position = c("RIGHT", "TOP")) +
  tm_scale_bar() +
  tm_style_grey() 
map_prev
```

I have also other two questions:
1. How can I reduce the space between the legend title and the legend itself?
2. If I try to reduce the outer.margins (top and bottom) I get the following error:
```
Error in grid.Call(C_convert, x, as.integer(whatfrom), as.integer(whatto),  : 
  Viewport has zero dimension(s)
```
Many thanks in advance for your precious help!

**Comment by mtennekes** [comment]
It was a bug, thanks for noticing me!

The space between title and legend is relative large, because the title size is decreased due to insufficient width. If you set title.size smaller, the space will probably be reduced. Or you could increase the legend.width.

Regarding the outer.margin: could you provide a reproducible example? What also could help, is to enable design.mode (set it to true in tm_layout).

**Comment by claudiofronterre** [comment]
Hi Marijn, 

I solved the problems. I didn't know about the design.mode, it's wonderful.

I am trying to download the development version.
