### ISSUE TITLE
How to integrate leaflet.extras search?

### ISSUE THREAD

**Issue by EKtheSage** [mtennekes/tmap#167]
I am trying to add search functionality to my maps, and found that leaflet.extras has the search function

http://rpubs.com/bhaskarvk/leaflet-search

It seems we should be able to have something like this below but I am unable to get it to work:

```
tmap_leaflet(object) %>% 
    addSearchFeatures(
        targetGroups = c("topic to be searched"),
        option = searchFeaturesOptions(openPopup = TRUE)
    )
```

Is there an example on how to get search to work?

**Comment by mtennekes** [comment]
Nice feature, thanks for the tip!

This works out of the box:

```r
data(metro)
tmap_leaflet(qtm(metro)) %>% 
 	addSearchOSM()
```

What kind of integration are you looking for? We could add a `tm_search` element:

```r
qtm(metro) + tm_search()
```

or just add a new argument to `tm_view`.

```r
qtm(metro) + tm_view(search = TRUE)
```

**Comment by EKtheSage** [comment]
If you look at the section "**Search Polygon**", the leaflet-search document, that's what I want to achieve with search. I should be able to specify variables in my data to be searched for, and the result should pop up with the data associated with that particular polygon.

I thought it would be as simple as adding the addSearchFeatures to the end of a `tmap_leaflet` object, but it doesn't recognize the variables I specify in the targetGroups.

**Comment by mtennekes** [comment]
We should definitely get this to work, awesome feature!

A non-yet-working example to start working from:

```r
tmap_mode("view")
tm <- tm_shape(World) + tm_polygons("HPI", id = "name")

tmap_leaflet(tm) %>% 
	addSearchFeatures(
		targetGroups  = 'World',
		options = searchFeaturesOptions(openPopup=TRUE, propertyName='name'))
```

**Comment by EKtheSage** [comment]
Thanks for the update, I look forward to seeing the new functionality!

**Comment by mtennekes** [comment]
It works:

```r
tmap_leaflet(tm) %>% 
	addSearchFeatures(
		targetGroups  = 'World',
		options = searchFeaturesOptions(openPopup=FALSE, zoom = 6))
```

When `leaflet.extras` is stable (and the CRAN version is updated), we can think about embedding these functions into `tmap`.

**Comment by EKtheSage** [comment]
The search button doesn't return anything, and why do you use `'World'` in the `targetGroups`?

**Comment by mtennekes** [comment]
The `World` indicates the group id, which is inside tmap set to the name of the shape file. Did you install the dev-version of leaflet.extras? Also note that it can only search through the values identified by the id argument of the layer function, i.e. `id = "name"`. It should look like this:

![screenshot from 2018-02-13 16-22-19](https://user-images.githubusercontent.com/2444081/36157785-eac19674-10da-11e8-913b-a5446d8bb032.png)

**Comment by Nowosad** [comment]
Inactive, close?
