### ISSUE TITLE
how to customize the scale bar?

### ISSUE THREAD

**Issue by microly** [mtennekes/tmap#168]
thanks for this amazing package!

But the scale bar is not so customizable.
For example, a journal ask me to set the scale bar like this:
![scalebar](https://user-images.githubusercontent.com/18700975/35767187-694800b6-0922-11e8-8200-b4be544288ab.png)
I find it is hard to do so in tmap now.

I try to write a function to customize it myself and have checked the source code of tm_scale_bar.
However, the code is not so straightforward for me to understand it.

would you give me some advice?

OR, could you (or others) supply more styles of scale bar?

**Comment by mtennekes** [comment]
If it's just for one map, you could also consider to export the map to pdf and process it afterwards with Inkscape.

If you want to draw it with R, you can use the `grid` package to add custom lines in an existing map. In tmap, the scale bar is plot in https://github.com/mtennekes/tmap/blob/master/R/meta_plot_items.R#L542

**Comment by microly** [comment]
Thanks for your kind reply!
I have added the new style scale bar on the output of tmap using **grid** package.

I see the source code in the link you supplied, thanks.
I hope I can update it to support more style~

**Comment by microly** [comment]
I write a raw function to draw a new kind scale_bar:

`
tm_scale_bar_my <- function(tick_height = 0.1) {

    #get the rect grob in scale_bar
    gls <- grid.ls(print = FALSE)
    gls_names <- gls$name
    scale_bar_rect_name <- gls_names[which(gls_names == 'scale_bar') + 1]
    scale_bar_rect <- grid.get(gPath(scale_bar_rect_name))

    #get the info of scale_bar_rect
    x_start <- grobX(scale_bar_rect, 180)
    x_width <- grobWidth(scale_bar_rect)
    y <- grobY(scale_bar_rect, 0)

    #get base line grob
    base_line <- linesGrob(x = unit.c(x_start, (x_start + x_width)),
                           y = unit.c(y, y))

    #get tick line grob
    y_height <- unit(tick_height, 'npc')

    tick_start <- linesGrob(x = unit.c(x_start, x_start),
                            y = unit.c(y, (y + y_height)))

    tick_end <- linesGrob(x = unit.c(x_start + x_width, x_start + x_width),
                          y = unit.c(y, (y + y_height)))

    #combine scale_bar
    scale_bar_my <- gList(base_line, tick_start, tick_end)

    #draw and clean
    downViewport('scale_bar')
    grid.draw(scale_bar_my)
    grid.remove(scale_bar_rect_name)
}
`

and modify the "save_tmap" to save the result to file

`
save_tmap_my <- function(tm = NULL, filename = NULL, width = NA, height = NA, units = NA,
                      dpi = 300, outer.margins = NA, asp = NULL, scale = NA, insets_tm = NULL,
                      insets_vp = NULL, verbose = TRUE, FUN_my = NULL, ...) {

    if (is.null(tm)) stop("A map has not been created yet")

    shp_name <- function(tm) {
        paste(tm[[1]]$shp_name, ".pdf", sep = "")
    }

    if (missing(filename)) {
        filename <- shp_name(tm)
    }
    
    get_ext <- function(filename) {
        pieces <- strsplit(filename, "\\.")[[1]]
        if (length(pieces) == 1) return("png")
        tolower(pieces[length(pieces)])
    }

    convert_to_inches <- function(x, units) {
        x <- switch(units, px = x / dpi, `in` = x, cm = x / 2.54, mm = x / 2.54 / 10)
    }
    convert_to_pixels <- function(x, units) {
        x <- switch(units, px = x, `in` = dpi * x, cm = dpi * x / 2.54, mm = dpi * x / 2.54 / 10)
    }


    tmap.mode <- getOption("tmap.mode")

    if (missing(filename)) {
        ext <- ifelse(tmap.mode == "view", "html", "png")
        filename <- paste(filename, ext, sep = ".")
    } else ext <- get_ext(filename)

    interactive <- (ext == "html")
    options(tmap.mode = ifelse(interactive, "view", "plot"))

    if (interactive) {
        lf <- tmap_leaflet(tm)
        saveWidget(lf, file = filename, ...)
        options(tmap.mode = tmap.mode)
        if (verbose) {
            message("Interactive map saved to ", suppressWarnings(normalizePath(filename)))
        }
        return(invisible())
    }

    ## impute missing w or h

    if (is.na(width) && is.na(height)) {
        width <- par("din")[1]
        height <- par("din")[2]
        if (is.na(units)) units <- "in"
        } else if (is.na(width) || is.na(height)) {
            if (!is.na(width)) {
                if (is.na(units)) units <- ifelse(width > 50, "px", "in")

                temp_size <- convert_to_pixels(width, units)
            } else {
                if (is.na(units)) units <- ifelse(height > 50, "px", "in")
                temp_size <- convert_to_pixels(height, units)
            }

            sasp <- tmaptools::get_asp_ratio(tm, width = temp_size, height = temp_size, res = dpi)
            if (is.na(width)) {
                width <- height * sasp
            } else if (is.na(height)) {
                height <- width / sasp
            }
        } else {
            if (is.na(units)) units <- ifelse(width > 50 || height > 50, "px", "in")
            }
    units_target <- ifelse(units == "px" && ext %in% c("png", "jpg", "jpeg", "bmp", "tiff"), "px", "in")


    eps <- ps <- function(..., width, height) grDevices::postscript(...,
                                                                    width = width, height = height, onefile = FALSE, horizontal = FALSE,
                                                                    paper = "special")
    tex <- function(..., width, height) grDevices::pictex(...,
                                                          width = width, height = height)
    pdf <- function(..., version = "1.4") grDevices::pdf(...,
                                                         version = version)
    svg <- function(...) grDevices::svg(...)
    wmf <- function(..., width, height) grDevices::win.metafile(...,
                                                                width = width, height = height)
    emf <- function(..., width, height) grDevices::win.metafile(...,
                                                                width = width, height = height)
    png <- function(..., width, height) grDevices::png(..., width = width,
                                                       height = height, res = dpi, units = units_target)
    jpg <- jpeg <- function(..., width, height) grDevices::jpeg(...,
                                                                width = width, height = height, res = dpi, units = units_target)
    bmp <- function(..., width, height) grDevices::bmp(..., width = width,
                                                       height = height, res = dpi, units = units_target)
    tiff <- function(..., width, height) grDevices::tiff(...,
                                                         width = width, height = height, res = dpi, units = units_target)



    if (units_target == "in") {
        width <- convert_to_inches(width, units)
        height <- convert_to_inches(height, units)

        if (ext == "pdf") {
            round_to_1_72 <- function(x) x %/% (1 / 72) / 72
            width <- round_to_1_72(width)
            height <- round_to_1_72(height)
        }
    } else {
        width <- convert_to_pixels(width, units)
        height <- convert_to_pixels(height, units)
    }

    do.call(ext, args = c(list(file = filename, width = width, height = height), list(...)))
    on.exit(capture.output(dev.off()), add = TRUE)
    args <- list()
    if (!is.na(outer.margins[1])) args$outer.margins <- outer.margins
    if (!missing(asp)) args$asp <- asp
    if (!is.na(scale)) args$scale <- scale
    print(tm + do.call("tm_layout", args))

    #######################################
    ####### the code I added ##################
    if (!is.null(FUN_my)) FUN_my
    #######################################

    if (!missing(insets_tm) && !missing(insets_vp)) {
        args_inset <- if (!is.na(scale)) list(scale = scale) else list()
        if (class(insets_tm) == "list" && class(insets_vp) == "list") {
            if (length(insets_tm) != length(insets_vp)) stop("Number of insets unequal to number of viewports")
            mapply(function(tm_i, vp_i) {
                print(tm_i + do.call("tm_layout", args_inset), vp = vp_i)
            }, insets_tm, insets_vp)
        } else if (inherits(insets_tm, "tmap") && inherits(insets_vp, "viewport")) {
            print(insets_tm + do.call("tm_layout", args_inset), insets_vp)
        } else {
            stop("Insets and/or its viewports not in the correct format")
        }
    }

    if (verbose) {
        message("Map saved to ", suppressWarnings(normalizePath(filename)))
        if (ext %in% c("png", "jpg", "jpeg", "bmp", "tiff")) {
            if (units_target == "px") {
                wp <- format(width)
                hp <- format(height)
                wi <- format(convert_to_inches(width, "px"))
                hi <- format(convert_to_inches(height, "px"))
            } else {
                wi <- format(width)
                hi <- format(height)
                wp <- format(convert_to_pixels(width, "in"))
                hp <- format(convert_to_pixels(height, "in"))
            }
            message("Resolution: ", format(wp), " by ", format(hp), " pixels")
            message("Size: ", wi, " by ", hi, " inches (", format(dpi), " dpi)")
        } else {
            wi <- format(width)
            hi <- format(height)
            message("Size: ", wi, " by ", hi, " inches")
        }
    }

    options(tmap.mode = tmap.mode)
    invisible()
}
` 

A example:
> library(tmap)
> data(NLD_muni)
> tm <- qtm(NLD_muni, theme = "NLD") + tm_scale_bar(breaks = c(0, 80), position = c("left", "bottom"))
> tm
> tm_scale_bar_my(0.2)
# save origin tmap
> save_tmap_my(tm = tm, filename = 'D:\\a.png', width = 7, unit = 'cm')

![a](https://user-images.githubusercontent.com/18700975/37250272-c648bf4e-2533-11e8-911d-43fe4287f000.png)

# save tmap with new scale_bar
> save_tmap_my(tm = tm, filename = 'D:\\b.png', width = 7, unit = 'cm', FUN_my = tm_scale_bar_my(0.2))

![b](https://user-images.githubusercontent.com/18700975/37250274-cf7e9e08-2533-11e8-969c-c1c3d5ea823d.png)

**Comment by Nowosad** [comment]
Close?
