### ISSUE TITLE
Clearly specify which version of leafletjs is being used (Upgrade plans from v0.7.7?)

### ISSUE THREAD

**Issue by knbknb** [mtennekes/tmap#169]
The "interactive map" version of tmap uses an older version of the Leaflet Javascript Library.
When I execute this javascript command in the Chrome developer tools, I get
```
// today is: 2018-02-06
L.version
"0.7.7"
```
Current version is Leaflet 1.3.1 ([Changelog](https://github.com/Leaflet/Leaflet/blob/master/CHANGELOG.md)) - 
Leaflet version 0.7.7 is [from 2015](http://leafletjs.com/download.html). It is still a [reference](http://leafletjs.com/reference-versions.html)  version. So I can live with the older version.

Are there any plans to ship the upcoming tmap 2.0 release with  a newer Leaflet release?

The tmap documentation also does not specify which leaflet version the `save_tmap()` functions puts into the standalone file it exports. The documentation here on Github should be improved in this respect. One or two sentences would suffice.

At this time,  I am using
```
 tmap         * 1.11       2017-11-24 CRAN (R 3.4.3)                    
 tmaptools      1.2-2      2017-11-24 CRAN (R 3.4.3) 

```

**Comment by tim-salabim** [comment]
AFAIK tmap uses library(leaflet) for interactive maps. Hence, the update needs to be made in the leaflet package, which already has a 1.x branch on github. At the time of this writing there are no clear indications as to when an update of the leafletjs base from 0.7.7 to 1.x will be made, but I have heard rumors that RStudio is going to contract someone soon for it. 

Hope that clarifies a bit.

**Comment by Nowosad** [comment]
The **leaflet** package is now using the latest leaflet.js v1.3.1 - https://github.com/rstudio/leaflet/blob/master/NEWS. 
Close?
