### ISSUE TITLE
tm_scale_bar doesn't work

### ISSUE THREAD

**Issue by joelgombin** [mtennekes/tmap#17]
Running the exemple 

```data(Europe)
tm_shape(Europe, unit = "miles", unit.size=1609) + tm_polygons() + tm_scale_bar()
```

doesn't produce a scale bar.

**Comment by mtennekes** [comment]
It works on my pc, I fixed a scale bar bug a couple of days ago. Do you have the latest version?

**Comment by joelgombin** [comment]
You're right, I've updated my installation and it works. 
Besides, there isn't a north arrow, is there?

**Comment by mtennekes** [comment]
No, not yet:)
