### ISSUE TITLE
Function's names - idea

### ISSUE THREAD

**Issue by Nowosad** [mtennekes/tmap#171]
@mtennekes Have you thought about unifying the function's names? Or maybe there is an idea behind them that I'm missing...
For example, right now most of the functions have prefix `tm_`,  some have `tmap_` (e.g. `tmap_style`), and there are a few without any prefix (e.g. `save_tmap`,  `last_map`.

**Comment by mtennekes** [comment]
Yes and no:) The functions with a `tm_` prefix are the layer functions, and all other functions are helper functions. The second group is indeed very inconsistent. There are about 6 `tmap_` functions, two `_tmap` functions, and three other functions. We could rename them to `tmap_` (while the old names still remain to be deprecated). What do you think?

**Comment by Robinlovelace** [comment]
My 5 cents: `tmap_*` for helper functions = good. The one I use most is `tmap_mode`. I think it would make it easier to find other helper functions if they also had a `tmap` prefix. In this scenario `save_tmap` would become `tmap_save`, a definite improvement in terms of usability I reckon.

**Comment by Nowosad** [comment]
Yes, I think that two groups of functions - `tm_` and `tmap_` - could be a very good improvement.

**Comment by mtennekes** [comment]
Yep
