### ISSUE TITLE
How to use same class intervals in different facets?

### ISSUE THREAD

**Issue by rsbivand** [mtennekes/tmap#173]
The reprex:

```
library(sf)
nc <- st_read(system.file("shape/nc.shp", package="sf"))
nc$r74 <- with(nc, SID74/BIR74)
nc$r79 <- with(nc, SID79/BIR79)
library(tmap)
tm_shape(nc) + tm_polygons(c("r74", "r79"), n=6, style="fisher", palette="YlOrBr", title="SIDS rate")
```
shows two maps with different legends and class intervals, and
```
tm_shape(nc) + tm_polygons(c("r74", "r79"), n=6, style="fisher", palette="YlOrBr", title="SIDS rate") + tm_format_Europe2() + tm_layout(panel.labels=c("1974-78", "1979-84"))
```
only shows the legend for the 1974-78 map. My workaround has been to take:
```
library(classInt)
cI <- classIntervals(c(nc$r74, nc$r79), n=6, style="fisher")
tm_shape(nc) + tm_polygons(c("r74", "r79"), breaks=cI$brks, palette="YlOrBr", title="SIDS rate") + tm_format_Europe2() + tm_layout(panel.labels=c("1974-78", "1979-84"))
```
I've looked for the proper way of coding this without success - where should I have looked?

**Comment by mtennekes** [comment]
`tm_facets` controls the way how scales and coordinates are determined for small multiples:

```r
tm_shape(nc) + tm_polygons(c("r74", "r79"), n=6, style="fisher", palette="YlOrBr", title="SIDS rate") +
	tm_facets(free.scales = FALSE) +
	tm_layout(panel.labels=c("1974-78", "1979-84"))
```

**Comment by rsbivand** [comment]
Thanks! This is, I think, mentioned in the forthcoming JSS article, p. 13:

> The argument `free.scales` is used to specify whether the aesthetic  scales should be determined per small multiple. By default, this argument is set to `TRUE` for the first method and `FALSE` for the second method. This can also be specified for each aesthetic separately.
