### ISSUE TITLE
Adjust the legend frame line width

### ISSUE THREAD

**Issue by valentinitnelav** [mtennekes/tmap#174]
I first addressed this aspect on stackoverflow [here](https://stackoverflow.com/questions/48887634/r-tmap-how-to-adjust-the-legend-frame-line-width).

I cannot figure it out how to adjust the legend frame line width. I checked the impressive list of `tm_layout` arguments, but the closest I found was `frame.lwd` However, that refers to the frame of the map. I took the guess with `legend.frame.lwd` but seems that is not defined. 

Having this option can be important because when creating maps that should fit a certain small size imposed by a journal, line thickness can become an "issue". It can happen that the thickness of the frame can easily stand out.

Thanks for your amazing work!

Here is an example:

```R
tm_shape(Europe) +
  tm_polygons("well_being", textNA="Non-European countries", title="Well-Being Index") +
  tm_text("iso_a3", size="AREA", root=5) +
  tm_layout(legend.position = c("RIGHT","TOP"),
            legend.frame = TRUE,
            frame.lwd = 5) # legend.frame.lwd does not exist
```

![image](https://user-images.githubusercontent.com/14074269/36450165-569ba846-168d-11e8-8b6b-20740c7a7fed.png)

**Comment by mtennekes** [comment]
Thanks for finding this! I didn't know it was not possible. Now it is:-) I've added the argument `legend.frame.lwd `.

**Comment by valentinitnelav** [comment]
Thanks for your great work @mtennekes ! Also, If you wish to add a short answer to the [SO question](https://stackoverflow.com/questions/48887634/r-tmap-how-to-adjust-the-legend-frame-line-width), I would gladly mark it as accepted.
