### ISSUE TITLE
Set default tmap options for duration of session

### ISSUE THREAD

**Issue by Robinlovelace** [mtennekes/tmap#178]
It's possible to set plotting options with `par()` that last the duration of a session.

Is this possible with tmap?

After searching help like `?tmap_style` and reading the coverage of `outer.width` in the vignette I still cannot figure it out so if it is I think it could be better documented. Reproducible example that shows my attempt and expected behaviour below:

```r
library(tmap)
library(sf)
data("Europe")
eu = st_as_sf(Europe)
par()$omi
plot(eu$geometry)
par(omi = rep(0.2, 4))
plot(eu$geometry)
qtm(eu)
style.current = tm_style_white()
style.current$tm_layout$outer.margins
style.current$tm_layout$outer.margins = rep(0.2, 4)
tmap_style(style.current)
qtm(eu)

# expected result
qtm(eu) + tm_layout(outer.margins = rep(0.2, 4))
```
![image](https://user-images.githubusercontent.com/1825120/36863465-afa483fe-1d81-11e8-93e8-ec8da3152bf8.png)

**Comment by mtennekes** [comment]
Good point.

The current situation is that `x` in `tmap_style(x)` is the name of the style where the function `tm_style_{x}` should exist and be a shortcut of `tm_layout` (like `tm_style_white`). While implementing it in this way, I thought this was quite intuitive, but your workflow requires some amount of hacking:

```r
qtm(eu)
tm_style_current <- function() tm_style_white(outer.margins = rep(0.2, 4))
tmap_style("current")
qtm(eu)
```

If you have any suggestions how to improve the usability of styles, please let me know. I could allow assigning the output of `tm_layout` (or a shortcut function such as `tm_style_white` to the argument of `tmap_style` like you did. And/or improving the documentation with some examples such as above...

**Comment by Robinlovelace** [comment]
Thanks for the quick + constructive reply: makes more sense now although the syntax may confuse newcomers.

Suggestion: a new function + documentation could make life much easier. I'm confident that there's a better way to implement this but I'm also confident it will get used. What do you think? Can help document something like this if it goes not. If not happy to document your solution (2 lines vs 1 : ).

Reproducible example highlighting the potential benefits of a new function:

``` r
library(tmap)
data("Europe")
tm_style_update <- function(...) {
  current.style <- tmap_style()
  tm_style_current <- match.fun(paste0("tm_style_", current.style))
  tm_style_new <<- function() tm_style_current(...)
  tmap_style("new")
}
qtm(Europe)
```

![](https://i.imgur.com/oCeaoXV.png)

``` r
tm_style_update(outer.margins = rep(0.2, 4))
#> current tmap style is "white"
#> tmap style set to "new"
qtm(Europe)
```

![](https://i.imgur.com/D0fuMF1.png)

``` r
tmap_style("white")  # reset
#> tmap style set to "white"
tm_style_update(outer.margins = rep(0.2, 4), bg.color = "blue")
#> current tmap style is "white"
#> tmap style set to "new"
qtm(Europe)
```

![](https://i.imgur.com/JTfU1RF.png)

**Comment by Robinlovelace** [comment]
Problems with that hack: 

1. No autocompletion of argument names.
2. It doesn't allow you to update `tm_style_new()` seemingly...

If we could find solutions to those problems it would be an ideal fix IMO.

**Comment by mtennekes** [comment]
Thanks for your suggestion! 

Maybe it would be better/easier to use options to store and update the settings. I could wrap all default values of `tm_layout` into a list and store it as an option called `tmap.layout`, e.g. `options(tmap.layout = list(bg.color = "red", frame = FALSE))`. We can add a function `tmap_style_update` (similar like yours) to update the tmap options. When `tm_layout()` or `tm_style_...()` is called, than the specified arguents will override the tmap options temporarily. What do you think?

P.S. I was offline for two weeks, because I had a nasty bicycle crash where a broke my hip. Hopefully, I will catch up with the R stuff in the next weeks. I'm still planning to go to eRum2018 for give a tutorial on tmap.

**Comment by tim-salabim** [comment]
To not overload the API, I quite like the way leaflet does it. E.g. have functions for different options as in `leaflet(..., options = leafletOptions())` which generates a list of standard/default values but can be changed via arguments. The options are described in a different helpfile. I am planning to follow a similar approach with mapview at some stage...

**Comment by Robinlovelace** [comment]
Hi Martijn, thanks for the feedback and I hope you get well soon (as you may know one of the main applications I use **tmap** for is visualising data for sustainable transport policy, including investment in cycling). I think your suggestion sounds great. To me it sounds like your suggested `tmap_style_update()` is analogous to `leafletOptions()`. I note that `tmap_options()` and `tmap_style()` already exists and think `tmap_style_update()` is an appropriate name but is a little long... Overall it seems we're moving to a solution and I'm happy to test what you come up with.

**Comment by mtennekes** [comment]
I've implemented a solution, please check if it works as expected, and if it is easy to use. Please check https://github.com/mtennekes/tmap/blob/master/examples/tmap_options.R for an example script that illustrates how it works. Please let me know if something is unclear.

Background of the implementation: all default values of `tm_layout`, `tm_view`, and `tm_style_...` are not stored in the function definition anymore, but in a hidden list (instead of using the general R `options` list, since there are so many tmap options). All the tmap options (so all arguments of `tm_layout`, `tm_view`, and a couple of others), can be get and set with `tmap_options()`. This function already existed for the other options, but I extended it with the `tm_layout` and `tm_view` arguments.

**Comment by Robinlovelace** [comment]
This looks great to me - the demo code is really helpful and is partly reproduced in the reprex below. Happy to close this issue, great work! All I would suggest now is in terms of documentation:

- A page explaining how to create new styles. This could encourage user-contributed styles.
- A prominent link to this in the docs if not there already.

Overall these are minor points that may be to some extent already sorted so closing for now. Thanks!

``` r
# test tmap new options code
devtools::install_github("mtennekes/tmap")
#> Skipping install of 'tmap' from a github remote, the SHA1 (9d7cd1fd) has not changed since last install.
#>   Use `force = TRUE` to force installation
library(tmap)
data("World")
tm_shape(World) + tm_polygons("HPI")
```

![](https://i.imgur.com/qTsvrkw.png)

``` r
o = tmap_options()
o[1:3]
#> $unit
#> [1] "metric"
#> 
#> $limits
#> facets.plot facets.view 
#>          64           4 
#> 
#> $title
#> [1] NA
tmap_style()
#> current tmap style is "white"
tmap_style(style = "albatross")
#> tmap style set to "albatross"
tmap_options_diff()  # see what's changed - nice!
#> $bg.color
#> [1] "#00007F"
#> 
#> $aes.color
#>      fill   borders   symbols      dots     lines      text        na 
#> "#4C4C88" "#00004C" "#BFBFFF" "#BFBFFF" "#BFBFFF" "#FFE700"  "grey60" 
#> 
#> $aes.palette
#> $aes.palette$seq
#> [1] "YlOrRd"
#> 
#> $aes.palette$div
#> [1] "RdYlGn"
#> 
#> $aes.palette$cat
#> [1] "Set3"
#> 
#> 
#> $attr.color
#> [1] "#BFBFFF"
#> 
#> $basemaps
#> [1] "CartoDB.DarkMatter"
#> 
#> $basemaps.alpha
#> [1] 0.5
qtm(World)
```

![](https://i.imgur.com/x3H8j31.png)

``` r
tm_shape(World) + tm_polygons("HPI")
```

![](https://i.imgur.com/k5kTuSC.png)

``` r
tmap_options(bg.color = "green")
tmap_options_diff()
#> $bg.color
#> [1] "green"
#> 
#> $aes.color
#>      fill   borders   symbols      dots     lines      text        na 
#> "#4C4C88" "#00004C" "#BFBFFF" "#BFBFFF" "#BFBFFF" "#FFE700"  "grey60" 
#> 
#> $aes.palette
#> $aes.palette$seq
#> [1] "YlOrRd"
#> 
#> $aes.palette$div
#> [1] "RdYlGn"
#> 
#> $aes.palette$cat
#> [1] "Set3"
#> 
#> 
#> $attr.color
#> [1] "#BFBFFF"
#> 
#> $basemaps
#> [1] "CartoDB.DarkMatter"
#> 
#> $basemaps.alpha
#> [1] 0.5
tmap_style()  # shows when it's modified
#> current tmap style is "albatross (modified)"
tmap_options_reset()
```

**Comment by mtennekes** [comment]
Thx for your feedback! Just one follow-up question: what is the most convenient way to create a style? With the current approach, there is none, since this is sort-of taken over by `tmap_options`. Is there still need for users to define a style and give it a name? If so, I have two solutions in mind:

### Solution 1

We could add a function `tmap_style_save(name)` which saves the current tmap options to a style called [name], e.g.

```r
tmap_options(bg.color = "purple")
tmap_style_save(name = "purple")
tmap_style()
#> current tmap style is "purple"
```

There are two downsides: you have to apply the options before defining a new style, and sharing styles is not possible (other than sharing code, i.e. the first two lines).

### Solution 2

Another, more sophisticated,  approach would be that the list that  `tmap_options` returns has a style name attribute.

```r
purpleStyle <- tmap_options(bg.color = "purple", style = "purple")
saveRDS(purpleStyle, "tmap_style_purple.rds")
```
The style argument of the first line is the new style name. If omitted, the style will be named "white (modified)", assuming "white" is the current style.

So `purpleStyle` is the complete tmap option list with an additional attribute name, in this case "purple". This makes it easy to reuse:

```r
purpleStyle <- readRDS("tmap_style_purple.rds")
tmap_style_load(purpleStyle)
#> tmap style "purple" loaded successfully"
tmap_style("purple")
#> tmap style set to "purple"
```

I'll close this issue again when the implementation has been done.

**Comment by mtennekes** [comment]
@Robinlovelace @tim-salabim @Nowosad @sjewo: does any of you use the `tm_format_` wrappers?

The original concept behind the tmap layout options was a distinction between styles and formats. In the upcoming JSS paper (published in two weeks; I can send a draft if you like):

> The wrapper functions **tm_format_X**, with X being the name of a predefined format, specify
position related arguments, such as margins and scale, and positions of map items such as
title, legend, and map attributes. **The optimal values of these arguments may depend on the
geometry of the shape.** The default format, which is specified by the default values of the
position related arguments of tm_layout, is supposed to be of general purpose, where the
legend position is automatically determined based on the coordinates of the shape. A couple
of these predefined formats are included in the tmap package, for instance tm_layout_World,
and users are able to specify their own.
The arguments that are specified with the **tm_style_X** wrapper functions, with X being the
name of a predefined style, **do not relate to position and are therefore shape independent**. The
default style is "white", which refers to the white background. Other styles are "natural"
with natural colors, "col_blind" with color-blind friendly color palettes, and "classic",
which emulates old-style maps. The function style_catalogue generates a catalogue of all
available styles. The default style is defined in the global option "tmap.style", and can be
get and set with the function tmap_style.

However, with the new (2.0) implementation it is hard to maintain this distinction. I will probably replace the static wrapper functions `tm_style_classic` with a dynamic one: `tm_style("classic")`. In this way, it is also possible to switch to custom styles.

We can do a similar approach for formats. However, within the tmap options (so all `tm_layout` and `tm_view` arguments) there is no clear distinction between style and format options. What we could do is the following. Suppose `tmap_format("world")` is called, then the corresponding options (in this case `scale`, and `inner.margins`, `legend.position`, and `attr.position`) will override the current options.

What you you think?

**Comment by mtennekes** [comment]
Done!

See the examples:
https://github.com/mtennekes/tmap/blob/master/examples/tmap_options.R
https://github.com/mtennekes/tmap/blob/master/examples/tmap_format.R

I'll have to check the doc pages...

**Comment by Robinlovelace** [comment]
Hi Martijn, I've just had a look at those examples and I think:

- `tmap_options_diff()` is very useful, great idea
- `tmap_style_save()` seems like a good idea but does not seem to work for me (see output below), also how long is it supposed to be saved for? Beyond the session would be most useful but only the session would be most foolproof.
- I really like the messages. Super-long reprex to follow (apologies but thought it more useful to show everything and be reproducible than just the error).

**Comment by Robinlovelace** [comment]
``` r
devtools::install_github("mtennekes/tmap")
library(tmap)
data(World)
# get current options
tmap_options()
#> $unit
#> [1] "metric"
# ...
# get current style
tmap_style()
#> current tmap style is "white"
#> other available styles are: "gray", "natural", "cobalt", "col_blind", "albatross", "beaver", "bw", "classic"
# plot map (with default options)
tm_shape(World) + tm_polygons("HPI")
```

![](https://i.imgur.com/wFeNVg0.png)

``` r

# change style to cobalt
tmap_style("cobalt")
#> tmap style set to "cobalt"
#> other available styles are: "gray", "natural", "col_blind", "albatross", "beaver", "bw", "classic"

# observe the changed options
tmap_options_diff()
#> current tmap options (style "cobalt") that are different from default tmap options (style "white"):
#> $bg.color
#> [1] "#002240"
#> 
#> $aes.color
#>      fill   borders   symbols      dots     lines      text        na 
#> "#0088FF" "#002240" "#FF9D00" "#FF9D00" "#FFEE80"   "white"  "grey60" 
#> 
#> $aes.palette
#> $aes.palette$seq
#> [1] "YlGn"
#> 
#> $aes.palette$div
#> [1] "RdYlGn"
#> 
#> $aes.palette$cat
#> [1] "Set3"
#> 
#> 
#> $attr.color
#> [1] "white"
#> 
#> $basemaps
#> [1] "CartoDB.DarkMatter"
#> 
#> $basemaps.alpha
#> [1] 0.5

# plot the map again
tm_shape(World) + tm_polygons("HPI")
```

![](https://i.imgur.com/5z7QrvH.png)

``` r

# change the background color
tmap_options(bg.color = "red")

# note that the current style is modified
tmap_style()
#> current tmap style is "cobalt (modified)"
#> other available styles are: "gray", "natural", "cobalt", "col_blind", "albatross", "beaver", "bw", "classic"

# observe the changed options
tmap_options_diff()
#> current tmap options (style "cobalt (modified)") that are different from default tmap options (style "white"):
#> $bg.color
#> [1] "red"
#> 
#> $aes.color
#>      fill   borders   symbols      dots     lines      text        na 
#> "#0088FF" "#002240" "#FF9D00" "#FF9D00" "#FFEE80"   "white"  "grey60" 
#> 
#> $aes.palette
#> $aes.palette$seq
#> [1] "YlGn"
#> 
#> $aes.palette$div
#> [1] "RdYlGn"
#> 
#> $aes.palette$cat
#> [1] "Set3"
#> 
#> 
#> $attr.color
#> [1] "white"
#> 
#> $basemaps
#> [1] "CartoDB.DarkMatter"
#> 
#> $basemaps.alpha
#> [1] 0.5

# save the current options as style 'red'
tmap_style_save("red")
#> current tmap options saved as style "red"

# plot the map again
tm_shape(World) + tm_polygons("HPI")
```

![](https://i.imgur.com/7fF0jk1.png)

``` r

# the specified arguments of tm_layout and tm_view will override the options
# temporarily:
tm_shape(World) + tm_polygons("HPI") + tm_layout(bg.color = "purple")
```

![](https://i.imgur.com/bBlrICn.png)

``` r

# when tm_style_ is called, it will override all options temporarily:
tm_shape(World) + tm_polygons("HPI") + tm_layout(bg.color = "purple") + tm_style("classic")
```

![](https://i.imgur.com/7tHnYm8.png)

``` r

# reset all options
tmap_options_reset()

# check style and options
tmap_style()
#> current tmap style is "white"
#> other available styles are: "gray", "natural", "cobalt", "col_blind", "albatross", "beaver", "bw", "classic", "red"
tmap_options_diff()
#> current tmap options are similar to the default tmap options (style "white")

tmap_style(style = "red")
#> Error: current style "red" unknown, i.e. the function "tm_style_red" does not exist.
tmap_style(style = "natural")
#> tmap style set to "natural"
#> other available styles are: "gray", "cobalt", "col_blind", "albatross", "beaver", "bw", "classic", "red"
```

**Comment by Robinlovelace** [comment]
+ just tried the new function `tmap_format_add(World_small, name = "World_small")`, great work!
