### ISSUE TITLE
The default value of `auto.palette.mapping` - question

### ISSUE THREAD

**Issue by Nowosad** [mtennekes/tmap#181]
@mtennekes, I've a question regarding to the `auto.palette.mapping` argument. As a default it is set to `TRUE`. This often confuses me. For example, I select a palette using `tmaptools::palette_explorer()` but in the final map I only get a half of possible colors (due to `auto.palette.mapping=TRUE`). In my opinion, `auto.palette.mapping = FALSE` is a better default as it does not add any unnecessary confusion.  What do you think about that? Or maybe I miss some point here?

``` r
library(sf)                                                                                     
#> Linking to GEOS 3.6.1, GDAL 2.1.4, proj.4 4.9.3
library(spData)                                                                                 
library(tmap)                                                                                   
breaks = c(0, 3, 4, 5) * 10000                                                                  
                                                                                                
# auto.palette.mapping = TRUE ---------------------------------------------                     
pa1 = tm_shape(nz) + tm_fill(col = "AREA_SQ_KM")                                                
pa2 = tm_shape(nz) + tm_fill(col = "AREA_SQ_KM", breaks = breaks)                               
pa3 = tm_shape(nz) + tm_fill(col = "AREA_SQ_KM", n = 10)                                        
pa4 = tm_shape(nz) + tm_fill(col = "AREA_SQ_KM", palette = "RdBu")                              
                                                                                                
# auto.palette.mapping = FALSE --------------------------------------------                     
# the same output                                                                               
pm1 = tm_shape(nz) + tm_fill(col = "AREA_SQ_KM", auto.palette.mapping = FALSE)                  
# the same output                                                                               
pm2 = tm_shape(nz) + tm_fill(col = "AREA_SQ_KM", breaks = breaks, auto.palette.mapping = FALSE) 
# the same output                                                                               
pm3 = tm_shape(nz) + tm_fill(col = "AREA_SQ_KM", n = 10, auto.palette.mapping = FALSE)          
# different output                                                                              
pm4 = tm_shape(nz) + tm_fill(col = "AREA_SQ_KM", palette = "RdBu", auto.palette.mapping = FALSE)
                                                                                                
tmap_arrange(pa1, pa2, pa3, pa4)                                                                
```

![](https://i.imgur.com/qYMrS8G.png)

``` r
tmap_arrange(pm1, pm2, pm3, pm4)                                                                
```

![](https://i.imgur.com/2iJCC9U.png)

**Comment by mtennekes** [comment]
Thx for your input. It's a difficult one. The intended use for `auto.palette.mapping` is the case where a variable contains both positive and negative values, and a diverging palette is selected. In this case, the neutral color will be mapped to 0 (which generally makes sense). Your application, in which one part of the diverging palette is not shown since there are no negative values, is one that I encountered many times.

For sequential palettes, there is also a difference, albeit very subtle. When `auto.palette.mapping = TRUE`, the contrast of the palette (see `tmaptools::palette_explorer() `) depends on `n`. When there are few categories, the contrast is somewhat reduced. You can see this in your top-left and -right maps. This is similar to `RColorBrewer`:
```r
> RColorBrewer::brewer.pal(9, "Blues")
[1] "#F7FBFF" "#DEEBF7" "#C6DBEF" "#9ECAE1" "#6BAED6" "#4292C6" "#2171B5" "#08519C" "#08306B"
> RColorBrewer::brewer.pal(3, "Blues")
[1] "#DEEBF7" "#9ECAE1" "#3182BD"
```

When `auto.palette.mapping = FALSE` the palette is taken as-is.


I'm not sure what is the best setting, also bearing in mind that I do not prefer to change default settings for consistency reasons (unless it is an definite improvement). Maybe, we can come up with a hybrid solution. Or, another alternative is to give a warning when the user applies a diverging color palette to a non-diverging variable. What do you think?

**Comment by Nowosad** [comment]
@mtennekes thanks for this answer. I agree it's a difficult one and I understand if you don't change anything here.

My problem with the default value of `auto.palette.mapping` is it trying to be "smarter" than a user. E.g. user selects and expects a diverging palette and get's something else. The same issue is regarding to sequential palettes - if somebody provides a palette with three values, this person expects those colors to be plotted and instead it gets something different... My thinking here would be changing the default to `FALSE`.

Maybe @Robinlovelace has some ideas here...

**Comment by mtennekes** [comment]
Just a note: the reduced contrast is only applied when the palette is a ColorBrewer name, not when the user provides manual colors. I am pretty sure I want to keep it this way by default.

For diverging palettes I tend to agree with you. However, on the other side, when a variable does contain negative and positive values, and the user specifies a diverging palette, the out-of-the-box solution where the middle color is mapped to 0 is desirable as default behavior, I think...

**Comment by Nowosad** [comment]
You are definitely right about the first example. 

Regarding to the second one - there are more examples of the use of diverging palettes than only for negative vs positive values. These palettes are used to show a departure from a reference value, which is not always zero. It could be a probability (e.g. less or more than 50%) or a ratio (e.g. sex ratio - https://en.wikipedia.org/wiki/List_of_countries_by_sex_ratio), etc.

**Comment by mtennekes** [comment]
@Nowosad: suppose we would replace `auto.palette.mapping` by other argument(s). What would you like?

One options is to have an argument `midpoint`, which simply determines which value will be shown as the neutral color. By default, we can set it to `NA` meaning the mean value (similar to `auto.palette.mapping = FALSE`.  In case the value range is from -10 to 40, the midpoint will therefore be set to 15 by default. However, for the user it is much more intuitive to specify `midpoint = 0` than `auto.palette.mapping = TRUE` (in case we would follow your suggestion to set it to FALSE by default).

However, what colors are assigned to the min and max values when `midpoint = 0`? Currently (with `auto.palette.mapping = TRUE`), 40 is dark green and -10 light orange. I think that is more desirable in most cases than mapping -10 to dark red. See also the bubble colors of https://github.com/mtennekes/tmap/tree/master/demo/BubbleMap

We can let the users apply the current `contrast` argument to truncate the red side of the color scale (i.e. `contrast = c(.25, 1)` means that the first quarter of the diverging palette is omitted), but this is not ideal for out-of-the-box mapping.

Once the midpoint is set, I think there are three common ranges to which both extreme colors of the diverging palette can be mapped:

* [`min(abs(values))`, `max(abs(values))`]
* [`min(values)`, `max(values)`]
* user specified values

If we follow this track, what would be a good interface to let users specify this range?

Of course, I'd like to hear any other approaches to make the palette mapping more intuitive.

**Comment by Nowosad** [comment]
@mtennekes - I'm going to think about it and let you know in the next few days. 
@Robinlovelace Do you have any ideas?

**Comment by Robinlovelace** [comment]
Just taken a look at this issue, indeed an interesting one and don't think there's any objective answer. Ultimately the user should have complete control over the palette and as long as that's possible it's a question of documentation.

For the record I don't think either is particularly good using the new Population variable in `nz`:

``` r
devtools::install_github("nowosad/spData")
#> Using GitHub PAT from envvar GITHUB_PAT
#> Skipping install of 'spData' from a github remote, the SHA1 (e59996ff) has not changed since last install.
#>   Use `force = TRUE` to force installation
library(spData)
library(tmap)
tm1 = tm_shape(nz) + tm_fill(col = "Population", palette = "RdBu")
tm2 = tm_shape(nz) + tm_fill(col = "Population", palette = "RdBu", auto.palette.mapping = FALSE)
tmap_arrange(tm1, tm2)
```

![](https://i.imgur.com/alOZxT3.png)

One think I've done in the past (I think with leaflet) was manually set the midpoint. Is that possible?

I think in the docs it should show that you can set the colors manually. This is an awesome feature btw that I suggest we document in the book (cc @Nowosad and @jannes-m ), as illustrated below:

``` r
devtools::install_github("nowosad/spData")
#> Using GitHub PAT from envvar GITHUB_PAT
#> Skipping install of 'spData' from a github remote, the SHA1 (e59996ff) has not changed since last install.
#>   Use `force = TRUE` to force installation
library(spData)
library(tmap)
n = 6
rcols = RColorBrewer::brewer.pal(n = n, "RdBu")
bins = classInt::classIntervals(var = nz$Population, style = "jenks", n = n)
nz$cols = as.character(cut(x = nz$Population, breaks = bins$brks, labels = rcols))
plot(nz$geom, col = nz$cols)
```

![](https://i.imgur.com/S5ISBFk.png)

``` r
tm_shape(nz) + tm_fill(col = "cols")
```

![](https://i.imgur.com/G09C3gz.png)

**Comment by Robinlovelace** [comment]
But is there a way of getting that final map while preserving the legend?

**Comment by Nowosad** [comment]
```r
library(tmap)
library(spData)
tm_shape(nz) + tm_fill(col = "Population", style = "jenks", 
    palette = "RdBu", auto.palette.mapping = FALSE, n = 6)
```

(Almost the same, but without this white (missing??) area)

**Comment by Robinlovelace** [comment]
Ah that solves it. So it's just the question of how to set the mid-point that remains for me. One to document. Thanks for all the awesome changes recently Martijn!

**Comment by mtennekes** [comment]
Thanks for your input!

I agree that midpoint is a great addition. I think I will improve the `auto.palette.mapping = TRUE` a little: when the range is either negative or positive, then the midpoint will be set to `mean(min, max)`, and when the range crosses 0, then the midpoint will be set to 0. Again, this is an automatic setting, which can be turned off by `auto.palette.mapping = FALSE`.

What remains is the question how to extremes of the diverging palette are mapped. Suppose the range is `[-2, 10]`, and the midpoint = 0, should -2 be colored by the darkest color of the palette, or by the color with the same brightness as the color by which 2 is colored?

**Comment by Nowosad** [comment]
I would expect (as a user) that -2 would be colored with the same brightness as 2.

**Comment by dschneiderch** [comment]
stumbled on this discussion because of issues with `auto.palette.mapping` that, after reading this, make sense.

I wholeheartedly agree that a midpoint argument would be useful to improve user control of the color palette. For comparison, ggplot2 uses midpoint=0 as the default for the diverging `scale_*_gradient2()` so that's what I expected.  

I would also expect -2 and 2 to have the same brightness in a range of [-2, 10] where the midpoint is 0.

**Comment by mtennekes** [comment]
Thanks! There are negative values, so the midpoint is snapped to 0. Therefore, you'll only see one side of the palette. I've added a message that could help in this case. Feel free to re-reopen if it doesn't work as expected.

**Comment by Nowosad** [comment]
This message is very helpful. Thanks

**Comment by Nowosad** [comment]
@mtennekes (I don't know if that's the best idea - treat this just as my thought):
- How about using `midpoint = NA` as a default and `midpoint = 0` only when diverging palette is set?

**Comment by mtennekes** [comment]
Not sure if I understand the background of your question. 

Currently, `midpoint = 0` is only used for diverging palettes when there are positive and negative values. For instance `qtm(World, "HPI", fill.palette = "RdYlGn")` uses `midpoint  = NA` as default.

Note that there are two things tmap considers:

1. Values. They can be diverging (i.e. when there are positive and negative values), sequential or categorical.
2. Palette type. Also one of `cat` (categorical), `seq` and `div`. By the (ColorBrewer) palette name, tmap knows which palette it is. If a manual color palette is provided, tmap guessed the type based on order brightness of the colors (a diverging palette is bright in the middle, whereas a sequential palette is bright at one end).

If the palette type (2) is undefined, then the default palette from `tmap_options("aes.palette")` is used. Which one, depends on the values (1). So, for example, if values are in the range [12, 44] and palette is undefined, `tmap_options("aes.palette")[[1]]$seq` is used. In `nz_elev` there are positive and negative values, so `tmap_options("aes.palette")[[1]]$div` is used.

Any combination of Values type and palette type is possible. E.g. 

```{r}
tm_shape(nz_elev) +
 	tm_raster(palette = "Reds")
```

Values are diverging, palette is sequential. In this case, midpoint is not used (PS: I just removed the message about the midpoint).

**Comment by Nowosad** [comment]
@mtennekes - I was probably confused, when I used a sequential palette and the midpoint message was printed. I will retest it later today.

**Comment by Nowosad** [comment]
I works as expected now;)
