### ISSUE TITLE
tm_tiles in plot mode

### ISSUE THREAD

**Issue by dschneiderch** [mtennekes/tmap#185]
first, Awesome package!
I was trying out your dev version because I am excited to be able to use basemaps in "plot" mode!

I apologize if this is an unfinished feature and this issue is superfluous.

The help describes `tm_basemap` as only available in "view" mode. To insert a basemap in "plot" mode, 

>  For plot mode, a tile image can be retrieved by read_osm. tm_tiles draws the tile layer as overlay layer where it follows the plotting order in which this layer is called.

So I was expecting to do 

```
library(sf)
library(tmap)
counties <- sf::st_as_sf(maps::map(database='county',regions='idaho',fill=TRUE,plot=F))
tmap_mode('plot')
CBS_osm2 <- tmaptools::read_osm(counties,raster=TRUE, type="stamen-terrain")
tm_tiles(CBS_osm2)+
tm_shape(counties)+tm_borders()

```

only the vector is plotted and an warning is given: 

`Warning message: In is.na(g$server) : is.na() applied to non-(list or vector) of type 'S4'`

This gives no warning but doesn't plot a basemap, only the vector

```
tm_shape(counties)+
  tm_borders(alpha=0.5)+
  tm_tiles(server=leaflet::providers$Stamen.TerrainBackground)
```

Interestingly, this works exactly as expected:

```
qtm(CBS_osm2)+
  tm_shape(counties)+tm_borders()
```

Perhaps there is simply some clarification needed in the documentation

**Comment by FolkyHobbit** [comment]
>  In plot mode, you'll need to explicitly read the tiles from a tile server and get a raster or a SpatialGridDataFrame object, which can indeed be done with `read_osm`.

Maybe you could help me out with this? Is there a way to read tiles from a tile server, other than from OSM? In my case satellite image data from PDOK (Dutch public geoservice) available as WMS, WMTS or TMS.

**Comment by francisbarton** [comment]
I would love it if it were easier to get `tm_basemap` and `tm_tiles` to work in plot mode.

The advice in the `tmap` docs is to use `read_osm`. I installed Java in order to get this working but it is not working for me (`read_osm` produces a 403 error when trying to download the tiles PNGs from OSM).

The documentation for `osmdata` (https://cran.r-project.org/web/packages/osmdata/vignettes/osmdata.html) says that it is for downloading vector data from OSM, not for raster files, and suggests using the `OpenStreetMap` package instead. It doesn't seem like `osmdata` is the right package to use to get the tiles that `tmap` would need.

I don't have enough knowledge to help fix this. Any ideas anyone? Does anyone have basemaps and overlays working in plot mode?

**Comment by francisbarton** [comment]
When I do:

`tm_shape(shp) +
tm_rgb()`

I get the error

> Error: shp consists of polygons, so it cannot accept tm_raster.

But `qtm(shp)` works fine - no error message - but no basemap either.

**Comment by djouallah** [comment]
I use ceramic package and it is working great, tmap is a great package

just an example
```
library(ceramic)
Sys.setenv(MAPBOX_API_KEY = "get code from mapbox")
map <- st_as_sf(dataset, coords = c("x", "y"), crs = 4326)
background <- cc_location(map)
tm_shape(background)+
 tm_rgb() +
```

**Comment by Lucius117** [comment]
When I do read_osm(sf_dataset)

`read_osm(sf_dataset, type = "osm")`

I get an error:

> Error in FUN(X[[i]], ...) : Sorry, parameter type `NA' is ambiguous or not supported.

Also, get the same result when running example code in the help document

**Comment by djouallah** [comment]
@gregmacfarlane just add another tm_shape(map)

```
library(sf)
library(dplyr)
library(tmap)
library(ceramic)
library(tmaptools)
Sys.setenv(MAPBOX_API_KEY = xxxxxxxxxx")
map <- st_as_sf(dataset, coords = c("x", "y"), crs = 4326)
background <- cc_location(map)
tm_shape(background)+
 tm_rgb() +
tm_shape(map) +
tm_symbols(col = "color", size = 0.04,shape=19)+
```

**Comment by francisbarton** [comment]
I saw this when you posted this originally @djouallah - and I've finally got around to using it myself.

This works great for me:
```{r}
library(ceramic)

ctr <- c(-1.25, 53.095)
bfr <- c(1.4e4, 1.7e4)

# other types are "mapbox.light", "mapbox.dark", "mapbox.satellite", "mapbox.streets",
# and in theory "mapbox.satellite-streets"...
# [](https://docs.mapbox.com/api/maps/#mapbox-styles)
# [](https://hypertidy.github.io/ceramic/)
ashfield_bg_outdoors <- cc_location(ctr, buffer = bfr, type = "mapbox.outdoors")

basemap <- tm_shape(ashfield_bg_outdoors) +
  tm_rgb()
```

**Comment by francisbarton** [comment]
My latest preferred solution to this is to use {`mapmisc`} instead of {`ceramic`}.

```
basemap_tiles <- mapmisc::openmap(shp, path = "hyda-base") # the spelling of "hydda" is wrong in the package
basemap <- tm_shape(basemap_tiles) + tm_rgb()
```

Lots of different map options not just the mapbox ones you get with `ceramic`.
And totally simple to use.

**Comment by francisbarton** [comment]
Just pointing back to [a related thread](https://github.com/prabhasp/OpenStreetMap.R/issues/1) in case anyone else ends up here looking for help with `read_osm`.
