### ISSUE TITLE
Error while plotting SpatialLinesDataFrame in interactive mode

### ISSUE THREAD

**Issue by manuelwaltschek** [mtennekes/tmap#189]
Hello there, I am facing an issue while plotting a SpatialLinesDataFrame object with tmap in interactive mode. 

The following line produces the following error only in interactive mode:
`tm_shape(spl, is.master = TRUE) + tm_lines()`

> Error in .local(obj, ...) : NA values in coordinates

I will provide the Spatial object which I saved with:
`saveRDS(spl, file="spl")`

Of course I know that this is not an object of the type data.frame, but it produces the same error and I did not want to provide the whole data.

I will be really happy if you could reproduce my problem, since I cannot believe that there are any na values in the coords slot of any of the Lines objects.

Regards
[spl.zip](https://github.com/mtennekes/tmap/files/1942962/spl.zip)

**Comment by manuelwaltschek** [comment]
BTW this is the function I used for creating the SpatialLinesObject:

```
listcoords <- lapply(split(df, df$weg_id), function(x){
  if(!is.na(x$lng_quelle) && !is.na(x$lng_ziel) && !is.na(x$lat_quelle) && !is.na(x$lat_ziel)){
    lng = c(x$lng_quelle, x$lng_ziel)
    lat = c(x$lat_quelle, x$lat_ziel)
    Lines(Line(cbind(lng, lat)), ID = x$weg_id)}})

spl<- SpatialLines(listcoords, proj4string = CRS("+init=epsg:4326"))
spl = spTransform(spl, projSalzburg)
spldf = SpatialLinesDataFrame(sl = spl, data = df, match.ID = "weg_id")
```

**Comment by mtennekes** [comment]
Did you use the latest github version of `tmap`?

I can run the code without errors:

![screenshot from 2018-04-25 09-24-52](https://user-images.githubusercontent.com/2444081/39231534-b3d02820-486a-11e8-89cf-ee242d9c17ee.png)

**Comment by manuelwaltschek** [comment]
Well I used the latest packages from CRAN and it didn't work. Now I tried to install tmap from github with the devtools package and got the following error:

`githubinstall::gh_install_packages("tmap")`

> Suggestion:
>  - mtennekes/tmap  R package for thematic maps
> Do you want to install the package (Y/n)?  Y
> Installing "tmap" package from GitHub, but already installed from CRAN.
> This package is already installed. Are you sure you want to overwrite it (Y/n)?  Y
> Downloading GitHub repo mtennekes/tmap@master
> from URL https://api.github.com/repos/mtennekes/tmap/zipball/master
> Installing tmap
> Installing 1 package: classInt
> Installing package into ‘C:/Users/manuel.waltschek/Documents/R/win-library/3.4’
> (as ‘lib’ is unspecified)
> trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/classInt_0.2-3.zip'
> Content type 'application/zip' length 56746 bytes (55 KB)
> downloaded 55 KB
> 
> package ‘classInt’ successfully unpacked and MD5 sums checked
> 
> The downloaded binary packages are in
> 	C:\Users\manuel.waltschek\AppData\Local\Temp\RtmpGSFWlM\downloaded_packages
> Installing 1 package: rgdal
> Installing package into ‘C:/Users/manuel.waltschek/Documents/R/win-library/3.4’
> (as ‘lib’ is unspecified)
> trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/rgdal_1.2-18.zip'
> Content type 'application/zip' length 32726339 bytes (31.2 MB)
> downloaded 31.2 MB
> 
> package ‘rgdal’ successfully unpacked and MD5 sums checked
> Warning: cannot remove prior installation of package ‘rgdal’
> 
> The downloaded binary packages are in
> 	C:\Users\manuel.waltschek\AppData\Local\Temp\RtmpGSFWlM\downloaded_packages
> Installing 1 package: spdep
> Installing package into ‘C:/Users/manuel.waltschek/Documents/R/win-library/3.4’
> (as ‘lib’ is unspecified)
> trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/spdep_0.7-7.zip'
> Content type 'application/zip' length 2385503 bytes (2.3 MB)
> downloaded 2.3 MB
> 
> package ‘spdep’ successfully unpacked and MD5 sums checked
> 
> The downloaded binary packages are in
> 	C:\Users\manuel.waltschek\AppData\Local\Temp\RtmpGSFWlM\downloaded_packages
> Installing 1 package: tmaptools
> Installing package into ‘C:/Users/manuel.waltschek/Documents/R/win-library/3.4’
> (as ‘lib’ is unspecified)
> Warning: package ‘tmaptools’ is in use and will not be installed
> "C:/PROGRA~1/R/R-34~1.3/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
>   "C:/Users/manuel.waltschek/AppData/Local/Temp/RtmpGSFWlM/devtools5742273dc2/mtennekes-tmap-1311621"  \
>   --library="C:/Users/manuel.waltschek/Documents/R/win-library/3.4" --install-tests 
> 
> ERROR: dependencies 'tmaptools', 'rgdal' are not available for package 'tmap'
> * removing 'C:/Users/manuel.waltschek/Documents/R/win-library/3.4/tmap'
> In R CMD INSTALL
> Installation failed: Command failed (1)

I then tried to clone the repo and install tmap with the following line:

`install.packages("tmap", lib="C:\Users\manuel.waltschek\Documents\R\external-libs\tmap")`

but the NA-error still occures

**Comment by mtennekes** [comment]
Sorry, you'll also need the github version of tmaptools. I didn't know the `githubinstall` package, but it seems similar to devtools:

```{r}
library(devtools)
install_github("mtennekes/tmaptools")
install_github("mtennekes/tmap")
```

Regarding the warning: cannot remove prior installation of package `rgdal`: I think you'll have to restart R, or, if that doesn't work, delete `rgdal` manually.

**Comment by manuelwaltschek** [comment]
Thank you, I didn't know that I had to install tmaptools and tmap in a specific order. Now it worked, but it also required to install package `lwgeom`

**Comment by Nowosad** [comment]
Close?

**Comment by mtennekes** [comment]
Thx for issue cleaning @Nowosad  (PS feel free to close them yourself)
