### ISSUE TITLE
The output map with a raster layer has smaller margins. 

### ISSUE THREAD

**Issue by Nowosad** [mtennekes/tmap#191]
Maps (i) without a raster layer and (ii) with a raster layer but using `tmap_arrange()` are rendered correctly. However, maps with a raster layer are clipped (or just inner margins are smaller in compare to vector maps). A few examples:

``` r
  library(spData)
  library(spDataLarge)
  library(tmap)
  library(sf)
#> Linking to GEOS 3.6.1, GDAL 2.1.4, proj.4 4.9.3
  library(raster)
#> Loading required package: sp
  
  map_nz = tm_shape(nz) + tm_polygons()
  
  map_nz1 = map_nz +
    tm_shape(nz_elev) + tm_raster(alpha = 0.7)
  
  nz_water = st_union(nz) %>% st_buffer(22200) %>%
    st_cast(to = "LINESTRING")
  map_nz2 = map_nz1 +
    tm_shape(nz_water) + tm_lines()
  
  map_nz3 = map_nz2 + 
    tm_compass(type = "8star", position = c("right", "top")) +
    tm_scale_bar(breaks = c(0, 100, 200), size = 1)
  
  map_nz4 = map_nz + 
    tm_compass(type = "8star", position = c("right", "top")) +
    tm_scale_bar(breaks = c(0, 100, 200), size = 1)
  
  # works well
  tmap_arrange(map_nz1, map_nz2, map_nz3)
```

![](https://i.imgur.com/n1qrYZm.png)

``` r

  # works well  
  map_nz4
```

![](https://i.imgur.com/bSmjF36.png)

``` r
  
  # works not so well
  map_nz3
```

![](https://i.imgur.com/I5h7r2M.png)

Created on 2018-04-29 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by mtennekes** [comment]
Yes, you already gave the answer: for rasters the inner.margins are set to 0 by default. The reason is that it is generally preferable, especially a whole raster with a frame:

``` r
library(tmap)
library(tmaptools)
data(land)
tm_shape(land) + tm_raster("cover")
#> Linking to GEOS 3.5.1, GDAL 2.2.2, proj.4 4.9.2
```

![](https://i.imgur.com/TCwavAm.png)

``` r

osm <- read_osm("Valkenburg, Netherlands")

qtm(osm)
```

![](https://i.imgur.com/ht2W5vv.png)

You can increase the margins by either setting inner.margins or by making another shape the master, e.g.

```{r}
map_nz2 = map_nz1 +
    tm_shape(nz_water, is.master = TRUE) + tm_lines()
```

**Comment by Nowosad** [comment]
Thanks Martijn, indeed that makes sense. The `is.master` argument is what I've been looking for.
