### ISSUE TITLE
environments related bug

### ISSUE THREAD

**Issue by mtennekes** [mtennekes/tmap#193]
``` r
mytitle1 <- "this one works"

data(World)
print(tm_shape(World) + tm_polygons() + tm_layout(title = mytitle1))


f <- function(mytitle2) {
	data(World)
	print(tm_shape(World) + tm_polygons() + tm_layout(title = mytitle2))
}

f("this doesn't")

Error in FUN(X[[i]], ...) : object 'mytitle2' not found 
```

The object `mytitle2` cannot be found in the parent environment (see https://github.com/mtennekes/tmap/blob/master/R/tm_layout.R#L198). Anyone knows how to fix this, maybe @edwindj?

**Comment by mtennekes** [comment]
StackOverFlow will come to rescue:-)

https://stackoverflow.com/questions/50314641/how-to-access-variables-from-higher-environments-in-r

**Comment by tim-salabim** [comment]
maybe... https://stackoverflow.com/a/50314934/2555983

**Comment by tim-salabim** [comment]
Answering your question about erum here, as Stackoverflow doesn't seem to be the right place. Answer is No. I have an agreement with my employer to attend useR every second year (when in Europe). I would need to take annual leave for erum, but I'd rather spend that with firends and family. Also, i am already taking a week of annual leave for geostat2018 in Prague... Are you going?

**Comment by mtennekes** [comment]
That's a pity. Yes, and we will give two workshops tomorrow: in the morning, @Robinlovelace @Nowosad and @jannes-m will give a general workshop on spatial data in R, and I'll give a workshop on tmap.

**Comment by tim-salabim** [comment]
That is indeed a pity! Have fun and say hello to the others!
