### ISSUE TITLE
tm_facets: issue when varying col, size and facet: Error in classIntervals() :    var is not numeric

### ISSUE THREAD

**Issue by MatthieuStigler** [mtennekes/tmap#197]
Hi

I am trying to map a point dataset, where I want to vary `col` and `size` according to some variable, then vary `facet` according to a third variable. I notice two problems:

* when the facetting variable is the same as the col one, only one colour is plotted, and legend shows only one value?
* when the facetting variable is a third variable, I end up getting an error message like: `Error in classIntervals(x, n, style = style, intervalClosure = interval.closure) :   var is not numeric`

Not sure what is happening, am I doing something wrong?

Thanks!

```
library(sf)
library(tmap)

data(metro)
m2 <- metro %>%
    st_as_sf() %>%
    mutate(var_fac1 = ifelse(1:nrow(.) < 200, "A", "B"),
           var_fac2=  ifelse(1:nrow(.) < 220, TRUE, FALSE)) 


tm_shape(m2)+
  tm_bubbles(col="var_fac1", size="pop2010") 

```

Facet variable is same as colour: only one colour shown/in legend?

```
tm_shape(m2)+
  tm_bubbles(col="var_fac1", size="pop2010") +
  tm_facets("var_fac1")

tm_shape(m2)+
  tm_bubbles(col="var_fac2", size="pop2010") +
  tm_facets("var_fac2")

```

![example_fac2](https://user-images.githubusercontent.com/108840/39964445-9b3f1dfc-5639-11e8-827f-b30215df5fc9.png)

Facet variable is a third one: error? 
```

tm_shape(m2)+
  tm_bubbles(col="var_fac2", size="pop2010") +
  tm_facets("var_fac1")

tm_shape(m2)+
  tm_bubbles(col="var_fac1", size="pop2010") +
  tm_facets("var_fac2")
```

**Comment by mtennekes** [comment]
It works for the latest development version. Recently, I improved the code for faceting. If you come across bugs or unexpected behavior, please let me know.
