### ISSUE TITLE
Interactivity

### ISSUE THREAD

**Issue by mtennekes** [mtennekes/tmap#20]
A follow-up thread from https://github.com/mtennekes/tmap/commit/75d70a8a9f6c3b2c47e26e3abfce7f66e93b0b96

Below on overview on the ideas regarding interactivity so far. I'm also trying to figure out how the interactivity works from a user perspective. Comments and ideas are welcome.

Basic interactivity:
* No zooming nor panning
* Mouse-over: 
  - show (thicker) borders of object. If objects have no color aesthetics, color highlighting/opacity can be added as well.
  - show hover text, which contains: 
    1. the name/id value of the object. Each layer function (e.g. ```tm_bubbles```) will get an ```id``` argument, in which the variable name of the id/name can be given.
    2. the values that are linked to the aesthetics of the corresponding layer.
    For example if we have a bubble map of cities, the hover text could be:
    
    **London**
    pop2010: 9,698,872
    growth: 1,19
* How does the user enable interactivity, or is it by default interactive? I could add an argument ```interactive``` to ```tm_layout```, that is ```TRUE``` by default.
* Implementation: via ```gridSVG```, maybe wrapped to an ```htmlwidget```?
     
More advanced interactivity:
* Zooming and panning
* Mouse-over: similar to above
* Implementation: ```htmlwidgets``` with javascript ```d3``` and ```leaflet``` for OSM layers. In this case, ```tmap``` would be not so very different from the R package ```leaflet```, or is it? As far as I know, that package (which I like very much) is lower level, and has some limitations (e.g. no bubble size legend). Maybe, we could also *use* the R package ```leaftlet```...

Let me know what you think.

**Comment by timelyportfolio** [comment]
Actually, zooming and panning is really simple using the `svgPanZoom` htmlwidget (see [Week 2 | svgPanZoom](http://www.buildingwidgets.com/blog/2015/1/15/week-02-)).  I added a simple example in https://github.com/mtennekes/tmap/commit/ae7266138e64c87ba5bd5d0b9deb65ac8b8f6b5e in these [lines](https://github.com/mtennekes/tmap/blob/ae7266138e64c87ba5bd5d0b9deb65ac8b8f6b5e/test/test_gridSVG.R#L63-L74).

**Comment by timelyportfolio** [comment]
This [recent tweet](https://twitter.com/chrtze/status/618440803900387328) provides a good reference piece for basic interactivity and another good example for replication in `tmap`.

**Comment by timelyportfolio** [comment]
Just a note, but `tm_facets()` will probably require lots of special attention for interactivity.

**Comment by timelyportfolio** [comment]
`svgPanZoom` is now on CRAN, so if we decide to use, it is ready.

**Comment by mtennekes** [comment]
Great, thanks!!! 

The pan up/down is still reversed when ```viewportSelector = "#mapElements\\.1"````. I assume that this is due to the fact the coordinate origin (or minimal point) in shapes is typically bottom-left, while in SVG, this is top-left. So panning the whole SVG is no problem, but panning the mapElements viewport with the shape coordinates is reversed.

**Comment by timelyportfolio** [comment]
Your assumption is correct.  I believe I can just intercept the pan zoom event and correct it, but I have not had a chance to try it yet.

**Comment by timelyportfolio** [comment]
@mtennekes, so I think the first round of interactivity integration has progressed rather nicely.  I'm wondering though, "Is it now so bulky that it should be moved into its own package?"  As we started this, I had envisioned a lightweight conversion to svg with a couple little bells and whistles, but it has sort of taken a life of its own with quite some  accompanying weight of dependencies. Just wanted to make sure you knew that I'm good either way.

One other thing that has been bothering me is that the CSS `id` assigned throughout the `svg` will very likely cause conflicts if they coexist with other interactive `tmap` on a single `HTML` page.  Since `htmlwidgets` are designed to be composable, this is a very likely scenario.  I"ll take a pass at removing them or converting them to `class` and assessing the impact.

**Comment by timelyportfolio** [comment]
These lines https://github.com/timelyportfolio/tmap/blob/devel/pkg/R/itmap.R#L139-L157 should fix our conflicting `id` problem.

**Comment by mtennekes** [comment]
I'm also okay with both options. Are there any downsides to migrating the interactive part to its own package? The maintenance aspect will be quite similar: we'll have to communicate anyway if something in `tmap` has changes that may influence the code of the interactive part.

**Comment by timelyportfolio** [comment]
I only see three potential downsides:

1.  A user might go unaware of the secondary package if it is not integrated.  However, I think much of this can be solved with extensive discussion, examples, and cross-references within the documentation.  I'm thinking sort of like `latticeExtra` with `lattice` or `gridExtra` with `grid`.  Also, i would think it would be best if the Github repo existed under @mtennekes or a new `tmap` organization.

1.  A user would have to install two packages to get the additional functionality.  I don't think this would be an impediment as long as both existed on `CRAN`.  Maybe we could even add an install message with `tmap` letting users know that the interactive version exists and requires a separate install.

1.  We would have to come up with a name :).  `itmap`, `tmap_widget` seem like two decent candidates, but I'm open to anything.

In terms of development workflow, I don't see anything changing with tight communication and quick, responsive integration of new functionality and changes in the API.  I'll be happy to commit to that.

To the advantages, we could remove 4 package dependencies from `tmap` core, which significantly eases the burden for someone not interested in the interactive component.

```
Imports:
    gridSVG,
    htmlwidgets,
    svgPanZoom,
    XML
```

**Comment by mtennekes** [comment]
Not sure which option I prefer. Actually, the burden of dependencies is inevitable for a high-level package like `tmap`. For instance, for OSM support, I had to add two dependencies as well, which on their own have dependencies including `rJava`. (FYI, I asked the author of OpenStreetMap to replace raster from Depends to Imports, as its `select` function conflicts with `dplyr::select`.)

What kind of future directions do you have in mind for the interactivity? I mean, does it get any bulkier? I can imagine a nice looking shiny app that includes the widget. If so, I favor a new package.

If we decide to create a new package:
* The name should start with `tmap` I think, for better findability. So `tmap_widget` sounds good to me. On the other hand, the function name `itmap` is very short and hence effective. A package name equal to a function name is also handy.
* Do you want to be maintainer? I guess will we both be main authors.

**Comment by timelyportfolio** [comment]
Good example, the `rJava` dependency proved problematic for me as I first wanted to play with `tmap` and also prevented me from enjoying your amazing project.  One last desperate attempt got me up and running.

Future directions on interactivity would most likely move toward a fuller `htmlwidget` implementation, so additional dependencies would probably be

1. `JS/CSS` dependencies (no install required, just some additional files)
2. `htmlwidgets`
3. `htmltools`

Another idea I had was to provide 3 export options instead of the one currently available.  This might argue toward a single package without an ancillary `htmlwidget`.

1. cleaned up `SVG` for export to Illustrator/Sketch/Inkscape would probably be nice for more graphics oriented shops who might just need a base for further customization
2. SVG + mouseover and tooltips
3. all of above + `svgPanZoom`

If a new package, I'm really not all that particular about details.  I would think you would still be main author, and I could be maintainer to hopefully help divert issues/requests from you, so you can focus on `tmap`.

**Comment by mtennekes** [comment]
Sound like a good plan! However, I don't understand what you mean by "This might argue toward a single package without an ancillary `htmlwidget`.".

**Comment by timelyportfolio** [comment]
@mtennekes I'm back on the side of just leaving it all-in and having `tmap` be comprehensive.  Nice work on the recent commits.  Love the teaser :)

**Comment by timelyportfolio** [comment]
Even more amazing is `itmap` nearly completely works with the github_teaser :+1:

**Comment by mtennekes** [comment]
Tnx! I also saw that the backgroud rect disappeared in `itmap`, but it should indeed be an easy fix.

**Comment by timelyportfolio** [comment]
CRAN now has the updated `svgPanZoom`, so should be all set there.

**Comment by mtennekes** [comment]
There are still two minor bugs. @timelyportfolio could you take a look at this?

1. The viewer pane in RStudio has scroll bars. This is probably caused by the margins between the map and the pane window frame.
2. When zooming with the mouse wheel, the map shifts upwards, as if the mouse pointer is in the center of Antarctica. To illustrate this, I point the mouse at Madrid

![image1](https://cloud.githubusercontent.com/assets/2444081/10646415/3ee5948c-7833-11e5-8902-602d3453b767.jpg)

and zoom in while keeping the mouse pointer in Madrid

![image2](https://cloud.githubusercontent.com/assets/2444081/10646419/464f1108-7833-11e5-95b2-0e4762792062.jpg)

Versions of relevant packages:

```
Packages -------------------------------------------------------
 package       * version  date       source                               
 htmltools       0.2.6    2014-09-08 CRAN (R 3.1.1)                       
 htmlwidgets     0.5.1    2015-10-21 Github (ramnathv/htmlwidgets@ee9864c)
 jsonlite        0.9.17   2015-09-06 CRAN (R 3.2.2)                       
 Rcpp            0.12.1   2015-09-10 CRAN (R 3.2.2)                       
 RCurl           1.95-4.7 2015-06-30 CRAN (R 3.2.1)                       
 RJSONIO         1.3-0    2014-07-28 CRAN (R 3.1.1)                       
 rstudioapi      0.3.1    2015-04-07 CRAN (R 3.2.0)                       
 svgPanZoom      0.3.0    2015-09-11 CRAN (R 3.2.2)                       
 tmap          * 1.1      <NA>       local                                
 XML             3.98-1.3 2015-06-30 CRAN (R 3.2.1)                       
 yaml            2.1.13   2014-06-12 CRAN (R 3.1.1)
```

**Comment by timelyportfolio** [comment]
Thanks for the report.  I do not get scroll bars on my side.  I wonder what is the difference.

In terms of the zoom, I am researching.  I am assuming the issue is caused by using an element instead of the whole `SVG` as our pan/zoom target.  I hope I can figure it out.

**Comment by timelyportfolio** [comment]
Actually, the issue is caused by the -1 scale used.  Although I have narrowed it down, unfortunately I have not discovered a solution.

**Comment by timelyportfolio** [comment]
more specifically, this *"sort-of fixes"* the problem, but unfortunately is a manual hack.  I'll keep working on it, but I don't want to hold up your timeline.

```
(tm_shape(World) +
	tm_polygons("income_grp", palette="-Blues", contrast=.7, id="name", title="Income group") +
	tm_shape(metro) +
	tm_bubbles("pop2010", col = "growth", 
			   border.col = "black", border.alpha = .5, 
			   style="fixed", breaks=c(-Inf, seq(0, 6, by=2), Inf),
			   palette="-RdYlBu", contrast=1, 
			   title.size="Metro population", 
			   title.col="Growth rate (%)", id="name") + 
	tm_layout(legend.bg.color = "grey90", legend.bg.alpha=.5, legend.frame=TRUE, asp=0)) %>% 
itmap() -> itm


#try to fix zoom issue caused by scale -1 on y
itm$x$config$beforeZoom = htmlwidgets::JS("
function(oldz,newz){
	this.zooming = true;
	this.zoomchange = newz - oldz;
	return newz
}
")
itm$x$config$onZoom = htmlwidgets::JS("
function(newz){this.zooming = false; return newz}
")
itm$x$config$beforePan = htmlwidgets::JS("
function(oldp, newp){
  if(this.zooming){
	newp.y = newp.y + 25 * 
			 (this.zoomchange === Math.abs(this.zoomchange)? 1 : -1) *
			 Math.max(.75,Math.min(this.getZoom(),1.25));
  }
  return newp;
}
")
itm$x$config$onPan = htmlwidgets::JS("
function(newp){
  return newp;
}
")
itm
```

**Comment by timelyportfolio** [comment]
and here is another approach with a smoother but less accurate result

```

#try to fix zoom issue caused by scale -1 on y
itm$x$config$beforeZoom = htmlwidgets::JS("
function(oldz,newz){
	this.zooming = true;
	this.zoomchange = newz - oldz;
	return newz
}
")
itm$x$config$onZoom = htmlwidgets::JS("
function(newz){this.zooming = false; return newz}
")
itm$x$config$beforePan = htmlwidgets::JS("
function(oldp, newp){
  if(this.zooming){
	debugger;
	if((this.zoomchange > 0 && newp.y < oldp.y) ||
	   (this.zoomchange < 0 && newp.y > oldp.y)) 
	{
		//expect pan change to be same sign as zoom change
		newp.y = oldp.y - (newp.y - oldp.y)
	}
	//newp.y = newp.y + 25 * 
	//		 (this.zoomchange === Math.abs(this.zoomchange)? 1 : -1) *
	//		 Math.max(.75,Math.min(this.getZoom(),1.25));
  }
  return newp;
}
")
itm$x$config$onPan = htmlwidgets::JS("
function(newp){
  return newp;
}
")
itm
```

**Comment by mtennekes** [comment]
Many thanks for your effort. It is still very strange: when I zoom all the way out, while the cursor is in the center (around Nigeria), the map first shifts a little down, and then shifts up. This shift behaves in a  parabolic way. That makes this difficult to solve I guess.
