### ISSUE TITLE
Possibility of saving the output of `tmap_arrange()` to a file

### ISSUE THREAD

**Issue by Nowosad** [mtennekes/tmap#202]
Right now, the `tmap_arrange()`does not return any objects, and therefore its output cannot be saved with `tmap_save()` (I know that other functions, such as `png()` can be used). 
My idea is to allow  `tmap_arrange()` to create a new object:

``` r
library(tmap)
library(spData)

p1 = tm_shape(nz) +
  tm_polygons("Name", legend.show = FALSE)

p2 = tm_shape(nz) +
  tm_polygons("Median_income", legend.show = FALSE)

p12 = tmap_arrange(p1, p2)
```

![](https://i.imgur.com/I1GsuBH.png)

``` r

# idea 
tmap_save(p12, "my_plot.png")
#> Error in tm + do.call("tm_layout", args): non-numeric argument to binary operator
```

Created on 2018-05-20 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by mtennekes** [comment]
Should be working now. However, it's not possible yet to save interactive small multiples. See https://github.com/r-spatial/mapview/issues/35
