### ISSUE TITLE
travis + testthat issue

### ISSUE THREAD

**Issue by mtennekes** [mtennekes/tmap#203]
I need some help with the testing.

Problem: I have a script that runs a test for 15-30 minutes. Travis fails with a time-out, so I tried a suggestion from https://github.com/travis-ci/travis-ci/issues/3849 (second-last comment), which is to split the test into multiple scripts. To test this solution, I created to scripts in the test folder: "test_a.R" and "test_b.R". In the testthat folder, I have some files that start with "test_a" and a file with "test_b". However Travis cannot find these files. This is the travis log. The path seems to be ok:

```{r}
> library(testthat)
> library(tmap)
> 
> print(getwd())
[1] "/tmp/RtmptwG3YK/R_LIBS5cb15960a7ea/tmap/tmap-tests"
> print(list.files(path = "testthat"))
[1] "test_a_classic_worldmap.R" "test_a_qtm.R"             
[3] "test_b_facets.R"          
> 
> test_check("tmap", filter = "^[a]")
Error in test_files(paths, reporter = reporter, env = env, stop_on_failure = stop_on_failure,  : 
  No matching test file in dir
```

Does somebody has a clue, or knows another approach?

**Comment by Nowosad** [comment]
https://twitter.com/jimhester_/status/999327841471746048

**Comment by mtennekes** [comment]
Really annoying, all this travis, testthat, tic stuff.

Now I get this:

[0K$ travis_wait 15 R -q -e 'tic::script()'
/home/travis/.travis/job_stages: eval: line 57: syntax error near unexpected token `('
/home/travis/.travis/job_stages: eval: line 57: `R -q -e tic::script() '

**Comment by Nowosad** [comment]
It works now - https://travis-ci.org/mtennekes/tmap/builds/389785113.
