### ISSUE TITLE
How to create a tmap style?

### ISSUE THREAD

**Issue by Nowosad** [mtennekes/tmap#206]
Hey @mtennekes,
I've spent some time today to figure it out, but without any results... How can I create a new **tmap** style?

``` r
library(tmap)
my_style = structure(
  list(
    title = "MY STYLE!",
    title.size = 1.3,
    bg.color = "red"
  ),
  style = "my_style"
)

tmap_style_load(my_style)
#> style "my_style" loaded successfully
tmap_style_save("my_style")
#> current style is the same as the default style, so nothing to save
tmap_style("my_style")
#> Error: current style "my_style" unknown, i.e. the function "tm_style_my_style" does not exist.
```

Created on 2018-05-26 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by mtennekes** [comment]
I guess a little documentation wouldn't hurt, thanks for pointing that out!

``` r
library(tmap)
data(World)

my_opts <- list(title = "MY STYLE!", title.size = 1.3, bg.color = "red")

tmap_options(my_opts)

tmap_style_save("my_style")
#> current tmap options saved as style "my_style"

tm_shape(World) + tm_polygons()
```

![](https://i.imgur.com/0o8N2eE.png)

So, you can use `tmap_options` to set your own options list, but you'll need to use tmap_style_save explicitly to save the style. This is needed to make the style accessible in the current R session (see the output of `tmap_style()`).

See also https://github.com/mtennekes/tmap/blob/master/examples/tmap_options.R

**Comment by Nowosad** [comment]
And what's the role of `tmap_style_load()`?

``` r
library(tmap)
my_style = structure(
  list(
    title = "MY STYLE!",
    title.size = 1.3,
    bg.color = "red"
  ),
  style = "my_style"
)

tmap_style_load(my_style)
#> style "my_style" loaded successfully

data(World)
tm_shape(World, projection = "longlat") + 
  tm_polygons()
#> Linking to GEOS 3.6.1, GDAL 2.1.4, proj.4 4.9.3
```

![](https://i.imgur.com/74hHRxW.png)

Created on 2018-05-27 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by mtennekes** [comment]
Not sure, probably it won't be needed anymore. Also, I found some old chunks of code that need to be replaced (e.g. https://github.com/mtennekes/tmap/blob/master/R/tmap_style.R#L91)

**Comment by mtennekes** [comment]
`tmap_style_load` has indeed become redundant, since it is now possible to feed a list of options to `tmap_options`. I'll probably rename `tmap_style_save` to `tmap_options_save` to make it more consistent. `tm_style` and `tmap_style` are just used to change the style.

**Comment by mtennekes** [comment]
Yesterday, I've updated the documentation of `tmap_options`, including a paragraph in the details about creation of new styles. It is still drafty, so there may still be some typos.

If things are still unclear, or do not work as expected, please let me know.

**Comment by Nowosad** [comment]
The description looks good. I am going to test it in the next few days!

**Comment by Nowosad** [comment]
I tried it today - it works perfectly!
