### ISSUE TITLE
tmap package does not install from CRAN or github in 3.5 R version

### ISSUE THREAD

**Issue by HumbertoSubiza** [mtennekes/tmap#210]
There is a problems installing tmap from CRAN:

Warning in install.packages :
  error 1 in extracting from zip file
Warning in install.packages :
  cannot open compressed file 'mapview/DESCRIPTION', probable reason 'No such file or directory'
Error in install.packages : cannot open the connection

and from this github page also the problem  seem to be mapview package and the DESCRIPTION file.

Thanks, Walter

**Comment by Nowosad** [comment]
Have your tried to install **mapview** first?

```R
install.packages("mapview")
```

**Comment by HumbertoSubiza** [comment]
Yes, I am sorry, but the problem seems to be on mapview package, the
DESCRIPTION file is not available according to the error message. So, the
mapview package is not installed and also the tmap. I open an issue on
mapview, Thanks for your reply.
Walter

2018-05-28 8:27 GMT-03:00 Jakub Nowosad <notifications@github.com>:
