### ISSUE TITLE
Styling continuous legend for raster 

### ISSUE THREAD

**Issue by JanCaha** [mtennekes/tmap#212]
I am looking for a way to style continuous legend.  What I would like to change is the width a height of the colour bar in the legend. I tried to experiment with various parameters, but without any luck.

Here is an example where I would like to change the legend appearance:
`
library(spData)
library(tmap)

data(elev)

tm_shape(elev) +
  tm_raster(style = "cont") +
tm_layout(legend.outside = TRUE)
`

![raster](https://user-images.githubusercontent.com/7641902/40874968-f1dd5504-6677-11e8-85e0-654c553caf75.png)

I am not sure if I am missing something or if these parameters are not available.

**Comment by mtennekes** [comment]
You cannot control it directly. It is derived from the legend fontsize and the number of breaks.

In principle, the width is equal to the height of 1 line of text. So if you increase the fontsize, and therefore the height of 1 line, the width is increased accordingly. The height of the legend is the height of 1 line of text times the number of legend text labels that are printed.


```
tm_shape(elev) +
	tm_raster(style = "cont", breaks = seq(5, 35, by = 10)) +
	tm_layout(legend.outside = TRUE, legend.text.size = 2)
```

![image](https://user-images.githubusercontent.com/2444081/40978132-16204d88-68d3-11e8-97c1-6a27df4fd681.png)
