### ISSUE TITLE
alpha by column: possible enhancement?

### ISSUE THREAD

**Issue by randomgambit** [mtennekes/tmap#218]
Hello @mtennekes ! 

I am not sure `tmap` can actually solve my problem summarized here: https://stackoverflow.com/questions/50864644/how-to-set-the-alpha-based-on-a-column

If so, do you think that could be a possible feature request for `tmap`?

Thanks!

**Comment by mtennekes** [comment]
See my answer at StackOverFlow. It could be a possible enhancement to have alpha transparency as additional aesthetic, so I leave this issue open. However, it will not be top priority.

**Comment by randomgambit** [comment]
ok thanks @mtennekes !
