### ISSUE TITLE
Data set ‘Europe’ not found

### ISSUE THREAD

**Issue by vicvandijk** [mtennekes/tmap#219]
When using the current development version, the command 

data(Europe)

yields 

"Data set ‘Europe’ not found"

**Comment by vicvandijk** [comment]
Ow, I see now a warning message when using tmap 1.11-2: "In tmap::tm_format_Europe() :
  tm_format_Europe not used anymore as of tmap version 2.0, since the data object Europe is no longer contained"
So, I guess I have to obtain the Europe data from elsewhere...

**Comment by mtennekes** [comment]
Correct, `Europe` will no longer be used in 2.0. to make the package lighter and easier to maintain.
I used shapes from naturalearthdata, combined with some other sources. See the build script: https://github.com/mtennekes/tmap/blob/master/build/create_world.R (if you browse through earlier version, say last year, you will also find the create_Europe script).
