### ISSUE TITLE
tm_facets(...,drop.shapes=T) does not work unless free.coords = T

### ISSUE THREAD

**Issue by timelyportfolio** [mtennekes/tmap#22]
Before digging into the code, I wanted to make sure that I am not just confused.  Using the example provided in tmap.R, I get the result I would expect.

```r
# Small multiples choropleth
tm_shape(NLD_muni) +
    tm_borders() +
    tm_facets(by="province") +
    tm_fill("population", style="kmeans", convert2density = TRUE) +
tm_shape(NLD_prov) +
    tm_borders(lwd=4) +
    tm_facets(by="name", free.coords=TRUE, drop.shapes=TRUE) +
tm_layout(legend.show = FALSE)
```

![image](https://cloud.githubusercontent.com/assets/837910/8586490/ad9717f6-25b4-11e5-8533-dfad31d9a8ce.png)

However, currently `drop.shapes=TRUE` seems to also require `free.coords=TRUE`, since removing the `free.coords=TRUE` leads to a result that I would not expect.

```r
tm_shape(NLD_muni) +
    tm_borders() +
    tm_facets(by="province") +
    tm_fill("population", style="kmeans", convert2density = TRUE) +
    tm_shape(NLD_prov) +
    tm_borders(lwd=4) +
    tm_facets(by="name", drop.shapes=TRUE) +
    tm_layout(legend.show = FALSE)
```

![image](https://cloud.githubusercontent.com/assets/837910/8586517/ffbfac6e-25b4-11e5-90a4-e11d09937dd8.png)

**Comment by mtennekes** [comment]
Thanks for reporting this. I am working on it: https://github.com/mtennekes/tmap/tree/facets

**Comment by mtennekes** [comment]
All four ```free.coords``` and ```drop.shapes``` combinations working now (see https://github.com/mtennekes/tmap/blob/master/test/test_facets.R)

**Comment by timelyportfolio** [comment]
brilliant!  As an additional check, I did this with `USAboundaries`.

```r
library(tmap)
#devtools::install_github("ropensci/USAboundaries")
library(USAboundaries)
library(pipeR)

{
	tm_shape(us_boundaries("1850/01/01")) +
		tm_borders() +
		tm_fill("terr_type")
} %>>%
	(tm~
		{
			print(tm+tm_facets("terr_type",drop.shapes = TRUE,free.coords = FALSE))
			print(tm+tm_facets("terr_type",drop.shapes = TRUE,free.coords = TRUE))
			print(tm+tm_facets("terr_type",drop.shapes = FALSE,free.coords = TRUE))
			print(tm+tm_facets("terr_type",drop.shapes = FALSE,free.coords = FALSE))
		}
	)
```
