### ISSUE TITLE
tm_add_legend does not show in leaflet/interactive view

### ISSUE THREAD

**Issue by ozjimbob** [mtennekes/tmap#221]
I'm having an issue with tmap where legends manually added using tm_add_legend do not show up in the interactive view mode.  I'm needing to use the tm_add_legend because I have a defined set of classes and colours that need to be present in the legend, although they may not all be present in a given sf object I'm plotting.    Examples of my output below - the first in plot mode, and the second in view mode, based on this code:

```
tm = tm_shape(v,name="Heritage Threshold Status") +
  tm_fill(col="color",
          style="cat",
          alpha = 0.7,
          title=paste0("Heritage Threshold Status ",current_year))+tm_add_legend(type="fill",labels=c("NoFireRegime","TooFrequentlyBurnt","Vulnerable","WithinThreshold","LongUnburnt", "Unknown","Recently Treated","Monitor OFH In the Field","Priority for Assessment and Treatment"), col=c("white","red","orange","grey","cyan","grey20","lightgreen","darkgreen","green"))+
  tm_view(view.legend.position=c("right","top"))+ 
  tm_basemap(server = c(NSW="http://maps.six.nsw.gov.au/arcgis/rest/services/public/NSW_Base_Map/MapServer/tile/{z}/{y}/{x}"))
```

![capture1](https://user-images.githubusercontent.com/1160363/42299898-03829132-8051-11e8-9ecb-ad53dc61c4f1.PNG)

![capture2](https://user-images.githubusercontent.com/1160363/42299899-03b080c4-8051-11e8-80bd-18d61228bf49.PNG)

Now obviously that code isn't reproducible, but for a trivial example, see code below - in "view" mode the normal legend displays but the manually defined tm_add_legend does not, while in plot mode both parts of legend are shown correctly. 

```
data(World)
tm_shape(World) + tm_fill(col="income_grp") + tm_add_legend(type = "fill",col=c("red","black"),labels = c("red","black"))
```

**Comment by mtennekes** [comment]
Done!

Example:

```
data(World)
tmap_mode("view")
qtm(World, fill = "HPI") + 
  tm_add_legend("fill", 
                labels = letters[1:5], 
                col = rainbow(5), 
                title = "My Legend")
```

![screenshot from 2018-07-10 18-57-30](https://user-images.githubusercontent.com/2444081/42525323-235d6768-8473-11e8-9f19-8a79d77bcfc6.png)
