### ISSUE TITLE
Could not find ImageMagick.

### ISSUE THREAD

**Issue by Nowosad** [mtennekes/tmap#224]
This is probably related to https://github.com/mtennekes/tmap/pull/220. 

``` r
library(tmap)
data(NLD_prov)

m1 <- tm_shape(NLD_prov) + 
        tm_polygons("yellow") +
        tm_facets(along = "name")

tmap_animation(m1, filename="Dutch_provinces.gif", width=800, delay=40)
#> Warning in syscall("magick convert -version"): error in running command
#> Error in tmap_animation(m1, filename = "Dutch_provinces.gif", width = 800, : Could not find ImageMagick. Make sure it is installed and included in the systems PATH
```

Created on 2018-07-07 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by mtennekes** [comment]
It should work now. I also added arguments `loop` and `restart.delay`.
Please reopen if it doesn't work as expected.

**Comment by mtennekes** [comment]
FYI: `tmap_animation` did not work on a Windows laptop:

```
d> shell("magick convert -version")
'magick' is not recognized as an internal or external command,
operable program or batch file.
Warning messages:
1: running command 'C:\WINDOWS\system32\cmd.exe /c magick convert -version' had status 1 
2: In shell("magick convert -version") :
  'magick convert -version' execution failed with error code 1

d> shell("convert -version")
Version: ImageMagick 6.8.6-7 2013-07-23 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2013 ImageMagick Studio LLC
Features: DPC OpenMP
Delegates: bzlib djvu fftw fontconfig freetype jng jp2 jpeg lcms lzma openexr pango png ps tiff x xml zlib
```

So, if one does check the "install legacy files (e.g., convert.exe)" box, "magick convert" does not work and "convert" does? Or it may be that "magick convert" is only supported recently.

Anyways, I have made the code for tmap_animation more robust now. Could you please check if works @jannes-m @Nowosad  ?

**Comment by Nowosad** [comment]
I can only test in on Linux - it works well.

**Comment by jannes-m** [comment]
I tried it on Windows, works like a charm, perfect, thanks!

**Comment by mtennekes** [comment]
Thanks for checking!

**Comment by arielfuentes** [comment]
I run @Nowosad example on Win10 and it didn't work 
```
sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=Spanish_Chile.1252  LC_CTYPE=Spanish_Chile.1252    LC_MONETARY=Spanish_Chile.1252
[4] LC_NUMERIC=C                   LC_TIME=Spanish_Chile.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] tmap_2.3

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1         raster_2.9-23      magrittr_1.5       units_0.6-3        viridisLite_0.3.0 
 [6] lattice_0.20-38    xtable_1.8-4       R6_2.4.0           tools_3.6.0        rgdal_1.4-4       
[11] dichromat_2.0-0    grid_3.6.0         KernSmooth_2.23-15 e1071_1.7-2        DBI_1.0.0         
[16] rgeos_0.4-3        htmltools_0.3.6    crosstalk_1.0.0    leafsync_0.1.0     class_7.3-15      
[21] leaflet_2.0.2      digest_0.6.19      lwgeom_0.1-7       sf_0.7-6           shiny_1.3.2       
[26] RColorBrewer_1.1-2 later_0.8.0        codetools_0.2-16   tmaptools_2.0-2    htmlwidgets_1.3   
[31] promises_1.0.1     mime_0.7           sp_1.3-1           compiler_3.6.0     XML_3.98-1.20     
[36] classInt_0.3-3     httpuv_1.5.1 
```

**Comment by Nowosad** [comment]
Can you add your error message?

**Comment by arielfuentes** [comment]
Error in tmap_animation(m1, filename = "Dutch_provinces.gif", width = 800,  : 
  Could not find ImageMagick. Make sure it is installed and included in the systems PATH
In addition: Warning messages:
1: In syscall("convert -version") :
  'convert -version' execution failed with error code 4
2: In syscall("magick convert -version") :
  'magick convert -version' execution failed with error code 1

**Comment by Nowosad** [comment]
Have you installed ImageMagick (https://imagemagick.org/index.php)?

**Comment by arielfuentes** [comment]
That was it, I'm sorry for the basic mistake. Although I get this warning:
```
Warning message:
In syscall("convert -version") :
  'convert -version' execution failed with error code 4
```
Is it normal that I get this?

**Comment by DidDrog11** [comment]
Sorry to re-open. Having the same problem with a Windows 10 PC. Installed package in R, and from the imagemagick website but also reports could not find ImageMagick. 

My R is installed to D: but Imagick was installed to C: is that the cause of the problem? If so how do I tell it to install to the right disk or is it a problem with the PATH directions (although I don't really understand this).

Many thanks.
