### ISSUE TITLE
Several maps within the same layout

### ISSUE THREAD

**Issue by Arevaju** [mtennekes/tmap#23]
Dear Martijn,

Congratulations on the great work done on tmap! 

I found your library very useful and flexible enough to produce great maps. I have recently developed a shiny app based on tmap (https://github.com/Arevaju/mapping-tool). I was wondering if there is a simple way to include two maps within the same layout map such in the image attached (Malta and Cyprus boxes) :
![eruope_map](https://cloud.githubusercontent.com/assets/6852532/8650772/2a04b294-2975-11e5-85ed-7ed5c22198d4.png)

Any ideas on how this could be addressed? 

Thanks for your help.

**Comment by mtennekes** [comment]
Nice to hear about the shiny app! I will have a look at it soon.
Your request is exactly addressed here: https://github.com/mtennekes/tmap/issues/7
