### ISSUE TITLE
tm_minimap() not working unless leaflet is loaded

### ISSUE THREAD

**Issue by mtennekes** [mtennekes/tmap#231]
Just before going to submit tmap(tools) 2.0 to CRAN, I found this bug:

```r
library(tmap)
qtm()  # shortcut for tm_basemap() + tm_minimap(), which automatically switches to view mode
```

throws this error, while 

```r
library(tmap)
library(leaflet)
qtm()
```

works.

The call traceback of the error is:

```r
Error in tiles %in% providers : object 'providers' not found 
8.
tiles %in% providers 
7.
(function (map, position = "bottomright", width = 150, height = 150, 
    collapsedWidth = 19, collapsedHeight = 19, zoomLevelOffset = -5, 
    zoomLevelFixed = FALSE, centerFixed = FALSE, zoomAnimation = FALSE, 
    toggleDisplay = FALSE, autoToggleDisplay = FALSE, minimized = FALSE,  ... 
6.
do.call(addMiniMap, c(list(map = lf), mmargs)) at view_tmap.R#653
5.
view_tmap(x, shps = list(dummy = NULL)) at print_tmap.R#120
4.
print_shortcut(x, interactive, args, knit) at print_tmap.R#341
3.
print_tmap(x = x, vp = vp, return.asp = return.asp, mode = mode, 
    show = show, knit = knit, options = options, ...) at print_tmap.R#40
2.
print.tmap(x) 
1.
function (x, ...) 
UseMethod("print")(x) 
```

The list object `providers` is not exported by `leaflet` (i.e. it is not in its NAMESPACE), but made accessible with this dirty (but working) hack: 

```r
utils::globalVariables(c("providers")) # To make R CMD Check happy
```
See https://github.com/rstudio/leaflet/blob/master/R/plugin-minimap.R#L1. Therefore, the `providers` object can be accessed with `leaflet::providers`.

Does anyone has a clue how to use `addMinimap` inside a package? It is called here: https://github.com/mtennekes/tmap/blob/master/R/view_tmap.R#L653 @tim-salabim : do you use minimaps or the `providers` object in `mapview`?

**Comment by tim-salabim** [comment]
Nope for both. Minimap is neat but doesn't really add any value for quick layer inspection. Regarding providers, I call `addProviderTiles("XXX")` directly, e.g. "CartoDB.Positron"

**Comment by mtennekes** [comment]
I think it's a nice feature, especially in unfamiliar areas. 

I made a pull request in leaflet, as you can see above. For now, a message "please load leaflet" is shown when `tm_minimap` doesn't work. Also I changed the default value of `qtm.minimap` to `FALSE`.
