### ISSUE TITLE
Enhancement request: ability to pass a list of tmap objects to tmap_arrange

### ISSUE THREAD

**Issue by smwoodman** [mtennekes/tmap#232]
I am using tmap to make maps of spatial data within a Shiny app, including occasionally multiple maps from different spatial data. Thus, I would like to use the very useful tmap_arrange. However, I would like the app to allow the user to control which maps they want displayed, and I am not sure how to accomplish this using tmap_arrange since tmap_arrange only accepts actual tmap objects as arguments (as well as its other specified arguments). The code below hopefully demonstrates both what I'm trying and would like to do.

What are your thoughts on having tmap_arrange also accept a list of objects of class tmap (as in the commented line in the code below) to allow for flexibility within say Shiny apps? Or am I missing something in the current tmap package?

Thank you!

```r
library(tmap)
library(spData)

p1 = tm_shape(nz) +
  tm_polygons("Name", legend.show = FALSE)

p2 = tm_shape(nz) +
  tm_polygons("Median_income", legend.show = FALSE)

p3 = tm_shape(nz) +
  tm_polygons("Population", legend.show = FALSE)

tmap.list <- list(p1, p2, p3)
tmap_arrange(p1, p2, p3) # Current use of tmap_arrange
# Desired use: tmap_arrange(tmap.list[1:2])

```

**Comment by mtennekes** [comment]
Hi Sam,

Nice question. I think 

```r
do.call(tmap_arrange, list(p1, p2))
```

is what you are looking for. 

I could program `tmap_arrange` such that the first element can be a list to make things easier for the user.

**Comment by smwoodman** [comment]
Ahh, do.call coming to the rescue yet again. Thanks for the quick fix!

**Comment by Robinlovelace** [comment]
> I could program tmap_arrange such that the first element can be a list to make things easier for the user.

I think that would be good for user-friendliness. Not many R beginners know about `do.call()`. Great to see **tmap** evolve!
