### ISSUE TITLE
tm_symbols/tm_bubbles size?

### ISSUE THREAD

**Issue by SwampThingPaul** [mtennekes/tmap#233]
Is it possible to control the size of the bubbles in tm_symbols/tm_bubbles? I would like for the bubbles to match the specified breaks in the color ramp. I have been pouring over the readme/help (`?tm_bubbles`) but haven't been able to figure out if its possible. 

BTW love the package...makes mapping in R so easy!!

**Comment by SwampThingPaul** [comment]
Nevermind, figured it out...just took me writing the comment to find the answer. To double check though...sizes.legend is where the sizes can be altered?

**Comment by mtennekes** [comment]
Thanks! Yes, the sizes in the legend. If you have any other question, let us know! (if it is just a regular question, please use StackOverflow first)
