### ISSUE TITLE
Long vectors not supported - Displaying Landsat-resolution raster

### ISSUE THREAD

**Issue by gponce-ars** [mtennekes/tmap#234]
Hi, 
I'm trying to follow one of the examples from the "tm_raster" documentation data(World, land,metro)... 
And I'm using a large raster file (~19 GB) in a server that has 1 TB RAM.
When I run the example with my raster, and after running for a little bit,  I get the error: `Error in pmax(l[1], d) long vectors not supported yet: ../../src/include/Rinlinedfuns.h:138`. 

See the image attached.

<img width="1089" alt="image" src="https://user-images.githubusercontent.com/20215136/42956467-e232c65c-8b34-11e8-9596-31c5b46cabf3.png">

**Comment by Nowosad** [comment]
I think this is an issue of the **raster** package and not **tmap**'s one. Were you able to just use `plot(gap)`?

**Comment by gponce-ars** [comment]
plot(gap) works just fine.
<img width="717" alt="image" src="https://user-images.githubusercontent.com/20215136/43038842-fd4462f0-8cd5-11e8-82c3-29fd0c34c62f.png">

**Comment by Nowosad** [comment]
Based on the help file in the **raster** package"
```
## S4 method for signature 'Raster,Raster'
plot(x, y, maxpixels=100000, cex, xlab, ylab, nc, nr, 
    maxnl=16, main, add=FALSE, gridded=FALSE, ncol=25, nrow=25, ...)
```
As a default, 100,000 pixels are plotted. The issue with **tmap** is that it tries to plot all of the pixels. 
A few days ago, I've opened another issue related to this problem - https://github.com/mtennekes/tmap/issues/235. We need to wait for @mtennekes response.

**Comment by mtennekes** [comment]
Thanks for your question. See #235 indeed.
