### ISSUE TITLE
tmap appears to change user palette values, what is gfill

### ISSUE THREAD

**Issue by smwoodman** [mtennekes/tmap#236]
Hello. When passing my own vector of colors to the palette argument of `tm_fill`, tmap appears to change to color values when mapping large spatial data sets with a larger number of color classes, and particularly when I'm using `style = "fixed"` and passing in my own break points. Below is my reproducible example; when using my data the color changes are even greater.

Also, this question should maybe be a separate thing, but after making a map using tmap, an object `gfill` appears in my global environment. It was very helpful for debugging in this case, but is this object appearing intentional/what is its purpose?

```r
# Prep
library(sf)
library(tmap)

x.df <- data.frame(
    lon = c(40, 40, 50, 50, 40),
    lat = c(0, 10, 10, 0, 0)
  )
x.sfc <- st_sfc(st_polygon(list(as.matrix(x.df))))
x <- st_sf(val = seq(1, 10, length.out = 2500), geometry = st_make_grid(x.sfc, n = 50), crs = 4326)
rm(x.df, x.sfc)

pal1 <- c("#313695", "#d1e5f0", "#d73027")
pal2 <- c(
  "#313695", "#4575b4", "#74add1", "#abd9e9", "#d1e5f0", "#fee090",
  "#fdae61", "#f46d43", "#d73027", "#a50026"
)

breaks_calc <- function(x, breaks = c(seq(0.4, 0.05, by = -0.05), 0.02)) {
  x <- x[!is.na(x)]
  x <- sort(x, decreasing = TRUE)

  c(-Inf, x[ceiling(breaks * length(x))], Inf)
}


# Colors stay identical to pal1
tm_shape(x) +
  tm_fill(col = "val", style = "equal", n = 3, palette = pal1, legend.show = FALSE)
table(gfill$fill[, 1])


# Colors change slightly from pal2
tm_shape(x) +
  tm_fill(col = "val", style = "equal", n = 10, palette = pal2, legend.show = FALSE)
table(gfill$fill[, 1])


# Colors change more from pal2
b1 <- breaks_calc(x$val)
tm_shape(x) +
  tm_fill(col = "val", style = "fixed", breaks = b1, palette = pal2, legend.show = FALSE)
table(gfill$fill[, 1])
```

**Comment by mtennekes** [comment]
Wow, great find! Thanks. Wonder how `gfill <<- ...` (used for debugging) has passed the CRAN tests :-))

Should be fixed now. The reason it didn't work, is that numeric palettes are internally converted to a 101 sized palette in order to find appropriate gradient colors. However, this should of course not happen when color palettes are provided with exactly the same number of colors as classes. Therefore I made a shortcut for those cases.

Let me know if it works as expected, and if now, please reopen this issue.

**Comment by smwoodman** [comment]
@mtennekes your fix seems to have done the trick; thank you for both the explanation and quick fix!
