### ISSUE TITLE
tmap_arrange outputs do not completely respect bbox inputs

### ISSUE THREAD

**Issue by smwoodman** [mtennekes/tmap#237]
Hello again. One of the features that I appreciate about tmap (esp relative to default sf plotting) is that tmap respects user-provided plot limits rather than filling the whole plot area, as shown in the first image below. However, this does not hold true when using `tmap_arrange` (unless the plot window is exactly the right size) as shown in the second image below. Both images were produced with the RStudio plot window to same size and the same dimensions (a square).

Would it be possible for `tmap_arrange` to behave like printing a single tmap object, i.e. the first image, when it is passed one (or more) tmap objects? Or are there other factors at work when using `tmap_arrange`?

```r
library(sf)
library(spData)
library(tmap)

nz.ll <- st_transform(nz, 4326) # for ease of providing bbox coordinates

p1 <- tm_shape(nz.ll, bbox = matrix(c(170, -47, 176, -32), nrow = 2)) +
  tm_polygons("Population", legend.show = FALSE) + tm_grid()

p1
```
![tmap_issue3a](https://user-images.githubusercontent.com/13037308/43600127-a192f62a-963e-11e8-8784-bfa762b0d072.png)

```r
tmap_arrange(p1)
```
![tmap_issue3b](https://user-images.githubusercontent.com/13037308/43600165-b974c9bc-963e-11e8-97e8-8124ceae7b9b.png)

**Comment by Nowosad** [comment]
Hey! There is the `asp` parameter in `tm_layout()`. As a default, it is set to `0`. Your expected output is with `asp = NULL`:

``` r
library(sf)
#> Linking to GEOS 3.6.1, GDAL 2.2.4, proj.4 4.9.3
library(spData)
library(tmap)

nz.ll <- st_transform(nz, 4326) # for ease of providing bbox coordinates

p1 <- tm_shape(nz.ll, bbox = matrix(c(170, -47, 176, -32), nrow = 2)) +
        tm_polygons("Population", legend.show = FALSE) + tm_grid()

p1
```

![](https://i.imgur.com/3UgJSPz.png)

``` r

tmap_arrange(p1, asp = NULL)
```

![](https://i.imgur.com/wIgaNIe.png)

Created on 2018-08-02 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by smwoodman** [comment]
Got it, thank you so much!
