### ISSUE TITLE
Possible to have degrees on tm_grid labels?

### ISSUE THREAD

**Issue by smwoodman** [mtennekes/tmap#238]
Is it possible within to have `tm_grid` labels have degrees symbols when plotting lat/long data, a la the sf plotting function illustrated below? Imo this makes the tick labels (or in tmap's current option, grid labels) nicer when plotting lat/long spatial data. And if not and this is an easy addition, could this be added as an enhancement? Thanks!

```r
library(sf)
library(spData)
library(tmap)

nz.ll <- st_transform(nz, 4326)

# Default sf version; axis tick labels include '°E' or '°S' (or '°W' or '°N' if map is of that part of the world)
plot(st_geometry(nz.ll), axes = T)
```

![tmap_issue4a](https://user-images.githubusercontent.com/13037308/43737324-c85c8e3a-9975-11e8-9b05-c32b7a0fc932.png)

```r
# Default tmap version
tm_shape(nz.ll) +
  tm_borders() +
  tm_grid()
```

![tmap_issue4b](https://user-images.githubusercontent.com/13037308/43737358-e3956172-9975-11e8-91aa-c74836344b27.png)

```r
# tmap with only degrees symbols - not sure how to differentiate between x and y labels for E/W or N/S addition to label
tm_shape(nz.ll) +
  tm_borders() +
  tm_grid(labels.format = list(fun = function(i) parse(text = paste(i, "*degree"))))
```

![tmap_issue4c](https://user-images.githubusercontent.com/13037308/43737415-0b81c126-9976-11e8-8560-fac53a10d5c2.png)

**Comment by mtennekes** [comment]
Thanks for this suggestion! It would make sense to use degrees as default for lat/lon coordinates.

**Comment by Nowosad** [comment]
It's here! https://github.com/mtennekes/tmap/issues/315
