### ISSUE TITLE
dot maps?

### ISSUE THREAD

**Issue by joelgombin** [mtennekes/tmap#24]
See http://www.washingtonpost.com/blogs/wonkblog/wp/2015/07/16/how-railroads-highways-and-other-man-made-lines-racially-divide-americas-cities/ for example

**Comment by timelyportfolio** [comment]
Her is a very nice interactive example http://demographics.coopercenter.org/DotMap/.

**Comment by mtennekes** [comment]
tmap-technically it's just a ```tm_bubbles``` with constant (small) sizes;-)
It would be nice to have data from one of these examples.

**Comment by timelyportfolio** [comment]
I did find this http://web.stanford.edu/~cengel/cgi-bin/anthrospace/dot-density-maps-in-r.

**Comment by joelgombin** [comment]
`spsample` seems quite useful indeed. 
With regards to data, I guess any population data will do.

**Comment by edwindj** [comment]
It would be nice to have dotmaps in tmap, however they are (very) computationally intensive if you implement them naively:

- spsample takes considerable time, depending on the number of regions, size of populations, and the resolution of the map.
- drawing the dots takes time  (Note that for the US 300M dots are generated)

I guess it takes some tuning and optimization to make them usable.

**Comment by mtennekes** [comment]
We'll have to sample anyway if there are over 1M data points, since the resolution is a bottleneck.
It may be a blessing in disguise, because it prevents serious running time/memory/occlusion issues.
I mean, `tmap` is probably equivalent to `ggplot2` regarding running time. Did any of you ever managed to plot 300M objects with `ggplot2`?

Maybe we could add a layer-function `tm_dots`, which is a simplified/faster version of `tm_bubbles`. 
Size isn't an aesthetic, only color. 

In order to make it fast, we could add an extra argument `N`, an upper bound to the number of plotted dots, sampled with `spsample`.

Another route that may be very promising is to use `raster`, which can handle very large objects. A procedure might be:
* Create a `Raster` object with dimensions that are matched to the required resolution.
* Bin the spatial points to raster cells. Raster cells without spatial points have the default `NA` values, and are hence transparent.
* Convert the `Raster` back to a `SpatialPointsDataFrame` in order to draw dots. (Only needed if they are larger than pixels.)

**Comment by mtennekes** [comment]
Does anyone of you has a population dataset that could be contained in the package? Or one that is contained in another package (preferably a little smaller than `UScensus2010blk`).

**Comment by edwindj** [comment]
:-) I had exactly the same idea: using raster to make a dotmap: I have been playing around with some code but it is still not trivial and time consuming.

- the number of points has to be scaled down
- the color have to mix nicely
- the number of different categories has to be restricted to max 5 (or something), I suspect 3 gives the best results.

I can contribute some code next week (current code is kind of messy)

**Comment by joelgombin** [comment]
Here is a small file https://www.dropbox.com/s/se97r1aorvnxfgw/Vaucluse.Rdata?dl=0, with a `POPULATION` variable. 

I  had thaught about the raster solution too, or at any rate some sort of binning. I'm not too sure how to handle the color mixing though...

**Comment by mtennekes** [comment]
Nice too see how good ideas are being picked up simultaneously.
Thanks for the data!

**Comment by mtennekes** [comment]
It would be nice to have some small, but detailed population data with different subgroups. I think the population datasets `NLD_muni` and `vaucluse` do not have a very fine resolution. Also I'm not sure what kind of subgroups we could display. Age groups (contained in `NLD_muni`) do not have a very non-uniform distribution like in the US example (i.e. the division of white, black, asian and hispanic people). @edwindj, maybe we could use some Dutch neighborhood data (http://www.cbs.nl/nl-NL/menu/themas/dossiers/nederland-regionaal/publicaties/geografische-data/archief/2015/wijk-en-buurtkaart-2014-art.htm) for this purpose? However, I'm still not sure what kind of categories we could show.

**Comment by mtennekes** [comment]
![dotmap](https://cloud.githubusercontent.com/assets/2444081/9307806/e57ba90a-4500-11e5-9709-03f62adb9c32.png)

This was a very nice afternoon exercise! The script is https://github.com/mtennekes/tmap/blob/master/test/test_dotmap.R. Of course, I'll have to clean it, and see what parts of it can be generalized.

**Comment by timelyportfolio** [comment]
I really like this example.

**Comment by mtennekes** [comment]
![dotmap2](https://cloud.githubusercontent.com/assets/2444081/9364405/710aa708-46ac-11e5-853c-52d2d47a930f.png)

**Comment by mtennekes** [comment]
Previous picture is updated. There was something wrong with the overall population density.

`sample_dots` is now fully working. The bottlenecks regarding computation time are `rasterize` and `sample`. I added the code to reproduce the example above to the examples (as dontrun). FYI, there is also a `jitter` argument to `tm_bubbles` / `tm_dots`, which is used in the first example of `sample_dots`.

**Comment by mbacou** [comment]
Jumping at random here, but I remember using `maptools::dotsInPolys()` to generate (random) dot density maps. don't recall it being particularly slow (I had used it on national surveys with about 5,000 households to random plot). Example here http://web.stanford.edu/~cengel/cgi-bin/anthrospace/dot-density-maps-in-r
