### ISSUE TITLE
bulkiness of tmap: dependencies and memory usage

### ISSUE THREAD

**Issue by mredaelli** [mtennekes/tmap#240]
Unless I am mistaken, simply doing

```R
library(tmap)
```

allocates 300 MB of RAM.

We are running a pool of Shiny applications using tmap, and this behaviour (plus the fact that the library is not loaded in shared memory, but duplicated for each process) really clogs us up.

Would it be possible to make a more "judicious" use of memory?

**Comment by mredaelli** [comment]
Alternatively, I would be happy to just load `tmap` when strictly needed, and unload it afterwards to free memory.
However, that doesn't seem to work (is this the way to do it?):
```R
Packrat mode on. Using library in directory:
- "~/src/proj/ems/ems/packrat/lib"
> gc()
         used (Mb) gc trigger (Mb) limit (Mb) max used (Mb)
Ncells 309196 16.6     654011   35         NA   654011   35
Vcells 622274  4.8    8388608   64      16384  1957831   15
> library(tmap)
> gc()
          used  (Mb) gc trigger  (Mb) limit (Mb) max used  (Mb)
Ncells 2959222 158.1    5312251 283.8         NA  4946520 264.2
Vcells 4595134  35.1   10146329  77.5      16384  8388608  64.0
> detach("package:tmap", unload=TRUE, force=TRUE)
> gc()
          used  (Mb) gc trigger  (Mb) limit (Mb) max used  (Mb)
Ncells 2960717 158.2    5312251 283.8         NA  4946520 264.2
Vcells 4598885  35.1   10146329  77.5      16384  8388608  64.0
> 
```

(I'm not sure why, but what I see in the operating system as memory usage matches the `max used` column rather than the `used`. I'm on MacOS, if it helps.)

**Comment by mredaelli** [comment]
Yeah, it looks like a dependency nightmare.

I will try investigating a bit the package unloading part, but my feeling would be that probably the right thing to do in my case is to move the code that needs `tmap` to a separate service, and call that from all the shiny instances. Not sure how that's doable in R, though.

But thanks for the investigation! 

I also tried
```R
> library(mapview)
> detach("package:mapview", unload=TRUE)
```
to see if this could be done inside in `tmap`, but again no difference in memory before and after.
I will try to ask them, too.

**Comment by tim-salabim** [comment]
AFAIK, tmap only requires mapview for `sync`, so maybe move it from Imports to Suggests and provide a proper warning when someone is trying to view interactive facets but doesn't have mapview installed. This should avoid much of the mapview overhead.

**Comment by mredaelli** [comment]
That would be already great.
However, I tried earlier to load mapview first, and then tmap, and the memory usage goes from 150MB to 300MB, so that's not the only part of the issue :/

**Comment by tim-salabim** [comment]
What I meant is that you could fall back to static mode when mapview is not available and provide a warning to install mapview for interactive facets. 
Having the same code in two places is never a good idea IMO ...

**Comment by mtennekes** [comment]
Not really ideal IMO. 

I am not sure how the dependency tree of mapview looks like and which functions depend of which packages, but isn't it an idea to start a new package with lightweight extensions to leaflet, such as facets?

**Comment by tim-salabim** [comment]
mapview naturally has hefty dependencies as it provides methods for the most common spatial classes. In the next CRAN release stars is added to that tree... maybe it is time to think about outsourcing the leaflet extensions to a lighter weight package. I am meeting with the r-spatial crew at Geostat 2018 in Prague in ten days or so and will discuss this.

**Comment by tim-salabim** [comment]
Ping @edzer

**Comment by edzer** [comment]
stars is light-weight and pure-R; all that's heavy (gdal, proj) was moved to sf - no compiled code.

**Comment by Nowosad** [comment]
The recent changes make a difference. Now:

``` r
gc()
#>          used (Mb) gc trigger (Mb) max used (Mb)
#> Ncells 477453 25.5    1034055 55.3   660191 35.3
#> Vcells 886107  6.8    8388608 64.0  1789408 13.7
library(tmap)
gc()
#>           used (Mb) gc trigger  (Mb) max used  (Mb)
#> Ncells 1518014 81.1    3009801 160.8  1972687 105.4
#> Vcells 2236160 17.1    8388608  64.0  3694550  28.2
```

<sup>Created on 2020-04-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
