### ISSUE TITLE
Override the "Missing" default on NA values.

### ISSUE THREAD

**Issue by chicofish** [mtennekes/tmap#243]
I'm trying to override the "Missing" default on NA values.
When I put it in tm_text, it does not override.
tm_shape(CAR) + tm_polygons("Graduates") +
tm_text("Label_Name", just = "top", auto.placement = TRUE, textNA = "No Frontline", colorNA = "#CC0000", col = "#000000") +
tm_layout(main.title = "Frontline Graduates by Country\nCaribbean", main.title.position = "center", inner.margins = c(.1, .2, .1, .2))

If I add a tm_fill layer, I get it to work, but the quick and easy tm_text doesn't work:

tm_shape(CAR)  + tm_fill(textNA = "Frontline not implemented") +
tm_text("Label_Name", just = "top", auto.placement = TRUE, textNA = "No Frontline", colorNA = "#CC0000", col = "#000000") +
tm_layout(main.title = "Frontline Graduates by Country\nCaribbean", main.title.position = "center", inner.margins = c(.1, .2, .1, .2))

**Comment by Nowosad** [comment]
Hey @chicofish, you are free to reopen the issue with a reproducible example.
