### ISSUE TITLE
plot hillshade in tmap

### ISSUE THREAD

**Issue by carbonmetrics** [mtennekes/tmap#244]
I have put a question on [stackoverflow](https://stackoverflow.com/questions/52150972/plot-hillshade-in-tmap), which unfortunately has not resulted in any answers.

I have this code, which produces hillshading in `raster`:

```
library(raster)
alt = getData('alt', country='CHE')
slope = terrain(alt, opt='slope')
aspect = terrain(alt, opt='aspect')
hill = hillShade(slope, aspect, 40, 270)
plot(hill, col=grey(0:100/100), legend=FALSE, main='Switzerland')
plot(alt, col=rainbow(25, alpha=0.35), add=TRUE)
```
![sj6ja](https://user-images.githubusercontent.com/40055991/45016691-17dace80-b02e-11e8-9fce-5a09564170e3.png)

The next step would be add layers (towns, roads, etc) in `tmap`. 

```
library(tmap)
tm_shape(hill) + tm_raster() + tm_shape(alt) + tm_raster()
```
does not give the required result. How could this be done?

**Comment by Nowosad** [comment]
``` r
library(raster)
#> Loading required package: sp
alt = getData('alt', country = 'CHE')
slope = terrain(alt, opt = 'slope')
aspect = terrain(alt, opt = 'aspect')
hill = hillShade(slope, aspect, 40, 270)

library(tmap)  
tm_shape(hill) +
 tm_raster(palette = gray(0:100 / 100), n = 100, legend.show = FALSE)  +
  tm_shape(alt) +
  tm_raster(alpha = 0.5, palette = terrain.colors(25),
            legend.show = FALSE)
#> Linking to GEOS 3.6.1, GDAL 2.2.4, proj.4 4.9.3
```

![](https://i.imgur.com/nQDTeq5.png)

Created on 2018-09-04 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).``` r
library(raster)
#> Loading required package: sp
alt = getData('alt', country = 'CHE')
slope = terrain(alt, opt = 'slope')
aspect = terrain(alt, opt = 'aspect')
hill = hillShade(slope, aspect, 40, 270)

library(tmap)  
tm_shape(hill) +
 tm_raster(palette = gray(0:100 / 100), n = 100, legend.show = FALSE)  +
  tm_shape(alt) +
  tm_raster(alpha = 0.5, palette = terrain.colors(25),
            legend.show = FALSE)
#> Linking to GEOS 3.6.1, GDAL 2.2.4, proj.4 4.9.3
```

![](https://i.imgur.com/nQDTeq5.png)

Created on 2018-09-04 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

You can see a similar example in the [geocompr book](https://geocompr.robinlovelace.net/geometric-operations.html#raster-vector) - the source code is at https://github.com/Robinlovelace/geocompr/blob/master/05-geometry-operations.Rmd.

**Comment by carbonmetrics** [comment]
Thanks! This works. BTW have you seen the [rayshader](https://github.com/tylermorganwall/rayshader) package? Can't get it to work with tmap. It can even print your maps on a 3D printer...

**Comment by tim-salabim** [comment]
AFAIK rayshader has no sense of space in a geographic sense, i.e. only works on matrices without projection information.
