### ISSUE TITLE
Title, Legend Layout Issue

### ISSUE THREAD

**Issue by cubiloju** [mtennekes/tmap#246]
I have a map using CDC mortality data in which I'm comparing female and male cancer death rates by county using a diverging color ramp. The code is the following:

```{r}
diverge <- c('#8c510a', '#d8b365', '#f6e8c3', '#f5f5f5', '#c7eae5', '#5ab4ac', '#01665e')
tm_shape(northeast2) +
  tm_fill('abs_change',
          breaks = c(-15,-10, -5, 0, 5, 10, 15),
          style = 'fixed',
          textNA = 'Suppressed Data',
          colorNA = 'white',
          palette = diverge,
          title = 'Absolute Difference in Rate per 100,000 py') +
  tm_borders(alpha = 0.2) +
  tm_credits('Source: CDC Wonder',
             position = c('LEFT', 'BOTTOM')) +
  tm_layout(main.title = 'Absolute Difference in Lung Cancer Mortality Rate by Gender, 2014-2016',
            bg.color = 'grey85')
summary(us2)
```
I have a few things that I'm trying to do, but can't seem to figure out:

1. How can I make it so that the titles of the map and legend go onto additional lines so that they aren't cut off?
2. How can I add a label on the other side of the color bar saying "Female" at the top and "Male" at the bottom? Is doing this even possible in tmap?
3. How can I add a line pattern to the counties that have suppressed data? Currently they appear white, but I would like to add a diagonal line pattern to make them stand out more.

Any help with these issues would be helpful. I'm relatively new to tmap, so I am not familiar with how to accomplish any of this.

**Comment by Nowosad** [comment]
Hey @cubiloju,
can you provide a reproducible example, for example by using some data from R packages, or by providing a file with your data?

Now, I can only answer the last question. I don't think it is possible now. See https://github.com/mtennekes/tmap/issues/49.

**Comment by cubiloju** [comment]
Sure. I've attached the data and included the complete code in addition to the map code I provided originally:

[Female_LungCancer_2014-2016.txt](https://github.com/mtennekes/tmap/files/2402892/Female_LungCancer_2014-2016.txt)
[Male_LungCancer_2014-2016.txt](https://github.com/mtennekes/tmap/files/2402893/Male_LungCancer_2014-2016.txt)

```{r}
deathmales <- read.table('Male_LungCancer_2014-2016.txt', sep = '\t',
                    header = T, na.strings = 'Missing', stringsAsFactors = F)
deathfemales <- read.table('Female_LungCancer_2014-2016.txt', sep = '\t',
                           header = T, na.strings = 'Missing', stringsAsFactors = F)

x <- as.numeric(deathmales$Deaths)
deathmales[is.na(x), ]

y <- as.numeric(deathfemales$Deaths)
deathfemales[is.na(y), ]

library(tidyverse)
summary(deathmales)
deathmales2 <- deathmales %>%
  mutate(deaths = ifelse(is.na(x), NA, Deaths),
         deaths = as.numeric(deaths),
         m_crude_rate = deaths / Population * 100000) %>%
  filter(!is.na(County.Code))%>%
  mutate(FIPS = sprintf('%05d', County.Code)) %>%
  select(County, FIPS, deaths, Population, m_crude_rate)


deathfemales2 <- deathfemales %>%
  mutate(deaths = ifelse(is.na(y), NA, Deaths),
         deaths = as.numeric(deaths),
         f_crude_rate = deaths / Population * 100000) %>%
  filter(!is.na(County.Code))%>%
  mutate(FIPS = sprintf('%05d', County.Code)) %>%
  select(County, FIPS, deaths, Population, f_crude_rate)

library(tidycensus)
library(tigris)
library(sf)

options(tigris_use_cache = T)
us <- counties(cb = TRUE, class = 'sf') %>%
  st_transform(102003)


northeast <- us %>%
  mutate(FIPS = GEOID) %>%
  filter((STATEFP %in% c('09', '23', '25', '33', '34', '36', '42', '44', '50'))) %>%
  select(FIPS, STATEFP, COUNTYFP, NAME)

merged <- merge(deathfemales2, deathmales2, by = 'FIPS')

merged$abs_change <- merged$m_crude_rate - merged$f_crude_rate

northeast2 <- merge(northeast, merged, by = 'FIPS', all.x = T)

library(tmap)
diverge <- c('#8c510a', '#d8b365', '#f6e8c3', '#f5f5f5', '#c7eae5', '#5ab4ac', '#01665e')
tm_shape(northeast2) +
  tm_fill('abs_change',
          breaks = c(-15,-10, -5, 0, 5, 10, 15),
          style = 'fixed',
          textNA = 'Suppressed Data',
          colorNA = 'white',
          palette = diverge,
          title = 'Absolute Difference in Rate per 100,000 py') +
  tm_borders(alpha = 0.2) +
  tm_credits('Source: CDC Wonder',
             position = c('LEFT', 'BOTTOM')) +
  tm_layout(main.title = 'Absolute Difference in Lung Cancer Mortality Rate by Gender, 2014-2016',
            bg.color = 'grey85')
summary(northeast2)
```

**Comment by Nowosad** [comment]
@cubiloju , 
The first question - you can use `\n` to split a long text into two lines, e.g. `'Absolute Difference in Lung Cancer Mortality Rate\nby Gender, 2014-2016'`.
I don't know what's the best solution for the second question

**Comment by mtennekes** [comment]
Regarding the other two questions:

2. That's not possible. Two workarounds: 

- You could add custom labels like `labels = c("-15 to -10 (male)", "-10 to -5", ...`
- You could place text anywhere in the map using `tm_credits`, e.g.  `+ tm_credits("Male", position = c(.2, .9))`

3. See #49

**Comment by tkt983** [comment]
I was just wondering how to split a title for an interactive map?  The \n can be used to split a long text into two lines for static maps; hower, this doesn't work for an interactive map. 
tm_credits also doesn't work for an interactive map. Is there a way to include map credits (data source) on an interactive map?
