### ISSUE TITLE
Takes very long time to load the package

### ISSUE THREAD

**Issue by shizidushu** [mtennekes/tmap#247]
``` r
system.time(library(tmap))
#>    user  system elapsed 
#>   2.280   0.112 257.043
```

<sup>Created on 2018-09-29 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by mtennekes** [comment]
Hope it was worth waiting for;-) See #240

**Comment by tim-salabim** [comment]
@shizidushu this seems to be an issue with your system. On my system this doesn't take nearly as long:

```r
system.time(library(tmap))
#   user  system elapsed 
#  1.381   0.011   1.877 
system.time(library(mapview))
#   user  system elapsed 
#  0.016   0.000   0.016 
```
Are you on some sort of server set-up?

@mtennekes I also checked mapview in case this is also caused by mapview (which it isn't it seems).

**Comment by shizidushu** [comment]
@tim-salabim About system(Debian 9), here is [my dockerfile repo](https://github.com/shizidushu/dockerfile/tree/rstudio).
I also check it in my local Fedora 28 and it takes long time to load too.
