### ISSUE TITLE
shell vs system in animation_tmap

### ISSUE THREAD

**Issue by rlzijdeman** [mtennekes/tmap#25]
Hi Martijn,

wow, really impressed of your new package, another great one like treemap.

I've rushed head-in to the animation, but when I run the examples from the documentation, I get the following error, using animation_tmap()

Error in animation_tmap({ : could not find function "shell"

From what I understand from https://stat.ethz.ch/R-manual/R-devel/library/base/html/system.html system is the actual function, although shell is directly used under Windows. Just to see if it worked, I replaced 'shell' with 'system'. Then the function starts, but I think later on there is another function call to 'shell' as the error is repeated. See here the function and output:

> animation_tmap2 <- function (expr, width = 1000, height = 1000, delay = 40, filename = "animation.gif") 
+ {
+     checkIM <- system("convert -version")
+     if (checkIM != 0) 
+         stop("Could not find ImageMagick. Make sure it is installed and included in the systems PATH")
+     d <- paste(tempdir(), "/tmap_plots", sep = "/")
+     dir.create(d)
+     png(filename = paste(d, "plot%03d.png", sep = "/"), width = width, 
+         height = height)
+     print(expr)
+     dev.off()
+     output <- shell(paste("convert -delay ", delay, " ", d, "/*.png \"", 
+                           filename, "\"", sep = ""))
+     unlink(d, recursive = TRUE)
+     invisible()
+ }
> animation_tmap2({
+     tm_shape(Europe) +
+         tm_fill("yellow") +
+         tm_borders() +
+         tm_facets(by = "name", nrow=1,ncol=1) +
+         tm_layout(scale=2)
+ }, width=1200, height=800, delay=100, filename="European countries.gif")
Version: ImageMagick 6.9.0-0 Q16 x86_64 2014-12-14 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2014 ImageMagick Studio LLC
Features: DPC Modules
Delegates (built-in): bzlib djvu fftw fontconfig freetype gslib jbig jng jp2 jpeg lcms ltdl lzma openexr png ps tiff webp x xml zlib

Error in animation_tmap2({ : could not find function "shell"

**Comment by mtennekes** [comment]
Thanks! Yes, there is a second `shell`, at bullet 11.

**Comment by rlzijdeman** [comment]
right, sorry for not keeping calm and cry for help. Shall I try to built in an OS-check on which either shell or system is used, or does system work on windows as well?

**Comment by mtennekes** [comment]
Yes, that would be nice!

**Comment by rlzijdeman** [comment]
ok, done! Code works for me, but can only check it on my mac. Pls also check whether you like the code, I am not a programmer :/

Richard

On 26 Jul 2015, at 10:57, mtennekes <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, that would be nice!
