### ISSUE TITLE
tm_rgb() looses detail in light or dark places

### ISSUE THREAD

**Issue by FolkyHobbit** [mtennekes/tmap#253]
I am fairly new to the package, so I hope I am not doing something obvious wrong here.

I want to use a satalite image as the background for a plot. I need a script that saves this background with multiple data sets so working with the vieuw mode and tm_basemap() or tm_tiles() is out. So I decided to save a section of satalite image with Qgis as a TIFF.  [bugreportTIFF.zip](https://github.com/mtennekes/tmap/files/2466356/bugreportTIFF.zip)  (I made a special one of a small area to keep the file size small)

when I run 
`BG <- brick([path to bugrport.0.tif]) `
`tm_shape(BG) + tm_rgb()`
I get a distorded image
![result-tm_rgb](https://user-images.githubusercontent.com/17499803/46763209-8409bb80-ccd9-11e8-88de-45f9e51795c7.png)

But if I run:
`plotRGB(BG)`
![result-plotrgb](https://user-images.githubusercontent.com/17499803/46763206-8409bb80-ccd9-11e8-99f8-bb18625531ec.png)

The image looks as expected, which makes me think there is a problem with the tm_rgb() function, but I am not sure.

**Comment by mtennekes** [comment]
Does image have the same sharpness? If not, you could try with `+ tm_layout(outer.margins = 0)`.
Regarding the colors: from the RGB values, I create a colortable of 256 colors in order to improve the computation speed. Probably, the number of colors can be increased, but requires some work.

**Comment by FolkyHobbit** [comment]
Thank you for your reply. I tried your suggestion and with the `+ tm_layout(outer.margins = 0)` the border around the plot disappears, but that was not my problem. My problem is with the colours. I guess it indeed looks like a image compression issue. I understand that in most cases it is not worth the computational speed, but in the case of imagery it might be useful to have a value to override to increase the quality in exchange for speed. Would be awesome if you or someone gets around to it some time. Thank you for this project.

**Comment by mtennekes** [comment]
It's fixed now. The colortable that was used is not needed anymore, since it doesn't improve the computation speed anymore.

**Comment by mtennekes** [comment]
For large rasters objects, it is still much slower than `plotRGB` by the way...
