### ISSUE TITLE
Installation on Debian stable (9 Stretch) 

### ISSUE THREAD

**Issue by paulauvirage** [mtennekes/tmap#256]
When trying to install through R Studio I am getting this error 

Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/paul/R/x86_64-pc-linux-gnu-library/3.5/png/libs/png.so':
  libpng12.so.0: cannot open shared object file: No such file or directory

libpng12 does not ship with Debian 9 and there seems to be no solution to installing it without it conflicting with other packages. 

Apologies if this is a Debian rather than tmap issue.

**Comment by Nowosad** [comment]
Can you install the png package:
```
install.packages("png")
```
?

**Comment by paulauvirage** [comment]
Thank you! I installed png as you suggested and was then able to successfully install tmap. I was in R Studio, and did not get an error message that tmap needed png
