### ISSUE TITLE
Option to increase space between axis titles and axis

### ISSUE THREAD

**Issue by robsalasco** [mtennekes/tmap#260]
Hi @mtennekes 

Thank you... tmap is awesome! 

I want to move the axis title a little to avoid the overlap. Can you add an option to set the space please?

<img width="432" alt="captura de pantalla 2018-11-18 a la s 22 27 51" src="https://user-images.githubusercontent.com/2642107/48681449-45410e00-eb81-11e8-99d4-6786c2d96418.png">

Best, Roberto.

**Comment by Robinlovelace** [comment]
A basic reproducible example could help verify the result here.

**Comment by robsalasco** [comment]
> A basic reproducible example could help verify the result here.

Here we go!
```
library(tmap)
data(World)
qtm(World, fill="#FFF8DC", projection="longlat") +
  tm_grid(col = "gray70", labels.inside.frame=F) +
  tm_xlab("Longitude") +
  tm_ylab("Latitude")
```

![plot_zoom](https://user-images.githubusercontent.com/2642107/48712269-1b710100-ebec-11e8-862a-a2234f22e21a.png)

**Comment by mtennekes** [comment]
Done! I've added an argument to `tm_xlab` and `tm_ylab` called `space`. When grid line labels are plotted outside the frame, it is set automatically to a value such that the axis titles are plotted near the grid line labels.

**Comment by robsalasco** [comment]
Thank you @mtennekes !!!
