### ISSUE TITLE
travis issues

### ISSUE THREAD

**Issue by mtennekes** [mtennekes/tmap#263]
Can't get travis to work:-( I've tried the .travis.yml script from both `sf` and `mapview`, but without succes.
It's not really important, but quite annoying... Any help is welcome (@tim-salabim @edzer @Nowosad)

**mapview script**

`mapview` uses postgis-2.4.4 (https://github.com/r-spatial/mapview/blob/develop/.travis.yml)
When using this script for tmap (see https://github.com/mtennekes/tmap/blob/8722b8b238d7360886ad6e67a06bd1de3bb6973f/.travis.yml), there are problems with lwgeom:

```
installing to /home/travis/R/Library/lwgeom/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error: package or namespace load failed for â€˜lwgeomâ€™ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/travis/R/Library/lwgeom/libs/lwgeom.so':
  liblwgeom-2.4.so.0: cannot open shared object file: No such file or directory
Error: loading failed
Execution halted
ERROR: loading failed
* removing â€˜/home/travis/R/Library/lwgeomâ€™
Error in i.p(...) : 
  (converted from warning) installation of package â€˜lwgeomâ€™ had non-zero exit status
```
(Complete log files: see https://travis-ci.org/mtennekes/tmap/builds/459769372)

**sf script**

`sf` uses postgis-2.3.2 (https://github.com/r-spatial/sf/blob/master/.travis.yml)
When using this script for tmap (see https://github.com/mtennekes/tmap/blob/master/.travis.yml), I get this error:

```
   creating vignettes ...
  
   creating vignettes ...
  
[31mE  [39m[31mcreating vignettes[39m[36m[36m (18.5s)[36m[39m
   Linking to GEOS 3.5.0, GDAL 2.2.2, PROJ 4.8.0
   ptarray_area_spheroid: cannot handle ptarray that crosses equator
```

(Complete log files: see https://travis-ci.org/mtennekes/tmap/builds/461192944)

This is probably related: https://groups.google.com/forum/#!topic/postgis-users/D4AyPPmeaQc

**Comment by edzer** [comment]
tmap shouldn't need postgis, since postgis is only needed for _checking_ sf, not (afaict) for _checking_ tmap. It should only need to be able to _install_ sf, meaning libgdal-dev, libgeos-dev, libproj-dev and libudunits2-dev. Installing stars will require additionally libnetcdf-dev and netcdf-bin for its dependencies.

What is your latest travis version that still worked?

**Comment by mtennekes** [comment]
Thanks! Makes sense. I decided to added the postgis installation because of this error:

`Warning: namespace ‘RPostgreSQL’ is not available and has been replaced`
(https://travis-ci.org/mtennekes/tmap/jobs/381625971#L2285)

This is the latest working one with postgis installation : https://github.com/mtennekes/tmap/blob/561089c7fbb8d70f16ea1e8b96e6c9494f5fde2a/.travis.yml
This is the last one that worked without postgis installation: https://github.com/mtennekes/tmap/blob/728f626925aa81232699fe031f22dd941c422f0a/.travis.yml

**Comment by edzer** [comment]
When I load `tmap`, `RPostgreSQL` does not get loaded. I don't see where this comes from. I'd go for the simplest possible travis setup; much of this is a waste of time, IMO, since it's all secondary (helping tmap development only indirectly).

**Comment by edzer** [comment]
Ah, and remove liblgweom-dev from travis.

**Comment by mtennekes** [comment]
Thx. Now I get this...

```
   ** byte-compile and prepare package for lazy loading
   Error in dyn.load(file, DLLpath = DLLpath, ...) : 
     unable to load shared object '/home/travis/R/Library/lwgeom/libs/lwgeom.so':
     liblwgeom-2.3.so.0: cannot open shared object file: No such file or directory
```

**Comment by edzer** [comment]
cache problem.
`cache: false`

**Comment by edzer** [comment]
As mentioned above: Installing stars will require additionally libnetcdf-dev and netcdf-bin for its dependencies.

**Comment by mtennekes** [comment]
Hmm, I did't know installation of stars was required. Fingers crossed:-)

**Comment by edzer** [comment]
My mistake - it was raster that requires ncdf4, and its system requirements.

**Comment by mtennekes** [comment]
Many thanks again. Problem solved!
