### ISSUE TITLE
Visualising uncertainty in maps

### ISSUE THREAD

**Issue by joelgombin** [mtennekes/tmap#266]
I'm not sure whether this will be high on your roadmap, but [this talk](https://youtu.be/E1kSnWvqCw0?t=1799) suggests what I think is a pretty interesting way of communicating uncertainty in maps. It might be worth considering implementing it in `tmap`. Plus, it shouldn't be too complicated to implement. What do you think?

**Comment by dickoa** [comment]
Just sharing this WIP package that implement most of these approaches to show uncertainty in maps.
https://github.com/pkuhnert/Vizumap
It will be definitly great to have them in tmap.
