### ISSUE TITLE
tm_facets not including data for 2 of 3 facets

### ISSUE THREAD

**Issue by GeraldCNelson** [mtennekes/tmap#267]
The code below draws three maps as expected, one for each year in the year column (2005, 2050, 2080) but includes colored polygons only for 2080. Is the problem in the code or the data?

```
library(tmap)
map.temp <- readRDS("test.RDS")
#map.temp <- filter(map.temp, year == "2005")
title <- "Maize rainfed yield <br> (mt/ha)"
legend_title <- title
tmap_mode("view")
tm_shape(map.temp) + 
   #  tm_polygons(col = "value", title = legend_title) +
     tm_fill(col = "value", title = legend_title)  +
  tm_borders(col = "gray") +
   #  tm_symbols(col = "black", border.col = "black", size = "value", title.col = legend_title) +
   tm_facets(by = "year",  nrow = 3, free.coords = FALSE, sync = TRUE) + 
  # tm_layout(title = title) +
  tm_view(view.legend.position  = c("left", "bottom"))
```

**Comment by GeraldCNelson** [comment]
Forgot to add that the test.RDS file is available [here](https://github.com/GeraldCNelson/nutmod/blob/master/test.RDS).

**Comment by GeraldCNelson** [comment]
Your SO fix did the trick. I put this in both places because at least the terminology in Help for the use of free.coords is unclear what TRUE actually does and wanted the developers to see it.

**Comment by mtennekes** [comment]
To clarify: `free.coords` determines whether the bounding box is specified per facet separately.
What you need if `drop.units = TRUE`. By default, `tmap` draws all spatial features for each grouped-by-category, assuming that each feature should have a value for each category (albeit `NA`). This obviously goes wrong when duplicating the features, one for each category. See https://github.com/mtennekes/tmap/issues/136 for a more detailed explanation.

The reason that is works with `free.coords = TRUE` is the default value of `drop.units`, which is  `drop.units=free.coords || as.layers`. 

If you have any suggestions to improve its behavior or the documentation, please let me know.

**Comment by GeraldCNelson** [comment]
I read #136 and have a better understanding now of what's going on although I'm just beginning to use tmap and have some trouble following its terminology. One suggestion would be to update the help text, both with improved text describing what the options do and more examples of their behavior. Another would be to have the default behavior of tm_facets _not_ to draw all three (in my case) polygons. But I suspect this would not really work. 

A more serious problem is the situation I reported on in #268 where the wrong data are being displayed.

**Comment by mtennekes** [comment]
Thx for your feedback. I have included some extra examples. Also, `drop.units` is now set to `TRUE` by default.
