### ISSUE TITLE
tmap facets displays the wrong data

### ISSUE THREAD

**Issue by GeraldCNelson** [mtennekes/tmap#268]
I'm trying to use tm_facets to display data (in this case on maize yields) in 2005, 2050, and 2080 using data in the test.RDS file, available [here](https://github.com/GeraldCNelson/nutmod/blob/master/test.RDS).

The code below does this, but displays the data in the wrong polygon and wrong years. To see this, run the script and click the dark red area in northeast Canada. The popup in all three maps says AMR_RUS with value of 5,634, but the colors are different. View the map.temp file (I'm using Rstudio to do all of this). Filter on FPU with AMR_RUS. The 2005 value is 6,047, 2050 is 5634 and 2080 is 4406 (ie, climate change will reduce yields in this area). Next look at the first couple of entries in the geometry column. The lat long coordinates are for a region along the Chinese-Russian border. The Amur River makes up that border and AMR_RUS FPU (food production unit) is to the north of the Amur River in Russia.

Is the problem with my code or data or the tm_facet function in tmap?

```
library(tmap)
map.temp <- readRDS("test.RDS")
title <- "Maize rainfed yield <br> (mt/ha)"
legend_title <- "(mt/ha)"
breaks <- c(1.0, 2139.2, 4277.5, 6415.8, 8554)
tm_shape(map.temp) + 
  tm_polygons(col = "value", title = legend_title) +
  tm_facets(by = "year") +
  tm_layout(main.title = title) +
  tm_view(view.legend.position  = c("left", "bottom"))
```

**Comment by mtennekes** [comment]
It should be fixed now.

**Comment by GeraldCNelson** [comment]
I updated my tmap from GitHub (current version I have on my mac is 2.2) and tmaptools is at version 2.0-1. This code
```
map.temp <- readRDS("test.RDS")
title <- "Maize rainfed yield <br> (mt/ha)"
legend_title <- "(mt/ha)"
breaks <- c(1.0, 2139.2, 4277.5, 6415.8, 8554)
tmap_mode("view")
tm_shape(map.temp) + 
  tm_polygons(col = "value", breaks = breaks, title = legend_title) +
  tm_facets(by = "year",  nrow = 3, free.coords = TRUE, sync = TRUE) + 
  tm_layout(title = title) +
  tm_view(view.legend.position  = c("left", "bottom"))
```
still has data in the wrong place. The easiest way to see this is to mouse over Greenland. The popup says it is CAF_GAB with a value of 1,877 in all three periods. But the Greenland polygon is gray, which is the NA color.

**Comment by mtennekes** [comment]
Strange, because it works on my pc (Unbutu 18.04, but for this issue is shouldn't matter)... Please make sure you have the latest github version running. Could you post me your `devtools::session_info()`?

**Comment by GeraldCNelson** [comment]
My bad. I restarted Rstudio and it seems to work fine now. I must have had the old version still running. Thanks for this!
