### ISSUE TITLE
[Q] Should `tm_lines` have a `title` argument?

### ISSUE THREAD

**Issue by Nowosad** [mtennekes/tmap#269]
Hey @mtennekes, latetly I've tried to add a legend title to a line dataset and found out the `title` argument does not exist in `tm_lines()`. Should `tm_lines()` have a `title` argument (the same as it exists in `tm_fill()`?

``` r
library(sf)
#> Linking to GEOS 3.6.1, GDAL 2.3.2, PROJ 4.9.3
library(tmap)
library(spData)

tm_shape(seine) + 
  tm_lines("name", title = "River name:")
#> Error in tm_lines("name", title = "River name:"): argument 2 matches multiple formal arguments
```

<sup>Created on 2019-01-03 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by mtennekes** [comment]
`title.col` is what you are looking for. Since `tm_lines` has two aesthetics, two titles can be specified: `title.col` and `title.lwd`.
