### ISSUE TITLE
tm_raster fails if the raster has both "in_memory" and "in file layers"

### ISSUE THREAD

**Issue by behrica** [mtennekes/tmap#274]
Using tm_raster with a "rasterStack" which contains both, a "on-disk raster"  and a "in memory raster", fails.

Code to reproduce:

```r
library(raster)
library(tmap)
fn = system.file("external/test.grd", package = "raster")
r_onDisk = raster(fn)
r_inMemory = r_onDisk > 0
mixed_stack = stack(r_onDisk, r_inMemory)

plot(mixed_stack)  # works

tm_shape(mixed_stack) + tm_raster()
# fails with Error in data.frame(..., check.names = FALSE) :
#  arguments imply differing number of rows: 0, 9200
```

**Comment by behrica** [comment]
There is a simple work around, which is to convert the RasterStack to a RasterBrick:
(or use the  RasterBrick from the begining)

```
tm_shape(brick(mixed_stack)) + tm_raster()
```

user "brick" works

```
mixed_brick = brick(r_onDisk,r_inMemory)
tm_shape(mixed_brick) + tm_raster()

```

**Comment by mtennekes** [comment]
Thx! It's fixed now.

The problem was that `raster::fromDisk(mixed_stack)` returns `FALSE`, even though one of the layers is read from disk.
