### ISSUE TITLE
text labels that adapt their shape to the lines

### ISSUE THREAD

**Issue by hmeleiro** [mtennekes/tmap#279]
I don't know if this is an issue but here it goes:

I'm trying to print a map of lines (streets) and want to visualize their labels (street names) in a way that they adapt to the shape of the line. I thought that the ``` along.lines ``` argument in the ``` tm_text() ``` function was going to do the job but it doesn't. I dont know if this is because is not the expected behaviour of ``` along.lines = T ``` or because I'm doing something wrong.

I first did this:

```
mapa <- tmap_mode(mode = "plot") +  
tm_shape(calles, name = "calles", bbox = b) + 
tm_lines(col = "black", alpha = 0.8) + 
tm_text(text = "NOMBRE", size = 0.6,  col = "black", fontfamily = "Roboto Condensed", along.lines = T, remove.overlap = T, shadow = T, overwrite.lines = T, auto.placement = T)
  
mapa
```
but got this error: ``` Error: is.list(x) is not TRUE ```

So I did this, didn't get the error but achieved nothing:

```
calles <-  readOGR("~/Downloads/900YTOYWDW/call2017.shp")
calles <- calles[calles@data$CMUN == "079",]

mapa <- tmap_mode(mode = "plot") +  
tm_shape(calles, name = "calles", bbox = b) + tm_lines(col = "black", alpha = 0.8) +
tm_shape(calles, name = "nomcalles", bbox = b) + tm_text(text = "NOMBRE", size = 0.6, col = "black", fontfamily = "Roboto Condensed", along.lines = T, remove.overlap = T, shadow = T, overwrite.lines = T, auto.placement = T)

mapa
```

In the case that this is not the expected behaviour of ``` along.lines ```, is there a way of achieving this with ```tmap()```?

The shapefile I'm using can be downloaded [here](https://github.com/hmeleiro/callejero).

Thank you very much in advance.
Great package by the way!!

**Comment by mtennekes** [comment]
Thanks for your question! 

First, `tmap_mode()` should be used separately.

When I run this code

```
tmap_mode(mode = "plot")
calles2 <- calles[1:10,]
tm_shape(calles2, name = "calles") + 
tm_lines(col = "black", alpha = 0.8) + 
	tm_text(text = "NOMBRE", size = 0.6,  col = "black", fontfamily = "Roboto Condensed", 
        along.lines = T, remove.overlap = T, shadow = T, overwrite.lines = T, auto.placement = T)
```

I get this map:

![rplot](https://user-images.githubusercontent.com/2444081/52901442-e0d72e80-3203-11e9-9a52-ba9ea63a488f.png)

The algorithms for these text functions (along lines, remove overlap, and auto placement) are not perfect, but with some tuning you may be able to get satisfying results.

**Comment by hmeleiro** [comment]
I get the same result using your code. I'll work with this functions to solve it out.

Thank you very much for your response.
