### ISSUE TITLE
title does not snap to legend when legend.outside = FALSE

### ISSUE THREAD

**Issue by Kanoet** [mtennekes/tmap#280]
In the example below the title does not snap to the legend when the legend is plotted inside, but it does when `legend.outside=FALSE`. 
```

library(tmap)
data("World", metro)
tm_shape(World) + tm_fill()+
     tm_shape(metro,title="Test") + 
     tm_symbols(
         size = "pop2020",
         col = "pop2020",
         title.size = "subtitle 1", 
         title.col =  "subtitle 2", 
         legend.size.is.portrait=TRUE) +
    tm_layout(legend.bg.color = "gray", 
                             legend.frame = "black", 
                             title="Title for all", 
                             title.snap.to.legend = TRUE, 
                             legend.outside=TRUE, 
                             title.size =  0.8,           
                             legend.title.size = 0.5, 
                             legend.text.size = 0.3,
                             title.fontface = "bold", 
                             legend.title.fontface = "italic" )
```
Output: 
<img width="741" alt="bildschirmfoto 2019-02-10 um 08 52 28" src="https://user-images.githubusercontent.com/47493422/52531151-5711f780-2d11-11e9-8c24-1f9217cf3838.png">
If I try with `legend.outside=FALSE` it does not work but the settings for `title.fontface` and `legend.title.fontface` are both used: 
```
tm_shape(World) + tm_fill()+
     tm_shape(metro,title="Test") + 
     tm_symbols(
         size = "pop2020",
         col = "pop2020",
         title.size = "subtitle 1", 
         title.col =  "subtitle 2", 
         legend.size.is.portrait=TRUE) +
    tm_layout(legend.bg.color = "gray", 
                             legend.frame = "black", 
                             title="Title for all", 
                             title.snap.to.legend = TRUE, 
                             legend.outside=FALSE, 
                             title.size =  0.8,           
                             legend.title.size = 0.5, 
                             legend.text.size = 0.3,
                             title.fontface = "bold", 
                             legend.title.fontface = "italic" )

```
Output: 
<img width="888" alt="bildschirmfoto 2019-02-10 um 08 52 53" src="https://user-images.githubusercontent.com/47493422/52531164-81fc4b80-2d11-11e9-9362-ad5a1970e267.png">
How can I snap the title to the legend when the legend is plotted inside? Ideally I would like the title to be bold and title.col and title.size to be italic.

**Comment by mtennekes** [comment]
The title is placed in a different corner than the legend. If you add `title.position = c("left", "bottom")`, it will work.

**Comment by Kanoet** [comment]
Many thanks! That worked. Is there a way to keep different font faces for the titles? As soon as I snap the title to the legend the settings for `legend.title.fontface` are used although I have set `title.fontface` to something else.

**Comment by mtennekes** [comment]
Thanks for letting me know. It should work now.
