### ISSUE TITLE
NA values are not displayed

### ISSUE THREAD

**Issue by Kanoet** [mtennekes/tmap#281]
As far as I understand the documentation NA values should be displayed with an x in case `showNa=TRUE` is enabled. In the example below it does not. 
```
library(tmap)
data(World, metro) 

# put population size pop2020 to NA for some cities
metro$pop2020[10:300] <- NA

tm_shape(World) + tm_fill()+
  tm_shape(metro) + 
  tm_symbols(
    size = "pop2020",
    col = "black",
    showNA = TRUE,
    shapeNA = 4,
    legend.size.is.portrait=TRUE) +
  tm_layout(legend.bg.color = "gray", 
            legend.frame = "black") 
```
Output: 
<img width="898" alt="bildschirmfoto 2019-02-10 um 13 29 24" src="https://user-images.githubusercontent.com/47493422/52533711-1bd6ef00-2d38-11e9-9ac5-c6a5f9c1f8dd.png">
I can get what I need using a workaround and adding an extra shape for the NA values: 
```
tm_shape(World) + tm_fill()+
  tm_shape(metro) + 
  tm_symbols(
    size = "pop2020",
    col = "black",
    showNA = TRUE,
    shapeNA = 4,
    legend.size.is.portrait=TRUE) +
  tm_shape(metro[is.na(metro$pop2020),]) +
  tm_dots(shape=4, size = 0.25, border.lwd = 0.2) +
  tm_layout(legend.bg.color = "gray", 
            legend.frame = "black")  + 
tm_add_legend(type="symbol", shape =4, labels = "not available", size = 0.5, border.lwd = 0.5, col = "black") 
```
Output: 
<img width="898" alt="bildschirmfoto 2019-02-10 um 13 30 29" src="https://user-images.githubusercontent.com/47493422/52533731-4fb21480-2d38-11e9-9925-03022b6a932f.png">
However, in my original map I have two legend elements that for layout needs I want to stack horizontally. Adding the NA values as an extra legend element as in my workaround would give me three instead of two columns. Is there any way I could solve this and why are the NA values not displayed?

**Comment by mtennekes** [comment]
The reason that they are not plotted, is because the size is unknown: you can assign a color for missing values, but not a size (since it would imply a certain value). Your approach to use x is a nice workaround. Not sure whether to implement this. We could add arguments `sizeNA` and `shapeNA`?

**Comment by Kanoet** [comment]
Thanks for your explanation! I think your suggestion to add `sizeNA` would be a very good option. 

PS: Fantastic package! Incredibly handy for me as I want to prepare more than 100 similar maps and animations. The tmap package and the possibility to loop in R make that task realistic and actually fun.
