### ISSUE TITLE
Cannot Install tmap from Cran or Github in R 3.3.3

### ISSUE THREAD

**Issue by ilared** [mtennekes/tmap#282]
Hi,

I have a Mac (Yosemite) and R version 3.3.3
I cannot install tmap neither from Cran or Github. 
I have also followed the instruction below to install the updated packages, but nothing.
Can anyone help me pls?

install.packages("devtools")
library(devtools)
install_github("mtennekes/tmaptools")
install_github("mtennekes/tmap")

This is the message I get installing it from CRAN (I have tried answering yy, nn, yn, ny..but I get the same result) :

install.packages("tmap")
also installing the dependencies ‘lwgeom’, ‘classInt’, ‘tmaptools’, ‘sf’, ‘units’, ‘leaflet’

  There are binary versions available but the source versions are later:
          binary source needs_compilation
classInt  0.1-24  0.3-1              TRUE
tmaptools  1.2-2  2.0-1             FALSE
sf         0.5-5  0.7-2              TRUE
units      0.5-1  0.6-2             FALSE
leaflet    1.1.0  2.0.2             FALSE
tmap        1.11    2.2             FALSE

Do you want to install from sources the packages which need compilation?
y/n: y
Package which is only available in source form, and may need compilation of C/C++/Fortran:
  ‘lwgeom’
Do you want to attempt to install these from sources?
y/n: y
installing the source packages ‘lwgeom’, ‘classInt’, ‘tmaptools’, ‘sf’, ‘units’, ‘leaflet’, ‘tmap’
....

* installing *source* package ‘classInt’ ...
** package ‘classInt’ successfully unpacked and MD5 sums checked
** libs
gfortran-4.8   -fPIC  -g -O2  -c fish1.f -o fish1.o
make: gfortran-4.8: No such file or directory
make: *** [fish1.o] Error 1
ERROR: compilation failed for package ‘classInt’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/classInt’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/classInt’
Warning in install.packages :
  installation of package ‘classInt’ had non-zero exit status
* installing *source* package ‘units’ ...
** package ‘units’ successfully unpacked and MD5 sums checked
configure: units: 0.6-2
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether clang++ accepts -g... yes
checking how to run the C++ preprocessor... clang++ -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... rm: conftest.dSYM: is a directory
rm: conftest.dSYM: is a directory
yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... no
checking for error_at_line... no
checking for gcc... clang
checking whether we are using the GNU C compiler... yes
checking whether clang accepts -g... yes
checking for clang option to accept ISO C89... none needed
checking for XML_ParserCreate in -lexpat... yes
checking udunits2.h usability... no
checking udunits2.h presence... no
checking for udunits2.h... no
checking udunits2/udunits2.h usability... no
checking udunits2/udunits2.h presence... no
checking for udunits2/udunits2.h... no
checking for ut_read_xml in -ludunits2... no
configure: error: in `/private/var/folders/80/kjckpyfs4k15nzyn796g8q0m0000gn/T/RtmpH6bjaz/R.INSTALL270d12ddf96c/units':
configure: error: 
--------------------------------------------------------------------------------
  Configuration failed because libudunits2.so was not found. Try installing:
    * deb: libudunits2-dev (Debian, Ubuntu, ...)
    * rpm: udunits2-devel (Fedora, EPEL, ...)
    * brew: udunits (OSX)
  If udunits2 is already installed in a non-standard location, use:
    --configure-args='--with-udunits2-lib=/usr/local/lib'
  if the library was not found, and/or:
    --configure-args='--with-udunits2-include=/usr/include/udunits2'
  if the header was not found, replacing paths with appropriate values.
  You can alternatively set UDUNITS2_INCLUDE and UDUNITS2_LIBS manually.
--------------------------------------------------------------------------------

See `config.log' for more details
ERROR: configuration failed for package ‘units’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/units’
Warning in install.packages :
  installation of package ‘units’ had non-zero exit status
* installing *source* package ‘leaflet’ ...
** package ‘leaflet’ successfully unpacked and MD5 sums checked
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘shiny’
ERROR: lazy loading failed for package ‘leaflet’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/leaflet’
Warning in install.packages :
  installation of package ‘leaflet’ had non-zero exit status
ERROR: dependency ‘units’ is not available for package ‘sf’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/sf’
Warning in install.packages :
  installation of package ‘sf’ had non-zero exit status
ERROR: dependencies ‘units’, ‘sf’ are not available for package ‘lwgeom’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/lwgeom’
Warning in install.packages :
  installation of package ‘lwgeom’ had non-zero exit status
ERROR: dependencies ‘sf’, ‘lwgeom’, ‘units’ are not available for package ‘tmaptools’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/tmaptools’
Warning in install.packages :
  installation of package ‘tmaptools’ had non-zero exit status
ERROR: dependencies ‘tmaptools’, ‘sf’, ‘units’, ‘leaflet’ are not available for package ‘tmap’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/tmap’
Warning in install.packages :
  installation of package ‘tmap’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/80/kjckpyfs4k15nzyn796g8q0m0000gn/T/RtmpLYIfoz/downloaded_packages’

**### This is the message I get using Github (and agreeing to update all packages):**

install_github("mtennekes/tmaptools")
Downloading GitHub repo mtennekes/tmaptools@master
These packages have more recent versions available.
Which would you like to update?

 1:   classInt (0.1-24   -> 0.3-1    ) [CRAN]   2:   DBI      (0.8      -> 1.0.0    ) [CRAN]
 3:   e1071    (1.6-8    -> 1.7-0.1  ) [CRAN]   4:   rgdal    (1.2-16   -> 1.3-6    ) [CRAN]
 5:   rgeos    (0.3-26   -> 0.4-2    ) [CRAN]   6:   sf       (0.5-5    -> 0.7-2    ) [CRAN]
 7:   sp       (1.2-6    -> 1.3-1    ) [CRAN]   8:   XML      (3.98-1.9 -> 3.98-1.17) [CRAN]
 9:   CRAN packages only                       10:   All                                    
11:   None                                     
Enter one or more numbers separated by spaces, or an empty line to cancel
1: 10
classInt (0.1-24   -> 0.3-1    ) [CRAN]
DBI      (0.8      -> 1.0.0    ) [CRAN]
e1071    (1.6-8    -> 1.7-0.1  ) [CRAN]
lwgeom   (NA       -> 0.1-5    ) [CRAN]
rgdal    (1.2-16   -> 1.3-6    ) [CRAN]
rgeos    (0.3-26   -> 0.4-2    ) [CRAN]
sf       (0.5-5    -> 0.7-2    ) [CRAN]
sp       (1.2-6    -> 1.3-1    ) [CRAN]
units    (NA       -> 0.6-2    ) [CRAN]
XML      (3.98-1.9 -> 3.98-1.17) [CRAN]
Installing 10 packages: classInt, DBI, e1071, lwgeom, rgdal, rgeos, sf, sp, units, XML

  There are binary versions available but the source versions are later:
           binary    source needs_compilation
classInt   0.1-24     0.3-1              TRUE
DBI           0.7     1.0.0             FALSE
e1071       1.6-8   1.7-0.1              TRUE
rgdal      1.2-16     1.3-6              TRUE
rgeos      0.3-26     0.4-2              TRUE
sf          0.5-5     0.7-2              TRUE
sp          1.2-6     1.3-1              TRUE
units       0.5-1     0.6-2             FALSE
XML      3.98-1.9 3.98-1.17              TRUE

Do you want to install from sources the packages which need compilation?
y/n: y
Package which is only available in source form, and may need compilation of C/C++/Fortran:
  ‘lwgeom’
Do you want to attempt to install these from sources?
y/n: y
installing the source packages ‘classInt’, ‘DBI’, ‘e1071’, ‘lwgeom’, ‘rgdal’, ‘rgeos’, ‘sf’, ‘sp’, ‘units’, ‘XML’

...

* installing *source* package ‘DBI’ ...
** package ‘DBI’ successfully unpacked and MD5 sums checked
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (DBI)
* installing *source* package ‘e1071’ ...
** package ‘e1071’ successfully unpacked and MD5 sums checked
checking for C++ compiler default output file name... a.out
checking whether the C++ compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether clang++ accepts -g... yes
** libs
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include    -fPIC  -Wall -mtune=core2 -g -O2  -c Rsvm.c -o Rsvm.o
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include    -fPIC  -Wall -mtune=core2 -g -O2  -c cmeans.c -o cmeans.o
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include    -fPIC  -Wall -mtune=core2 -g -O2  -c cshell.c -o cshell.o
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include    -fPIC  -Wall -mtune=core2 -g -O2  -c floyd.c -o floyd.o
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include    -fPIC  -Wall -mtune=core2 -g -O2  -c init.c -o init.o
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include    -fPIC  -Wall -mtune=core2 -g -O2  -c svm.cpp -o svm.o
clang++ -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o e1071.so Rsvm.o cmeans.o cshell.o floyd.o init.o svm.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Library/Frameworks/R.framework/Versions/3.3/Resources/library/e1071/libs
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (e1071)
* installing *source* package ‘sp’ ...
** package ‘sp’ successfully unpacked and MD5 sums checked
** libs
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include    -fPIC  -Wall -mtune=core2 -g -O2  -c Rcentroid.c -o Rcentroid.o
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include    -fPIC  -Wall -mtune=core2 -g -O2  -c gcdist.c -o gcdist.o
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include    -fPIC  -Wall -mtune=core2 -g -O2  -c init.c -o init.o
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include    -fPIC  -Wall -mtune=core2 -g -O2  -c pip.c -o pip.o
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include    -fPIC  -Wall -mtune=core2 -g -O2  -c pip2.c -o pip2.o
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include    -fPIC  -Wall -mtune=core2 -g -O2  -c sp_xports.c -o sp_xports.o
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include    -fPIC  -Wall -mtune=core2 -g -O2  -c surfaceArea.c -o surfaceArea.o
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include    -fPIC  -Wall -mtune=core2 -g -O2  -c zerodist.c -o zerodist.o
clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o sp.so Rcentroid.o gcdist.o init.o pip.o pip2.o sp_xports.o surfaceArea.o zerodist.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Library/Frameworks/R.framework/Versions/3.3/Resources/library/sp/libs
** R
** data
** demo
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (sp)
* installing *source* package ‘units’ ...
** package ‘units’ successfully unpacked and MD5 sums checked
configure: units: 0.6-2
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether clang++ accepts -g... yes
checking how to run the C++ preprocessor... clang++ -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... rm: conftest.dSYM: is a directory
rm: conftest.dSYM: is a directory
yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... no
checking for error_at_line... no
checking for gcc... clang
checking whether we are using the GNU C compiler... yes
checking whether clang accepts -g... yes
checking for clang option to accept ISO C89... none needed
checking for XML_ParserCreate in -lexpat... yes
checking udunits2.h usability... no
checking udunits2.h presence... no
checking for udunits2.h... no
checking udunits2/udunits2.h usability... no
checking udunits2/udunits2.h presence... no
checking for udunits2/udunits2.h... no
checking for ut_read_xml in -ludunits2... no
configure: error: in `/private/var/folders/80/kjckpyfs4k15nzyn796g8q0m0000gn/T/RtmpYkCe47/R.INSTALL4ac553669120/units':
configure: error: 
--------------------------------------------------------------------------------
  Configuration failed because libudunits2.so was not found. Try installing:
    * deb: libudunits2-dev (Debian, Ubuntu, ...)
    * rpm: udunits2-devel (Fedora, EPEL, ...)
    * brew: udunits (OSX)
  If udunits2 is already installed in a non-standard location, use:
    --configure-args='--with-udunits2-lib=/usr/local/lib'
  if the library was not found, and/or:
    --configure-args='--with-udunits2-include=/usr/include/udunits2'
  if the header was not found, replacing paths with appropriate values.
  You can alternatively set UDUNITS2_INCLUDE and UDUNITS2_LIBS manually.
--------------------------------------------------------------------------------

See `config.log' for more details
ERROR: configuration failed for package ‘units’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/units’
Error in i.p(...) : 
  (converted from warning) installation of package ‘units’ had non-zero exit status
> install_github("mtennekes/tmap")
Downloading GitHub repo mtennekes/tmap@master
These packages have more recent versions available.
Which would you like to update?

 1:   BH          (1.66.0-1 -> 1.69.0-1 ) [CRAN]   2:   callr       (2.0.2    -> 3.1.1    ) [CRAN]
 3:   classInt    (0.1-24   -> 0.3-1    ) [CRAN]   4:   colorspace  (1.3-2    -> 1.4-0    ) [CRAN]
 5:   digest      (0.6.13   -> 0.6.18   ) [CRAN]   6:   gdtools     (0.1.6    -> 0.1.7    ) [CRAN]
 7:   glue        (1.2.0    -> 1.3.0    ) [CRAN]   8:   htmlwidgets (1.2      -> 1.3      ) [CRAN]
 9:   httpuv      (1.3.5    -> 1.4.5.1  ) [CRAN]  10:   jsonlite    (1.5      -> 1.6      ) [CRAN]
11:   later       (0.5      -> 0.7.5    ) [CRAN]  12:   mapview     (2.2.0    -> 2.6.3    ) [CRAN]
13:   markdown    (0.8      -> 0.9      ) [CRAN]  14:   mime        (0.5      -> 0.6      ) [CRAN]
15:   R6          (2.2.2    -> 2.3.0    ) [CRAN]  16:   rgdal       (1.2-16   -> 1.3-6    ) [CRAN]
17:   rgeos       (0.3-26   -> 0.4-2    ) [CRAN]  18:   sf          (0.5-5    -> 0.7-2    ) [CRAN]
19:   sourcetools (0.1.6    -> 0.1.7    ) [CRAN]  20:   stringi     (1.1.7    -> 1.2.4    ) [CRAN]
21:   stringr     (1.3.0    -> 1.4.0    ) [CRAN]  22:   utf8        (1.1.3    -> 1.1.4    ) [CRAN]
23:   XML         (3.98-1.9 -> 3.98-1.17) [CRAN]  24:   yaml        (2.1.16   -> 2.2.0    ) [CRAN]
25:   CRAN packages only                          26:   All                                       
27:   None                                        
Enter one or more numbers separated by spaces, or an empty line to cancel
1: 26
BH          (1.66.0-1 -> 1.69.0-1 ) [CRAN]
callr       (2.0.2    -> 3.1.1    ) [CRAN]
classInt    (0.1-24   -> 0.3-1    ) [CRAN]
colorspace  (1.3-2    -> 1.4-0    ) [CRAN]
digest      (0.6.13   -> 0.6.18   ) [CRAN]
gdtools     (0.1.6    -> 0.1.7    ) [CRAN]
glue        (1.2.0    -> 1.3.0    ) [CRAN]
htmlwidgets (1.2      -> 1.3      ) [CRAN]
httpuv      (1.3.5    -> 1.4.5.1  ) [CRAN]
jsonlite    (1.5      -> 1.6      ) [CRAN]
later       (0.5      -> 0.7.5    ) [CRAN]
leaflet     (NA       -> 2.0.2    ) [CRAN]
lwgeom      (NA       -> 0.1-5    ) [CRAN]
mapview     (2.2.0    -> 2.6.3    ) [CRAN]
markdown    (0.8      -> 0.9      ) [CRAN]
mime        (0.5      -> 0.6      ) [CRAN]
R6          (2.2.2    -> 2.3.0    ) [CRAN]
rgdal       (1.2-16   -> 1.3-6    ) [CRAN]
rgeos       (0.3-26   -> 0.4-2    ) [CRAN]
sf          (0.5-5    -> 0.7-2    ) [CRAN]
shiny       (NA       -> 1.2.0    ) [CRAN]
sourcetools (0.1.6    -> 0.1.7    ) [CRAN]
stringi     (1.1.7    -> 1.2.4    ) [CRAN]
stringr     (1.3.0    -> 1.4.0    ) [CRAN]
tmaptools   (NA       -> 2.0-1    ) [CRAN]
units       (NA       -> 0.6-2    ) [CRAN]
utf8        (1.1.3    -> 1.1.4    ) [CRAN]
XML         (3.98-1.9 -> 3.98-1.17) [CRAN]
yaml        (2.1.16   -> 2.2.0    ) [CRAN]
Installing 29 packages: BH, callr, classInt, colorspace, digest, gdtools, glue, htmlwidgets, httpuv, jsonlite, later, leaflet, lwgeom, mapview, markdown, mime, R6, rgdal, rgeos, sf, shiny, sourcetools, stringi, stringr, tmaptools, units, utf8, XML, yaml

  There are binary versions available but the source versions are later:
              binary    source needs_compilation
BH          1.65.0-1  1.69.0-1             FALSE
callr          1.0.0     3.1.1             FALSE
classInt      0.1-24     0.3-1              TRUE
colorspace     1.3-2     1.4-0              TRUE
digest        0.6.13    0.6.18              TRUE
gdtools        0.1.6     0.1.7              TRUE
glue           1.2.0     1.3.0              TRUE
htmlwidgets      0.9       1.3             FALSE
httpuv         1.3.5   1.4.5.1              TRUE
jsonlite         1.5       1.6              TRUE
later            0.5     0.7.5              TRUE
leaflet        1.1.0     2.0.2             FALSE
mapview        2.2.0     2.6.3              TRUE
markdown         0.8       0.9              TRUE
mime             0.5       0.6              TRUE
R6             2.2.2     2.3.0             FALSE
rgdal         1.2-16     1.3-6              TRUE
rgeos         0.3-26     0.4-2              TRUE
sf             0.5-5     0.7-2              TRUE
shiny          1.0.5     1.2.0             FALSE
sourcetools    0.1.6     0.1.7              TRUE
stringi        1.1.6     1.2.4             FALSE
stringr        1.2.0     1.4.0             FALSE
tmaptools      1.2-2     2.0-1             FALSE
units          0.5-1     0.6-2             FALSE
utf8           1.1.3     1.1.4              TRUE
XML         3.98-1.9 3.98-1.17              TRUE
yaml          2.1.16     2.2.0              TRUE

Do you want to install from sources the packages which need compilation?
y/n: y
Package which is only available in source form, and may need compilation of C/C++/Fortran:
  ‘lwgeom’
Do you want to attempt to install these from sources?
y/n: y
installing the source packages ‘BH’, ‘callr’, ‘classInt’, ‘colorspace’, ‘digest’, ‘gdtools’, ‘glue’, ‘htmlwidgets’, ‘httpuv’, ‘jsonlite’, ‘later’, ‘leaflet’, ‘lwgeom’, ‘mapview’, ‘markdown’, ‘mime’, ‘R6’, ‘rgdal’, ‘rgeos’, ‘sf’, ‘shiny’, ‘sourcetools’, ‘stringi’, ‘stringr’, ‘tmaptools’, ‘units’, ‘utf8’, ‘XML’, ‘yaml’

.....

* installing *source* package ‘BH’ ...
** package ‘BH’ successfully unpacked and MD5 sums checked
** inst
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (BH)
* installing *source* package ‘classInt’ ...
** package ‘classInt’ successfully unpacked and MD5 sums checked
** libs
gfortran-4.8   -fPIC  -g -O2  -c fish1.f -o fish1.o
make: gfortran-4.8: No such file or directory
make: *** [fish1.o] Error 1
ERROR: compilation failed for package ‘classInt’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/classInt’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/classInt’
Error in i.p(...) : 
  (converted from warning) installation of package ‘classInt’ had non-zero exit status

> library("tmap")
Error in library("tmap") : there is no package called ‘tmap’

**Comment by mtennekes** [comment]
Hi, please find out which dependency package fails to install. It is likely one of them that causes this problem.

**Comment by Nowosad** [comment]
@ilared please try to install the **sf** package first. The installation instructions are at https://github.com/r-spatial/sf. Please reopen the issue if this doesn't fix your issue.

**Comment by ilared** [comment]
Ok, thank you.

________________________________
Da: mtennekes <notifications@github.com>
Inviato: giovedì 14 febbraio 2019 00:13
A: mtennekes/tmap
Cc: ilared; Author
Oggetto: Re: [mtennekes/tmap] Cannot Install tmap from Cran or Github in R 3.3.3 (#282)


Hi, please find out which dependency package fails to install. It is likely one of them that causes this problem.

**Comment by ilared** [comment]
Thanks, but it doesn't work either.
Cannot install "sf" either.


________________________________
Da: Jakub Nowosad <notifications@github.com>
Inviato: giovedì 14 febbraio 2019 14:35
A: mtennekes/tmap
Cc: ilared; Mention
Oggetto: Re: [mtennekes/tmap] Cannot Install tmap from Cran or Github in R 3.3.3 (#282)


@ilared<https://github.com/ilared> please try to install the sf package first. The installation instructions are at https://github.com/r-spatial/sf. Please reopen the issue if this doesn't fix your issue.
