### ISSUE TITLE
tm_raster: how to map categorical palette consistently?

### ISSUE THREAD

**Issue by MatthieuStigler** [mtennekes/tmap#283]
Hi

Image raster has 2 bands, first with A, B, C, second with A and C only. If I use a categorical palette, I would want C to appear with same colour on each plot. I see a different behaviour:

- use no palette: works, C has same colour on facet 1 and 2
- use `palette = my_colors`: now C has third colour on facet 1 (which has A, B, C), but second on facet 2 (as has only A and C)

So how can I make sure maping is consistent among colours? Thanks!

    library(raster)
    #> Loading required package: sp
    library(tmap)
    r = raster(nrows = 5,
               ncols = 5,
               vals = c(rep(1, 12), 2, rep(3, 12)))
    r$r2 <- c(rep(1, 12), rep(3, 13))

    my_colors = c("red", "green", "blue")

    tm_shape(r) +
      tm_raster(style = "cat")
    #> Linking to GEOS 3.6.2, GDAL 2.2.3, PROJ 4.9.3

![](https://i.imgur.com/OJRziyl.png)

    tm_shape(r) +
      tm_raster(style = "cat", palette = my_colors)

![](https://i.imgur.com/YSD9xgw.png)

<sup>Created on 2019-02-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by Nowosad** [comment]
One solution would be to have just one legend to all rasters:

``` r
library(raster)
#> Loading required package: sp
library(tmap)
r = raster(nrows = 5,
           ncols = 5,
           vals = c(rep(1, 12), 2, rep(3, 12)))
r$r2 <- c(rep(1, 12), rep(3, 13))


my_colors = c("red", "green", "blue")

tm_shape(r) +
  tm_raster(style = "cat", palette = my_colors) +
  tm_facets(free.scales = FALSE)
#> Linking to GEOS 3.6.1, GDAL 2.3.2, PROJ 4.9.3
```

![](https://i.imgur.com/O54Bj82.png)

<sup>Created on 2019-02-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by MatthieuStigler** [comment]
Good point, that's a nice fix for this issue indeed

**Comment by Nowosad** [comment]
Please reopen if you find any problems with this approach.
