### ISSUE TITLE
tm_fill alpha not working with custom fill colors

### ISSUE THREAD

**Issue by bangen** [mtennekes/tmap#289]
I'm trying to make a map using hex fill colors.  I need to make the filled polygon layer transparent to display contours and a hillshade underneath.  However, the alpha argument doesn't do anything when I set the fill to my hex field (i.e., the polygon layer is completely opaque).  Just wondering if it's possible to make a custom fill transparent and if so how?  Thanks!

Here is some reproducible code:

```
library(sf)
library(tmap)
library(spData)
library(tidyverse)

country_name = c("United Kingdom", "Ireland", "Norway", "Sweden", "Finland")
country_hex = c('#004DA8', '#00A9E6', '#73DFFF', '#E6E600', '#FF7F7F')
country_fill = tibble(country_name, country_hex)

world_sub = world %>% 
  filter(name_long %in% country_fill$country_name) %>%
  left_join(country_fill, by = c("name_long" = "country_name"))

map_fill = tm_shape(world_sub) + tm_fill("name_long", alpha = 0.3)

map_my_fill = tm_shape(world_sub) + tm_fill("country_hex", alpha = 0.3)
```
Here's the `map_fill` output.  The alpha parameter works when 'col' is set to a categorical field:

![map_fill](https://user-images.githubusercontent.com/6502954/54149522-98babe80-43f3-11e9-92be-fbc3e62daba8.PNG)

 Here's the `map_my_fill` output.  The alpha parameter does not work when 'col' is set to a field with color values:

![map_my_fill](https://user-images.githubusercontent.com/6502954/54149536-9f493600-43f3-11e9-9e01-5f543a092949.PNG)

**Comment by mtennekes** [comment]
Good point. I didn't implement this before, since I thought it was very slow to process all colors (which could be 1e8 in a raster object). However, for such raster it only took 2 seconds extra. So it's implemented now!
