### ISSUE TITLE
Basic markers not visible in chrome/firefox - OK in rstudio/safari

### ISSUE THREAD

**Issue by richardbeare** [mtennekes/tmap#291]
Hi,
I have been experiencing this problem on mac and linux. For the most recent trial I've used both cran and github versions of tmap under R 3.5.3. The subject covers it - a simple marker in an Rmd document works fine for the rstudio viewer and safari, but not in chrome or firefox. If I run the same code, then export the html using the button in rstudio (i.e. to produce a page with the map only) then the marker is visible in chrome. The Rmd content is attached as a txt file.

[tmap_test.txt](https://github.com/mtennekes/tmap/files/2991652/tmap_test.txt)

**Comment by mtennekes** [comment]
That's odd...

This code chunk does work in Firefox:

```r
library(leaflet)
leaflet() %>% addMarkers(data = MMCLocation) %>% addTiles()
```

**Comment by richardbeare** [comment]
Yep - that works for me too. I stick that in the Rmd as a separate chunk and I get a marker in chrome, but not in the one created with tmap (in the same document).

**Comment by mtennekes** [comment]
Same problem as #304
