### ISSUE TITLE
Greater controls over map layout?

### ISSUE THREAD

**Issue by jhollist** [mtennekes/tmap#295]
First, I am really enjoying getting to know tmap.  Thanks for all your efforts on this!

I initially posted a question on twitter about this ( https://twitter.com/jhollist/status/1114182324936114176).  Per @Nowosad suggestion am moving this to an issue.

I would like compose a map layout with separate panes for the map itself, the map junk (north arrows, legend, scale bar, title, etc.), and then another pane for other stuff (e.g. table, figures, text, etc.).  Is there a way to do this with tmap currently?

A rough sketch of what I was wanting to do:
![map layout](https://pbs.twimg.com/media/D3Ze07WWwAAeOt5.jpg)

**Comment by Nowosad** [comment]
(Not perfect possibility is to use the **grid** package and viewports, e.g. https://geocompr.robinlovelace.net/adv-map.html#inset-maps)

**Comment by mtennekes** [comment]
Yes, the `grid` package is indeed the way forward. Not sure if we could make an easy function for this, or how to improve the work flow...

``` r
library(tmap)
library(grid)
data(NLD_muni)
grid.newpage()
pushViewport(viewport(layout=grid.layout(2, 2, widths=c(0.8, 0.2))))

map <- tm_shape(NLD_muni) +
    tm_polygons("pop_65plus", legend.show = FALSE) +
    tm_layout(asp = 0)

legend <- tm_shape(NLD_muni) +
    tm_polygons("pop_65plus") +
    tm_layout(legend.only = TRUE)

print(map, vp = viewport(layout.pos.col=1, layout.pos.row=1))
print(legend, vp = viewport(layout.pos.col=2, layout.pos.row=1))

pushViewport(viewport(layout.pos.col=2, layout.pos.row=2))
grid.rect(gp=gpar(fill="purple"))
upViewport(1)
```

![](https://i.imgur.com/vL6R9JG.png)

<sup>Created on 2019-04-06 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by jhollist** [comment]
Thanks for the leads! I had actually started playing around with grid.  I've been meaning to dig into a bit more and this gives me a reason.  If (when) I get something up and running for the layout I want, I post what I did back here.  Will also think about how I'd roll this into a general use function.  Happy to share that if it 1) works and 2) is of interest for a `tmap` enhancement.

Thanks again for the leads!

**Comment by tim-salabim** [comment]
Also checkout `gridExtra::grid.arrange`

**Comment by jhollist** [comment]
Does gridExtra work with the `tmap` objects?

**Comment by tim-salabim** [comment]
If grid does, then gridExtra should too
