### ISSUE TITLE
how to show two variables in one map?

### ISSUE THREAD

**Issue by maoyimin** [mtennekes/tmap#296]
Dear all, 
I want to use tmap package to draw a graph like the attached figure.  It shows the values of coefficients with different colors, and  shows the related results of significance test with lines. How can I combine these two layers together in one map? Thank you!

![fig](https://user-images.githubusercontent.com/42795195/56005695-5216f780-5d04-11e9-8dac-36fef1465ee7.png)

**Comment by mtennekes** [comment]
See #49
