### ISSUE TITLE
Share leaflet's dependencies folders between maps

### ISSUE THREAD

**Issue by ccamara** [mtennekes/tmap#297]
If I am not wrong, whenever a map is created in interactive mode and saved into a html file with `tmap_save()`, a *.html file is created as well as a folder containing several subfolders (e.g. `htmlwidgets-1.2`, `jquery-1.12.4`, `leaflet-1.3.1`...), each of them containing its own javascript.

While this approach makes much sense, if several maps are created (e.g. within a loop), each map will  have its own subfolders, which is redundant and takes time and hard disk space to generate them.  

Would it be possible to specify a folder to store all dependencies so they can be shared by all the html_outputs?

**Comment by tim-salabim** [comment]
`tmap_save()` uses `htmlwidgets::saveWidget()` for interactive maps and passes arguments to that function via `...` so specifying the `libdir` argument should work. Here's an example using `saveWidget` directly to use a shared folder between 2 maps:

```r
library(leaflet)
library(htmlwidgets)

map = leaflet() %>%
  addTiles() %>%
  addCircleMarkers(data = breweries91)

saveWidget(widget = map, 
           file = "C:/Users/Tim/Desktop/test_map.html", 
           selfcontained = FALSE,
           libdir = "test")

map2 = leaflet() %>%
  addTiles() %>%
  addPolygons(data = gadmCHE)

saveWidget(widget = map2, 
           file = "C:/Users/Tim/Desktop/test_map2.html", 
           selfcontained = FALSE,
           libdir = "test")
```

**Comment by ccamara** [comment]
Thank you!
