### ISSUE TITLE
Minify leaflet js files into a single file

### ISSUE THREAD

**Issue by ccamara** [mtennekes/tmap#298]
If I am not wrong, whenever a map is created in interactive mode and saved into a html file with `tmap_save()`, a *.html file is created as well as a folder containing several subfolders (e.g. `htmlwidgets-1.2`, `jquery-1.12.4`, `leaflet-1.3.1`...), each of them containing its own javascript.

While this approach makes much sense, it makes more cumbersome to share the output and reuse it and I am wondering if it would be possible to combine/minify all javascript and dependencies in a single file, pretty much as leaflet for r does.

**Comment by tim-salabim** [comment]
have you tried `tmap_save(<yourmap>, selfcontained = TRUE)` ? AFAIKT this will still create the `<yourmap_files>` folder, but it should also work without it (though you need to rename the `.html` to break the link between the file and the folder & the code won't be minified).

This functionality is all provided by `htmlwidgets::saveWidget` so ultimately an issue should be there.

**Comment by mtennekes** [comment]
Yes, indeed.

If there is anything left that is tmap related, please reopen this issue.

**Comment by ccamara** [comment]
Thank you! I missed the `selfcontained` parameter. Shame on me.

**Comment by PedroBelavenutti** [comment]
I have this problem when running an R script with the above line through windows Task Scheduler (which calls Rscript.exe). When I save the map into a html file with tmap_save(<yourmap>, selfcontained = TRUE), it produces the subfolders. When running the same script without using the R package taskscheduleR, it works just fine and produced only one selfcontained HTML file.
In this tutorial they have similar problem:
https://stackoverflow.com/questions/67696141/how-do-i-force-savewidget-to-create-a-single-file-outside-of-rstudio

Thank you for helping!
