### ISSUE TITLE
Error in number of legend categories using "n" function

### ISSUE THREAD

**Issue by RAJohansen** [mtennekes/tmap#299]
Using the "n" function does not always produce n categories/breaks in the legend.

#### Produces 7 categories
tm_shape(world) +
  tm_fill(col = "pop", n =  5) + 
  tm_borders() 

![tm_n_categories](https://user-images.githubusercontent.com/29709655/56374697-d02a4100-61d1-11e9-8115-f0e37b340743.JPG)

**Comment by mtennekes** [comment]
In the documentation, it says "preferred number of color scale classes". It is not always the exact number. To put it differently, what 5 pretty intervals (so 6 breaks) do you expect for these data?

```{r}
for (i in 3:10) {
    cat(i, ":", (pretty(c(0,1.4e09), i)), "\n")
}
#> 3 : 0 5e+08 1e+09 1.5e+09 
#> 4 : 0 5e+08 1e+09 1.5e+09 
#> 5 : 0 2e+08 4e+08 6e+08 8e+08 1e+09 1.2e+09 1.4e+09 
#> 6 : 0 2e+08 4e+08 6e+08 8e+08 1e+09 1.2e+09 1.4e+09 
#> 7 : 0 2e+08 4e+08 6e+08 8e+08 1e+09 1.2e+09 1.4e+09 
#> 8 : 0 2e+08 4e+08 6e+08 8e+08 1e+09 1.2e+09 1.4e+09 
#> 9 : 0 2e+08 4e+08 6e+08 8e+08 1e+09 1.2e+09 1.4e+09 
#> 10 : 0 1e+08 2e+08 3e+08 4e+08 5e+08 6e+08 7e+08 8e+08 9e+08 1e+09 1.1e+09 1.2e+09 1.3e+09 1.4e+09
```
