### ISSUE TITLE
Add `stringsAsFactors` parameter for `read_shape`

### ISSUE THREAD

**Issue by joelgombin** [mtennekes/tmap#3]
and maybe put it to FALSE by default?

**Comment by joelgombin** [comment]
Also maybe add an `encoding` parameter? 
Then, one might argue, one could use `readOGR` directly...

**Comment by mtennekes** [comment]
Very true. One philosophy of the package was that only tmap is required when creating thematic maps. (In other words, I'm lazy;-)). 

I have chosen the ... solution.
