### ISSUE TITLE
Dependency on RCurl

### ISSUE THREAD

**Issue by mbacou** [mtennekes/tmap#30]
Just wondering if the dependency on `RCurl` and `RJSONIO` could be removed as some of us use the `curl` and `jsonlite` packages instead? https://cran.r-project.org/web/packages/curl/index.html
Not sure what's the right way to handle this. My understanding is `curl` is a more flexible choice moving  forward. Some explanation here https://www.opencpu.org/posts/curl-release-0-8/

**Comment by mtennekes** [comment]
Neither of these packages dependencies are indirect

**Comment by mtennekes** [comment]
`tmap` doesn't depend directly on those package. See  https://github.com/mtennekes/tmap/blob/master/pkg/DESCRIPTION. I found that RCurl is needed by `osmar`, but I'm not sure which one uses `RJSONIO`.

**Comment by mbacou** [comment]
Sorry my bad -- then best to wait til the others make the switch as well.
