### ISSUE TITLE
use different legend.text.color for different legends

### ISSUE THREAD

**Issue by Kanoet** [mtennekes/tmap#300]
In the example below I want to the font colour of the legend 1 labels to be black, in the legend 2 I want them to be as defined in `mycolours`. Can I individually specify the label colors for different legends? And why is the first element of the the `legend.text.color` also used for the title? 

```

data(World, metro) 

mycolours <- c(red", "orange", "green"")

tm_shape(World) + tm_fill()+
  tm_shape(metro) + 
  tm_symbols(
    size = "pop2020",
    legend.size.show = FALSE) +
  tm_layout(
    legend.text.color = mycolours) +
  tm_add_legend(type="symbol", title = "legend 1", labels = c("A", "B", "C"), col = "black") +
  tm_add_legend(type="symbol", title = "legend 1",  labels = c("A", "B", "C"), col = "black") 

```
<img width="506" alt="Bildschirmfoto 2019-04-24 um 13 08 23" src="https://user-images.githubusercontent.com/47493422/56655081-1419bc00-6692-11e9-987d-d1fd55732ad0.png">

**Comment by mtennekes** [comment]
Ah, you managed to color the legend items with different colors. That should not be possible: `legend.text.color` should be a single color for all legend text. However, I just added `legend.title.color` which you can use to color the legend titles (somehow this was not implemented yet).

It is difficult to customize the legend text colors for each legend, since they are defined globally. Please let me know what your use-case is. Maybe there is a work-around.

**Comment by Kanoet** [comment]
Thanks for updating and clarification! 

> It is difficult to customize the legend text colors for each legend, since they are defined globally. Please let me know what your use-case is. Maybe there is a work-around.

The general idea is pretty much as described in the minimum example. I have two custom legend elements, one for population size and one for population trend. To reduce the amount of text in the legend and for easier understanding I want to replace the legend labels for the trend with unicode  arrows (up or down or stable for the trend) that have the self-defined colors. I am thinking to use empty labels within `tm_add_legend` and to place the labels manually with `tm_add_credits`. But maybe you can think of a more elegant way?

**Comment by mtennekes** [comment]
That's probably the way to go. Maybe easier to use `grid::grid.text` rather than `tm_add_credits`.

Another, more hacky approach is to color the text afterwards:

```{r}
library(grid)

data(World)
qtm(World, fill = "pop_est_dens")

grid.ls() # use this to find the GRID.text object
grid.edit("GRID.text.130", gp = gpar(col = rainbow(6)))
```

![Rplot](https://user-images.githubusercontent.com/2444081/56860049-5a249780-6992-11e9-8001-f3c9243c962e.png)
