### ISSUE TITLE
cartogram_ncont and cartogram_dorling shrink a map?

### ISSUE THREAD

**Issue by shadrackkibet** [mtennekes/tmap#301]
I am a newbie  in using tmap package to produce maps!. So this might be a simple problem to solve. I am using `cartogram_dorling` and `cartogram_ncont ` to Plot a map of Africa representing Life expectancy. I think the problem arises since this values  are 'small' and maybe the range (`26.962, 57.964)`  is small. So when representing this on the map, polygons are shrunk such that they are too small and not visible. For the case of `cartogram_dorling ` they appear as circles and the  shape of African is not maintained.

I import a shapefile and since I have life expectancy in a separate file I then append it as a column on the spatial polygon dataframe. I the proceed with mapping.  Below is my code. I am sorry this code might not reproducible i am just attaching for display together with my outputs.  Any  quick solution to this?. Thanks.

`world <- st_read("TM_WORLD_BORDERS-0.3/TM_WORLD_BORDERS-0.3.shp")
africa <- world[world$REGION == 2, ]`

`Africa_life_Expectancy <- read_excel("Africa_Population.xlsx",sheet = "Sheet6")`

`africa <- africa[order(africa$NAME),]`

`africa <- as_Spatial(africa)`

`Africa_life_Expectancy <- Africa_life_Expectancy[order(Africa_life_Expectancy$Region),]`

`africa$Life_Expectancy_1950_1955 <- Africa_life_Expectancy$1950-1955 `

`africa <- spTransform(africa, CRS("+init=epsg:3395"))`

`africa_cont <- cartogram_ncont(africa,  'Life_Expectancy_1950_1955 ', inplace = TRUE)`

`tm_shape(africa_cont) + 
    tm_polygons('Life_Expectancy_1950_1955 ', style = "jenks", area = 'AREA') +
    tm_layout(frame = FALSE, 
              legend.position = c("left","top"),
              legend.title.size = 2,
              legend.text.size = 0.6,
              legend.bg.color = "white",
              legend.outside=TRUE
    )`

Here is the output:

![image](https://user-images.githubusercontent.com/26301973/57176125-ebd94c80-6e4b-11e9-9065-9cb9a402ed98.png)

`africa_cont <- cartogram_dorling(africa, 'Life_Expectancy_1950_1955 ')`

  `tm_shape(africa_cont) + 
    tm_polygons('Life_Expectancy_1950_1955 ', style = "jenks") +
    tm_layout(frame = FALSE, 
              legend.position = c("left","top"),
              legend.title.size = 1,
              legend.text.size = 0.6,
              legend.bg.color = "white",
              legend.outside=TRUE
    )`

Ouput:
![image](https://user-images.githubusercontent.com/26301973/57176145-29d67080-6e4c-11e9-8ebf-0a8eebd7e771.png)

Using `cartogram_cont` seems to be better. But the Mean size error for iteration is very high.

`Mean size error for iteration 1: 47.7556381408357`
`Mean size error for iteration 2: 40.5957713606489`
`Mean size error for iteration 3: 34.4636034987029`

I am aware increasing the number of iterations reduces the error.

`africa_cont <- cartogram_cont(africa, 'Life_Expectancy_1950_1955 ', itermax = 3)`

` tm_shape(africa_cont) + 
    tm_polygons('Life_Expectancy_1950_1955 ', style = "jenks") +
    tm_layout(frame = TRUE, 
              legend.position = c("left","top"),
              legend.title.size = 1,
              legend.text.size = 0.6,
              legend.bg.color = "white",
              legend.outside=TRUE
    )+ 
    tm_scale_bar()`

![image](https://user-images.githubusercontent.com/26301973/57176228-550d8f80-6e4d-11e9-8517-be4798317f79.png)

**Comment by KhapTain** [comment]
I have also encountered a similar problem, where the range for my data values was really small.
I would be grateful if you could help with a solution.
Thank you

**Comment by Nowosad** [comment]
@shadrackkibet this seems to be an issue related to the **cartogram** package, not **tmap**. Please reopen this issue at https://github.com/sjewo/cartogram/issues.

**Comment by shadrackkibet** [comment]
Thanks.
