### ISSUE TITLE
Mapping Election Results.

### ISSUE THREAD

**Issue by shadrackkibet** [mtennekes/tmap#303]
This is a question!

I am new to using tmap package and I don't know exactly how this package works. I have a spatial polygon dataframe which I have appended votes for candidates (**Kuffour,   Mills , Mahama, Aggudey**) per region as shown below. Is it possible to map this using tmap package? If possible how?  Any link to such an example using tmap?

![image](https://user-images.githubusercontent.com/26301973/57623724-45e2bc00-7588-11e9-810e-f13bbd6ab330.png)

**Comment by mtennekes** [comment]
`tm_shape(x) + tm_bubbles(size = c("Kuffour", "Mills" , "Mahama", "Aggudey"))` will probably do the job.

See this excellent online book: https://geocompr.robinlovelace.net (chapter 8)
