### ISSUE TITLE
faceted map not shown in Shiny app using leafletOutput 

### ISSUE THREAD

**Issue by stragu** [mtennekes/tmap#305]
I don't think this has been reported here.

I try to show a faceted tmap in a Shiny app, but I just get an empty space.
See this reproducible example:

```r
# minimal example for bug report
library(shiny)
library(leaflet)
library(tmap)
# import data
data(World)

# Define UI for application that draws static and slippy maps
ui <- fluidPage(
    
    # Application title
    titlePanel("Example maps"),
    # Sidebar with a slider input for year of interest
    sidebarLayout(
        sidebarPanel(),
        # Show two maps
        mainPanel(
            h2("no facets"),
            leafletOutput("onePanel"),
            h2("facets"),
            leafletOutput("twoPanels")
        )
    )
)

# Define server logic
server <- function(input, output) {
    # single panel map
    output$onePanel <- renderLeaflet({
        tm <- 
            # render gdp per capita
            tm_shape(World) +
            tm_polygons("gdp_cap_est")
        # default mode is "view"
        tmap_leaflet(tm)
    })
    output$twoPanels <- renderLeaflet({
        tmFacet <- 
            # render gdp per capita + pop density, synced
            tm_shape(World) +
            tm_polygons(c("gdp_cap_est", "pop_est_dens")) +
            tm_facets(ncol = 2)
        # default mode is "view"
        tmap_leaflet(tmFacet)
    })
}

# Run the application 
shinyApp(ui = ui, server = server)
```
Running only the code that generates the faceted map works fine. Even running `tmap_leaflet(tmFacet)` works, so I guess the issue happens around the `leafletOutput()` call.

The same happens for both "plot" and "view" modes.

Here is what I get in the console:

> Warning in renderWidget(instance) :
>   Ignoring appended content; appendContent can't be used in a Shiny render call
> Warning: 'mapview::latticeView' is deprecated.
> Use 'leafsync::latticeView' instead.
> See help("Deprecated") and help("mapview-deprecated").

And this is my session info:

> R version 3.6.0 (2019-04-26)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 18.04.2 LTS
> 
> Matrix products: default
> BLAS:   /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
> LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so
> 
> locale:
>  [1] LC_CTYPE=en_AU.UTF-8       LC_NUMERIC=C              
>  [3] LC_TIME=en_AU.UTF-8        LC_COLLATE=en_AU.UTF-8    
>  [5] LC_MONETARY=en_AU.UTF-8    LC_MESSAGES=en_AU.UTF-8   
>  [7] LC_PAPER=en_AU.UTF-8       LC_NAME=C                 
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
> [11] LC_MEASUREMENT=en_AU.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] sf_0.7-4      tmap_2.2      leaflet_2.0.2 shiny_1.3.2  
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_1.0.1         compiler_3.6.0     later_0.8.0       
>  [4] RColorBrewer_1.1-2 base64enc_0.1-3    class_7.3-15      
>  [7] tools_3.6.0        digest_0.6.18      jsonlite_1.6      
> [10] satellite_1.0.1    lattice_0.20-38    viridisLite_0.3.0 
> [13] rlang_0.3.4        png_0.1-7          DBI_1.0.0         
> [16] crosstalk_1.0.0    yaml_2.2.0         rgdal_1.4-3       
> [19] e1071_1.7-1        raster_2.9-5       htmlwidgets_1.3   
> [22] rgeos_0.4-3        webshot_0.5.1      stats4_3.6.0      
> [25] classInt_0.3-3     grid_3.6.0         R6_2.4.0          
> [28] XML_3.98-1.19      sp_1.3-1           magrittr_1.5      
> [31] scales_1.0.0       promises_1.0.1     tmaptools_2.0-1   
> [34] codetools_0.2-16   htmltools_0.3.6    units_0.6-3       
> [37] dichromat_2.0-0    colorspace_1.4-1   mime_0.6          
> [40] xtable_1.8-3       httpuv_1.5.1       mapview_2.7.0     
> [43] KernSmooth_2.23-15 munsell_0.5.0      lwgeom_0.1-7

**Comment by mtennekes** [comment]
When I replace the shiny server code

```r
tmFacet <- 
            # render gdp per capita + pop density, synced
            tm_shape(World) +
            tm_polygons(c("gdp_cap_est", "pop_est_dens")) +
            tm_facets(ncol = 2)
        # default mode is "view"
tmap_leaflet(tmFacet)
```

by

```r
leafsync::latticeview(mapview::mapview(World), mapview::mapview(World))
```

it still doesn't work.

Probably multiple (synced) maps are not supported in shiny yet.
@tim-salabim can you confirm this? (also tagging @timelyportfolio)

**Comment by tim-salabim** [comment]
Confirmed, I have been meaning to see whether I can leverage `manipulateWidget` for `latticeView/sync` but haven't gotten to it yet...
https://github.com/r-spatial/mapview/issues/172
