### ISSUE TITLE
max.categories statement in tmap_options not being heeded

### ISSUE THREAD

**Issue by francisbarton** [mtennekes/tmap#309]
I have the following statement in a `tmap_options` block at the top of my RMarkdown document:

`tmap_options(
... various other options ...,
max.categories = 32)`

Then in the body of my document I am using `tmap` to create maps from my dataset, and I get a persistent warning when using `knitr` to create my output:

`Warning message:
Number of levels of the variable "ward" is 32, which is larger than max.categories (which is 30), so levels are combined. Set tmap_options(max.categories = 32) in the layer function to show all levels.`

All the other options I have set in my `tmap_options` statement seem to be being heeded, but for some reason `max.categories` is - according to this warning message - being ignored.

I have tmap 2.2 from CRAN.

**Comment by mtennekes** [comment]
Could you provide me a reproducible example?

These code chunks work in RMarkdown, also for tmap 2.2.

```{r}
library(tmap)
data(World)
tmap_options(max.categories = 32)
```

```{r}
World$pop_est2 <- cut(World$pop_est, breaks = 32)
tm_shape(World) + tm_polygons("pop_est2")
```

**Comment by Nowosad** [comment]
@francisbarton Please reopen the issue if the problem still occurs.
