### ISSUE TITLE
Is it (or will it be) possible to set tm_scale_bar options globally in tmap_options?

### ISSUE THREAD

**Issue by francisbarton** [mtennekes/tmap#311]
More of a feature request than a problem. I would like to be able to set options for `tm_scale_bar` in a `tmap_options` statement. 

For example, you can do
```
tm_scale_bar(width = 0.5)
```
but there's no documented option to set scale bar parameters such as `width` globally in `tmap_options`. However, by contrast, the `text.color`, `position` and `just` attributes of the scale bar _can_ be set in `tmap_options`.

It would be useful for me to be able to customise the scale bar in `tmap_options`, just to save doing it each time within `tm_scale_bar`. Even better would be some kind of `scale.bar.show = TRUE` option so that tmap will include a bar by default each time rather than having to add the `tm_scale_bar` line to each map.

Previously posted [here](https://stackoverflow.com/questions/56130691/is-it-or-will-it-be-possible-to-set-tm-scale-bar-options-globally-in-tmap-opti)

**Comment by mtennekes** [comment]
The global options are meant to specify parameters across layers/attributes, not for just one of them. The attributes that you mention are also used by other attributes, such as `tm_compass`.

If I would add the scale bar width as global parameter, then to be consistent, I would have to add all arguments from all layers and attributes. Hope you see my point.

A workaround is to define a custom scale bar function (notice that it is a copy-paste from the original function with different default value for width).

```{r}
tm_scale_bar2 <- function(breaks=NULL,
		 width=.7, 
		 size=.5,
		 text.color=NA,
		 color.dark="black", 
		 color.light="white",
		 lwd=1,
		 position=NA,
		 just=NA) {
	g <- list(tm_scale_bar=as.list(environment()))
	names(g$tm_scale_bar) <- paste("scale", names(g$tm_scale_bar), sep=".")
	class(g) <- "tmap"
	attr(g, "call") <- names(match.call(expand.dots = TRUE)[-1])
	g
}

data(NLD_muni)
qtm(NLD_muni) + tm_scale_bar2()
```
