### ISSUE TITLE
Missing polygones using tm_shape and tm_bubbles in "view" mode

### ISSUE THREAD

**Issue by odelaigue** [mtennekes/tmap#319]
When I use the `tm_bubbles` after the `tm_polygons` in the "view" mode, some polygones are missing in the map (it is not the case with the "plot mode")

My datasets and the complete code are in the zip file

```r
# OK
tmap_mode("plot")
tm_shape(bvs) +
  tm_polygons() +
  tm_shape(exu) +  
  tm_bubbles()
```
```r
# NOT OK
tmap_mode("view")
tm_shape(bvs) +
  tm_polygons() +
  tm_shape(exu) +  
  tm_bubbles()
```
[2019-06-12_tmap_bug.zip](https://github.com/mtennekes/tmap/files/3280177/2019-06-12_tmap_bug.zip)

**Comment by mtennekes** [comment]
Did you use the latest github version? It might be that this problem has already been solved. At least, I see no problems when running the code.

**Comment by odelaigue** [comment]
You are right, it has been solved with the latest version available on GitHub!
Thank you very much and sorry for the disruption.
