### ISSUE TITLE
Only manual legend

### ISSUE THREAD

**Issue by wkedziora** [mtennekes/tmap#320]
I am preparing a map in which I would like to use manual legend **only**. However, code like this is not working:

```
tm_shape(metro) + 
        tm_bubbles(size = "pop2030") +
        tm_style("cobalt") +
        tm_format("World") +
        tm_layout(legend.show = FALSE) +
        tm_add_legend("symbol", col = "red", size = c(1), labels = c("B"))
```

I have tried other option but couldn't find the right way. How can I delete the native legend and use only the added one?

**Comment by Nowosad** [comment]
Hi @wkedziora, you probably need to disable legends in some layers. This could be done, depending on a function with  `legend.show = FALSE`, ` legend.size.show = FALSE` or similar.

``` r
library(tmap)
data("metro")
tm_shape(metro) + 
  tm_bubbles(size = "pop2030", legend.size.show = FALSE) +
  tm_style("cobalt") +
  tm_format("World") +
  tm_add_legend("symbol", col = "red", size = c(1), labels = c("B"))
#> Linking to GEOS 3.7.1, GDAL 2.3.2, PROJ 5.2.0
```

![](https://i.imgur.com/UOLCV2x.png)

<sup>Created on 2019-06-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by wkedziora** [comment]
Thanks @Nowosad for such fast reply. I have checked and it works for me. 
Regards!
