### ISSUE TITLE
Treatment of polygons outside the breaks range

### ISSUE THREAD

**Issue by barryrowlingson** [mtennekes/tmap#322]
When colouring polygons with a value outside the limits of `breaks`, the polygon is shaded as the largest interval, which is labelled on the legend with the breaks. Example:

Use the World data with an `x` variable, set Australia (row 9) to 0.5:

```
> data(World)
> World$x = runif(nrow(World))
> World$x[9]=0.5
```

These two maps look fine:

```
> tm_shape(World) + tm_fill("x")
> tm_shape(World) + tm_fill("x", breaks=c(0,.4,.8,1.0))
```

But push Australia off the breaks:

```
> World$x[9]=10
> tm_shape(World) + tm_fill("x", breaks=c(0,.4,.8,1.0))
```

And Australia is shaded in the last colour of the legend which is still labelled "0.8 to 1.0", despite it having the value of 10.

I think the solution would be to colour anything outside the range of the breaks (as also modified by `interval.closure`) in a special colour, in a similar way to `colorNA` or `colorNULL`. As it is the software is producing silently wrongly-labelled (and hence possibly misleading) maps.

Using version 2.2 recently from CRAN.

**Comment by mtennekes** [comment]
I have opted for warnings, similar to the underlying function `classInt::classIntervals`.
Coloring it differently adds unnecessary complexity in my opinion. Coloring it with `colorNA` is also not the way to go, since these polygons have a value.
