### ISSUE TITLE
Passing a vector to alpha in tm_fill/tm_polygons/etc

### ISSUE THREAD

**Issue by malithianuka** [mtennekes/tmap#323]
First off, fabulous package!

I'm trying to create a map with a fill `alpha` that varies based on a vector. I've set `col` and `size` arguments equal to vectors via their variable names before, but get an error when I do the same for `alpha`. 

> Error: alpha argument in tm_polygons/tm_fill is not a numeric

Does tmap support a non-constant value for `alpha`?`

Thanks!

**Comment by mtennekes** [comment]
Not yet, see also #218 and the SO link there.

**Comment by malithianuka** [comment]
Thanks, @mtennekes!

**Comment by mtennekes** [comment]
Just checking whether it is possible to set de alpha/opacity per polygon:

```r
# plot mode
library(grid)
grid.newpage()
grid.points(x = unit(c(.5, .5), "npc"), y = unit(c(.25, .75), "npc"), pch = 21, gp=gpar(fill = c("red", "blue"), alpha = c(.25, .75)))

# view mode
library(leaflet)
data(World)
leaflet() %>% 
	addPolygons(data = World %>% st_transform(crs = "+proj=longlat +datum=WGS84"), fillOpacity =seq(0,1,length.out=177))
```

So, the answer is yes:-)

Currently, I am working on a next stable CRAN release (2.3). After that, we can work on this feature, and (much more difficult) the fill patterns (#49)

**Comment by malithianuka** [comment]
Good to know there are cases where manually specifying values is possible! 

In the `leaflet `example, is the opacity just varied randomly for the 177 countries? I wasn't able to get it to behave in a predictable manner whn playing around with the example. 

Thanks for your work on this :)

**Comment by mtennekes** [comment]
Thx! Yes, that's this part of the code   `fillOpacity =seq(0,1,length.out=177)`
