### ISSUE TITLE
tm_facet: split the panel label in two lines

### ISSUE THREAD

**Issue by bertagrau** [mtennekes/tmap#325]
I am using tmap to built a facet map, with `tm_facet` . The names of the panels of my facet map are too long, so they appear cut when printed as a map. How could I split the names? It seems that `labeller = label_wrap_gen(width=10)` doesn't work for tmap. 

See my code: 
```
map_m<- tm_shape(m) +
  tm_polygons(col = "count", palette = "-Blues", title="") +
  tm_layout(frame = F, legend.title.size = .9, panel.label.size = 1, panel.label.bg.color = "white", between.margin = 1 , inner.margins = c(0, 0, 0, 0)) +
  tm_fill("count") +
  tm_facets(by = "ntd", inside.original.bbox = F, labeller = label_wrap_gen(width=10))
print(map_m)

```

**Comment by mtennekes** [comment]
Hi, thanks for your question. You can split the labels by putting \n in the string.
Could you share the object `m` or otherwise make this example reproducible?

**Comment by Nowosad** [comment]
@bertagrau please reopen the issue if you still have any questions.
