### ISSUE TITLE
shape argument not working in tmap_mode("view")

### ISSUE THREAD

**Issue by GuiAlDuS** [mtennekes/tmap#327]
Hi  Martijn,

I just noticed that the _shape_ argument of the _tm_symbols_ function doesn´t work in the _tmap_mode("view")_.  

Thanks!

**Comment by mtennekes** [comment]
True, as far as I know leaflet doesn't support it (yet). You should have gotten this warning message: "Symbol shapes other than circles or icons are not supported in view mode."

I noticed that it wasn't clearly described in the docs, will do that.
