### ISSUE TITLE
Dashed borders rendered as solid in view mode

### ISSUE THREAD

**Issue by adam52** [mtennekes/tmap#328]
For some reason, dashed borders render as solid lines when tmap is in "view" mode. Here is a minimal example:

    library(tmap)
    data("World")

    tmap_mode("view")
    tm_shape(World) +
        tm_fill("#cd7f81") +
        tm_borders(lty="dashed", col="black")

Any ideas? Thanks!

**Comment by mtennekes** [comment]
Should be working now. Reopen if necessary.

**Comment by adam52** [comment]
Works great. Thanks mtennekes!
