### ISSUE TITLE
Foreground / text color is fixed

### ISSUE THREAD

**Issue by sjewo** [mtennekes/tmap#33]
`tmap` produces nice looking maps! Alas the foreground and text color in maps are set to "black" by default. It would be a great enhancement, if the forground color could be set as an option in tm_layout.

**Comment by mtennekes** [comment]
Do you mean `title.color`, and `legend.title.color`

**Comment by sjewo** [comment]
Yes, something like this! I was searching for a parameter like par(fg="black") to set the color for the titles, the legend labels and so on. 
I'd like to see this parameter particulary to style the map to fit in beamer presentations with non black text colors.

**Comment by mtennekes** [comment]
There is a `attr.color` and `aes.color` now in `tm_layout`! I have not tested all examples yet, but it should be working. Please let me know if this is as you expected it.

**Comment by sjewo** [comment]
Hi Martijn! I've tested the new options with different maps (including facets and multiple shapes) and it works great so far. 

Thank you for the quick response and your efforts!
