### ISSUE TITLE
Installation problem with Debian 10 (stable, Buster)

### ISSUE THREAD

**Issue by paulauvirage** [mtennekes/tmap#332]
Hello,

having upgraded to Debian 10, tmap cannot upgrade, or install when I try re-installing, with this error message (installing/updating through R Studio)

Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/paul/R/x86_64-pc-linux-gnu-library/3.6/sf/libs/sf.so':
  libproj.so.12: cannot open shared object file: No such file or directory

Debian 10 uses libproj13. I have this and libproj-dev installed.

**Comment by Nowosad** [comment]
You problem seems to be related to the **sf** package. Have you tried to reinstall it (and restart R session afterwards)?

```r
install.packages("sf")
```

**Comment by paulauvirage** [comment]
Thanks. I did that and also uninstalled and reinstalled lwgeom and rgdal in response to extra similar error messages related to libproj.so.12 and tmap now installs. However, when I load it I get the warning:

Warning message:
In fun(libname, pkgname) :
  rgeos: versions of GEOS runtime 3.7.1-CAPI-1.11.1
and GEOS at installation 3.5.1-CAPI-1.9.1differ 

I have not yet tested whether tmap works OK despite the warning.

**Comment by paulauvirage** [comment]
I've run through a tmap vignette and the warning message does not seem to affect anything, so I'll close this. many thanks for your help.
