### ISSUE TITLE
Adding raster to plot changes plot area

### ISSUE THREAD

**Issue by sschloss1** [mtennekes/tmap#335]
I'm trying to plot the same map with and without a raster layer shown, and the plot areas seem to change depending on whether or not I include the raster (via `tm_raster`).  With a raster, the map zooms in slightly.  Specifying a bbox and/or setting "is.master" in tm_shape does not seem to change this outcome.

Reproducible example modified from the `tm_raster` documentation:

```
require(raster)
require(tmap)
data(World, land, metro)
bbox=subset(World,name=="United States")
pal8 <- c("#33A02C", "#B2DF8A", "#FDBF6F", "#1F78B4", "#999999", "#E31A1C", "#E6E6E6", "#A6CEE3")
tm_shape(land, ylim = c(-88,88)) +
    tm_raster("cover_cls", palette = pal8, title = "Global Land Cover") +
tm_shape(metro) + tm_dots(col = "#E31A1C") +
tm_shape(World,is.master=T,bbox=bbox) +
    tm_borders(col = "black") +
tm_layout(scale = .8, 
	legend.position = c("left","bottom"),
    legend.bg.color = "white", legend.bg.alpha = .2, 
    legend.frame = "gray50")
tmap_save(tmap_last(),"xx.png",dpi=600,width=7200,asp=1.5,outer.margins=0)
```
This produces this map: 
![image](https://user-images.githubusercontent.com/39743221/62502380-f5a08200-b7a3-11e9-9e2b-7cf7c894f814.png)

Now, the same map without the raster.

```
tm_shape(metro) + tm_dots(col = "#E31A1C") +
tm_shape(World,is.master=T,bbox=bbox) +
    tm_borders(col = "black") +
tm_layout(scale = .8, 
	legend.position = c("left","bottom"),
    legend.bg.color = "white", legend.bg.alpha = .2, 
    legend.frame = "gray50")
tmap_save(tmap_last(),"xx.png",dpi=600,width=7200,asp=1.5,outer.margins=0)
```

The area plotted is zoomed out slightly: 
![image](https://user-images.githubusercontent.com/39743221/62502403-12d55080-b7a4-11e9-8a12-bea71c5cba4c.png)

I'm making maps for presentations, and I need the map areas to be identical regardless of what layers are plotted.  Any help would be appreciated. Thanks.

**Comment by Nowosad** [comment]
There are different default settings for inner.margins for vector data and raster data. If you want to have identical map areas you need to set the `inner.margins` in `tm_layout()`:

```r
tm_shape(metro) + tm_dots(col = "#E31A1C") +
        tm_shape(World, is.master = T, bbox = bbox) +
        tm_borders(col = "black") +
        tm_layout(
                scale = .8,
                legend.position = c("left", "bottom"),
                legend.bg.color = "white",
                legend.bg.alpha = .2,
                legend.frame = "gray50",
                inner.margins = 0
        )
```

**Comment by sschloss1** [comment]
Thanks, and now I see that's mentioned in the help for `tm_layout`.  

But the help also says that the smaller `inner.margins` only apply when the raster layer is the master.  When I run this code with the raster layer explicitly not the master, I still get the same map as above, with `inner.margins`=0 (the first one above).  Is that a bug, or am I missing something?
```
tm_shape(land, ylim = c(-88,88),is.master=F) +
    tm_raster("cover_cls", palette = pal8, title = "Global Land Cover") +
tm_shape(metro) + tm_dots(col = "#E31A1C") +
tm_shape(World,is.master=T,bbox=bbox) +
    tm_borders(col = "black") +
tm_layout(scale = .8, 
	legend.position = c("left","bottom"),
    legend.bg.color = "white", legend.bg.alpha = .2, 
    legend.frame = "gray50")

```

**Comment by Nowosad** [comment]
It could be a bug. @mtennekes ?

**Comment by mtennekes** [comment]
Yes, that's a bug indeed.

I'm also thinking about making the defaults a little simpler: setting the first shape to the master by default (regardless whether it is a raster).

What do you think?

**Comment by Nowosad** [comment]
Good idea.

**Comment by mtennekes** [comment]
It should be fixed now. Please check @sschloss1  and @Nowosad
