### ISSUE TITLE
Ways to specify breaks in tm_dots legend.hist

### ISSUE THREAD

**Issue by wcrice** [mtennekes/tmap#339]
Hi!

I really like the way tm_dots can make a small histogram in the legend and I would like to use it. Is there a way to specify where the breaks happen in that legend? I've tried a few things but it doesn't seem to observe the breaks specified in the rest of tm_dots.

Thank you for this amazing tool!

**Comment by mtennekes** [comment]
Hi, I am still looking for a better approach to add small charts like histograms inside the maps. The current implementation is a one-trick pony and therefore not easy to maintain / extend. See #251
