### ISSUE TITLE
Hide controls in 'view' mode

### ISSUE THREAD

**Issue by grobins** [mtennekes/tmap#340]
I'm trying to create a map of linestrings for each of 20 vehicles, i.e. 20 maps, and export to PDF

I need to have a basemap as part of the PDF and the only way to do that is with the 'view' mode and knitting a RMarkdown doc to a PDF.

However the interactive controls, zoom and layer selection, are not required, and I don't see how to remove them.  Is there a way to do this with tmap?

**Comment by mtennekes** [comment]
You can do this via `leaflet`, e.g. 

```r
lf <- tmap_leaflet(qtm(World))
lf %>% leaflet::removeLayersControl()
```

Not sure how to remove the zoom icons. Probably also somewhere in the leaflet package?
