### ISSUE TITLE
tmap_arrange widths parameter not working

### ISSUE THREAD

**Issue by nreguera** [mtennekes/tmap#341]
Hi,

When I try to use the **widths** argument in the tmap_arrange function, 

`tmap_arrange(map1, map2, ncol = 2, nrow = 1, widths = c(.25, .75))`

I get this error:

`Error in tmap_arrange(map1, map2, ncol = 2, nrow = 1, widths = c(0.25,  : 
  Not all arguments are tmap objects.
Calls: <Anonymous> ... withCallingHandlers -> withVisible -> eval -> eval -> tmap_arrange`

If I remove the **widths** argument it works fine. 

I am just trying to adjust the size of both maps. The tmap version is 2.2. 

Thanks.

**Comment by mtennekes** [comment]
This one works, at least with the github version:

```r
data(World)
data(metro)

map1 <- qtm(World)
map2 <- qtm(metro)

tmap_arrange(map1, map2, ncol = 2, nrow = 1, widths = c(.25, .75))
```

**Comment by nreguera** [comment]
I just updated to latest version (2.3) and now seems working. Thanks anyway.
