### ISSUE TITLE
Error in if (!is.na(x)[1]) { : missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by nreguera** [mtennekes/tmap#342]
Hi,

I am trying to plot an animation using **tmap_animation** function, and I get this error:

![screenshot](https://user-images.githubusercontent.com/8281704/63646330-e7a4a800-c736-11e9-8d47-03c327c2c790.png)

I have shown the traceback in the attached screenshot. Any idea on what is happening?

Thanks.

**Comment by mtennekes** [comment]
Hi, could you provide a reproducible example? Or you can send me the objects `country.map` and `layer`, then I'll be able to reproduce your code.

**Comment by nreguera** [comment]
Hi, Just after updating the version the message didn´t show up anymore. Anyway thanks.
