### ISSUE TITLE
mapply error with overlay

### ISSUE THREAD

**Issue by francisbarton** [mtennekes/tmap#343]
I am getting the error message:

```
Error in mapply(function(a, tmsi) { : 
  zero-length inputs cannot be mixed with those of non-zero length
```
when I try to generate a tmap with the overlays setting.

#261 (closed) has a similar error but I can't find much other help on this error message on the web elsewhere.
(I was also getting the same error as #329 so I switched to the github version of `tmap` and restarted: so my current `tmap` version is 2.3-1. That error has not yet re-appeared. But the upgrade has not fixed this `mapply` error as I'd hoped!)

Here's my reprex:
```
library(tmap)
library(spData)
library(magrittr)
ealing <- spData::lnd %>% subset(NAME == "Ealing")
tmap_options_reset()
tmap_options(
  basemaps = leaflet::providers$Hydda.Base)
tm_shape(ealing) +
  tm_polygons() # works

tmap_options_reset() # just to be on the safe side
tmap_options(
  basemaps = leaflet::providers$Hydda.Base,
  overlays = leaflet::providers$Hydda.RoadsAndLabels)
tm_shape(ealing) +
  tm_polygons() # doesn't work: gives mapply error

tmap_options_reset()
tmap_options(
  basemaps = leaflet::providers$CartoDB.PositronNoLabels) # test different tile provider
tm_shape(ealing) +
  tm_polygons() # works

tmap_options_reset()
tmap_options(
  basemaps = leaflet::providers$CartoDB.PositronNoLabels,
  overlays = leaflet::providers$CartoDB.PositronOnlyLabels)
tm_shape(ealing) +
  tm_polygons() # doesn't work: gives mapply error

tmap_options_reset()
tmap_options(
  basemaps = leaflet::providers$CartoDB.PositronOnlyLabels) # test labels tiles as basemap
tm_shape(ealing) +
  tm_polygons() # works
```

The above is an artificial bit of mapping just to be able to provide a reprex for you. I'm pretty sure I was using basemaps and overlays in my actual script a few weeks ago without this error. But when I returned to it last week, suddenly this error appeared.

**Comment by francisbarton** [comment]
But:
```
tmap_options_reset()
tm_basemap("Hydda.Base") +
  tm_shape(ealing) +
    tm_polygons() +
    tm_tiles("Hydda.RoadsAndLabels", alpha = 0.3) # works
```

**Comment by mtennekes** [comment]
Thx @francisbarton Should be fixed. Please check and reopen if necessary.
