### ISSUE TITLE
scale bar goes off map, last segment looses the border.

### ISSUE THREAD

**Issue by micha-silver** [mtennekes/tmap#346]
The scalebar extends off the map when using `breaks=...`
```
tm_shape(World) + tm_polygons() +
    tm_scale_bar(breaks = c(2000, 4000, 8000), width = 0.5)
```
Specifiying `position=...` overcomes this,

But then the last section of the scalebar does not have a border:
```
tm_shape(World) + tm_polygons() +
   tm_scale_bar(breaks = c(2000, 4000, 8000), position = c(0.6, 0.1))
```

**Comment by mtennekes** [comment]
I've looked at it a bit, and added some warnings, e.g. breaks cannot  be used together with width.

I found out that I implicitly assumed that breaks are linear and starting from 0, e.g. `c(0, 4000, 8000, 12000)`. If that holds, the results are fine. Otherwise, not.

**Comment by mtennekes** [comment]
Should be fixed now. Please try @micha-silver and reopen this issue if necessary.
