### ISSUE TITLE
midpoint not always working

### ISSUE THREAD

**Issue by mtennekes** [mtennekes/tmap#347]
Check HPI, div palette, midpoint = 25

**Comment by Nowosad** [comment]
``` r
library(tmap)
data(World)
tm_shape(World) +
  tm_polygons(
    "HPI",
    palette = "RdBu",
    midpoint = 25
  ) 
```

![](https://i.imgur.com/mEeUPO6.png)

<sup>Created on 2019-09-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mtennekes** [comment]
Hmmm, not sure why it didn't work during the workshop. Maybe a typo;-)
