### ISSUE TITLE
tm_raster() unable to find variables when a projection is specified

### ISSUE THREAD

**Issue by Farewe** [mtennekes/tmap#348]
Hello, 

I have encountered a bug while trying to map rasters in the Southern Ocean. Basically, what happens is that tm_raster() works properly if no projection is specified, but fails to find variables when a projection is specified. I tried to make a reproducible example to illustrate my issue:

``` r
# Preparing the example
library(tmap)
library(raster)
a <- raster(extent(-180, 180, -90, -30),
            res = 1)
a[] <- rep(1:4, 5400)
a <- ratify(a)
levels(a)[[1]]$test <-  as.factor(c(2, 4, 3, 1))
levels(a)[[1]]$color <- c("#7FC97F", "#BEAED4", "#FDC086", "#FFFF99") 
``` 

``` r
# Basic plot
tm_shape(a) +
  tm_raster("test",
            palette = levels(a)[[1]]$color)
```
![image](https://user-images.githubusercontent.com/7148016/64262253-1a685080-cf2e-11e9-942f-23c51a8c53de.png)

The following code does not work:
``` r
# Plot with projection
tm_shape(a, projection = "+proj=stere +lat_0=-90 +lat_ts=-71 +lon_0=0 +k=1 +x_0=0 +y_0=0 
            +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0") +
  tm_raster("test",
            palette = levels(a)[[1]]$color)
```
Here is the error I receive:
**Error: Invalid color specification. The available raster variables are: "test", "color".**

If I do not specify the variable name, it works:
``` r
tm_shape(a, projection = "+proj=stere +lat_0=-90 +lat_ts=-71 +lon_0=0 +k=1 +x_0=0 +y_0=0 
            +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0") +
  tm_raster(palette = levels(a)[[1]]$color)
```
With a message:
*Only the first variable is shown. The available variables are: "test", "color".*

![image](https://user-images.githubusercontent.com/7148016/64262476-6e733500-cf2e-11e9-8984-05b6f7735264.png)

**Comment by mtennekes** [comment]
Thx! Should be fixed now. Please reopen if necessary.
