### ISSUE TITLE
Facets happen too easily

### ISSUE THREAD

**Issue by Robinlovelace** [mtennekes/tmap#35]
Reproducible example:

Run the code on this page: https://github.com/Robinlovelace/stplanr

The this is the result of the following code:

```
tm_shape(osm_tiles) +
  tm_raster() +
  tm_shape(rnet) +
  tm_lines(lwd = rnet$All / rnet$All) 
```

![rplot](https://cloud.githubusercontent.com/assets/1825120/10602411/10a1b8cc-7710-11e5-9660-2b4689da932d.png)

Not sure what's going on here - guess I've mis-understood the tmap syntax.

What I want is a plot like this but with the osm background:

![rplot](https://cloud.githubusercontent.com/assets/1825120/10602835/a2b1994c-7712-11e5-9544-421d0fa8a101.png)

**Comment by mtennekes** [comment]
Thanks for reporting this! Actually, it's not a bug. Aesthetics, like lwd, may take a vector, but if so, each value will correspond to a facet. Like `qtm(World, fill=c("red", "blue"))` does. The key is to assign the values to a shape variable.

This will produce the kind of map you want:

```{r}
osm_tiles <- read_osm(bb(rnet, ext = 1.05))
rnet$lwd <- rnet$All / mean(rnet$All)
tm_shape(osm_tiles) +
	tm_raster(saturation = .25) +
	tm_shape(rnet) +
	tm_lines(lwd = "lwd", scale = 5, legend.lwd.show = FALSE)  +
tm_shape(cents) +
	tm_bubbles()
```

![rplot](https://cloud.githubusercontent.com/assets/2444081/10629905/1b2eb02e-77d3-11e5-8269-a798d6920dcf.png)

**Comment by Robinlovelace** [comment]
Many thanks for this clear, detailed and reproducible response. Your code has been used directly in the README and it's looking great: https://github.com/Robinlovelace/stplanr

Making the facetting depend on the data source is an elegant solution that makes sense - I'll try to add some documentation to tmap on this if I get a chance.
