### ISSUE TITLE
How to split an interactive map title into two lines in tmap?

### ISSUE THREAD

**Issue by tkt983** [mtennekes/tmap#352]
I was just wondering how to split a title for an interactive map? The "\n" can be used to split a long text into two lines for static maps; hower, this doesn't work for an interactive map.
"tm_credits" also doesn't work for an interactive map. Is there a way to include map credits (data source) on an interactive map?

**Comment by tkt983** [comment]
Many thanks. It works.
Any comment on map credits?

**Comment by tim-salabim** [comment]
Nope, sorry
