### ISSUE TITLE
Extremeley slow plotting with large dataset.

### ISSUE THREAD

**Issue by Foxhound013** [mtennekes/tmap#353]
The tmap package thus far has been a great tool and I'm enjoying learning its ins and outs, thank you for all your work so far!

I wanted to check and see if others have run into issues when trying to plot large polygon datasets in tmap. I have a cencus blocks dataset that I am attempting to plot with roughly 260,000 points. I've copied a snippet of code that I've tried below.

`
tm_shape(data) + tm_polygons('blockArea')
`
or
`
qtm(data)
`

The above snippets takes 20+ minutes each and never finish, I killed it around the 20 minute mark. I had wondered if it was just a graphical issue/limitation in R Studio, so I plotted directly to pdf like below.

`
pdf('test.pdf')
tm_shape(data) + tm_polygons('blockArea')
dev.off()
`

The same issue occurred here as well. I then tried ggplot instead and had the same issue.

`
pdf('test.pdf')
ggplot(data_proj) +
  geom_sf(aes(fill=as.numeric(blockArea)))
dev.off()
`

I've got a fairly decent machine (6 core i7 with 8gb of ram). Is this just not possible with this many data points to quickly produce a figure? Any suggestions or thoughts would be greatly appreciated.

**Comment by tim-salabim** [comment]
Do you really need to plot that many points? Can you see them all in a static plot? Maybe some sort of aggregation/rasterization is a better approach for that many points? 

Also, have you tried base plot?

**Comment by Foxhound013** [comment]
Hey Tim,

That's a fair point. This is for a class assignment where the goal was to perform some clustering of the census blocks. I had just attempted to get a quick look at the dataset as the end goal is to create a chloropleth from the clustered sets. 

I did try just a base plot with about half of the points and it did eventually work but had the issue you mention of not being visible in a static plot.

I'll proceed with clustering and see if I can visualize it post clustering. Thank you for your comment!

**Comment by tim-salabim** [comment]
If you want to have a look at such large data, I'd recommend [leafgl](https://github.com/r-spatial/leafgl) which gives you interactivity to examine points at different zoom levels. Or [mapdeck](https://github.com/SymbolixAU/mapdeck) which is same same but different

**Comment by Foxhound013** [comment]
> If you want to have a look at such large data, I'd recommend [leafgl](https://github.com/r-spatial/leafgl) which gives you interactivity to examine points at different zoom levels. Or [mapdeck](https://github.com/SymbolixAU/mapdeck) which is same same but different

Thanks for the suggestion! I'll take a look at those!
