### ISSUE TITLE
pictures on README.md for london crimes map on github aren't rendering!

### ISSUE THREAD

**Issue by dan-reznik** [mtennekes/tmap#354]
do check it out -- pictures here aren't rendering:

https://github.com/mtennekes/tmap/tree/master/demo/LondonCrimes

**Comment by mtennekes** [comment]
Thx! Since I don't maintain these demo's anymore, I removed them. The source code is still available as a vignette (https://github.com/mtennekes/tmap/blob/master/vignettes/tmap-JSS-code.Rmd), and the pictures are in the JSS paper (link is on the README homepage).
