### ISSUE TITLE
tm_compass ( north= ..) does not seem to work

### ISSUE THREAD

**Issue by FrogBoss74** [mtennekes/tmap#357]
Trying to get north orientation in customised direction when plotting data in local coordinate system (plan view) to show difference between plan north and true north. Is this possible? Below code does not seem to work. Only north=0 works.

```r
library(tmap)
tmap_mode("plot") 
data(NLD_muni) 
qtm(NLD_muni, theme = "NLD") + tm_compass(north=30) 
```

**Comment by mtennekes** [comment]
Working now
