### ISSUE TITLE
Frame does not contain legend text

### ISSUE THREAD

**Issue by gregmacfarlane** [mtennekes/tmap#358]
My legend text is not contained within the frame created by `legend.frame`

```r
tm_shape(background) + tm_rgb() +
  tm_shape(acs_logsums) + 
  tm_polygons("Accessibility", alpha = 0.5, palette = "-viridis", border.col = NULL) +
  tm_legend(legend.position = c(0.85, 0.05), legend.frame = TRUE, legend.width = 7)
```
![image](https://user-images.githubusercontent.com/2234830/66872632-af199180-ef63-11e9-9c7e-8edeae275707.png)

I've been fiddling around with the `legend.width` argument but it only moves the text, not the frame.

**Comment by mtennekes** [comment]
Hi Greg, thanks for the issue. Could you either share the spatial objects (`background` and `acs_logsums`) or create a reproducible example with data included in tmap?

**Comment by gregmacfarlane** [comment]
Here's a complete MWE:

```r
library(tigris)
library(tmap)
library(ceramic)
library(tidyverse)

# get tracts
tracts <- tracts("Utah", "Utah", class = "sf")

logsums <- tracts %>%
  transmute(
    access = sample(c(-3:3), nrow(tracts), replace = TRUE)
  )

background <- cc_location(tracts, type = "mapbox.light")

tm_shape(background) + tm_rgb() +
  tm_shape(logsums) + 
  tm_polygons("access", alpha = 0.5, palette = "-viridis", border.col = NULL) +
  tm_legend(legend.position = c(0.85, 0.05), legend.frame = TRUE, legend.width = 7)
```

**Comment by mtennekes** [comment]
The `legend.width` cannot be larger as 1, which means the whole map width. A positive number will not have effect in your example, unless you want it smaller.

Probably this is what you are after:

```r
tm_shape(logsums) + 
  tm_polygons("access", alpha = 0.5, palette = "-viridis", border.col = NULL) +
  tm_legend(legend.position = c(0.85, 0.05), legend.frame = TRUE, legend.width = -0.13)
```
![Rplot02](https://user-images.githubusercontent.com/2444081/71882659-2d399e80-3135-11ea-961d-d4fd73734c6c.png)

I updated the docs, please check if it is clear now. Reopen if necessary.
