### ISSUE TITLE
bb bug?

### ISSUE THREAD

**Issue by joelgombin** [mtennekes/tmap#36]
I've encountered a weird error with `bb`, which I can't fully understand, even by looking (quickly) at the source code.

This code:

```r
bb(x = matrix(c(881247, 905582, 6232997, 6257704), nrow = 2, ncol = 2, dimnames = list(c("x", "y"), c("min", "max"))),
   ext = 1.2,
   projection = "+proj=lcc +lat_1=44 +lat_2=49 +lat_0=46.5 +lon_0=3 +x_0=700000 +y_0=6600000 +ellps=GRS80 +units=m +no_defs",
   current.projection = "+proj=lcc +lat_1=44 +lat_2=49 +lat_0=46.5 +lon_0=3 +x_0=700000 +y_0=6600000 +ellps=GRS80 +units=m +no_defs")
```

leads to an error: `Error in .spTransform_Polygon(input[[i]], to_args = to_args, from_args = from_args,  : 
  failure in Polygons 1 Polygon 1 points 1`

whereas

```r
bb(x = matrix(c(881247, 905582, 6232997, 6257704), nrow = 2, ncol = 2, dimnames = list(c("x", "y"), c("min", "max"))),
   ext = 1.2)
```
works, as well as:

```r
bb(x = matrix(c(881247, 905582, 6232997, 6257704), nrow = 2, ncol = 2, dimnames = list(c("x", "y"), c("min", "max"))),
   ext = 1.2,
#   projection = "+proj=lcc +lat_1=44 +lat_2=49 +lat_0=46.5 +lon_0=3 +x_0=700000 +y_0=6600000 +ellps=GRS80 +units=m +no_defs",
   current.projection = "+proj=lcc +lat_1=44 +lat_2=49 +lat_0=46.5 +lon_0=3 +x_0=700000 +y_0=6600000 +ellps=GRS80 +units=m +no_defs")
```

or
 
```r
bb(x = matrix(c(5, 45, 6, 46), nrow = 2, ncol = 2, dimnames = list(c("x", "y"), c("min", "max"))),
   ext = 1.2,
   projection = "longlat",
   current.projection = "longlat")
```

and this lags:

```r
bb(x = matrix(c(881247, 905582, 6232997, 6257704), nrow = 2, ncol = 2, dimnames = list(c("x", "y"), c("min", "max"))),
   ext = 1.2,
   projection = "+proj=lcc +lat_1=44 +lat_2=49 +lat_0=46.5 +lon_0=3 +x_0=700000 +y_0=6600000 +ellps=GRS80 +units=m +no_defs",
   # current.projection = "+proj=lcc +lat_1=44 +lat_2=49 +lat_0=46.5 +lon_0=3 +x_0=700000 +y_0=6600000 +ellps=GRS80 +units=m +no_defs"
   )
```

What am I missing here?

**Comment by joelgombin** [comment]
Also this doesn't work:

```r
bb(x = matrix(c(881247, 905582, 6232997, 6257704), nrow = 2, ncol = 2, dimnames = list(c("x", "y"), c("min", "max"))),
   ext = 1.2,
   projection = "merc",
   current.projection = "merc")
```

So basically it seems that whenever `projection` and `current.projection` have the same value and that value is not `longlat`, it fails...

**Comment by joelgombin** [comment]
OK so I think I tracked down the bug to the `end_of_the_world` function. When it's called in `bb`, it should be fed with an `bbx` argument, I believe. Otherwise it uses its default `bbx` argument, which is wrong for other projections than a `longlat` proj.

**Comment by joelgombin** [comment]
(Indeed, commit 687b36fdb2131a6ad12e062390a59a8335a624aa works just fine)

**Comment by mtennekes** [comment]
Thanks for this clear investigation! The `bbx` argument of `end_of_the_world` refers to the end of the world using the datum `earth.datum`. By default, this is wgs84 (`"longlat"`), and `c(-180, 180, -90, 90)`. What happens is that a polygon is created which represents the world. Within `bb` this is used to crop the bounding box by. (To prevent unreal bounding boxes.) This can only be done for specific projections, typically aimed at world maps (e.g. `"eck4"`, `"robin"`, and `"wintri"`).


```{r}
end_of_the_world(proj="robin")
```

However, for the mercator projection, this leads to an unfeasible solution:
```{r}
end_of_the_world(proj="merc")
```
unless the end of the world is set a little shorter:
```{r}
end_of_the_world(proj="merc", bbx=c(-179.999, 179.999, -89.999, 89.999))
```

I don't know the most elegant solution yet. I'll check whether we can leave the bbx like above, of maybe first trycatch the true bounds polygon, and then this one.

I also found an inconsistency in `bb`, which I'll solve:

```
> bb(bb(land))
   min max
x -180 180
y  -90  90
> bb(extent(bb(land)))
   min max
x -180 180
y  -90  90
> bb(as.vector(extent(bb(land))))
   min max
x -180 -90
y  180  90
```

**Comment by mtennekes** [comment]
I think it's fixed, but I'l have to run through the examples again.

```{r}
bb(x = matrix(c(881247, 905582, 6232997, 6257704), nrow = 2, ncol = 2, dimnames = list(c("x", "y"), c("min", "max"))),
   ext = 1.2,
   projection = "+proj=lcc +lat_1=44 +lat_2=49 +lat_0=46.5 +lon_0=3 +x_0=700000 +y_0=6600000 +ellps=GRS80 +units=m +no_defs",
   # current.projection = "+proj=lcc +lat_1=44 +lat_2=49 +lat_0=46.5 +lon_0=3 +x_0=700000 +y_0=6600000 +ellps=GRS80 +units=m +no_defs"
   )
```
now gives an error, because the current projection is not set, so it is assumed to be long lat.

Please check if this solution is ok.
