### ISSUE TITLE
Continuous legend renders poorly on pdf 

### ISSUE THREAD

**Issue by johnbaums** [mtennekes/tmap#361]
When a map includes a continuous raster with alpha < 1, saving to pdf results in a poorly rendered legend. Writing to png is fine. 

Is there any workaround? Is it possible to construct a continuous legend using `tm_add_legend`? If so, I would be satisfied with the legend having alpha=1.

```R
library(tmap)
data(land)
m <- tm_shape(land) +
  tm_raster('elevation', style='cont', alpha=0.5) +
  tm_layout(legend.outside=TRUE, 
            legend.outside.position='right')
tmap_save(m, 'test.png')
tmap_save(m, 'test.pdf')
```

[test.pdf](https://github.com/mtennekes/tmap/files/3781345/test.pdf)

png:
![test](https://user-images.githubusercontent.com/818438/67731014-e0598d80-fa4a-11e9-82dc-064a5ae28c7d.png)

pdf screenshot:
![image](https://user-images.githubusercontent.com/818438/67731106-39292600-fa4b-11e9-9e1e-36290030c379.png)

**Comment by johnbaums** [comment]
I'm on macOS. You're right, overlapping rectangles would explain this. 

For the above example, can I plot the legend with full opacity while keeping the raster layer semi-transparent?

**Comment by Nowosad** [comment]
I think the solution here could be to use a different graphic device (e.g., cairo_pdf) - https://github.com/mtennekes/tmap/issues/585. @johnbaums feel free to reopen this issue if the problem still occurs.
