### ISSUE TITLE
Control white space between legend title and legend when adding line breaks? 

### ISSUE THREAD

**Issue by jeffcsauer** [mtennekes/tmap#362]
Hi all, 

Thought I was going mad, but then was able to reproduce. Seems that the more line breaks I add in the `tm_polygons("varname", title = "")` argument increases the white space between legend title and legend itself. Is there any way to control this white space?

Example: 

```
library(tmap)
data("World")

tm_shape(World) +
  tm_polygons("HPI")

tm_shape(World) +
  tm_polygons("HPI", title = "This is a title with no line breaks line")

tm_shape(World) +
  tm_polygons("HPI", title = "This is a title with \n one  new line")

tm_shape(World) +
  tm_polygons("HPI", title = "This is a title \n with \n two  new line")

tm_shape(World) +
  tm_polygons("HPI", title = "This is \n a title \n with \n three new line")
``` 

Perhaps similar to this: https://github.com/mtennekes/tmap/issues/260

**Comment by mtennekes** [comment]
The white space between title and legend remains the same. What OS and package versions are you using?

**Comment by jeffcsauer** [comment]
R version 3.6.1
Platform: x86_64-apple-darwin15.6.0 (64-bit)
macOS Sierra 10.12.6

tmap version 2.3-1

Perhaps it was just an issue with the size of the screen and how Rstudio was rendering the plot. I think we can close the issue for now.
