### ISSUE TITLE
Tm_iso seems to render text on random places

### ISSUE THREAD

**Issue by wcrice** [mtennekes/tmap#366]
Hi Everyone,

I'm trying to make a contour map using tmap because the rest of my figures are in tmap and they look fantastic! I'm going bonkers trying to make this work...

I made contour lines from a raster (a 1 arc dem) then tried to render it in tmap using the code below but instead of numbers showing up over lines they show up in completely random places:

    dem_basin_topo = dem_basin_extend*3.28084 #convert to feet above mean sea level
     
    cuts = seq(3000,9000, 100)
    
     topo.contour <- rasterToContour(dem_basin_topo, levels = cuts)
    
     tm_shape(dem_basin_topo) +
     tm_raster(palette = terrain.colors(20), style = "cont", title = "Elevation (feet amsl)") +
     tm_shape(topo.contour) +
     tm_iso(alpha=0.3)

I figure it may be useful to give the output of my input files...

    > dem_basin_topo
    class      : RasterLayer 
    dimensions : 985, 1125, 1108125  (nrow, ncol, ncell)
    resolution : 23.1, 30.8  (x, y)
    extent     : -179050.4, -153062.9, 415198.1, 445536.1  (xmin, xmax, ymin, ymax)
    crs        : +proj=aea +lat_1=34 +lat_2=40.5 +lat_0=0 +lon_0=-120 +x_0=0 +y_0=-4000000 +datum=NAD83 +units=m +no_defs +ellps=GRS80 +towgs84=0,0,0 
    source     : memory
    names      : layer 
    values     : 3175.721, 7419.524  (min, max)
    
    > cuts
     [1] 3000 3100 3200 3300 3400 3500 3600 3700 3800 3900 4000 4100 4200 4300 4400 4500 4600 4700 4800 4900 5000 5100 5200 5300 5400 5500 5600 5700 5800 5900 6000 6100 6200 6300 6400 6500 6600 6700
    [39] 6800 6900 7000 7100 7200 7300 7400 7500 7600 7700 7800 7900 8000 8100 8200 8300 8400 8500 8600 8700 8800 8900 9000
    > topo.contour
    class       : SpatialLinesDataFrame 
    features    : 42 
    extent      : -179011.8, -153101.4, 415249.6, 445484.7  (xmin, xmax, ymin, ymax)
    crs         : +proj=aea +lat_1=34 +lat_2=40.5 +lat_0=0 +lon_0=-120 +x_0=0 +y_0=-4000000 +datum=NAD83 +units=m +no_defs +ellps=GRS80 +towgs84=0,0,0 
    variables   : 1
    names       : level 
    min values  :  3200 
    max values  :  7300 

What in the world am I doing wrong? When I do this on other rasters they seem to render just fine....

**Comment by Nowosad** [comment]
Hi @wcrice , 
it is hard to tell what is wrong with your code without any data. However, you can maybe take a look at the code (https://github.com/Robinlovelace/geocompr/blob/befc63fd56e47acd889ef9ee4e3639f36f0f0ee7/05-geometry-operations.Rmd#L1168-L1188) we used to create this figure - https://geocompr.robinlovelace.net/geometric-operations.html#fig:contour-tmap.

**Comment by mtennekes** [comment]
Closing this issue for now.  @wcrice if you have a reproducible example, feel free to reopen it.

See also related issue #373
