### ISSUE TITLE
How to adjust the width of legend to the same width of plot? 

### ISSUE THREAD

**Issue by ianzhangtianyi** [mtennekes/tmap#367]
When setting legend.outside to TRUE, is it possible to extend the width of legend to the same width of plot? I have changed the  legend.width to different value. But it seems  nothing happened. I know  the size of the legend is determined by the content. How can I make it bigger? Thanks

My code: 

```r
    library(tmap)
    data(land)
    tm_shape(land) + 
      tm_raster("elevation", legend.is.portrait = FALSE, style="cont") + 
      tm_layout(earth.boundary = TRUE, legend.outside = TRUE, legend.outside.position = "bottom", 
                legend.width = 10) 
```

**Comment by mtennekes** [comment]
Not possible yet. A hacky workaround is to increase the legend font size (`legend.text.size = 25`), and use the `grid` package to change the font size of the labels back to normal.

I'll leave this issue open as enhancement.
