### ISSUE TITLE
how to deal with rJava??

### ISSUE THREAD

**Issue by mtennekes** [mtennekes/tmap#37]
I'd like your opinion on the following:

tmap requires OpenStreetMap -> rJava -> Java. The installation of Java is often a pain in the a**. For Windows, the 32 bit version of Java is typically installed, which does not work with 64bit R. For Ubuntu, I didn't manage to get openjdk to work with rJava. There are some stackoverflow posts on this topic, but they are often outdated and not always generic. In the end, I succeeded with the oracle version of Java.

Possible options:
* Leave it as it is, so users will have to install rJava.
* Create another package with the OSM functionality, so users can easily install the base tmap package.
* Is it possible to show some kind of installation instructions, such as "For Windows, please install 32 or 64 bit Java depending on your current Windows configuration." Ideally, these instruction should show up via something like onLoad (onInstall does not exist:)).
* Any other ideas?

**Comment by mtennekes** [comment]
Does anyone know whether `Enhances: OpenStreetMap` solves this problem?

**Comment by timelyportfolio** [comment]
I am not sure of the best solution, but I almost gave up on `tmap` when first installing because of the difficulties with `rJava`.  Glad I powered through.

**Comment by mtennekes** [comment]
Tnx! I discussed this with Edwin yesterday, and he told me that packages listed in `Suggests` are not required to be installed, but can be used while using `requireNamespace`. However, they are necessary for the CRAN check and devtools. Packages listed in `Enhances` seem to be approached  in a similar way. If that is the case, Enhances is better suited according to this description: https://cran.r-project.org/web/packages/miniCRAN/vignettes/miniCRAN-dependency-graph.html.

Although the installation difficulties still remain for the github devel-version (using devtools), casual users will now be able to install tmap without problems.
