### ISSUE TITLE
Is there a way to improve the quality of exported mpg tmap_animation()?

### ISSUE THREAD

**Issue by philmikejones** [mtennekes/tmap#374]
Hi @mtennekes 

When I export an animation with `tmap_animation()` as an `mpg` there are some very noticeable compression artefacts. Is there a way to adjust the export quality or turn off compression? gif looks fine suggesting it's compression rather than a problem with shapefiles.

The attached screenshots show the problem (they've been scaled up but otherwise unadjusted).

Below is the relevant log file:

```
Linking to GEOS 3.7.1, GDAL 2.2.3, PROJ 4.9.3
Version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org
Copyright: © 1999-2017 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP 
Delegates (built-in): bzlib djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png tiff wmf x xml zlib
Animation saved to /home/phil/gits/hugo/export/coal_prison_animation.mpg
```

Thanks,
Phil

![Screenshot_2019-11-27_14-55-22](https://user-images.githubusercontent.com/5681718/69734059-43ac0d80-1126-11ea-86b9-ae08ef930249.png)

![Screenshot_2019-11-27_14-55-22](https://user-images.githubusercontent.com/5681718/69733986-24ad7b80-1126-11ea-8891-0959845ddd58.png)

**Comment by mtennekes** [comment]
How is the quality of one png image? If it is better than the animation, than we have to look at imagemagick. Probably there is a setting that controls the level of compression.

**Comment by philmikejones** [comment]
Hi @mtennekes sorry it took me a long time to reply to this. Here's a screenshot at 400% as a png. This is the same data as the animation. You can see that there are no compression artefacts. Standing by to test anything if I can help.
Thanks.
![Screenshot_2020-02-16_22-02-41](https://user-images.githubusercontent.com/5681718/74613760-0180df80-5109-11ea-881d-932f46f31946.png)

**Comment by Nowosad** [comment]
Hi @philmikejones - I am not sure if this is a case, but maybe (to some degree) it is the issue of the mpg format (https://www.imagemagick.org/discourse-server/viewtopic.php?t=14436). Have you tried other formats?

**Comment by philmikejones** [comment]
Hi @Nowosad @mtennekes Yes I'm almost certain it's an mpeg compression artefact issue. I've exported the animation as a gif and it is clean (i.e. no artefacts). The png still image is also clean. It's only the mpg that has problems. I don't how if it's possible/how to increase the quality of the exported mpg. Is it possible? Thanks

**Comment by Nowosad** [comment]
Based on the code (https://github.com/mtennekes/tmap/blob/master/R/tmap_animation.R) I think it is impossible at the moment. You can try and modify it to allow for more imagemagick parameters (here https://github.com/mtennekes/tmap/blob/895c4d42957573eb1b848d7ddf178e35aab10278/R/tmap_animation.R#L52 and here https://github.com/mtennekes/tmap/blob/895c4d42957573eb1b848d7ddf178e35aab10278/R/tmap_animation.R#L56, I believe).

**Comment by Nowosad** [comment]
@philmikejones I think the recent improvements in tmap could be useful in your case - look at https://github.com/mtennekes/tmap/issues/446#issuecomment-689640864.

**Comment by philmikejones** [comment]
Thanks @Nowosad  - sorry I saw this notification back in September then forgot to comment. Yes, I was able to export at higher quality without the artefacts. Thanks

**Comment by Nowosad** [comment]
Great to hear that!
