### ISSUE TITLE
Error with custom legend.format

### ISSUE THREAD

**Issue by sjewo** [mtennekes/tmap#375]
I'm running into a problem with custom legend formats. The following example will produce an error:
```
library(tmap) # 2.3-1
library(tmaptools) # 2.0-2

data(metro)
tm_shape(metro) +
  tm_symbols(size = "pop2010") + 
            tm_layout(legend.format = list(scientific = FALSE,
                                 digits = 0,
                                 text.separator = "bis",
                                 text.less.than = "weniger als",
                                 text.or.more = "oder mehr",
                                 decimal.mark=",",
                                 big.mark=" "))
```
```
Error in if (is.na(align) || align == "left") { :
  missing value where TRUE/FALSE needed
```
The error disappears if I add  `text.align = "left"` to the `legend.format` options or if I use `col = "pop2010"`.

**Comment by mtennekes** [comment]
In the devel version it throws this error `Error: Names in legend.format unknown: decimal.mark, big.mark`.

The function `tm_layout` is used to overwrite tmap options. For the arguments that are passed on to `formatC`, in your case `decimal.mark` and `big.mark`, there are no global tmap options. See `tmap_options("legend.format")`.

Therefore, you cannot specify those arguments in `tm_layout`, but you have to specify them in the layout functions (e.g. `tm_symbols`).

**Comment by sjewo** [comment]
Thank you for the clarification! 

Is assumed any additional options are simply passed to ```formatC```, because the man page for ```tm_layout``` states under the option ```legend.format```: 
``` ...  Other arguments passed on to ‘formatC’ ```

My example code worked flawlessly in the past, so there might had been some internal changes.
```
library(tmap) # 1.2
library(tmaptools) # 2.0-2

data(metro)
metro$pop2010t <- metro$pop2010/1000
tm_shape(metro) +
  tm_dots(col = "pop2010", style="quantile") + 
            tm_layout(legend.format = list(scientific = FALSE,
                                 digits = 1,
                                 text.separator = "bis",
                                 text.less.than = "weniger als",
                                 text.or.more = "oder mehr",
                                 decimal.mark=",",
                                 big.mark=" "))
```

![pop2010](https://user-images.githubusercontent.com/2435621/71726574-c87dfb80-2e37-11ea-9d3e-7dd7185b26a0.png)

If it's difficult to pass the additional option to ```formatC```, I would suggest to change the man page and change the error message to something like this: 
```Error: Names in legend.format unknown: decimal.mark, big.mark. Please specify options separatly in each tm_symbols or tm_fill layer.  ```

**Comment by mtennekes** [comment]
I improved `legend.format` in both `tm_layout` and `tmap_options`. Now it should accept all arguments from `formatC`. Please check if it does the job correctly and reopen if necessary.
