### ISSUE TITLE
Error in saving a faceted interactive plot to html

### ISSUE THREAD

**Issue by lbusett** [mtennekes/tmap#381]
Hi, 
 I am encountering an error when trying to save a faceted interactive map using `tmap_save()`
``` r
library(tmap)
library(sf)

nc <- st_read(system.file("shape/nc.shp", package="sf"))
plot <- tmap::tm_shape(nc) +
    tmap::tm_polygons(c("NWBIR74", "PERIMETER"))
fileout <- tempfile(fileext = ".html")
tmap::tmap_save(plot, filename = fileout)   

#> Error in .getNamespace(pkg) : 
#>   invalid type/length (symbol/0) in vector allocation

```
Note that:
1. Saving non-faceted html plots works properly; 
2. Saving to html from the "Export" button of RStudio and selecting "Save as Webpage" also works.
3. Saving to "png" using `tmap_save()` also works properly.

I am working on R 3.6.1, RStudio 1.2.5033, with all packages up to date.

HTH, 
 
 Lorenzo 

PS:  Thanks for your work on the package! It is really a great help!

**Comment by mtennekes** [comment]
Saving interactive small multiples is not implemented yet in the underlying package leafsync (see #252). 
I added a more useful error message.

**Comment by lbusett** [comment]
@mtennekes  Thanks for looking into this. I did not notice the related issues, sorry. 

I tried the workaround proposed in https://github.com/r-spatial/mapview/issues/35#issuecomment-237900713 by @timelyportfolio, and it seems to work. I think that with a few modifications it could be implemented within `tmap`: would you consider a PR aimed at doing that?

**Comment by tim-salabim** [comment]
@lbusett @mtennekes I think this should really happen in [`leafsync`](https://github.com/r-spatial/leafsync). 
One pissibility is to use [`combine_widgets`](https://github.com/rte-antares-rpackage/manipulateWidget/blob/master/R/combine_widgets.R) from package `manipulateWidget`. I've been meaning to look into this for a long time, but keep getting sidetracked with other cool stuff, sorry :-)

**Comment by PieterjanVerhelst** [comment]
I am trying to save a faceted interactive plot to html and found out on this issue that such a functionality has not been developed for `tmap_save()`. Are there any developments on this front?
