### ISSUE TITLE
tm_facet by two factors produces small row panels

### ISSUE THREAD

**Issue by ngwalton** [mtennekes/tmap#382]
I'm using `tm_facet` with two variables and the row panel labels are getting squished. I tried setting `panel.label.height` in `tm_layout`, but this only effected the column panel labels. I see the example in [issue 14](https://github.com/mtennekes/tmap/issues/14) does not have this issue, so maybe it's something new. Or maybe I'm missing something in which case I apologize.

On my machine, this replicates the issue I'm having:
```
library(tmap)
data("metro")
metro <- metro[1:2, ]

tm_shape(metro) +
  tm_dots() +
  tm_facets(by = c("name", "iso_a3")) +
  tm_layout(panel.label.height = 4)
```
Thanks for your help and for an awesome R package!

**Comment by ngwalton** [comment]
Update: I had the above issue while running R 3.6.1/tmap_2.3-1. When switched back to R 3.4.3/tmap_2.2 and reran both row and column panel labels had the same "height" (i.e. no issue).

**Comment by mtennekes** [comment]
Thx. Should be fixed now. Reopen if necessary.
