### ISSUE TITLE
Unable to execute tm_text function when in interactive "view" mode

### ISSUE THREAD

**Issue by rocknruds** [mtennekes/tmap#384]
Hi! 

When I try to modify a layer of county labels using tm_text, I am able to use the function in tmap_mode("plot")... but when I switch to "view" mode, the formatting of the text goes away.

Any ideas?

Thanks!
Adam

**Comment by mtennekes** [comment]
What do you mean by modifying a layer? Maybe easier with a reproducible example. Thanks!

**Comment by Nowosad** [comment]
Please reopen the issue when you have a reproducible example.
