### ISSUE TITLE
Constant colour scale range over frames

### ISSUE THREAD

**Issue by MxNl** [mtennekes/tmap#385]
Hello,
I just created an animation with facets using tmap. The frames are representing single timestamps. So far everything works fine. The only issue I couldnt solve is that each facet in each frame has an adapted colour scale range. I want to fix the colour scale range so that the values are visually comparable over time. By the way, I think this should be default with an option to set an argument "free.scales.fill.frames" = TRUE. Is that somehow possible? Or is there any work-around?
Thanks a lot!

**Comment by mtennekes** [comment]
What do you mean by frames? In tmap-terminology, the frame is just the map border (as in `qtm(World) + tm_layout(frame = "red")`). A reproducible example would help.

**Comment by MxNl** [comment]
Yes, sorry, my mistake. I used the ggplot terminology. By frame I mean the `along` argument. If it is still not clear, I will provide a reproducible example. Thanks for the help!

**Comment by mtennekes** [comment]
The color scale is fixed in this example:

```r
data(World)
tm_shape(World) + tm_polygons("gdp_cap_est") +
	tm_facets(along = "continent")
```

Please provide an example for which this is not the case.
