### ISSUE TITLE
Categorical rasters colors

### ISSUE THREAD

**Issue by Nowosad** [mtennekes/tmap#388]
Hi @mtennekes - this issue is bothering me every other month. I have a large raster data with some specified color legend, but I need to visualize only a rather small part of the data. Sometimes this small part has all of the colors (see `raster1` below), but sometimes it has only selected colors (see `raster2` below). It is impossible now (or I just do not know how to do it) to use the same color palette for both areas.
Would it be possible for you to add some option to specify a color palette as a named vector (colors and values) or a data frame with two columns (colors and values) that could make the above case possible? If not, do you have any alternative ideas?
Best,
Jakub

``` r
library(tmap)
library(stars)
#> Loading required package: abind
#> Loading required package: sf
#> Linking to GEOS 3.7.1, GDAL 2.3.2, PROJ 5.2.0

my_colors = c("#FFFF64", "#006400", "#BE9600", "#00DC82", "#C31400")
names(my_colors) = as.factor(1:5)

raster1 = matrix(c(rep(1, 4), rep(2, 4), rep(3, 4), rep(4, 2), rep(5, 2)),
                 nrow = 4, ncol = 4)
dim(raster1) = c(x = 4, y = 4)
raster1 = st_as_stars(raster1)

raster2 = matrix(c(rep(1, 4), rep(2, 4), rep(3, 4), rep(5, 4)),
                 nrow = 4, ncol = 4)
dim(raster2) = c(x = 4, y = 4)
raster2 = st_as_stars(raster2)

# full palette used -------------------------------------------------------
tm_shape(raster1) +
        tm_raster(style = "cat", palette = my_colors)
#> Warning: Currect projection of shape raster1 unknown. Long-lat (WGS84) is
#> assumed.
```

![](https://i.imgur.com/m6HzIpm.png)

``` r

# some colors are not used ------------------------------------------------
# the last color should be red --------------------------------------------
tm_shape(raster2) +
        tm_raster(style = "cat", palette = my_colors)
#> Warning: Currect projection of shape raster2 unknown. Long-lat (WGS84) is
#> assumed.
```

![](https://i.imgur.com/oWqqVRG.png)

<sup>Created on 2020-01-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mtennekes** [comment]
Thanks for bringing this up! It also bothers me every now and then. Your solution to name the colors is a good one.  I also thought about having another argument `levels` which specifies the levels. However, then it might be better to let the user cast the star data to factors.

Speaking of which: do you (or @edzer ) know the easiest way to create a factorized stars object?
This one works but feels a bit hacky:

```r
raster3 = factor(c(rep(1, 4), rep(2, 4), rep(3, 4), rep(6, 2), rep(5, 2)), levels = 1:6)
dim(raster3) <- c(4, 4)
class(raster3) <- c("factor", "matrix")
raster3 = st_as_stars(raster3)
```

PS: there was an issue with the order of rows (y dimension value), which should now be fixed in the `stars` branch.

**Comment by edzer** [comment]
@mtennekes 
```r
library(stars)
# Loading required package: abind
# Loading required package: sf
# Linking to GEOS 3.8.0, GDAL 3.0.2, PROJ 6.2.1
x = read_stars(system.file("tif/L7_ETMs.tif", package = "stars"))
(y = cut(x, c(0, 50, 100, 200, 255)))
# stars object with 3 dimensions and 1 attribute
# attribute(s):
#     L7_ETMs.tif    
#  (0,50]   :156060  
#  (50,100] :503764  
#  (100,200]: 77002  
#  (200,255]:   262  
# dimension(s):
#      from  to  offset delta                       refsys point values    
# x       1 349  288776  28.5 +proj=utm +zone=25 +south... FALSE   NULL [x]
# y       1 352 9120761 -28.5 +proj=utm +zone=25 +south... FALSE   NULL [y]
# band    1   6      NA    NA                           NA    NA   NULL    
plot(y)
class(y[[1]])
# [1] "factor"
dim(y[[1]])
#    x    y band 
#  349  352    6 
```
![x](https://user-images.githubusercontent.com/520851/72980207-667f3900-3dda-11ea-91ef-e9ed77e9766d.png)

I pretty much found out by accidents that arrays can be factor, but it's a bit clumsy; look for "factor" in the stars code.

**Comment by edzer** [comment]
BTW, @mtennekes your approach also works, and may be the better one; we'll see.

**Comment by Nowosad** [comment]
Now it works!
