### ISSUE TITLE
Crash in tmap

### ISSUE THREAD

**Issue by drikkes-jue** [mtennekes/tmap#390]
In a certain case 
> print(tm_shape(roads) + tm_lines(col='#636363', lwd=0.9))
returned the error
> Fehler in w_legend[-c(length(w_legend) - 3, length(w_legend) - 1)] : 
>   nur Nullen dürfen mit negativen Indizes gemischt werden
translated in English:
> Error in w_legend[-c(length(w_legend) - 3, length(w_legend) - 1)] :
>   only zeros may be mixed with with negative values

Knowing not much of tmap a couldn't follow the generated traceback; but using debug i
could see that the immediate cause of the error is that tmap:::process_line_lwd_vector is
called with a matrix x whith range(x) == c(0.9, 0.9) and that has pretty(x, 7) returning
c(0.0, 0.5, 1.0) and so, after dropping the value 0.0, w_legend has length 2, therefore
  -c(length(w_legend) - 3, length(w_legend) - 1) == c(-1, 1)
explaining the error message.

**Comment by mtennekes** [comment]
Thanks. Could you please provide a reproducible example? (Or share `roads`?)

**Comment by Robinlovelace** [comment]
Closing for now as no reproducible example. Please post a reprex if you have one and thanks for reporting @drikkes-jue .
