### ISSUE TITLE
inner.margins error when graticules, raster, and borders are used

### ISSUE THREAD

**Issue by Nowosad** [mtennekes/tmap#391]
@mtennekes - one of participants of my spatial data analysis course found this issue. Customizing of inner.margins returns error when graticules, raster, and borders are used at the same time. See a reprex below:

``` r
library(tmap)
library(spData)
library(spDataLarge)

# works
tm_shape(nz) + 
        tm_graticules() +
        tm_borders() +
        tm_layout(inner.margins = c(0.2, 0.2, 0, 0))
```

![](https://i.imgur.com/vz1NnaB.png)

``` r

# works
tm_shape(nz_elev) +
        tm_raster() +
        tm_shape(nz) + 
        tm_borders() +
        tm_layout(inner.margins = c(0.2, 0.2, 0, 0))
```

![](https://i.imgur.com/gCVHr7E.png)

``` r

# error
tm_shape(nz_elev) +
        tm_graticules() +
        tm_raster() +
        tm_shape(nz) + 
        tm_borders() +
        tm_layout(inner.margins = c(0.2, 0.2, 0, 0))
#> Error in valid_numeric_matrix(x): is.numeric(x) is not TRUE
```

<sup>Created on 2020-02-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mtennekes** [comment]
It runs without errors in the `stars` branch. However, there is this a problem with the grid lines, because the bounding box for which the graticules are calculated crosses the 180 longitude.

**Comment by mtennekes** [comment]
Should be fixed now with the stars branch from tmaptools.
