### ISSUE TITLE
tm_lines lwd.legend.labels not working? 

### ISSUE THREAD

**Issue by xiaofanliang** [mtennekes/tmap#394]
```r
data(World, rivers)
tm_shape(World) +
  tm_fill() +
  tm_shape(rivers) +
  tm_lines(col="white", lwd="scalerank", scale=2, 
           legend.lwd.show = TRUE, 
           lwd.legend.labels = c('1','1','1','1')) +
  tm_style("cobalt", title = "Rivers of the World") +
  tm_format("World")
```

<img width="562" alt="Screen Shot 2020-02-17 at 8 48 11 PM" src="https://user-images.githubusercontent.com/22874361/74696808-d9f04c80-51c6-11ea-91ca-9d7be636d502.png">

I try editing the labels of the lwd legend for the plot above using the lwd.legend.labels argument but it has not been working. I also tried the labels argument and it does not work as well. Is this a bug or is there another way to change the legend labels for line width? 

I apologize that I do not know how to format this code better.

**Comment by mtennekes** [comment]
Thanks! Fixed (stars branch)
