### ISSUE TITLE
Non-overlapping legend intervals

### ISSUE THREAD

**Issue by pbpearman** [mtennekes/tmap#399]
I love this package, but I refer you to this [post](https://stackoverflow.com/questions/60506683/r-tmap-modify-legends-dynamically-to-prevent-overlapping-legend-values)
There should be some straightforward way to specify non-overlapping legend intervals automatically, as requested in the post.  If it's not simply a case of me not seeing how to do this (if so, please enlighten me), can you please develop a feature to accomplish what the posted question requests: straightforward, dynamic, non-overlapping legend intervals? Manually specifying labels is tedious. The default should be non-overlapping intervals, since overlapping value ranges are inherently ambiguous.

**Comment by mtennekes** [comment]
I don't understand. The default intervals *are* non-overlapping, or do I miss something? 

The default interval notation ("10 to 20", "20 to 30") may not be clear. Suggestions welcome. In scientific mode:

```{r}
data("World")
tm_shape(World) +
    tm_polygons("HPI", n = 7, legend.format = list(scientific = TRUE, format = "f"))
```

returns the commonly used notation, which is [ for closed and ( for open. So [20, 25) means 20 to 24.999999999. You can set begin of the interval to open and the end to closed, so (20, 25], with `interval.closure`. See

```{r}
tm_shape(World) +
    tm_polygons("HPI", n = 7, legend.format = list(scientific = TRUE, format = "f"),
        interval.closure = "right")
```

**Comment by mtennekes** [comment]
Peter, I just read your comment in the SO answer. Sorry mate, but I don't agree with you that the [a, b) notation is non-standard. It definitely is.

If I understand you correctly, do you mean "10 <= HPI < 20" ?

**Comment by Nowosad** [comment]
There is a new improvement in this area with **tmap** > 3.0. More examples are at https://github.com/mtennekes/tmap/issues/406#issuecomment-610559092.

``` r
library(tmap)
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0
data("World", package = "tmap")

World$x <- sample(0:20, size = 177, replace = TRUE)
tm_shape(World) + tm_polygons("x")
```

![](https://i.imgur.com/hB7Et6f.png)

<sup>Created on 2020-04-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
