### ISSUE TITLE
Interactivity (part 2)

### ISSUE THREAD

**Issue by mtennekes** [mtennekes/tmap#40]
Please check out the new branch called leaflet, which will soon be merged to the master branch. Today, I managed to output tmap interactively by using leaflet. I turned out to be pretty straightforward.

The old interactive `itmap` also worked (thanks again @timelyportfolio), but had some flaws and did not support zoomable OSM tiles. The new approach is easy maintainable, since it just a wrapper of leaflet (wonderful package, thanks @jcheng5)

Some remarks:

* It (obviously) does not support small multiples. For convenience, I just take the first small multiple.
* The projection is always Mercator.
* The legend is limited to a legend of polygon colors, I guess(?)
* Map attributes, such as compass, are not shown.

The two examples in https://github.com/mtennekes/tmap/blob/leaflet/examples/itmap.R work. I'll implement text, lines and raster images soon.

What I would also like is a master opacity slider in leaflet to control the overall opacity of the layers. Don't no if it's possible, and if not, a `opacity` or `alpha` argument to `itmap` will do.

**Comment by mtennekes** [comment]
It's working! I've made a `tmap_mode()` and `ttm()` function which are used to swap between `"plot"` mode and interactive `"view"` mode. See http://von-tijn.nl/tijn/research/tmap/tmap_demo.html for a working example.

**Comment by Robinlovelace** [comment]
Great work - look forward to testing on Tuesday on my R for spatial data course: https://www.cdrc.ac.uk/training-session/introduction-to-r-for-spatial-data-analysis/
