### ISSUE TITLE
Many leaflet basemaps don't render in interactive view

### ISSUE THREAD

**Issue by jtene001** [mtennekes/tmap#401]
I've been preparing interactive maps for COVID-19 and I've had good results with the Stamen basemaps, but most of the other maps at the page referenced in the package manual (http://leaflet-extras.github.io/leaflet-providers/preview) don't render. 

I've been using code like the following:

map3 + tm_basemap(leaflet::providers$Stamen.TonerLite)

This one works, but the ESRI maps and the others don't seem to.

Are we limited to Stamen?

**Comment by mtennekes** [comment]
I think they do render in the browser (but not in RStudio), don't they?

**Comment by Nowosad** [comment]
I cannot reproduce this issue:

``` r
library(tmap)
library(spData)
tmap_mode("view")
#> tmap mode set to interactive viewing
tm_shape(nz) +
  tm_borders() +
  tm_basemap(leaflet::providers$Esri.WorldStreetMap)
#> Linking to GEOS 3.7.1, GDAL 2.3.2, PROJ 5.2.0
```

![](https://i.imgur.com/wEw4qwB.png)

<sup>Created on 2020-04-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

@jtene001 please reopen the issue if you still have some problems with it.
