### ISSUE TITLE
upcoming lwgeom will break tmap

### ISSUE THREAD

**Issue by edzer** [mtennekes/tmap#402]
```
> library(tmap)
Error: package or namespace load failed for ‘tmap’:
 object ‘st_make_valid’ is not exported by 'namespace:lwgeom'
```
`st_make_valid` is now exported by `sf` 0.9-0, which is on CRAN.

**Comment by mtennekes** [comment]
I am aware of this. `tmap` and `tmaptools` were already adjusted. Hope to submit them soon on CRAN.

Thanks @edzer for releasing new versions of `sf` and `lwgeom`! Are you also planning to release a new version of `stars` soon?

**Comment by edzer** [comment]
Yes, I'll have to - I also broke it!
