### ISSUE TITLE
consider adding option to tm_grid to show only one axis's labels

### ISSUE THREAD

**Issue by cmkonrad** [mtennekes/tmap#403]
I was making an arrangement of maps but was surprised to see it didn't look like there was an option in tm_grid to use labels.show	to show tick labels on my y but not x axis. Perhaps I am missing an option that is elsewhere in the code? This sort of thing would be quite helpful for cases where I have a grid arrangement of maps with the same extents and so don't want to show all axis labels on all maps.

**Comment by mtennekes** [comment]
Done. `labels.show` now accepts a vector of two. Please test and reopen it necessary.
