### ISSUE TITLE
Error in if (!tmaptools::is_projected(shp)) { : valeur manquante là où TRUE / FALSE est requis

### ISSUE THREAD

**Issue by wilcar** [mtennekes/tmap#407]
I am working on geospatial data :

     place_name    id region_country     x     y
        <chr>      <dbl> <chr>          <dbl> <dbl>
         1 Barcelona  10102 Spain           41.4  2.18
         2 Bilbao     10103 Spain           43.2 -2.97
         3 Cadiz      10104 Spain           36.5 -6.30
         4 Gibraltar  10106 Spain           36.1 -5.35
         5 La Coruña  10107 Spain           43.4 -8.38

I want to plot this cities over the World basemap of tmap.

	library(sf)
    library(tmap)
    data("World")

Here are my data :

	x <- c(41.38333, 43.25000, 36.53361, 36.13333, 43.36667)
	y <- c(2.18333, -2.96667, -6.29944, -5.35000, -8.38333)

Creating a data.frame object :

     geocode <- data.frame(x,y)

Converting to sf object :

    geocode2 <- st_as_sf(geocode, coords = c("x", "y"))

Building the map :

	map1 <- tm_shape(World) +  # basemap
			tm_fill() +
			tm_borders() +
			tm_shape(geocode2)+      # dots shape
			tm_dots()

    map1

The error :

    Error in if (!tmaptools::is_projected(shp)) { : valeur manquante là où TRUE / FALSE est requis

**Comment by mtennekes** [comment]
Thanks. Should be solved with the release of tmap 3.0.
