### ISSUE TITLE
tmap crashes on "big" raster brick/stack visualization 

### ISSUE THREAD

**Issue by lbusett** [mtennekes/tmap#408]
I noticed that `tmap` currently crashes if trying to visualize a "big" raster brick or stack (i.e., one bigger than max.raster), such as in: 

``` r
library(tmap)
#> Warning: replacing previous import 'sf::st_make_valid' by
#> 'lwgeom::st_make_valid' when loading 'tmap'
library(raster)
#> Loading required package: sp

tmap_mode("plot")
#> tmap mode set to plotting
tmap_options(max.raster = c(plot = 1e+06, view = 1e+06))
r <- raster::raster(nrows=4000, ncols=4000, vals = 1:1.6e07)
b <- raster::brick(r, r)
rastfile <- tempfile(fileext = ".tif")
writeRaster(r, rastfile)
b <- raster::brick(rastfile)
tmap::tm_shape(b) + tm_raster()
#> Raster object has 1.6e+07 (4000 by 4000) cells, which is larger than 1e+06, the maximum size determined by the option max.raster. Therefore, the raster will be shown at a decreased resolution of 1e+06 cells. Set tmap_options(max.raster = c(plot = 1.6e+07, view = 1.6e+07)) to show the whole raster.
#> Error in (function (classes, fdef, mtable) : unable to find an inherited method for function 'bandnr' for signature '"RasterBrick"'
```

Note that:

1) All works properly on a single-band raster, even if it is bigger than max.raster

``` r
b <- raster::raster(rastfile)
tmap::tm_shape(b) + tm_raster()
#> Raster object has 1.6e+07 (4000 by 4000) cells, which is larger than 1e+06, the maximum size determined by the option max.raster. Therefore, the raster will be shown at a decreased resolution of 1e+06 cells. Set tmap_options(max.raster = c(plot = 1.6e+07, view = 1.6e+07)) to show the whole raster.
#> Linking to GEOS 3.6.1, GDAL 2.2.3, PROJ 4.9.3
```

![](https://i.imgur.com/KV2iIyV.png)

2) All works properly if the brick is in memory, such as in: 

``` r
r <- raster::raster(nrows=4000, ncols=4000, vals = 1:1.6e07)
b <- raster::brick(r, r)
tmap::tm_shape(b) + tm_raster()
#> Raster object has 1.6e+07 (4000 by 4000) cells, which is larger than 1e+06, the maximum size determined by the option max.raster. Therefore, the raster will be shown at a decreased resolution of 1e+06 cells. Set tmap_options(max.raster = c(plot = 1.6e+07, view = 1.6e+07)) to show the whole raster.
```

![](https://i.imgur.com/GAlvvwd.png)

Given that, I'd guess the culprit could be in the function used to subsample bricks within the `raster` 
package (https://github.com/rspatial/raster/blob/58cf107b04a0b727a392534b3189cdf5c765990b/R/sampleRegular.R), missing a method when reading from disk. 
Pinging therefore also @rhijmans : I'd try a fix, but I am not so confident on working on methods...

HTH!

<sup>Created on 2020-04-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mtennekes** [comment]
Thanks for your message!

Good news and good news:

* The good news is that it's working on tmap 3.0, which has been published on CRAN yesterday.

* The good news is that there is an excellent new package out there to handle big raster data: `stars`. See the vignette about stars proxy objects: https://r-spatial.github.io/stars/articles/stars2.html

**Comment by lbusett** [comment]
Great, thanks! I'll check it out ASAP (sorry for not checking on the devel github version).
Thanks also for the hint about `stars`. I am gradually migrating my packages towards it where possible, but it will take some time.
