### ISSUE TITLE
tmap does not draw some polygons

### ISSUE THREAD

**Issue by joelgombin** [mtennekes/tmap#41]
I've encountered a very weird bug which I cannot wrap my head around. Since I'm not sure how to make it reproducible, I've put my test dataset here: https://www.dropbox.com/s/vzi6kfrqg0qu2up/test.Rdata?dl=0

The weird thing is that `tmap`seems to plot some polygons as if they were missing values, even though they're not. Consider:

``` r
downloader::download("https://www.dropbox.com/s/vzi6kfrqg0qu2up/test.Rdata?dl=1", destfile = "./test.Rdata", mode = "wb")
load("./test.Rdata")
summary(test@data$testvar)
#>    Mode   FALSE    TRUE    NA's 
#> logical    1581     870       0
library(tmap)
tm_shape(test, bbox = bb(test[test@data$cantville %in% "1399",]), ext = 1.2) + tm_borders() # no problem
```

![](http://i.imgur.com/VXQwaDP.png)

``` r
tm_shape(test, bbox = bb(test[test@data$cantville %in% "1399",]), ext = 1.2) + tm_fill(col = "testvar") # problem
```

![](http://i.imgur.com/dC30M5E.png)

So here we have weird grey polygons, even though there are no missing values in the variable plotted. 

Also, it works fine with the [`cartography`](https://github.com/Groupe-ElementR/cartography) package: 

``` r
load("./test.Rdata")
library(cartography)
layoutLayer(extent = test[test@data$cantville %in% "1399",])
typoLayer(test, test@data, var = "testvar", border = "transparent", add = TRUE)
```

![](http://i.imgur.com/HoNgRj8.png)

@mtennekes, any idea what's going on here?

**Comment by mtennekes** [comment]
Yep, it's the famous `thres.poly` argument of `tm_fill`. This argument prevents tiny polygons from being print. This will work.

    tm_shape(test, bbox = bb(test[test@data$cantville %in% "1399",]), ext = 1.2) + tm_fill(col = "testvar", thres.poly = 0)

The idea behind this argument is that the data of small polygons may skew the overall data distribution. For instance, the population density of Monaco:

    qtm(Europe, fill="pop_est_dens")
    qtm(Europe, fill="pop_est_dens", thres.poly=0) # including Monaco

This one also works:

    test2 <- raster::crop(test, bb(test[test@data$cantville %in% "1399",], ext=1.2))
    tm_shape(test2) + tm_fill(col = "testvar")

So what I'll do, is to take into account the adjusted bounding box. Also, I'll have to set `thres.poly=0` in the interactive view mode.

Thanks for letting me know!

**Comment by joelgombin** [comment]
Wow, well done. I truly couldn't figure out what was going on. The fix for my code is then very easy, great news ;-) I wonder whether it wouldn't be wiser to put 0 as the default value. Or at least put a warning in the documentation?

**Comment by joelgombin** [comment]
Alternatively, the default could be put to 0 when `style = "fixed"`, since in that case the distribution of the variable doesn't matter to the algorithm.

**Comment by mtennekes** [comment]
I went with your first suggestion. I think it's more transparent. And less work for me;-)
