### ISSUE TITLE
border.lwd seems not to have any effect on tm_symbols in view mode

### ISSUE THREAD

**Issue by francisbarton** [mtennekes/tmap#413]
When plotting symbols or bubbles in view mode, I want to be able to use the border colour as a way of distinguishing subsets of my data (*feature request!* - it would be great if we could map `border.col` to a variable just like we can with `col`!).

For now I can use different border colours by manually creating subsets of the data and plotting them as separate layers with different `border.col`. However I find that in view mode the border is so thin as to be virtually invisible and thus it is not much use. You can see the border colour is there, when zoomed out, but as you zoom in on a symbol, the border line seems to get thinner and thinner relative to the symbol size. It's like it can't go bigger than 1 pixel or something.

I have tried setting `border.lwd` to all sorts of values but it doesn't make any difference. This seems like a bug.
The code is below is not strictly a reprex - it gives me an error about html output when using the reprex package. But hopefully it is good enough. Try running the code below and zooming in on a circle and see how thin the border line is. I can provide a screenshot if necessary.

I'm on tmap v 2.3-2 [edit: just noticed 3.0 is out - going to upgrade and see if it's the same]

```
library(dplyr)
library(tmap)

data(metro)

uk_cities <- metro %>% 
  filter(iso_a3 == "GBR")

tmap_mode("view")

tm_shape(uk_cities) +
  tm_symbols(size = "pop2030",
             border.col = "deeppink",
             border.lwd = 1250000)
```

**Comment by mtennekes** [comment]
Thx, yes `border.col` as aesthetic would be nice indeed, but also requires a lot of work and also a lot of extra arguments in the layer functions (both tm_symbols and tm_polygons). I'll tag this issue as enhancement.

As for the thin border lines in view mode: we'll have to look into leaflet (`addCircles` and `addCirclemarkers`) how to make them ticker.

**Comment by mtennekes** [comment]
Fixed. Please test and reopen if necessary.
