### ISSUE TITLE
attempt to create faceted plot involving raster and vector fails

### ISSUE THREAD

**Issue by lbusett** [mtennekes/tmap#415]
Hi, 

   on tmap 3.0, trying to create a faceted plot involving both raster and vector datasets with the same number of "facets" is currently failing, as in: 

``` r
library(dplyr)
library(stars)
library(tmap)

s = stars::read_stars(system.file("tif/L7_ETMs.tif", package = "stars"))%>% 
  stars::st_warp(crs = 3857)
v = sf::st_as_sf(sf::st_as_sfc(sf::st_bbox(s)))
v = rbind(v,v,v,v,v,v)
v$band = 1:6                 

tmap_mode("plot")
rast <- tm_shape(s) + tm_raster() + tm_facets()
vect <- tm_shape(v) + tm_borders() + tm_facets("band")
```
``` r
rast 
# renders ok
```
``` r
vect
# renders ok
```
``` r
rast + vect
```
## Fails with: 
>Error in by_counts_pos[-1] != by_counts_pos[1] : 
  comparison of these types is not implemented

(Sorry for the missing pictures, but reprex does not want to work, this morning...)

HTH, 

Lorenzo

**Comment by lbusett** [comment]
**UPDATE**

See https://github.com/lbusett/tmap/commit/b9eb35914ba406dfa7e02b74102db93426f49cbf
for a possible fix

**Comment by mtennekes** [comment]
Thanks Lorenzo!
