### ISSUE TITLE
visual distortion for the usa and russia

### ISSUE THREAD

**Issue by djouallah** [mtennekes/tmap#419]
I am using this code to draw the boundaries of all coutries, it works well except for the USA and Russia ?
```
library(sf)
library(tmap)
library(readr)
dataset <- read_csv("https://www.dropbox.com/s/qtkrwuhwsn55t89/Countries_Geometry.csv?dl=1", 
                               col_types = cols(feature_type = col_skip(), 
                                                osm_id = col_skip()))
map <- st_as_sf(dataset, wkt="geometry",crs = 4326)
tm_shape(map)+tm_polygons()
```

![image](https://user-images.githubusercontent.com/12554469/79727669-160f6d00-8330-11ea-9fb0-83af2022d294.png)

**Comment by mtennekes** [comment]
Thanks for letting us know. 

This is not `tmap` related, since `plot(map)` also returns the same distortion. There is a geometry problem because `all(sf::st_is_valid(map))` returns `FALSE`. You could try to use `sf::st_make_valid`.

**Comment by Nowosad** [comment]
It think it is related to https://github.com/r-spatial/sf/issues/1372.
