### ISSUE TITLE
Default font

### ISSUE THREAD

**Issue by joelgombin** [mtennekes/tmap#42]
I think the defult value of the `fontfamily` argument to the `tm_layout` function should be whatever default font family the device is using. That's particularly useful in knitr, for example (with somethink like this)

```r
opts_chunk$set(
               dev = "cairo_pdf",
               dev.args = list(family = 'A750-Sans-Light'),
 )
```

**Comment by mtennekes** [comment]
Do you know how to extract the default font family of a device?

**Comment by joelgombin** [comment]
Nope, but I can try to find out.

**Comment by joelgombin** [comment]
So I think what happens is that `cairo_pdf` just passes its `family` argument to `par()`. If I understand well your code what you do is use `gpar()`, which in turns uses `par`. So IMHO the easy fix would be to just pass `""` as the default argument to `tm_layout`. What do you think? Does it make sense?

**Comment by mtennekes** [comment]
There are a couple of thinks I don't quite understand yet:

	# set default font family to serif
	par(family="serif")
	
	# serif font used in base graphics:
	plot(1:10)
	
	# ggplot uses "sans" as default!
	library(ggplot2)
	qplot(mpg, wt, data = mtcars)
	
	# strange: font family used by grid graphics is not inherited from par...
	library(grid)
	grid.newpage()
	grid.text("Test1233")

Suppose the default `fontfamily` value is `""`. Then I'll have to do something like this:

    if (par("family")!="" && fontfamily=="") fontfamily <- par("family")

I'm not sure what the downsides are, especially since `ggplot2` doesn't use the device parameters.

**Comment by joelgombin** [comment]
I don't exactly know how `ggplot2` and `grid` handle the default font family when used interactively, but one thing I know is that they both use the `dev.args=list(family="mono")` when using a `cairo` device. What I don't understand is that actually, `tmap` should also, since it's buit on `grid`, right? But it doesn't. For exemple, try to Rmarkdown [this file](https://gist.githubusercontent.com/joelgombin/b9c63458943b2409433e/raw/eed8f883b2c3706c78970f3079e234cf5f5ed28a/test.Rmd).

Are you able to identify at which step `tmap` manages to override the `dev.args=list(family="mono")` specification, which neither `ggplot2` nor `grid` (nor base graphics) do?

**Comment by joelgombin** [comment]
Maybe @yihui could help us here to understand the internals of the way `knitr` deals with fonts... 
Also for the record when the device is `tikz` the font used is the LaTeX document main font.

**Comment by mtennekes** [comment]
Now it seems to work well. I just put `""` as default value for 

    ```{r fig8}
    devtools::load_all("pkg")
    data(World)
    qtm(World, title="Test123456")
    ```

    ```{r fig9, dev = "cairo_pdf", dev.args=list(family = "mono")}
    devtools::load_all("pkg")
    data(World)
    qtm(World, title="Test123456")
    ```
