### ISSUE TITLE
How to use hcl_palettes or, alternatively, set a vector of colors in tmap?

### ISSUE THREAD

**Issue by ericmelse** [mtennekes/tmap#424]
**tmap** uses colorbrewer based palettes to fill the polygons of a map:
![R_tmap_palettes](https://user-images.githubusercontent.com/3686136/80069411-9822b000-8541-11ea-8fc1-f7709303c0ba.png)

I am not complaining about the lack of choice that **tmap** offers. However, I want also to be able to use HCL-palettes (see the R library **colorspace**):
![HCL_Palettes](https://user-images.githubusercontent.com/3686136/80069506-bf797d00-8541-11ea-840b-8bdcca906738.png)

Although with **colorspace** 

> 'a suitable vector of colors can be easily computed by specifying the desired number of colors and the palette name'

can be computed and used (see [here](http://colorspace.r-forge.r-project.org/articles/colorspace.html)), like:

```
library("colorspace")
hcl_palettes(plot = TRUE)
q4 <- qualitative_hcl(4, palette = "Dark 3")
q4
```
the (new) vector of colors is not accepted by **tmap** (Error: Invalid palette):

```
library(tmap)
library(tmaptools)
data(NLD_prov)
qtm(NLD_prov, fill = "population", fill.palette="q4")
```
After much reading and searching, I did find the following reference in **tmap**'s _help file_ in the section **tm_layout**, for the Argument **aes.palette** the following is explained:

> 'Default color palettes for the aesthetics. It takes a list of three items: seq for sequential palettes, div for diverging palettes, and cat for categorical palettes. By default, Color Brewer palettes ... are used. It is also possible [to] provide a vector of colors for any of these items.'

What triggers me is the last line promising that it indeed is possible to set in **tmap** a _vector of colors to code data with sequential-, diverging-, or categorical palettes_.

### But how?

Any example how to do this is much appreciated.

(Note that this question was also posted by me on [StackOverFlow](https://stackoverflow.com/questions/61365791/how-to-use-hcl-palettes-or-alternatively-set-a-vector-of-colors-in-tmap).)

**Comment by tim-salabim** [comment]
As a side note, these `hcl_palette`s are now available in base R, see https://developer.r-project.org/Blog/public/2019/04/01/hcl-based-color-palettes-in-grdevices/

**Comment by ericmelse** [comment]
Thank you very much Tim, for pointing me in the right direction!

The following example indeed works, like:
`tm_shape(World) + tm_layout(frame=FALSE) +
  tm_polygons("well_being", style = "fixed", breaks=c(2,3,4,5,6,7,8),
              palette=hcl.colors(6, "Tropic"), n = 6) +
  tm_legend(position=c("left", "bottom"), bg.color="white", frame="white")`
which results in:
![WORLD_well_being_hclTropic](https://user-images.githubusercontent.com/3686136/80108988-426bf900-857d-11ea-94f0-d0181d0620cd.png)

However, notice that this visualization will benefit from the inversion of this HSL-scale, by putting a dash (`-`) before the scale name, like
`... palette=hcl.colors(6, "-Tropic"), n = 6)  ...`

But, **tmap**, will now not invert the scale, whereas that does work with the regular scales (e.g. `-RdBu`), like:
`tm_shape(World) + tm_layout(frame=FALSE) +
  tm_polygons("well_being", style = "fixed", breaks=c(2,3,4,5,6,7,8),
              palette="-RdBu", n = 6) +
  tm_legend(position=c("left", "bottom"), bg.color="white", frame="white")`
which results in:
![WORLD_well_being_RdBu_i](https://user-images.githubusercontent.com/3686136/80109041-531c6f00-857d-11ea-8524-c565204aee95.png)

In the above example we see a similar color coding with 'warm colors' at the high end of the scale, whereas the regular scale is in this case much better (i.e. this scale is just the opposite situation), like:
`tm_shape(World) + tm_layout(frame=FALSE) +
  tm_polygons("well_being", style = "fixed", breaks=c(2,3,4,5,6,7,8),
              palette="RdBu", n = 6) +
  tm_legend(position=c("left", "bottom"), bg.color="white", frame="white")`
which results in:
![WORLD_well_being_RdBu](https://user-images.githubusercontent.com/3686136/80109022-4e57bb00-857d-11ea-986b-590dbc2cde81.png)

So, I assume to have **tmap** invert any base R `hcl_palette` some internal code modification is required.
### Is it possible to submit a request to enable `tmap` to invert any base R `hcl_palette` ?

**Comment by tim-salabim** [comment]
You can simply `rev` the palette:

``` r
library(tmap)

data(World)

tm_shape(World) + 
  tm_layout(frame=FALSE) + 
  tm_polygons("well_being", style = "fixed", breaks=c(2,3,4,5,6,7,8), 
              palette=rev(hcl.colors(6, "Tropic")), n = 6) + 
  tm_legend(position=c("left", "bottom"), bg.color="white", frame="white")
```

![](https://i.imgur.com/1el9LQv.png)

<sup>Created on 2020-04-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ericmelse** [comment]
Dear Tim,
Very simple indeed! Many thanks!

**Comment by tim-salabim** [comment]
My pleasure!
