### ISSUE TITLE
tm_credit's background not moving with align argument

### ISSUE THREAD

**Issue by ryanscharf** [mtennekes/tmap#425]
When using align in tm_credits, the text gets justified properly, but the background appears to not be adjusted properly. Align = 'right' moves the background even further to the right.

```r
library(tmap)
data(World)

tm_shape(World) +
  tm_fill() +
  tm_credits(
    'Note: The cone contains the probable path of the storm center but does not show\nthe size of the storm. Hazardous conditions can occur outside of the cone.',
    bg.color = 'black',
    col = 'red',
    align = 'center',
    position = c('center', 'top')
  )
```

![image](https://user-images.githubusercontent.com/16695353/80110518-c2c63600-854c-11ea-9e3f-4a5965745c77.png)

**Comment by mtennekes** [comment]
Thx! Fixed. Please check and reopen if necessary.
