### ISSUE TITLE
Colors are not correct when `drop.levels=TRUE`

### ISSUE THREAD

**Issue by Nowosad** [mtennekes/tmap#427]
See it in the examples below. On the side note, I am starting to think that `drop.levels=TRUE` should be the default here. I assume most user would have data for some smaller area (not with all categories) to plot.

``` r
library(stars)
#> Loading required package: abind
#> Loading required package: sf
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 7.0.0
library(raster)
#> Loading required package: sp
library(tmap)
# data download -----------------------------------------------------------
tf = tempfile(fileext = ".zip")
td = tempdir()
download.file("https://github.com/r-spatial/stars/files/4345255/lanform-example.zip", tf)
unzip(tf, exdir = td)
lf_path = paste0(td, "/lanform.tif")

# data read ---------------------------------------------------------------
# works
lf = read_stars(lf_path)
plot(lf)
```

![](https://i.imgur.com/t3htuPh.png)

``` r

# also works
lf2 = droplevels(lf)
plot(lf2)
```

![](https://i.imgur.com/rF27oWO.png)

``` r

# works (with a warning)
tm_shape(lf) + 
  tm_raster(drop.levels = FALSE)
#> Warning: Duplicated levels found. They have been omitted
```

![](https://i.imgur.com/1c0r4kR.png)

``` r

# works, but with wrong colors
tm_shape(lf) + 
  tm_raster(drop.levels = TRUE)
```

![](https://i.imgur.com/BCAH1Rz.png)

<sup>Created on 2020-04-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mtennekes** [comment]
Fixed. Please reopen if necessary.
P.S Travis keeps failing. If anyone knows why, please let me know.

**Comment by Nowosad** [comment]
@mtennekes I will try to help with Travis tomorrow.

**Comment by Nowosad** [comment]
@mtennekes ok, I checked Travis and it seems that the problem is related to having very old GDAL and PROJ versions. I do not know how to fix it there. @Robinlovelace and I moved most of geocompr stuff to GitHub Actions recently. If you want, I can try to add GH Actions to **tmap** as well. Let me know.

**Comment by mtennekes** [comment]
Thanks for the effort! Nut sure about GH Actions, since I'm not familiar with that. Could that replace travis, or how would you use it?

**Comment by Nowosad** [comment]
Yes, exactly. This could replace Travis. @Robinlovelace and I already replaced Travis with GH Actions for our book (https://github.com/Robinlovelace/geocompr/blob/master/.github/workflows/master.yaml), our package (https://github.com/geocompr/geocompkg/blob/master/.github/workflows/pkgdown.yaml), and our webpage (https://github.com/geocompr/geocompr.github.io/blob/source/.github/workflows/blogdown.yaml). Let me know what you think about it.
