### ISSUE TITLE
Setting background color for tm_compass and tm_scale_bar

### ISSUE THREAD

**Issue by Nowosad** [mtennekes/tmap#428]
@mtennekes do you plan to add a possibility of setting background color for `tm_compass` and `tm_scale_bar`? Sometimes their defaults are hard to see:

``` r
library(landscapemetrics)
library(tmap)
data("augusta_nlcd", package = "landscapemetrics")

tm_shape(augusta_nlcd) +
  tm_raster() + 
  tm_scale_bar() +
  tm_compass() +
  tm_layout(legend.show = FALSE)
#> Warning: Duplicated levels found. They have been omitted
```

![](https://i.imgur.com/aUtLa7f.png)

<sup>Created on 2020-04-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mtennekes** [comment]
Yes, sure. It doesn't have high priority, but on the other hand, this should be easy. Note that ... `+ tm_layout(design.mode = TRUE)` is already quite close.

I guess we want a `bg.color` and a `bg.alpha`, just like `legend.bg.color` and `legend.bg.alpha`?

**Comment by Nowosad** [comment]
Yes, exactly those two.

**Comment by Nowosad** [comment]
@mtennekes could you point me to the parts of the code where this should be added? I would try to learn how to implement it...

**Comment by mtennekes** [comment]
Great!

Yesterday, I renamed all R files to be more consistent with each other. The `pre_` and `process_` scripts/functions stand for preprocessing and processing respectively, and the `plot_` and `view_` scripts/functions refer to the plotting / viewing method specific functionalities. The main procedure script is `print_tmap`.

The map compass and scare bar are examples of plot-only method, so this falls into the `plot_` category.

This is the plotting script: https://github.com/mtennekes/tmap/blob/master/R/plot_attributes.R
E.g. see the line 43 generates a background rectangle for design mode, which you can use as a starting point. Once you've drawn a nice looking background rectangle, you can work upstream towards `tm_scale_bar`. You can trace the upstream route (i.e. how the arguments are passed on) by looking at other scale bar attributes.

Let me know if you need help.

**Comment by Nowosad** [comment]
@mtennekes my first try can be found at https://github.com/mtennekes/tmap/pull/436. Please let me know what you think about it.

``` r
library(landscapemetrics)
library(tmap)
data("augusta_nlcd", package = "landscapemetrics")

# tm_compass
tm_shape(augusta_nlcd) +
    tm_raster() + 
    tm_scale_bar() +
    tm_compass(bg.color = "white", 
               bg.alpha = 0.7,
               type = "8star",
               position = c("left", "top"),
               size = 3) +
    tm_layout(legend.show = FALSE)
#> Warning: Duplicated levels found. They have been omitted
```

![](https://i.imgur.com/bJ2F0Mh.png)

``` r


# tm_scale_bar
tm_shape(augusta_nlcd) +
    tm_raster() + 
    tm_scale_bar(bg.color = "yellow",
                 bg.alpha = 0.8,
                 position = c("center", "bottom")) +
    tm_compass() +
    tm_layout(legend.show = FALSE)
#> Warning: Duplicated levels found. They have been omitted
```

![](https://i.imgur.com/ShgHfNZ.png)

<sup>Created on 2020-05-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mtennekes** [comment]
Great work @Nowosad! Looks solid to me.
