### ISSUE TITLE
The view mode drops a color palette for raster data

### ISSUE THREAD

**Issue by Nowosad** [mtennekes/tmap#429]
``` r
library(tmap)
library(stars)
#> Loading required package: abind
#> Loading required package: sf
#> Linking to GEOS 3.7.1, GDAL 2.3.2, PROJ 5.2.0
library(raster)
#> Loading required package: sp
# data download -----------------------------------------------------------
tf = tempfile(fileext = ".zip")
td = tempdir()
download.file("https://github.com/r-spatial/stars/files/4345255/lanform-example.zip", tf)
unzip(tf, exdir = td)
lf_path = paste0(td, "/lanform.tif")

# data read ---------------------------------------------------------------
# colors are here
lf = read_stars(lf_path)

# colors are correct
tm_shape(lf) +
  tm_raster()
#> Warning: Duplicated levels found. They have been omitted
```

![](https://i.imgur.com/wJ671uM.png)

``` r

# colors are not correct
tmap_mode("view")
#> tmap mode set to interactive viewing
tm_shape(lf) +
  tm_raster()
#> Warning: Duplicated levels found. They have been omitted
```

![](https://i.imgur.com/q5lnuKb.png)

<sup>Created on 2020-04-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mtennekes** [comment]
Fixed now.

@Nowosad Do you have the latest github version? I ask because the colors of the first map are also incorrect. They do look correct over here. The saturated green should be 5, and 17 should be blue. (Sorry, to lazy to take a screenshot).

@edzer The `"colors"` attribute got lost after an `st_warp`. I have `sf` 0.9-2, so not sure if you already fixed this.

**Comment by Nowosad** [comment]
Thanks for asking @mtennekes - I usually work on a server with the latest dev version of **tmap**, and I found this issue there. However, I made the reprex on my local computer (which is going to be updated to Fedora 32 and R4 this week)..

**Comment by edzer** [comment]
I'm looking at this, but with `tmap` installed from github I see
```r
> tm_shape(lf) +
+   tm_raster()
Error in bb(x = c(xmin = -1091676.0997804, ymin = -1182669.97103175, xmax = 1117098.54433339,  : 
  unused argument (asp.limit = 10)
> traceback()
5: do.call("bb", args)
4: process_shapes(shps, x[gm$shape.id], gm, data_by, allow.crop = FALSE, 
       interactive = interactive)
3: print_tmap(x = x, vp = vp, return.asp = return.asp, mode = mode, 
       show = show, knit = knit, options = options, ...)
2: print.tmap(x)
1: (function (x, ...) 
   UseMethod("print"))(x)
```

**Comment by Nowosad** [comment]
@edzer you probably also need to update **tmaptools**: `remotes::install_github("mtennekes/tmaptools")`
