### ISSUE TITLE
in 'view' mode, can't change colors

### ISSUE THREAD

**Issue by joelgombin** [mtennekes/tmap#43]
When using the 'view' mode, it seems that the `palette` argument to `tm_fill` has no effect when the variable mapped to `col` is qualitative.

**Comment by mtennekes** [comment]
Seems to work on my machine:

    data(World)
    tmap_mode("view")
    qtm(World, fill="income_grp", fill.palette="Dark2")

(Which is similar to using `tm_fill`)

Could you post an example that goes wrong?

**Comment by joelgombin** [comment]
OK, so I think I've identified the origin of the bug, and it has nothing to do with the 'view' mode (it caan be reproduced in both 'plot' and 'view' modes). The problem seems to arise when the mapped variable is a character variable with only numbers. 

``` r
library(tmap)
data("World", envir = environment())
qtm(World, fill = "income_grp", fill.palette = "Dark2")
```

![](http://i.imgur.com/4wtCmMd.png)

``` r

World@data$income_grp <- substr(World@data$income_grp, 1, 1)
qtm(World, fill = "income_grp", fill.palette = "Dark2")
```

![](http://i.imgur.com/y5crnZO.png)

**Comment by joelgombin** [comment]
And by the way, in these instances, the legend disappears - in both 'view' and 'plot' modes.

**Comment by mtennekes** [comment]
That's a nice one: if the provided variable is a character, then tmap first checks whether the values can be interpreted as color names. For instance:

    World$col <- sample(c("lightblue1", "violet"), length(World), replace = TRUE)
    qtm(World, fill = "col", fill.palette = "Dark2")
![rplot01](https://cloud.githubusercontent.com/assets/2444081/13046094/2dd79da2-d3d7-11e5-906b-47b3e19c7704.png)

The thing is, that "1" can also be interpreted as a color. So although technically not a bug, it can be improved. What I can do is only consider these cases as fixed colors:

* If the values are contained in `colors()`
* If the values are color codes, such as "#FF644D"
* Any other?

**Comment by joelgombin** [comment]
I thaught it was probably a feature, not a bug, at some level ;-)

Your solution sounds good and shouldn't break too much existing code. I guess at a conceptual level, it would perhaps be more satisfying to differenciate between mapping and setting (something along these lines: <http://ggvis.rstudio.com/properties-scales.html>), but that's not the choices that were made (and your solution is more intuitive for the user).

**Comment by mtennekes** [comment]
Agree. Common R practice is to use factors for categorical data, not characters, and since factors are always mapped, I think there there won't be much confusion. For instance, this

    World$col <- factor(sample(c("lightblue1", "violet"), length(World), replace = TRUE))
    qtm(World, fill = "col", fill.palette = "Dark2")

does mapping rather then setting.

The available numeric aesthetics (bubble size, line width, and text size) are always mapped. However, I think there is not much need for setting those values to, for instance, pixels.

**Comment by joelgombin** [comment]
Maybe @yihui could help here...

**Comment by mtennekes** [comment]
Done! https://github.com/mtennekes/tmap/commit/73343092f1bdfb66267836ddaac1f68d6ca25c09
