### ISSUE TITLE
Cannot change color of the line width legend 

### ISSUE THREAD

**Issue by xiaofanliang** [mtennekes/tmap#439]
```
library(tmap)
data(rivers)

rivers = rivers %>% mutate(newbreaks = case_when(
  strokelwd >= 1.5 & strokelwd <= 2.0 ~ 0.1,
  strokelwd > 2.0 & strokelwd <= 2.5 ~ 0.15,
  strokelwd > 2.5 & strokelwd <= 3.5 ~ 0.2,
  strokelwd > 3.5 & strokelwd <= 12 ~ 0.5
))

tm_shape(rivers) +
  tm_lines(col="newbreaks", style='fixed',
           breaks=c(0.1,0.15,0.2,0.5),
           palette = c('red', 'orange', 'green','blue'),
           lwd="newbreaks", scale=0.5, 
           lwd.legend=c(0.1,0.15,0.2,0.5),
           legend.lwd.show = TRUE) + 
  tm_layout(inner.margins = c(0.05, 0.2, 0.05, 0.05))
```
<img width="523" alt="Screen Shot 2020-05-05 at 11 11 05 AM" src="https://user-images.githubusercontent.com/22874361/81082333-22afcb80-8ec1-11ea-8336-b31d389e80a3.png">

The legend of line width picks up the green color from tm_lines's palette by default, but I want to change it to black or grey since the color has meaning, which is defined in the color legend. I have not found a parameter that allows me to define lwd.legend.col in this case. Is there a workaround or solution?

**Comment by mtennekes** [comment]
Thanks again @xiaofanliang !

I've added an argument `lwd.legeld.col` which you can use. Apparently, `tm_symbols` already had such an argument (`shapes.legend.fill`) but `tm_lines` didn't.
