### ISSUE TITLE
Title and legend style in leaflet

### ISSUE THREAD

**Issue by rcbull** [mtennekes/tmap#443]
Hi,

I have two questions at Leaflet.

1) Is it possible to place the title centered on the Leaflet?
I see in view_add_leaflet_titles.R the tag "leaflet-right", but I couldn't change it

2) Is it possible customize legend style or overwrite css class?
![image](https://user-images.githubusercontent.com/451853/81347229-1b8be780-9092-11ea-853a-e149dca532a9.png)

Regards!

**Comment by mtennekes** [comment]
1. tmap is build on top of the R package leaflet. In the documentation of `leaflet::addlegend` you can see that only the four corner options are possible for the legend. The function internal `view_add_leaflet_titles.R` creates a title for facets (for which I've used the leaflet html-class attribute).
2. I think not in a direct way. You can check if it's possible in the r-package leaflet, and if it's implemented there, let me know, and I'll be happy to do this in tmap as well. What you can do, is save the interactive map with `tmap_save` (make sure you save it as .html and set `selfcontained = FALSE`). Then you'll see all the source code (including the leaflet css file) which you can change anyway you want.
