### ISSUE TITLE
Plot mode maps with multiple tm_shape objects do not scale to shapes correctly.

### ISSUE THREAD

**Issue by Roqarr** [mtennekes/tmap#449]
When using tmap_mode("plot") and multiple tm_shape's, the drawn map will scale / zoom to the first referenced tm_shape, and will draw other tm_shape's out of view.

Specifically, when using USA State TIGER Line shape files to draw a tri-state map:

`nj_shape = st_read("$path to local New Jersey TIGER Line File")`
`ny_shape = st_read("$path to local New York TIGER Line File")`
`pa_shape = st_read("$path to local Pennsylvania TIGER Line File")`

`tm_shape(nj_shape) +
  tm_polygons("STATEFP") +
tm_shape(ny_shape) +
  tm_polygons("STATEFP") +
tm_shape(pa_shape) +
  tm_polygons("STATEFP") +
tm_legend(legend.outside = T,
            legend.outside.position = "right") +
tm_layout(frame = F)`

The Map drawn will zoom to the size of the first tm_shape referenced, and will draw the other tm_shapes around the first, with contents truncated out of view. tmap_mode("view") will however render all areas correctly.

**Comment by mtennekes** [comment]
You can use the argument `is.master = TRUE` in the last `tm_shape`.

If that is not what you are looking for, please provide a reproducible example and reopen this issue.

**Comment by Roqarr** [comment]
Apologies: Had difficulty in attaching image before.

The result of the above segmetn is attached below.

![tm_shape](https://user-images.githubusercontent.com/29576181/82435356-2ebf8f80-9a62-11ea-8d5d-b0e8b4322874.png)

The anticipated result would be a png that is scaled to include the area of all three shapes. The shape files were loaded using st_read, and are in the ESRI shape file format.

**Comment by mtennekes** [comment]
Then you'll need to get the bounding boxes (with `st_bbox`), and create a large bounding box that include them all (so a bounding box of bounding boxes). One could also write a function for that. You can feed this in the `bbox` argument of the first `tm_shape`.

**Comment by Nowosad** [comment]
You can also rbind all the data before plotting.
