### ISSUE TITLE
tm_polygons: The .shp file is invalid

### ISSUE THREAD

**Issue by huangguacui** [mtennekes/tmap#452]
Hi, 
I am trying to read a **.shp file using sf package, then maps with tmap. Got warning message (The shape SubShp is invalid. See sf::st_is_valid ) in using tm_polygons.

Here is some details:
```
library(tmap) 
library(sf)
library(ggplot2)  
```

1. No problem in reading .shp file
```
SubShp<-st_read(dsn = "subs1.shp")     
```
2. Got  problem in tm_polygons
```
tm_shape(SubShp) + tm_polygons(col="pcp_ECCC")
Warning message:The shape SubShp is invalid. See sf::st_is_valid 
```

```
tm_shape(SubShp) + tm_sf(col="pcp_ECCC")
Get the same warning message.
```

```
tm_shape(SubShp) +
     tm_polygons(col="pcp_ECCC",title="pcp", n = 5,style = 'fixed',breaks = my.breaks)
Other functions not working because the shape SubShp is invalid
```
3. Works in ggplot
```
ggplot() +
  geom_sf(data = SubShp, aes(fill=pcp_ECCC))      
```

Any idea or suggestion to fix this problem if I want to make it in Tmap? Thanks.

**Comment by xiaofanliang** [comment]
I am not one of the tmap crews, but can help take a look. Can you show a few lines of SubShp shapefile so that I can see what attributes/data are in the shp? Also can you run sf::st_is_valid(SubShp) and show the results? It is hard to figure out what is wrong without access to the file.

**Comment by huangguacui** [comment]
@xiaofanliang  Thanks.

1.  head(SubShp)
```
> head(SubShp)
Simple feature collection with 6 features and 24 fields
geometry type:  MULTIPOLYGON
dimension:      XY
bbox:           xmin: -1838826 ymin: 2169697 xmax: -1181491 ymax: 2401126
projected CRS:  NAD_1983_Albers
  OBJECTID GRIDCODE Subbasin      Area      Slo1     Len1       Sll       Csl     Wid1
1        1        1        1 1119491.9 29.137045 227081.0  15.23926 0.5522258 346.7387
2        2        2        2  252358.3 37.770901 123286.8  15.23926 1.3172534 141.8405
3        3        3        3  575134.4 33.990265 164808.6  15.23926 1.0460617 232.5152
4        4        4        4  556459.8 30.563320 155981.9  15.23926 0.9263895 227.9555
5        5        5        5  201362.8  1.533786 105973.9 121.91405 0.1330516 123.8732
6        6        6        6  207369.1  1.622805 129894.5 121.91405 0.1170181 126.0771
      Dep1      Lat     Long_      Elev ElevMin ElevMax Bname Shape_Leng  Shape_Area HydroID
1 5.414417 57.37726 -126.6246 1448.6874     689    2686  <NA>  1051771.4 11194918719  300001
2 2.983667 57.68985 -125.0809 1439.5681     721    2892  <NA>   444516.8  2523582948  300002
3 4.148118 57.22605 -125.0075 1365.0693     659    2844  <NA>   659762.2  5751343959  300003
4 4.093708 56.82608 -125.7968 1469.8391     659    2379  <NA>   609772.1  5564598417  300004
5 2.726058 58.32676 -117.6658  365.9566     303     588  <NA>   377443.7  2013628009  300005
6 2.758297 58.08052 -117.3750  357.4397     249     662  <NA>   449911.4  2073691183  300006
  OutletID                       geometry temp_mean pcp_mean temp_mean pcp_mean
1   100001 MULTIPOLYGON (((-1672851 23...       0.1      577      -3.3     1252
2   100002 MULTIPOLYGON (((-1699914 23...      -1.5      724      -4.3      835
3   100004 MULTIPOLYGON (((-1691373 22...      -0.9      670      -3.3      742
4   100003 MULTIPOLYGON (((-1724010 22...       1.4      547      -2.9     1242
5   100005 MULTIPOLYGON (((-1253869 22...      -0.9      376       1.0      614
6   100006 MULTIPOLYGON (((-1225997 21...       0.5      478       1.2      565
```
2. sf::st_is_valid(SubShp)
```
> sf::st_is_valid(SubShp)
  [1] FALSE FALSE FALSE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [15] FALSE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [29]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
 [43]  TRUE  TRUE FALSE FALSE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE
 [57]  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE FALSE
 [71] FALSE FALSE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [85] FALSE  TRUE  TRUE FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [99] FALSE  TRUE  TRUE FALSE  TRUE
```

**Comment by xiaofanliang** [comment]
Normally, st_is_valid(SubShpe) should all return TRUE for tmap to work. You should check on geometries that return FALSE to see why that may be the case. One way is to just plot them (using plot or ggplot2) to see what they look like and how they are different from those that are TRUE. I cannot access your geometry so cannot debug further.

**Comment by huangguacui** [comment]
It seems that ggplot2 works  well for coloring/filling those polygons that return false (st_is_valid(SubShpe)). I'm just wondering if tmap also can work for this .shp file. Anyway, thanks for your suggestion @xiaofanliang.

**Comment by mtennekes** [comment]
`tmap` does a few 'sophisticated' things that require valid shapes. You can fix it with `SubShpe <- sf::st_make_valid(SubShpe)`.

**Comment by huangguacui** [comment]
Hi, thanks for your suggestion @mtennekes. I tried it. There are no warning message now. But it still has problem.
```
test<-sf::st_make_valid(SubShp)
```
```
tm_shape(test) +  tm_polygons(col="pcp_ECCC")      no legend
```
![image](https://user-images.githubusercontent.com/25955721/82835529-88b8be80-9e81-11ea-8ff8-c91d51631b92.png)

```
tm_shape(test) + tm_polygons(col="pcp_ECCC", style = 'pretty',palette = "plasma")

Get the same figure. No legend, other arguments are not working.
```
![image](https://user-images.githubusercontent.com/25955721/82835674-f664ea80-9e81-11ea-8dd3-a2d167744775.png)

**Comment by mtennekes** [comment]
What kind of data is in this variable `pcp_ECCC`? You probably can't share the data, can't you?

**Comment by huangguacui** [comment]
Thanks @mtennekes. It's precipitation data. I added it to original spatial  data (SubShp.shp).   It's very tricky. I write the .shp file and read it again. Then it works. No idea what's going on.

```
> class(SubShp$pcp_ECCC)
[1] "matrix" "array" 
```

```
> head(SubShp$pcp_ECCC)
     pcp_mean
[1,]      577
[2,]      724
[3,]      670
[4,]      547
[5,]      376
[6,]      478
```


```
st_write(SubShp, "SubShp.shp")
```

```
test2<-st_read(dsn = "SubShp.shp")   #use sf read shp file
```


```
> tm_shape(test2) +tm_polygons(col="pcp_ECCC")
Warning message:The shape test2 is invalid. See sf::st_is_valid 
```
![image](https://user-images.githubusercontent.com/25955721/82843784-85323100-9e9b-11ea-9168-337f4d706e9f.png)


```
> test2<-sf::st_make_valid(test2)
> tm_shape(test2) + tm_polygons(col="pcp_ECCC", style = 'pretty',palette = "plasma")
```

![image](https://user-images.githubusercontent.com/25955721/82843833-b3177580-9e9b-11ea-8b96-cf8def9bc138.png)

**Comment by mtennekes** [comment]
That explains: internally, `tmap` converts the data variable to be visualized (which is assumed to be a vector) into a color matrix. When the data variable is already a matrix, then it is treated as color matrix (R maps numeric values to base colors). Instead of `st_write`/`st_read`, you could probably also do `SubShp$pcp_ECCC <- as.vector(SubShp$pcp_ECCC)`.
