### ISSUE TITLE
When knitting Rmd files, `print.tmap` behaves differently, throwing errors, then when used interactively

### ISSUE THREAD

**Issue by Matherion** [mtennekes/tmap#454]
I have an interesting issue. I'll probably end up work around it for now, but I thought you might want to know about it.

When merging data to the World dataset, `dplyr::join` complains about the `geometry` column not being a vector - _but only when knitting an Rmd file_, but in interactive use.

My Rmd file is at https://gitlab.com/a-bc/your-covid-19-risk/-/blob/c8ab704fb21652db73abf8ce18830048d009b53a/v1/scripts/your-covid-19-risk-v1-analyses.Rmd#L328-383

Specifically, the code is the following.

First, I load the data and convert the iso_a3 column to character (it was stored as a factor - maybe also something to change in the package, because this is typically a column people will use to append data?)"

```
data(World, package="tmap");
World$iso_a3 <- as.character(World$iso_a3);
```

Then I load a file with alpha2 and alpha3 codes, because my `data.frame` only has alpha2 codes, and the World `sf` `data.frame` only has alpha3. I also convert it to a convenient conversion vector and use that to add alpha3 to my `data.frame`:

```
country_iso_codes <-
  utils::read.delim(file.path(dataPath, "country-iso-alpha2-alpha3.csv"),
                    encoding = "UTF-8");
iso_a3 <-
  stats::setNames(country_iso_codes$iso_a3,
                  nm = country_iso_codes$iso_a2);
dat$iso_a3 <-iso_a3[toupper(dat$country_aggregated)];
```

I count the number of rows in my `data.frame` for each country (i.e. each alpha3 code):

```
usersPerCountry <-
  table(dat$iso_a3);
```

And then we're ready to append this to the World `sf` `data.frame`:

```
mapdat <- dplyr::left_join(World,
                           data.frame(iso_a3 = names(usersPerCountry),
                                      users = as.vector(usersPerCountry),
                                      stringsAsFactors = FALSE),
                           by = "iso_a3");
```

Now, mindbogglingly, this works fine. Until you knit the Rmd file. Then you get:

```
Quitting from lines 329-388 (your-covid-19-risk-v1-analyses.Rmd) 
Error: All columns in a tibble must be vectors.
x Column `geometry` is a `sfc_MULTIPOLYGON/sfc` object.
Backtrace:
     x
  1. +-rmarkdown::render(...)
  2. | \-knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
  3. |   \-knitr:::process_file(text, output)
  4. |     +-base::withCallingHandlers(...)
  5. |     +-knitr:::process_group(group)
  6. |     \-knitr:::process_group.block(group)
  7. |       \-knitr:::call_block(x)
  8. |         \-knitr:::block_exec(params)
  9. |           +-knitr:::in_dir(...)
 10. |           \-knitr:::evaluate(...)
 11. |             \-evaluate::evaluate(...)
 12. |               \-evaluate:::evaluate_call(...)
 13. |                 +-evaluate:::timing_fn(...)
 14. |                 +-base:::handle(...)
 15. |                 +-base::withCallingHandlers(...)
 16. |                 +-base::withVisible(eval(expr, envir, enclos))
 17. |                 \-base::eval(expr, envir, enclos)
 18. |                   \-base::eval(expr, envir, enc

Execution halted
```

I understand the error - that column _does_ have that class. That's why this the World object a tibble and not a data.frame in the first place, I assume.

But I have no idea why `dplyr::join_left` doesn't mind 'interactively', but it suddenly complains when ran during knitting.

If I remove the `geometry` column, and temporarily store it in another object, I get:

```
Error in sf_join(NextMethod(), attr(x, "sf_column"), suffix[1]) : 
  sf_column %in% names(g) is not TRUE
```

Which makes sense, because the `sf_column` is set (in the corresponding attribute) to `geometry` :-)

Using base R, specifically `merge`, fixes this:

```
mapdat <-
  merge(x = World,
        y = data.frame(iso_a3 = names(usersPerCountry),
                       users = as.vector(usersPerCountry),
                       stringsAsFactors = FALSE),
        by = "iso_a3",
        all.x = TRUE,
        all.y = FALSE,
        sort = TRUE);
```

Which has the added benefit of not requiring `dplyr`, which I don't use for anything else :-)

But then this error is thrown when printing the map:

```
Quitting from lines 329-424 (your-covid-19-risk-v1-analyses.Rmd) 
Error in get_bb(x, cx = cx, cy = cy, width = width, height = height, xlim = xlim,  : 
  Incorrect x argument
Calls: <Anonymous> ... knit_print.tmap -> print_tmap -> gather_shape_info -> bb -> get_bb
Execution halted
```

Note that I first ran `tmap::tmap_mode("plot");`, so it just tries to plot - but for some reason, that's a problem _when knitting_ but not normally.

Oh, interesting - when I don't print the plot, but only try to save it to disk, I get almost the same error:

```
Quitting from lines 329-424 (your-covid-19-risk-v1-analyses.Rmd) 
Error in get_bb(x, cx = cx, cy = cy, width = width, height = height, xlim = xlim,  : 
  Incorrect x argument
Calls: <Anonymous> ... print.tmap -> print_tmap -> gather_shape_info -> bb -> get_bb
Execution halted
```

(Well, the same error, but from a different place.)

Hmm. Ok, so this is actually not something I can work around - but I'm also not sure what the issue is exactly.

It clearly has to do with `tmap:::print_tmap` behaving differently while knitting, but I'm not sure how, or how to fix this.

This different behavior only seem to be a problem when merging an `sf` data.frame with additional data columns; if I don't merge anything, there is no problem.

Very, very weird.

Hmm - I now tried sorting World and the merged `data.frame` on the alpha3 code, and then adding the relevant column to World manually. That produces another error:

```
Quitting from lines 329-440 (your-covid-19-risk-v1-analyses.Rmd) 
Error in st_geometry.sf(x) : 
  attr(obj, "sf_column") does not point to a geometry column.
Did you rename it, without setting st_geometry(obj) <- "newname"?
Calls: <Anonymous> ... st_crs.sf -> st_crs -> st_geometry -> st_geometry.sf

Execution halted
```

Fascinating, because when I do this interactively, I can see that all attributes of World remain untouched when I add the new column.

But apparently, during knitting, they get removed when adding that new column?

I now forced an error where I print `names(World)` and `class(World$geometry)` after having added the column. Indeed, `geometry` loses its class. Using `class` to reinstate it doesn't work.

Ok, I'll have to stop debugging for now, this took a few hours that I actually didn't have :-)

I'll post this here already, 1) for myself as documentation of my progress, 2) so that others who run into the same problems can chime in and maybe share more information from their situation/debugging attempts, and 3) in case all this points one of the developers to the actual problem :-)

I realise that without a reprex this isuse is almost impossible to address, so, feel free to just leave this sitting here until I either found the problem and can report that specifically, or used all this info to create a minimal reprex.

**Comment by Matherion** [comment]
Hmm - if I use `rnaturalearth::ne_countries`, merge that with the users per country, and the plot using `ggplot2`, it does seem to work. That means that my own personal issue is solved for now, just not with `tmap`. This means I'll not spend more time debugging this.

However, I can imagine you'll still want to try to figure out what is happening here. I'll keep this tab open in my browser for a while and check back a few times. If you'd like to pick this back up later, feel free to contact me through e.g. Twitter at https://twitter.com/matherion. I don't use GitHub much (GitLab is now my primary Git 'home'; https://gitlab.com/matherion), so if you'd like to get a hold of me, this may not be the best medium :-)

I can _also_ imagine that you have no desire whatsoever to dive into this - in that case, please feel free to just close this issue :-)

**Comment by mtennekes** [comment]
Thanks for this issue. It's difficult to follow since there are a few issues. Moreover knitr is difficult to debug. When dplyr methods do not work for sf objects, it could be that sf is not loaded. Functions like `left_join` are implemented for sf objects (see ?sf::tidyverse).

I would also recommend to install the github versions for both tmap and tmaptools. I plan to submit them to CRAN within two weeks.

PS1: I saw on your gitlab homepage that you're also based in Maastricht. What are the odds...:-)
PS2: Great work on the CIVID-19 Risk project. At least, it seems like a very useful.
