### ISSUE TITLE
Add the SpatialPosition package models to smooth map

### ISSUE THREAD

**Issue by joelgombin** [mtennekes/tmap#46]
The new [`SpatialPosition` package](https://github.com/Groupe-ElementR/SpatialPosition) offers interesting possibilities for smoothing a map, including the possibility to respect the original borders (Stewart model). It woudl be great to implement that in `tmap`.

**Comment by mtennekes** [comment]
Sounds nice!

**Comment by joelgombin** [comment]
I'v rethaught about this, and I actually think it's not really worth implementing that: it's more flexible to run `SpatialPosition` first, and then use the results as an input to `tmap`. It seems more right that way: otherwise, `tmap` would have to implement whatever packages offer to smooth/model spatial data.
