### ISSUE TITLE
color of the symbol borders is not working

### ISSUE THREAD

**Issue by Si-Chong** [mtennekes/tmap#462]
I use R version 3.6.3 and tmap version 3.0
The `border.col` argument in the `tm_symbols` function seems not working.
Thanks for the help!

The example can be (the symbol border colour is now the same as the symbol colour itself):

```
library(tmap)
library(spData)
urb_2020 = subset(urban_agglomerations, year == 2020)
tm_shape(world) + tm_borders() +
  tm_shape(urb_2020) +
  tm_symbols(col = "population_millions", size = 1, shape = 19,
             alpha = 0.5, border.col = "black", border.lwd = 2, border.alpha = 1)
```

![tmap](https://user-images.githubusercontent.com/49397144/85192887-2a360300-b2bc-11ea-8906-74927df8bf87.png)

**Comment by mtennekes** [comment]
Shape number 19 doesn't have a border; see:

``` r
require(ggplot2)
#> Loading required package: ggplot2
print(ggplot(data.frame(p=c(0:25,32:127))) +
    geom_point(aes(x=p%%16, y=-(p%/%16), shape=p), size=5, fill="red") +
    geom_text(mapping=aes(x=p%%16, y=-(p%/%16+0.25), label=p), size=3) +
    scale_shape_identity() +
    theme(axis.title=element_blank(),
          axis.text=element_blank(),
          axis.ticks=element_blank(),
          panel.background=element_blank()))
```

![](https://i.imgur.com/PPGtVky.png)

<sup>Created on 2020-06-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

You'll need to use `shape = 21` for that (which is also the default).
