### ISSUE TITLE
legend digits french notation

### ISSUE THREAD

**Issue by wilcar** [mtennekes/tmap#465]
Hi, 
In digits you use comma for separate thousands like 25,000
In french we do not use comma (comma is used for decimal separator)
How can I display 25000 or better with 25 000

**Comment by mtennekes** [comment]
Good question. This setting is a little bit hidden, and requires some attention (in the docs or examples).

```r
tm_shape(World) +
	tm_polygons("pop_est_dens", legend.format = list(big.mark=" "))
```

`big.mark` is one of the arguments that is passed on to the underlying function `prettyC`.
