### ISSUE TITLE
Defining a single symbol size in tm_add_legend 

### ISSUE THREAD

**Issue by xiaofanliang** [mtennekes/tmap#469]
I have an edge case to this problem in this [post](https://github.com/mtennekes/tmap/issues/451). I can match up the size in tm_add_legend if I give the tm_add_legend a vector of sizes (for more than one node). Here I presented an example that I want to create a legend that features the largest node size from the data, and I cannot match up the node size using your method (As you can see, largest pop_est_size is not the same as the largest node in pop_est). 

```
data(World)
tm_shape(World) + 
      tm_polygons() + 
      tm_symbols(col='pop_est', style='quantile', palette='YlOrRd', size='pop_est', sizes.legend=c(max(World$pop_est)/2, max(World$pop_est)), size.max=max(World$pop_est), scale=1, legend.size.is.portrait=T) + 
      tm_add_legend('symbol', col='white', border.col='black', size=(c(max(World$pop_est))/max(World$pop_est))^0.5,  labels=c('33-1339 mln'), title="Largest pop_est size")
```
![Screen Shot 2020-07-06 at 2 52 29 PM](https://user-images.githubusercontent.com/22874361/86628846-7bbadf00-bf98-11ea-9058-41b51a8fd407.png)

If I add one more node into the size argument with the value `max(World$pop_est)/2` in tm_add_legend, then the largest size is scaled in the correct format. 

```
data(World)
tm_shape(World) + 
      tm_polygons() + 
      tm_symbols(col='pop_est', style='quantile', palette='YlOrRd', size='pop_est', sizes.legend=c(max(World$pop_est)/2, max(World$pop_est)), size.max=max(World$pop_est), scale=1, legend.size.is.portrait=T) + 
      tm_add_legend('symbol', col='white', border.col='black', size=(c(max(World$pop_est)/2, max(World$pop_est))/max(World$pop_est))^0.5,  labels=c('33-1339 mln'), title="Largest pop_est size")
```

![Screen Shot 2020-07-06 at 2 56 44 PM](https://user-images.githubusercontent.com/22874361/86629210-0f8cab00-bf99-11ea-8314-2e2d2f26d310.png)

Let me know how I can fix this if I only want to feature one node with the largest size in this case. Thanks!

**Comment by mtennekes** [comment]
It should be working now. The problem was that when one size number was specified, the legend was process as "symbol.col' type, rather than "symbol.size" type. Now it is processed as "symbol.size". Furthermore, I fixed the "symbol.col" default sizing, such that the symbol sizes are now consistent with the "symbol.col" legends created with `tm_symbols`.

Let me know if that solves the problem, and if not please reopen this issue.

**Comment by xiaofanliang** [comment]
It works! Thanks!
