### ISSUE TITLE
How to set top/bottom outer margins?

### ISSUE THREAD

**Issue by mbacou** [mtennekes/tmap#47]
Hi,
I'm trying to replicate the attached map layout using `tmap`, but I'm not finding the right values for argument `outer.margins`. Basically I'd like to place the title and any legend in the outer top part over a white background, and credits in the outer bottom, and have a default grey background inside the frame.

I've tried to define a layout below with different top/bottom margin values, but don't get any extra outer margin.

Thanks for any help!

```{R}
windowsFonts(ArialNarrow=windowsFont("Arial Narrow"))

tm_layout_hc <- function(...) tm_layout(
    fontfamily="ArialNarrow",
    bg.color="grey80",
    outer.margins=c(4, 0, 8, 0), 
    outer.bg.color="white",
    legend.position=c("left", "top"), 
    title.snap.to.legend=T,
  aes.color=c(
    fill="darkolivegreen3", borders="black", 
    bubbles="tomato2", dots="firebrick",
    lines="steelblue", text="grey20", na="grey50"),
  aes.palette=list(seq="YlGn", div="RdYlGn", cat="Set3"),
...)
```

![ind-rurpop-2010](https://cloud.githubusercontent.com/assets/260325/13205564/d5206e50-d8b8-11e5-8ccb-eeaf2d0bcac4.png)

**Comment by mbacou** [comment]
After a few trial & errors, I managed as below, but not quite there yet.

```
  tm_shape(ind, bbox=bbox(g2)+c(-1E5, -1E5, 1E5, 1E5), unit="km") + 
    tm_polygons(col="NAME_1", border.col="grey50", lwd=.4) +
    tm_credits(paste("  IFPRI/HarvestChoice", "FEB 2016  ", sep=stri_dup(" ", 80)),
      position=c("LEFT", "BOTTOM"), size=1, col="grey20", bg.color="white") +
    tm_scale_bar(position=c("right", "TOP")) + 
    tm_layout(
      #design.mode=T,
      fontfamily="ArialNarrow",
      bg.color="grey80",
      asp=1,
      outer.margins=c(0, 0, 0.22, 0),
      inner.margins=c(0.1, 0, 0, 0),
      outer.bg.color="white",
      legend.bg.color="white",
      legend.height=0.22,
      legend.position=c(0, 1), 
      title.snap.to.legend=T)
```

![test](https://cloud.githubusercontent.com/assets/260325/13206032/ede78f80-d8c3-11e5-9764-0902cdbf4bce.png)

**Comment by mtennekes** [comment]
You are right, map attributes such as scale bar are designed to be placed inside the frame (except for grid labels `tm_grid`, which can also be placed outside). The same applies for the legend. The way you placed the legend is a nice dirty trick that works. I suppose this doesn't work with the scale bar?

**Comment by mbacou** [comment]
Right, I realized this was not currently feasible. The scalebar doesn't move beyond the inner margins either, neither does the main title. I just simply have to go for a different layout for now.
Great package nonetheless. Thanks.

**Comment by mtennekes** [comment]
FYI, now legend and map attributes can be placed outside:
```
qtm(Europe, fill="HPI") + 
tm_scale_bar() + 
tm_layout(attr.outside = TRUE, legend.outside = TRUE)
```

![rplot06](https://cloud.githubusercontent.com/assets/2444081/14941287/308ceee4-0f96-11e6-89cd-259316befa82.png)

**Comment by mbacou** [comment]
Great, thx.
