### ISSUE TITLE
Customize Individual legend's position for multiple legends

### ISSUE THREAD

**Issue by xiaofanliang** [mtennekes/tmap#476]
Tmap package now only allows adjusting legend position through `tm_layout` argument `legend.position` and it only applies to one legend. I tried giving the `legend.position` a vector containing multiple vectors, but it will only respond to the first input. The `legend.stack` argument in `tm_layout` is not enough to reach what I want. 

I want to define legend positions for multiple legends (e.g., one on bottom left and one on bottom right). This is what the current codes output. 

```
data(World)
tm_shape(World) + 
  tm_polygons() + 
  tm_symbols(size='pop_est', sizes.legend=c(max(World$pop_est)/2, max(World$pop_est)), 
             size.max=max(World$pop_est), scale=1, legend.size.is.portrait=T) + 
  tm_add_legend('symbol', col='white', border.col='black', size=1^0.5,  
                labels=c('33-1339 mln'), title="Largest pop_est size") + 
  tm_layout(legend.position=c(c('left', 'bottom'), c('right', 'bottom')))
```
![Screen Shot 2020-07-15 at 4 45 33 PM](https://user-images.githubusercontent.com/22874361/87594226-a274c600-c6ba-11ea-948b-f8ae5499ce89.png)

I would love a solution to this problem! Thanks!

**Comment by mtennekes** [comment]
This is not possible in that way unfortunately. The layout is intended to have one legend block of stacked legends.

However, there is a nice workaround/hack to achieve multiple legend positions:

``` r
library(tmap)
data(World)
tm_shape(World) + 
    tm_polygons() + 
    tm_symbols(size='pop_est', sizes.legend=c(max(World$pop_est)/2, max(World$pop_est)), 
               size.max=max(World$pop_est), scale=1, legend.size.is.portrait=T) + 
    tm_layout(legend.position=c('left', 'bottom'))

tm = tm_shape(World) + tm_fill(alpha = 0) + # dummy layer
    tm_add_legend('symbol', col='white', border.col='black', size=1^0.5,  
                  labels=c('33-1339 mln'), title="Largest pop_est size") + 
    tm_layout(legend.position=c('right', 'bottom'), bg.color = NA)

print(tm, vp = grid::viewport())
```

![](https://i.imgur.com/yvXKzV3.png)

<sup>Created on 2020-07-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

It basically creates a inset map (like https://cran.r-project.org/web/packages/tmap/vignettes/tmap-JSS-code.html#section-4.4), with invisible polygons and the manually added legend.
