### ISSUE TITLE
Dependency on markdown not working in R 4.0.2

### ISSUE THREAD

**Issue by oduilln** [mtennekes/tmap#479]
Apologies if this is an issue on my end. I tried to install tmap from GitHub to pick up some fixes from yesterday, using devtools:

`> devtools::install_github("mtennekes/tmap")
`
There seems to be a dependency on Markdown which fails:

```
> install.packages(pkgs = "C:/Users/Nathan.Doyle/Downloads/markdown_1.1/")
Warning in install.packages :
  package ‘C:/Users/Nathan.Doyle/Downloads/markdown_1.1/’ is not available (for R version 4.0.2)
```

Markdown is currently in maintenance only mode and has been superseded by RMarkdown

**Comment by mtennekes** [comment]
Thanks for the issue, but this does not seem to be tmap related. If it is, please reopen this issue again.
