### ISSUE TITLE
Raster image transparency problem

### ISSUE THREAD

**Issue by behrica** [mtennekes/tmap#48]
I have a raster image which I overlay over a (partially filled) polygon layer and I want that the filled polygons "shine through" for every raster point which is NA.

I played with all combinations of 'alpha' and colorNA, but don't get it working.

It is the default behavior of using two calls to plot:

```
plot(world.eu);plot(koppenCombined,add=T)
```

I can simulate it 'nearly' by using something like:

```
qtm(world.eu) + 
tm_shape(koppenCombined) + 
tm_raster(alpha = 0.5,colorNA = c("#FFFFFFFF"))
```

but it is not the same, as in this case the whole second layer is semi-transparent (so 'pale')

I only want the NA dots of the raster layer to be (full) transparent.

The documentation of raster::plot says:

   colNA: The color to use for the background (default is transparent)

It seems to me that I cannot get the same effect by using 'colorNA' from tm_raster()

**Comment by mtennekes** [comment]
The color that you used for `colorNA` is solid. Transparent white is `"FFFFFF00"`.
If you use that, you'll still see a Missing category in the legend. To prevent that, you could either set `showNA=FALSE`, or use `colorNA=NULL`. I've recently set `NULL` as the default value for `colorNA` in `tm_raster`. So this reproducible example will produce the result you want, if I understand you correctly:

    data(World)
    data(land)
    land$trees[land$trees<40] <- NA

    qtm(World) +
	tm_shape(land) + 
	tm_raster("trees", alpha=.5)
 
![rplot02](https://cloud.githubusercontent.com/assets/2444081/13253092/7c98aa12-da3a-11e5-9bae-a422c0426260.png)

**Comment by behrica** [comment]
Yes , it works in your example, but you specify alpha=0.5 which changes the collors of the whole map.
It would like to use it like this:

```
qtm(World) +
tm_shape(land) + 
tm_raster("trees", alpha=1)
```
So the background colors(continents) stay unchanged and only the rastet dots with NA are transparent at 100%. 

I will try to make an reprodicible example.

**Comment by behrica** [comment]
I did not find a raster file quickly...

My koppenCombined is a RasterLayer:
class       : RasterLayer 
dimensions  : 168, 528, 88704  (nrow, ncol, ncell)
resolution  : 0.08333333, 0.08333333  (x, y)
extent      : -10.01667, 33.98333, 34.00833, 48.00833  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=longlat +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +no_defs 
data source : in memory
names       : layer 
values      : 5, 9  (min, max)

which hast a lot of NAs. And usingf 2* plot() it is possible to overlay this over a SpatialPolygonsDataFrame and let the lower layer shine throug for every point which
is NA in the RasterLayer (without making the top layer partialy transparent)

**Comment by mtennekes** [comment]
I think I don't understand you question. Could you post an example image?

This code

   qtm(World) +
    tm_shape(land) + 
    tm_raster("trees", alpha=1)

gives
![rplot](https://cloud.githubusercontent.com/assets/2444081/13290806/92501bb6-db15-11e5-8f0a-2787d275b81f.png)

The polygons below the NA raster values have the same colors as the original (see picture in my first post)

**Comment by behrica** [comment]
I get something else...

This code  gives:
```
library(tmap)
data(World)
data(land)
land$trees[land$trees<40] <- NA

qtm(World) +
tm_shape(land) + 
tm_raster("trees", alpha=1)
```
![ex1](https://cloud.githubusercontent.com/assets/127361/13301712/94254c28-db46-11e5-989d-e0d4719aca09.png)

And this gives:

```
library(tmap)
data(World)
data(land)
qtm(World) +
tm_shape(land) + 
tm_raster("trees", alpha=1)
```

![ex2](https://cloud.githubusercontent.com/assets/127361/13301725/a26d957e-db46-11e5-8381-18b18c9f8d24.png)

I run it on an fresh R session
My session info is:

```
R version 3.2.2 (2015-08-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 15.10

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] tmap_1.2-1

loaded via a namespace (and not attached):
 [1] spdep_0.5-92       Rcpp_0.12.3        raster_2.5-2       splines_3.2.2     
 [5] MASS_7.3-45        geosphere_1.5-1    gridBase_0.4-7     lattice_0.20-33   
 [9] rgdal_1.1-3        grid_3.2.2         nlme_3.1-124       KernSmooth_2.23-15
[13] coda_0.18-1        e1071_1.6-7        deldir_0.1-9       htmltools_0.3     
[17] rgeos_0.3-15       class_7.3-14       digest_0.6.9       RJSONIO_1.3-0     
[21] gridSVG_1.5-0      Matrix_1.2-3       osmar_1.1-7        RColorBrewer_1.1-2
[25] htmlwidgets_0.5    bitops_1.0-6       RCurl_1.95-4.7     sp_1.2-2          
[29] LearnBayes_2.15    boot_1.3-17        classInt_0.1-23    XML_3.98-1.3      
[33] svgPanZoom_0.3.0  
```

**Comment by behrica** [comment]
I tried to explicitely specify the colorNA, which does indeed work for the world and land data:

```
library(tmap)
data(World)
data(land)
qtm(World) + 
   tm_shape(land) + 
   tm_raster("trees",colorNA="#00000000")
```
![ex3](https://cloud.githubusercontent.com/assets/127361/13302520/892f35be-db4a-11e5-9f7f-7dc943e4a041.png)

But for my case (so using a RasterLayer instead of a SpatialGridDataFrame) it does not work.

**Comment by mtennekes** [comment]
Ah, I think you're using an older tmap version. Did you try the latest github version `install_github("mtennekes/tmap", subdir = "pkg")`?

A RasterLayer instead of a SpatialGridDataFrame should work:

    library(raster)
    land_raster_layer <- raster(land, layer="trees")

    qtm(World) +
    	tm_shape(land_raster_layer) + 
    	tm_raster("trees", alpha=1)

**Comment by behrica** [comment]
it works indeed with latest version.

Thanks.
