### ISSUE TITLE
tmap layer name

### ISSUE THREAD

**Issue by Hengshan** [mtennekes/tmap#481]
Hello, I am new to tmap and shiny. I appreicate if anyone can help with this.

I wonder whether each tm_shape command creates a new layer. If yes, whether we can assign a different name (not the first arg name of tm_shape) for the layer. 

For example, in the following code, I am trying to add a specific date data to tmap. The date was chosen by a select input using Shiny. The tricky part is that I can only add one layer, as all layers have the same name: dt_sales_shp %>%
                   filter(SaleYM==input$yearmonInput)). 
So I wonder how assign a layer name on the fly based on selectinput.

The second question is, whether tmap supports delete a layer by name. I know we an use zindex to remove a layer. But it seems only work for zindex =401. when I tried to change zindex -402, or 403, it doesn't work. Thanks

 observe({
    ym <- input$yearmonInput
    tmapProxy("plot_spatial_select", session, {
        tm_shape(**dt_sales_shp %>%
                   filter(SaleYM==input$yearmonInput))**+
        tm_dots(col="darkred")
    })
  })

  output$plot_spatial_select <- renderTmap({
    dt_sales_shp_ini <-
      dt_sales_shp %>%
      filter(SaleYM==max(dt_sales_shp$SaleYM))   

    tm_shape(subzone_join_shp) +
      tm_borders()+
      tm_shape(dt_sales_shp_ini)+
      tm_dots(col="darkred")
  })

**Comment by mtennekes** [comment]
`tm_shape` itself is not a layer, but a shape specification for one or more layers like `tm_polygons`.
Each of these layer functions has a `group` argument that refers to the layer id/grouping used in view mode.

As for your second question: removing layers by zindex should work. If not, make sure you are using the development (github) version of tmap. If that still doesn't work, please create a reproducible example.
