### ISSUE TITLE
problem installing the package

### ISSUE THREAD

**Issue by jucianom** [mtennekes/tmap#487]
I have a problem to install the tmap package.

When I try to install I get this error message:

Error: package or namespace load failed for ‘tmap’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘XML’

**Comment by Nowosad** [comment]
See a discussion at https://github.com/mtennekes/tmap/issues/150#issuecomment-659502024.
