### ISSUE TITLE
tmap/shiny remove layer issues

### ISSUE THREAD

**Issue by ScriptedChicken** [mtennekes/tmap#496]
Hi there,

I'm new to tmap and even newer to Shiny, so I hope that this question isn't a mistake on my part. I'm having problems with using tm_remove() with zindex, as the point data that should have been deselected still stays on the map. This is not an issue when using tmap_mode('view')  or tmap_mode('plot') outside of RShiny.

The map is of river clarity values in New Zealand, with both size and colour representing these values. In the example below the Canterbury region (the south island, east coast, with the little peninsula) is being selected. All other bubbles should have disappeared:

_When selecting all regions:_
![all_selected](https://user-images.githubusercontent.com/71040581/92649515-425b7280-f33f-11ea-9d91-05865a47a39b.PNG)

_When selecting just Canterbury region:_
![canterbury_selected](https://user-images.githubusercontent.com/71040581/92649519-44253600-f33f-11ea-925b-18ac9f38f7e1.PNG)

The code for testing this outside of RShiny can be seen below:

```
library(shiny)
library(ggplot2)
library(plotly)
library(dplyr)
library(tmap)
library(jsonlite)
library(geojsonsf)
library(httr)
library(sf)
library(RColorBrewer)
library('shinydashboard')
library("DT")

# load river quality point data
# 1) water clarity
water_clarity <- st_read("water-clarity-19892013.shp")

# 2) ammonical nitrogen
am_nitrogen <- st_read("ammoniacal-nitrogen-trends-19892013.shp")

# 3) nitrate nitrogen
nitrate_nitrogen <- st_read("nitratenitrogen-trends-19892013.shp")

# merge all together into one data set (subset by npID)
full_rivers <- rbind(water_clarity, am_nitrogen)
full_rivers <- rbind(full_rivers, nitrate_nitrogen)

# load polygon data for NZ regions
nz_regions <- st_read("regional-council-2020-generalised.gpkg")
nz_regions <- st_as_sf(nz_regions, coords = c("lat", "long"), crs = 2193)

# get and subset region names of NZ
# get the unique names of all regions
region_names <- unique(nz_regions$REGC2020_V1_00_NAME) 

# convert to char and exclude 'outside region'
region_names <- as.character(region_names[1:16]) 

# lookup table of region names, for referencing in the server 
# when a region is selected
region_lookup <- c("Manawatū-Whanganui Region" = "HRC",
                   "Greater Wellington Region" = "GWRC",
                   "Nelson Region" = "NRC",
                   "Taranaki Region" = "TRC",
                   "Marlborough Region" = "MDC",
                   "Hawke's Bay Region" = "HBRC",
                   "Auckland Region" = "AC",
                   "Otago Region" = "ORC",
                   "Canterbury Region" = "ECAN",
                   "Tasman Region" = "TDC",
                   "Southland Region" = "ES",
                   "Gisborne Region" = "GDC",
                   "Bay of Plenty Region" = "BOP",
                   "west Coast Region" = "WCRC",
                   "Waikato Region" = "EW")


river_names <- full_rivers %>%
  select("river") %>%
  st_set_geometry(NULL)
    
### Subset rivers by indicator ###
ID <- "CLAR"
mapTitle <- "Water Clarity"
popups <- c("Water Clarity" = "T_Median", 
            "Dominant Landcover Type" = "LANDCOVER",
            "Location" = "location")
var_rivers <- full_rivers %>% filter(npID == ID)
    
# use lookup table to get region code for selected region
region_code <- unname(region_lookup['Canterbury Region'])

# filter the river data to the selected region
region_rivers <- var_rivers %>% dplyr::filter(srcid == region_code)

# change the bbox to encompass only that region
bbox <- nz_regions %>% filter(REGC2020_V1_00_NAME == 'Canterbury Region')

# This works as expected outside of shiny, only showing 
# the point data according to the selected region.
tmap_mode('view')
tm_shape(region_rivers, bbox = st_bbox(bbox)) +
  tm_bubbles(size = "T_Median",
           col = "T_Median",
           title.col = mapTitle,
           popup.vars = popups,
           palette = "-RdBu",
           style = "pretty",
           alpha = 0.5,
           id = "river",
           zindex = 401)
```

The txt file for the full shiny application can be found here: 
[tmap_issues.txt](https://github.com/mtennekes/tmap/files/5204442/tmap_issues.txt)

Also, the version of tmap that is being used is 3.2.

Any help that could be offered would be greatly appreciated - I'm at a loss for why this is happening!

**Comment by mtennekes** [comment]
Thanks for issuing this.

I experienced problems with `tm_remove_layer` myself, but recently solved a few of them. Did you use the latest github version?
The tmap part of your shiny code looks correct. One minor tip which is unrelated to the issue: 

`tmap_options` is a global stand-alone function. Which you can call just after library(tmap). Alternatively, you can set the basemap during the plot call with `tm_basemap("Esri.OceanBasemap", group = "Canvas")`

Is it possible to send me the data objects so that I can reproduce the code?

**Comment by ScriptedChicken** [comment]
That was a fast reply! Yes, I'm using the latest github version with all suggested packages installed. Thanks for the extra tip as well - I'll put that to use.


[Scriptedchicken_issue_496.zip](https://github.com/mtennekes/tmap/files/5200113/Scriptedchicken_issue_496.zip)

**Comment by mtennekes** [comment]
I'm missing `nz_regions`.

**Comment by ScriptedChicken** [comment]
Ah, That is because the code was in the wrong order for some reason. The zip file contains `nz_regions`, but R was trying to manipulate/mutate the data before reading it from the file (using st_read()). The file 'tmap_issues.txt' in the original post has been updated to work correctly.

**Comment by mtennekes** [comment]
I already looked in the files for it, but didn't find it there either:

```r
> list.files("local/View Error Documentation/")
 [1] "all_selected.PNG"                            "ammoniacal-nitrogen-trends-19892013-ISO.pdf" "ammoniacal-nitrogen-trends-19892013.cpg"    
 [4] "ammoniacal-nitrogen-trends-19892013.dbf"     "ammoniacal-nitrogen-trends-19892013.prj"     "ammoniacal-nitrogen-trends-19892013.shp"    
 [7] "ammoniacal-nitrogen-trends-19892013.shx"     "ammoniacal-nitrogen-trends-19892013.txt"     "ammoniacal-nitrogen-trends-19892013.xml"    
[10] "ammoniacal-nitrogen-trends.pdf"              "canterbury_selected.PNG"                     "nitrate-nitrogen-trends.pdf"                
[13] "nitratenitrogen-trends-19892013-ISO.pdf"     "nitratenitrogen-trends-19892013.cpg"         "nitratenitrogen-trends-19892013.dbf"        
[16] "nitratenitrogen-trends-19892013.prj"         "nitratenitrogen-trends-19892013.shp"         "nitratenitrogen-trends-19892013.shx"        
[19] "nitratenitrogen-trends-19892013.txt"         "nitratenitrogen-trends-19892013.xml"         "regional-council-2020-generalised.gpkg"     
[22] "tmap_issues.r"                               "water-clarity-19892013.cpg"                  "water-clarity-19892013.dbf"                 
[25] "water-clarity-19892013.prj"                  "water-clarity-19892013.shp"                  "water-clarity-19892013.shx"
```

**Comment by ScriptedChicken** [comment]
The file name is `"regional-council-2020-generalised.gpkg"` - it is there in the file list. The problem is due to me writing bad code, I think. Please use the R file and data in the attached file called "full_project_issue_496". I have changed the shape files to geopackages to make the data less cluttered, plus made sure that the R code so that "regional-council-2020-generalised.gpkg" loads as ``nz_regions".
[full_project_issue_496.zip](https://github.com/mtennekes/tmap/files/5211065/full_project_issue_496.zip)

**Comment by mtennekes** [comment]
Thx! It should be fixed now. It not, please reopen this issue.

For the record, I created this (almost) minimal example to reproduce and solve the issue:

```r
require("shiny")

data(World)
world_vars <- setdiff(names(World), c("iso_a3", "name", "sovereignt", "geometry"))

ui <- fluidPage(
	tmapOutput("map"),
	selectInput("var", "Variable", world_vars),
	selectInput("cont", "Continent", c("all", levels(World$continent)))
)

server <- function(input, output, session) {
	output$map <- renderTmap({
		tm_shape(World) +
		tm_bubbles(size = "pop_est", col = world_vars[1], zindex = 401)
	})
	
	observe({
		var <- input$var
		cont <- input$cont
		
		if (cont != "all") {
			World_sel <- World[World$continent == cont, ]
		} else {
			World_sel <- World
		}
		
		tmapProxy("map", session, {
			tm_remove_layer(401) +
			tm_shape(World_sel) +
			tm_bubbles(size = "pop_est", col = var, zindex = 401)
		})
	})
}	

shinyApp(ui, server)

```

**Comment by ScriptedChicken** [comment]
Many thanks for the update and easy-to-reproduce example. :)

Unfortunately the problem is persisting, so I'll reopen the issue. Explanation and documentation will be provided there.
