### ISSUE TITLE
tmap/shiny remove layer issues (continued from #496)

### ISSUE THREAD

**Issue by ScriptedChicken** [mtennekes/tmap#498]
Hi again,

As documented in issue #496, tm_remove_layers is not removing some symbols from tmap correctly. Bubbles are removing correctly, so thank you for fixing that! Super helpful.

However, there is still a problem with marker removal; this can be see in the following pictures:

How the map looks on loading:
![all_selected](https://user-images.githubusercontent.com/71040581/93293130-61746b80-f83b-11ea-8232-4612f7cb3ddc.PNG)

Selecting an individual river the first time works fine:
![first_select](https://user-images.githubusercontent.com/71040581/93293141-66391f80-f83b-11ea-9ad4-1cfb86cd273c.PNG)

However, when selecting a different river the markers for the first do not remove:
_Note: The three points for the Clutha river are expected, as the data includes multiple test sites. The problem is removing the first selected river (Hoteo, in this example)._
![second_select](https://user-images.githubusercontent.com/71040581/93293149-69341000-f83b-11ea-83ee-b483c445ec4a.PNG)

tmap version is 3.2, tmaptools version is 3.1.

As before, any help would be much appreciated.

Code and data:
[scriptedchicken_issue_498.zip](https://github.com/mtennekes/tmap/files/5229729/scriptedchicken_issue_498.zip)

**Comment by mtennekes** [comment]
Thx! I've checked, but the river-markers seem to disappear correctly here:

![Screenshot from 2020-09-18 09-15-05](https://user-images.githubusercontent.com/2444081/93567855-97c2ff80-f98f-11ea-85e1-09239512ada4.png)

Did you try the cran version 3.2, released two days ago?

**Comment by ScriptedChicken** [comment]
Sorry for the delay in replying! I've spent some time looking into this, as I wanted to make sure that I wasn't doing anything silly on my end. As it turns out I won't be able to install the latest version of tmap as I get an error message saying that `Rtools is required to build R packages but is not currently installed`. Unfortunately our coursework requires R version 3.6, and Rtools is only available on version 4.

I'll close the issue for now, as I think that this is causing the issue. Many thanks, once again!

**Comment by tim-salabim** [comment]
Rtools is available for all R releases. Rtools40 is just for the current R release. You can download older versions here:

https://cran.r-project.org/bin/windows/Rtools/history.html

**Comment by stragu** [comment]
I am having a similar issue: using `tm_dots()` and `tm_bubbles()`, the previous layer is removed. However, using `tm_markers()`, the previous markers remain despite using `tm_remove_layer()` on the correct `zindex`.

Using R 4.4.2 and tmap 3.3-4.

An minimal example:

```r
library(shiny)
library(tmap)
library(sf)

# create initial point data
click_point <- st_point(c(0, 0))
click_sf <- st_sfc(click_point, crs = "WGS84")

# UI
ui <- fluidPage(
  tmapOutput("map")
)

server <- function(input, output, session) {
  # draw tmap
  output$map <- renderTmap({
    tm_shape(click_sf) +
      tm_markers(zindex = 401)
  })
  
  # observe click, remove and redraw only layer
  observeEvent(input$map_click, {
    click_point <- st_point(c(input$map_click$lng, input$map_click$lat))
    click_sf <- st_sfc(click_point, crs = "WGS84")
    tmapProxy("map", session, {
      tm_remove_layer(401) +
        tm_shape(click_sf) +
        tm_markers(zindex = 401)
    })
  })
}	

shinyApp(ui, server)
```

Run the app, click on the map: the previous marker(s) remain.
If you replace both `tm_markers()` calls with either `tm_dots()` or `tm_bubbles()`, the removal does work. So something special about markers?

I guess I should test tmap4.

**Comment by stragu** [comment]
Ah, turning clustering off with `clustering = FALSE` in `tmap_markers()` makes it work as expected in my example!
Maybe a hint for a potential fix, if at all needed for tmap4?
