### ISSUE TITLE
Logarithmic scales improvements

### ISSUE THREAD

**Issue by Nowosad** [mtennekes/tmap#499]
I've been testing some color styles in **tmap** recently and found two issues (?) with logarithmic scales (see examples in the code below).
The first issue is related to the number and values of breaks when logarithmic scales are used. 
For example, `gdpPercap` variable has breaks of `1,000`, `3,162`, `10,000`, `31,623`, etc. 
Shouldn't it be just  `1,000`, `10,000`, etc.?
The second issue occurs when the input variable is not very skewed (e.g., `lifeExp`) - then the logarithmic scales do not work at all.
I would probably expect a warning here, stating that "the use logarithmic scale is not possible for this variable; some other style was used instead".

``` r
library(tmap)
library(spData)

# issue 1
tm_shape(world) +
  tm_polygons("gdpPercap", style = "log10")
#> Linking to GEOS 3.8.1, GDAL 3.0.4, PROJ 6.3.2
```

![](https://i.imgur.com/rtweBse.png)

``` r
tm_shape(world) +
  tm_polygons("gdpPercap", style = "log10_pretty")
#> Warning: non-rounded breaks occur, because style = "log10_pretty" is designed
#> for large values
```

![](https://i.imgur.com/de237Lk.png)

``` r

# issue 2
tm_shape(world) +
  tm_polygons("lifeExp", style = "log10")
```

![](https://i.imgur.com/P3OzO7F.png)

``` r
tm_shape(world) +
  tm_polygons("lifeExp", style = "log10_pretty")
#> Warning: non-rounded breaks occur, because style = "log10_pretty" is designed
#> for large values
```

![](https://i.imgur.com/NI2qPbA.png)

<sup>Created on 2020-09-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mtennekes** [comment]
``` r
# issue 1
tm_shape(world) +
    tm_polygons("gdpPercap", style = "log10")
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1
```

![](https://i.imgur.com/xacS0Ws.png)

``` r

tm_shape(world) +
    tm_polygons("gdpPercap", style = "log10_pretty")
```

![](https://i.imgur.com/hx4Y112.png)

``` r

# issue 2
tm_shape(world) +
    tm_polygons("lifeExp", style = "log10")
```

![](https://i.imgur.com/4N9K8Sa.png)

``` r

tm_shape(world) +
    tm_polygons("lifeExp", style = "log10_pretty")
```

![](https://i.imgur.com/EmXGoT8.png)

<sup>Created on 2020-10-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Please review and reopen if necessary.

**Comment by Nowosad** [comment]
The examples looks great. Where can I find the updated code? It does not seem to be on github..

**Comment by mtennekes** [comment]
Now it is:-)

**Comment by Nowosad** [comment]
Awesome
