### ISSUE TITLE
tmap installation failed until I manually installed Shiny

### ISSUE THREAD

**Issue by smach** [mtennekes/tmap#50]
FYI I have used tmap with no problem on 2 other systems, but when I tried to install it on a fresh R installation,  the tmap install failed saying there was no package "shiny." Maybe that should be added to the package dependencies? Installation worked fine after I first manually installed shiny.

I really like the tmap package and am looking forward to any work you do on interactive maps! 

Thanks.

**Comment by mtennekes** [comment]
Thanks for your message. Strange, since I've never used `shiny` for `tmap`. Which version did try to you install?

**Comment by smach** [comment]
CRAN with install.packages(). I was installing a lot of packages at once so perhaps some dependencies got crossed, but it was the message for installing tmap and it worked fine afterwards. Not a big deal, if it happens to anyone else they'll know what to do :-) Just thought I'd mention it.
