### ISSUE TITLE
'headtails' style does not work according to the 'n' argument in tm_lines (or tm_polygons)

### ISSUE THREAD

**Issue by xiaofanliang** [mtennekes/tmap#501]
Here is a test example. I want to color the line based on the style "headtails" and define the number of classes to 4 (n=4). However, the classes show up do not correspond to the `n` argument. I tried out on the style quantile and it works fine. I can go around by calculating the breaks for headtails and used style 'fixed' to define the breaks, but that defeats the purpose of the argument `style`. Is it my operation mistake or a bug in the code? 

Here is an example that works with the style 'quantile'.
```
data(rivers)

#assigning a column of exponential values for headtail style coloring. 
rivers = rivers %>% mutate(exp_distribution_samples = rexp(nrow(rivers), rate = 1))

tm_shape(rivers) + 
  tm_lines(col = 'exp_distribution_samples', style="quantile", n = 4)
```
![Screen Shot 2020-09-22 at 9 40 39 PM](https://user-images.githubusercontent.com/22874361/93954719-48c4f380-fd1c-11ea-8417-57d793748232.png)

```
data(rivers)

#assigning a column of exponential values for headtail style coloring. 
rivers = rivers %>% mutate(exp_distribution_samples = rexp(nrow(rivers), rate = 1))

tm_shape(rivers) + 
  tm_lines(col = 'exp_distribution_samples', style="quantile", n = 3)
```
![Screen Shot 2020-09-22 at 9 41 12 PM](https://user-images.githubusercontent.com/22874361/93954908-9b9eab00-fd1c-11ea-8676-50cceddfe14c.png)

Here are examples using 'headtails' style and the class number did not change:

```
data(rivers)
#assigning a column of exponential values for headtail style coloring. 
rivers = rivers %>% mutate(exp_distribution_samples = rexp(nrow(rivers), rate = 1))
tm_shape(rivers) + 
  tm_lines(col = 'exp_distribution_samples', style="headtails", n = 4)
```
![Screen Shot 2020-09-22 at 9 41 26 PM](https://user-images.githubusercontent.com/22874361/93954941-b07b3e80-fd1c-11ea-916e-727de60a6c83.png)

```
data(rivers)
#assigning a column of exponential values for headtail style coloring. 
rivers = rivers %>% mutate(exp_distribution_samples = rexp(nrow(rivers), rate = 1))
tm_shape(rivers) + 
  tm_lines(col = 'exp_distribution_samples', style="headtails", n = 3)
```
![Screen Shot 2020-09-22 at 9 41 36 PM](https://user-images.githubusercontent.com/22874361/93954986-c8eb5900-fd1c-11ea-9ccf-956bdb936588.png)

**Comment by mtennekes** [comment]
I think that for `style = "headtails"`, the number of classes `n` is the *preferred*  number of classes.

The underlying code is:

``` r
x = rexp(1616, rate = 1)
classInt::classIntervals(x, n=3, style = "headtails")
#> style: headtails
#> [0.003596569,0.9662782)    [0.9662782,1.963183)     [1.963183,2.978586) 
#>                    1040                     366                     134 
#>     [2.978586,4.058808)     [4.058808,5.287042)     [5.287042,6.507469) 
#>                      50                      16                       5 
#>     [6.507469,7.756934] 
#>                       5
```

@rsbivand: can you confirm this?

**Comment by xiaofanliang** [comment]
I can control the number of breaks from classInt 'headtails' by adjusting the `thr` argument until the breaks show up fits my intended `n`. I am not sure if this is something that you want to implement at this point since the algorithm has to iterative tested out different values of `thr` until you find the intended `n`. Right now I work around this by just using fixed breaks from a skewed quantile (e.g., c(0, 0.5, 0.8, 0.9, 0.99)).

**Comment by rsbivand** [comment]
Yes, `"headtails"` like `"pretty"` and `"sd"` does not have to keep to `n=`. Perhaps the documentation https://r-spatial.github.io/classInt/reference/classIntervals.html needs to be even clearer.
