### ISSUE TITLE
Implement Edge Arc 

### ISSUE THREAD

**Issue by xiaofanliang** [mtennekes/tmap#504]
This is part of a series of issues (#503 #505) I raised for mapping spatial networks using tmap. When mapping spatial social networks, often time there will be a lot of edges crossing over each other, and even after adjusting for transparency and color, they cannot stand out from each other. Edge arc will be helpful to curve the edges and reduce the edge clutter. It is a pretty mature technique in ArcGIS and other mapping software. 

(An example of the mess without curving)
![04-edges-1](https://user-images.githubusercontent.com/22874361/94729901-67387980-0330-11eb-94bf-033157c69015.png)

The function I am looking for is something similar to `geom_curve` (example [here](https://ggplot2.tidyverse.org/reference/geom_segment.html) and [here](https://www.r-bloggers.com/2018/05/three-ways-of-visualizing-a-graph-on-a-map/)) in ggplot2. Maybe it can be a new function called `tm_curve()` or an additional argument in `tm_line()`. This will be a great addition for mapping network type map in tmap. 

This is an example with edge arc and edge directionality implemented map. 
<img width="525" alt="thanksgiving-flight-patterns-1448336773738-facebookJumbo" src="https://user-images.githubusercontent.com/22874361/94731202-6274c500-0332-11eb-8213-9b7ec955363c.png">

Thanks!

**Comment by mtennekes** [comment]
This is outside the scope of `tmap`, since it modifies spatial data.
However.... @Robinlovelace and I are working on an origin-destination data package.

Currently we have two prototypes, which we will merge):
https://github.com/ITSLeeds/od
https://github.com/mtennekes/odf
(Issue about the merge: https://github.com/ITSLeeds/od/issues/20)

The curved edges are already implemented.

**Comment by xiaofanliang** [comment]
@mtennekes Thanks. Just for clarification, do you mean the curved edges are already implemented in `tmap` or `od` package (or implemented in the upcoming merge)?

**Comment by xiaofanliang** [comment]
Thanks for pointing out the od package! I did not realize that it exists!

**Comment by mtennekes** [comment]
You're welcome!

Currently, it is in the `odf` package (https://github.com/mtennekes/odf, see its vignette), but this will be merged with the `od` package.
