### ISSUE TITLE
Implement Edge Bundling 

### ISSUE THREAD

**Issue by xiaofanliang** [mtennekes/tmap#505]
This is part of a series of issues (#503 #504) I raised for mapping spatial networks using tmap. Edge bundling is an important technique to reduce edge clutters. It curves the edges that are going to the same directions and summarized the weights to make the "combined" edge wider. Here is an example of what it looks like: 

Without Bundle:
![Screen Shot 2020-09-30 at 3 44 07 PM](https://user-images.githubusercontent.com/22874361/94732120-d794ca00-0333-11eb-87a2-84c582180113.png)

With Bundle 
![Screen Shot 2020-09-30 at 3 44 13 PM](https://user-images.githubusercontent.com/22874361/94732122-d82d6080-0333-11eb-9be9-d9c325a09e2d.png)

This may be harder to implement than arc and directionality because it involves more than just changing the aesthetics of the edges. What I am looking for is a function similar to `geom_conn_bundle` (reference [here](https://rdrr.io/cran/ggraph/man/geom_conn_bundle.html)) in the `ggraph` package or the equivalent of `dashshader` package (reference [here](https://github.com/ropensci/ozunconf17/issues/1) and [here](https://stackoverflow.com/questions/61333273/how-to-use-edge-bundling-with-networkx-and-matplotlib-in-python)) in Python/Networkx. 

Out of all three issues raised, I will prefer to have the arc and directionality problem solved then this one, but this will be really nice to have and if done will exceed all other packages at mapping spatial networks. 

Thanks!

**Comment by mtennekes** [comment]
Same answer as #504

As you mention, this one is very hard to implement, as there are many algorithms. It would be great if we could reuse one. But again, this is outside the scope of `tmap`.

**Comment by xiaofanliang** [comment]
Just want to say that I figured out a way to use edge bundling through another package called "edgebundle" and use `tmap` to visualized the exported shapefiles! https://github.com/schochastics/edgebundle/issues/4

**Comment by mtennekes** [comment]
Excellent! In tmap4 there will be a possibility to implement such extensions, e.g. via the layer function `tm_edgebundle`.
