### ISSUE TITLE
Error in if (any(zeros)) { missing value where TRUE/FALSE needed - trying to map the Antarctic

### ISSUE THREAD

**Issue by Federicoaluciani** [mtennekes/tmap#506]
I've been working for many time with tmap tool in r and have been learning a lot with my country's shape with multipolygons with provinces boundaries, Argentina (https://ramsac.ign.gob.ar/api/v1/capas-sig/Geodesia+y+demarcaci%C3%B3n/L%C3%ADmites/provincia/shp).

Suddenly, the maps couldn't run anymore, with the message: "Error in if (any(zeros)) { where TRUE/FALSE needed".

I tried to see which was the problem, so i tried to simplify by mapping:

```
library(tmap)
library(sf)

provIGN=st_read('provincia.shp')

tm_shape(provIGN)+tm_polygons()
#Got the same error
```

Then I localized that the problem was with one province, so i was able to graph the whole map except that particular province (Tierra del Fuego, Antártida e Islas del Atlántico Sur) by:

```
tm_shape(subset(provIGN,nam!="Tierra del Fuego, Antártida e Islas del Atlántico Sur"))+tm_polygons()
#Got the graph of Argentina without the problematic province.
```

I was able to get another shapefile of Argentina, where the limits where not the provinces but the departments (provinces > departments) and I could graph the whole country except the Antarctic department.

I could graph the entire country with no problems using QGIS 3.14

So finally i could solve the issue by installing the previous version of the ´tmap´ package (3.0).

Hope this helps other users and the development team, or if someone can tell me how to solve the issue without using the previous version.

Thank you!

**Comment by mtennekes** [comment]
Have you tried the GitHub version of tmap? I fixed a bug this morning which could be the cause. If, not I'll have a better look tomorrow.

**Comment by Federicoaluciani** [comment]
Oh, thank you very much, I've installed the package with:

`library(remotes)
install_github("mtennekes/tmaptools")
install_github("mtennekes/tmap")`

and it works fine!
