### ISSUE TITLE
Automatic selection of the color palette when the midpoint is specified

### ISSUE THREAD

**Issue by Nowosad** [mtennekes/tmap#507]
Currently, the color palette stays the same (the colors are slightly brighter) when the midpoint is specified. How about change this behaviour to automatically use of some diverging color palette in those cases?

``` r
library(tmap)
library(spData)

# without specified midpoint
tm_shape(world) +
  tm_polygons(col = "lifeExp")
#> Linking to GEOS 3.8.1, GDAL 3.0.4, PROJ 6.3.2
```

![](https://i.imgur.com/HF0mjZP.png)

``` r

# with specified midpoint
tm_shape(world) +
  tm_polygons(col = "lifeExp", midpoint = 70)
```

![](https://i.imgur.com/7IDrwov.png)

<sup>Created on 2020-10-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mtennekes** [comment]
That makes sense. It's implemented, please review.

**Comment by Nowosad** [comment]
Awesome. Test results:

``` r
library(tmap)
library(spData)

# without specified midpoint
tm_shape(world) +
  tm_polygons(col = "lifeExp")
#> Linking to GEOS 3.8.1, GDAL 3.0.4, PROJ 6.3.2
```

![](https://i.imgur.com/dcwWEHH.png)

``` r

# with specified midpoint
tm_shape(world) +
  tm_polygons(col = "lifeExp", midpoint = 70)
```

![](https://i.imgur.com/7UytnC8.png)

<sup>Created on 2020-10-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
