### ISSUE TITLE
Hi I have 3 diferent maps and I want to show them alltogether. Thus I perform the tm_arrange function and it works properly.

### ISSUE THREAD

**Issue by PauGallesClara** [mtennekes/tmap#511]

**Comment by PauGallesClara** [comment]
Hi I have 3 diferent maps and I want to show them alltogether. Thus I perform the tm_arrange function and it works properly. But now I want to add a main title in common for the three maps. For that porpouse I'm using  the next script
`tmap_arrange (map_IA14D, map_IA14H, map_IA14T) 
tmap_arrange (map_IA14D, map_IA14H, map_IA14T, outer.margins = NULL) + tm_layout(main.title = " IA14 del 7 al 20 de setembre ")
`
The first  tmap_arrange is the one that works. But when I add the tm_layout I get the next error message:
"Error in tmap_arrange(map_IA14D, map_IA14H, map_IA14T, outer.margins = NULL) +  : 
  argumento no-numérico para operador binario" 

Thank you!!

**Comment by PauGallesClara** [comment]
Sorry, I haven't pase properly the code.
It should be as it follows:
`tmap_arrange (map_IA14D, map_IA14H, map_IA14T)`   This one works (whithout the title)
`tmap_arrange` (map_IA14D, map_IA14H, map_IA14T, outer.margins = NULL) + tm_layout(main.title = " IA14 del 7 al 20 de setembre `")`  This one doesn't

**Comment by Nowosad** [comment]
@PauGallesClara please create a reproducible example (https://www.tidyverse.org/help/). It will help us help you.

**Comment by mtennekes** [comment]
It's not possible to add a main title to `tmap_arrange`, since `tmap_arrange` only combines tmap plots (nothing more).
A workaround is something like this:

``` r
library(tmap)
data(World)
tm1 <- qtm(World, fill = "HPI") + tm_layout(main.title = "Test")
tm2 <- qtm(World, fill = "well_being")
tm3 <- qtm(World, fill = "economy")

tmap_arrange(tm1, tm2, tm3, outer.margins = 0, ncol = 1)
```

![](https://i.imgur.com/WyA0WKN.png)

<sup>Created on 2020-10-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Agree with @Nowosad suggestion to use a reproducible example next time. Also recommended to use `reprex` so that we can see the output directly in github.

**Comment by Nowosad** [comment]
@mtennekes also related - https://github.com/mtennekes/tmap/issues/338. Complete `tmap_grob()` function could help with this issue.

**Comment by PauGallesClara** [comment]
Hi !! I've been playing with your recomendations.
As it happens with the 3 world maps made by @mtennekes, the one that has the main title is a bit different than the others. So, I'm afraid that It's not a good option. Is there any way to fix that?
I've also tried the tmap_grob() without luck!!
I've decided to keep it without a main tittle

Sorry, for not being more clear with the sintax and the resulting maps, but I'm not sure that I can publish this kind of data yet. (Hope you understand). But in any case your advices have been very helpful!!

Many Thanks,
Pau

**Comment by Nowosad** [comment]
Hi Pau,
an alternative approach to this problem would be to use the **grid** package:

``` r
library(tmap)
library(grid)
data(World)
tm1 <- qtm(World, fill = "HPI")
tm2 <- qtm(World, fill = "well_being")
tm3 <- qtm(World, fill = "economy")

# by rows -----------------------------------------------------------------
grid.newpage()
pushViewport(viewport(layout = grid.layout(
        nrow = 4,
        ncol = 1,
        heights = c(0.1, 0.3, 0.3, 0.3))))
grid.text("Title", vp = viewport(layout.pos.row = 1))
print(tm1, vp = viewport(layout.pos.row = 2))
print(tm2, vp = viewport(layout.pos.row = 3))
print(tm3, vp = viewport(layout.pos.row = 4))
#> Legend labels were too wide. The labels have been resized to 0.46, 0.40, 0.44, 0.44, 0.46, 0.54, 0.43. Increase legend.width (argument of tm_layout) to make the legend wider and therefore the labels larger.
```

![](https://i.imgur.com/6ifDMTQ.png)

``` r

# by cols -----------------------------------------------------------------
grid.newpage()
pushViewport(viewport(layout = grid.layout(
        nrow = 2,
        ncol = 3,
        heights = c(0.1, 0.9))))
grid.text("Title", vp = viewport(layout.pos.row = 1, layout.pos.col = 1:3))
print(tm1, vp = viewport(layout.pos.row = 2, layout.pos.col = 1))
print(tm2, vp = viewport(layout.pos.row = 2, layout.pos.col = 2))
print(tm3, vp = viewport(layout.pos.row = 2, layout.pos.col = 3))
#> Legend labels were too wide. The labels have been resized to 0.35, 0.30, 0.33, 0.33, 0.35, 0.40, 0.32. Increase legend.width (argument of tm_layout) to make the legend wider and therefore the labels larger.
```

![](https://i.imgur.com/zlpeywk.png)

<sup>Created on 2020-10-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by PauGallesClara** [comment]
Hi  !!

With your recomendations now I have different solutions, now I must choose the one  it fits better.

Many thanks!!
