### ISSUE TITLE
I'm having problems with the attr.outside.position setting

### ISSUE THREAD

**Issue by francisbarton** [mtennekes/tmap#512]
I'm very sorry I am really busy today and don't have time to prepare a reprex - but I will provide one as soon as I can.

I have map where I am adding various elements:
`tm_credits`, `tm_scale_bar` and `tm_compass`.

I am having difficulty getting them to obey their position attributes; specifically, they are all being displayed at the bottom of the map. I would like the credits and scale bar to be displayed outside the map at the bottom, and the compass to be displayed inside the map frame, and at the top.

 I have `attr.outside` set to `TRUE`.
If I set `attr.outside.position = "TOP"` within `tm_layout`, I get an error:

```r
Error in grid.Call(C_convert, x, as.integer(whatfrom), as.integer(whatto),  : 
  Viewport has zero dimension(s)
```
and no map is produced.
If I set `attr.outside.position = c("right", "top")` within `tm_layout`, I get a warning:
```r
Warning messages:
1: In if (ext_attr_pos == "top") { :
  the condition has length > 1 and only the first element will be used
2: In if (attr.between.legend.and.map) { :
  the condition has length > 1 and only the first element will be used
```
and the elements remain at the bottom.

**Comment by mtennekes** [comment]
It's not possible to show some attributes in the map and others outside at the same time, but there are work arounds for that.
I'll wait for a reproducible example to dive into the error messages.

**Comment by francisbarton** [comment]
OK I've managed to make a reprex that gives the error message I reported last week.
I'm not saying that `tmap` is doing anything wrong here! More likely there's something I'm not understanding, or I haven't read the docs properly 😬.

I think I had assumed that `attr.outside.position` would be a way of setting a default position for attrs, with more specific position details being possible to set on each one, as needed. But it seems like `attr.outside.position` is just "do you want them above or below the plot?"

I'd like to be able to set the compass to "top, right"; the scale bar to "centre, bottom", the credits to "left, bottom" and have them all within the plot, but sufficiently spaced so they don't overlap the map. However I was finding that they always overlapped the map itself, so I tried to move them outside - then I get this:

``` r
library(dplyr, warn.conflicts = FALSE)
library(tmap)

data("World")

tmap_options(
  attr.outside = TRUE,
  outer.margins = 0
)

tmap_design_mode(design.mode = TRUE)
#> design.mode: ON
tmap_mode("plot")
#> tmap mode set to plotting

m <- World %>% 
  dplyr::filter(name %in% c("Denmark", "United Kingdom", "Netherlands", "Ireland")) %>% 
  tm_shape() +
  tm_fill("well_being")

m +
  tm_layout(
    attr.outside.position = "bottom",
    ) +
  tm_credits(
    "made with tmap",
    size = 0.8,
    position = c("left", "BOTTOM")) +
  tm_scale_bar(
    text.size = 0.6,
    width = 0.25,
    position = c("center", "BOTTOM")) +
  tm_compass(
    size = 1.5,
    position = c("right", "top"))
#> ----------------aspect ratios-----------------------
#> | specified (asp argument of tm_layout)         NA |
#> | device (yellow)                         1.400000 |
#> | device without outer margins (green)    1.400000 |
#> | frame (blue)                            2.160263 |
#> | master shape, ., (red)                  2.160263 |
#> ----------------------------------------------------
```

![](https://i.imgur.com/ddQDSGe.png)

``` r
  

m +
  tm_layout(
    attr.outside.position = "top",
  ) +
  tm_credits(
    "made with tmap",
    size = 0.8,
    position = c("left", "BOTTOM")) +
  tm_scale_bar(
    text.size = 0.6,
    width = 0.25,
    position = c("center", "BOTTOM")) +
  tm_compass(
    size = 1.5,
    position = c("right", "top"))
#> ----------------aspect ratios-----------------------
#> | specified (asp argument of tm_layout)         NA |
#> | device (yellow)                         1.400000 |
#> | device without outer margins (green)    1.400000 |
#> | frame (blue)                            2.160263 |
#> | master shape, ., (red)                  2.160263 |
#> ----------------------------------------------------
#> Error in grid.Call(C_convert, x, as.integer(whatfrom), as.integer(whatto), : Viewport has zero dimension(s)
```

![](https://i.imgur.com/7HDdRdd.png)

<sup>Created on 2020-10-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by francisbarton** [comment]
Hi Martijn,
Please can you have a look at the reprex above and let me know what you think?
It seems like it's not possible to have the compass outside and above the plot, while having the scale bar and caption outside the plot and below it.
Thank you.

**Comment by mtennekes** [comment]
Placement of attributes/legend outside the map is indeed very limited. I'm not planning to fix this soon, since there will be a major update early next year.

I would recommend to draw the attributes inside the map, and set the inner margins sufficiently large.
