### ISSUE TITLE
One logo per polygon

### ISSUE THREAD

**Issue by Kibria2017** [mtennekes/tmap#513]
Hi, 

Can we load a logo in the polygon? For example, I want to insert the logo of the "World AIDS Day" into the priority districts. I didn't find anything in your documentation. Could you introduce this feature?

Thanks,
kibria

**Comment by mtennekes** [comment]
Yes, please take a look at the documentation of `tm_symbols`. A logo is nothing more than a (proportional) symbol. See the second last example of `tm_symbols`, in which airplane icons are used. This will work with polygons as well, since then centroid points are used for the position of the icons.

**Comment by Kibria2017** [comment]
Thanks, a lot!
