### ISSUE TITLE
Categorical Raster Legend Issue and Warning

### ISSUE THREAD

**Issue by ailich** [mtennekes/tmap#516]
When plotting categorical rasters I get a warning about x being NULL. Additionally, if values for classes don't start at 1 (which can be the case if you are subsetting an area or if you are stacking maps to get the unique combinations of 2 categorical raster layers), it adds NA as a class to the legend and says there are duplicated levels. Following the example from issue #204 

```
#Rversion 3.6.3, tmap version 3.1
library(raster)
library(tmap)
library(spData)
data("grain")

tm_shape(grain) + 
  tm_raster() 
Warning message:
In rep(attr(shp[[1]], "colors"), length.out = length(lvls)) :
  'x' is NULL so the result will be NULL
```
![Rplot1](https://user-images.githubusercontent.com/28163862/96911279-a5781300-146e-11eb-9778-e28020d6b241.png)
```
grain2<- as.factor(grain*10)
levels(grain2)[[1]]$VALUE<- levels(grain)[[1]]$VALUE
tm_shape(grain2) + 
  tm_raster() 
Warning messages:
1: In rep(attr(shp[[1]], "colors"), length.out = length(lvls)) :
  'x' is NULL so the result will be NULL
2: Duplicated levels found. They have been omitted 
```
![Rplot2](https://user-images.githubusercontent.com/28163862/96911125-69dd4900-146e-11eb-981d-25e2987fd99d.png)

**Comment by Nowosad** [comment]
Dear @ailich as you mentioned, you are using **tmap** version 3.1. Have you tried the current version 3.2 (https://cran.r-project.org/package=tmap) or even the development github version?

**Comment by ailich** [comment]
@Nowosad, sorry about not using the latest version. I updated to the development version, and the x is NULL issue no longer persists, but I still get the warning about duplicated levels and the NA in the legend for the second plot.

**Comment by Nowosad** [comment]
The second issue seems to be related to the **stars** package. (The **tmap** package uses **stars** to handle raster data) 

I think you could ask about this issue in the **stars** issue tracker.

``` r
library(stars)
#> Loading required package: abind
#> Loading required package: sf
#> Linking to GEOS 3.8.1, GDAL 3.0.4, PROJ 6.3.2
library(spData)
library(raster)
#> Loading required package: sp
data("grain")

grain2 <- as.factor(grain*10)
levels(grain2)[[1]]$VALUE <- levels(grain)[[1]]$VALUE

st_as_stars(grain)
#> stars object with 2 dimensions and 1 attribute
#> attribute(s):
#>   layer   
#>  clay:12  
#>  silt:12  
#>  sand:12  
#> dimension(s):
#>   from to offset delta                       refsys point values x/y
#> x    1  6   -1.5   0.5 +proj=longlat +datum=WGS8...    NA   NULL [x]
#> y    1  6    1.5  -0.5 +proj=longlat +datum=WGS8...    NA   NULL [y]
st_as_stars(grain2)
#> stars object with 2 dimensions and 1 attribute
#> attribute(s):
#>      layer   
#>  clay   :12  
#>  silt   :12  
#>  sand   :12  
#>  NA     : 0  
#>  NA     : 0  
#>  NA     : 0  
#>  (Other): 0  
#> dimension(s):
#>   from to offset delta                       refsys point values x/y
#> x    1  6   -1.5   0.5 +proj=longlat +datum=WGS8...    NA   NULL [x]
#> y    1  6    1.5  -0.5 +proj=longlat +datum=WGS8...    NA   NULL [y]
```

<sup>Created on 2020-10-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ailich** [comment]
Ok, thanks. I'll look into this a bit and then post it over there.

**Comment by ailich** [comment]
@Nowosad, stars apparently handles factors a bit differently than raster. Currently it would need to be plotted as
`tm_shape(droplevels(st_as_stars(grain2))) + tm_raster()`, but edzer from the stars package mentioned that maybe a call to droplevels should be added internally into stars or tmap's plotting routines for categorical rasters.

https://github.com/r-spatial/stars/issues/339

**Comment by mtennekes** [comment]
Hmm, difficult one. The reason for the `NA` levels,

```{r}
grain2_stars <- st_as_stars(grain2)
levels(grain2_stars[[1]])
#> [1] NA     NA     NA     NA     NA     NA     NA     NA     NA     "clay" NA     NA     NA     NA     NA     NA     NA     NA     NA    
#> [20] "silt" NA     NA     NA     NA     NA     NA     NA     NA     NA     "sand"
```

, is that for the integer values go up to 30, 30 levels are expected, while only 3 have been defined (clay=10, silt=20, sand=30).

There already was a `drop.levels` argument, which works for this case.

```{r}
tm_shape(grain2) + tm_raster(drop.levels = TRUE)
```

The only thing I am not satisfied with, is that in the original map (`tm_shape(grain2) + tm_raster()`) the NA values are not treated as missing values; normally missing values should be shown with a different color as the last 'category'.
