### ISSUE TITLE
Static view only displays one polygon

### ISSUE THREAD

**Issue by idduerr** [mtennekes/tmap#517]
After updating my R spatial packages I have been having a very odd error that I can't seem to get rid of. When I run my previous code which used to create maps with multiple polygons I now only see one polygon (whichever is the first row in the shapefile) while the rest do not display. I have also found that if I switch into interactive mode all the polygons display correctly. 

I have tried reinstalling both the tmap package (version 3.2) and its dependencies but nothing resolves the error. I have updated versions of gdal (GDAL 3.1.2), geos (3.8.1), and proj (7.1.1) and my other spatial packages all seem to be running fine.

##R specs:

platform       x86_64-apple-darwin15.6.0   
arch           x86_64                      
os             darwin15.6.0                
system         x86_64, darwin15.6.0        
status                                     
major          3                           
minor          5.2                         
year           2018                        
month          12                          
day            20                          
svn rev        75870                       
language       R                           
version.string R version 3.5.2 (2018-12-20)
nickname       Eggshell Igloo              

##Example code

Should create a map of all the precincts in one county with labels. Now creates only borders for one precinct (X029) but labels for all precincts. Note that precinct X029 is the first row of my shapefile. In other tests the first row in the shapefile is consistently the only one displayed. Error occurs similarly when using tm_fill instead of tm_borders.

```R
library(tmap)
library(sf)
shp_file <- st_read("fl.shp") #reads in shapefile, error occurs with other shapefiles / loading functions

shp_file_red <- shp_file %>%
  filter(county %in% c("BRO")) #Removes all but one county for simplicity, also doesn't effect error

tm1 <-tm_shape(shp_file_red) + 
  tm_borders() +
  tm_text("pct", size = 0.4, col = "black", shadow = T)+
  tm_layout(legend.position = c(0,0.6),
            inner.margins = c(.03,.07,.03,.03),
            legend.frame = F) 
tm1 
```

![image](https://user-images.githubusercontent.com/69167803/97049097-1c81da00-1549-11eb-814a-441ac39829d5.png)

switching to interactive mode causes the same code to display all precinct polygons

```R
ttm() # switch to interactive mode

tm1 <-tm_shape(shp_file_red) + 
  tm_borders() +
  tm_text("pct", size = 0.4, col = "black", shadow = T)+
  tm_layout(legend.position = c(0,0.6),
            inner.margins = c(.03,.07,.03,.03),
            legend.frame = F) 
tm1 
```
<img width="369" alt="Screen Shot 2020-10-23 at 4 11 00 PM" src="https://user-images.githubusercontent.com/69167803/97049889-6919e500-154a-11eb-96cb-23b6ecdd4568.png">

**Comment by Nowosad** [comment]
@idduerr two ideas:
- Could you update your R version? (The current one is 4.0.3)
- Could you share your shapefile with us?

**Comment by idduerr** [comment]
> @idduerr two ideas:
> 
>     * Could you update your R version? (The current one is 4.0.3)
> 
>     * Could you share your shapefile with us?

Updating R (went to 4.0.3) did it! This weird error has been bugging me for awhile now and I love the tmap package so having it working again is fantastic. 

Thanks for the quick response and the easy fix!

PS - if you (or anyone else who comes across this post) still want the shapefiles I used above you can get em here: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/NH5S2I

**Comment by Nowosad** [comment]
Awesome!
