### ISSUE TITLE
Suggestion: categorical palette when the style = "cat"

### ISSUE THREAD

**Issue by Nowosad** [mtennekes/tmap#518]
**tmap** uses the Set3 palette to color objects when the provided variable is of a character or factor type. However, it still uses sequential palette when the style is set to "cat" on numerical values. I would suggest to automatically change color palette when the style is "cat":

``` r
library(tmap)
library(spData)

nz$group = c(rep(1, 4), rep(2, 6), rep(3, 3), rep(4, 3))

# ok
tm_shape(nz) +
        tm_polygons("Island")
```

![](https://i.imgur.com/ZyhrIA4.png)

``` r

# ok
tm_shape(nz) +
        tm_polygons("group")
```

![](https://i.imgur.com/YwdYtYJ.png)

``` r

# not ok
tm_shape(nz) +
        tm_polygons("group", style = "cat")
```

![](https://i.imgur.com/SQpF7Ey.png)

``` r

# my expectation
tm_shape(nz) +
        tm_polygons("group", style = "cat", palette = "Set3")
```

![](https://i.imgur.com/LweXE3H.png)

<sup>Created on 2020-10-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mtennekes** [comment]
Thanks for bringing this up. The reason behind this behavior is that `group` when cast to a categorical variable, is *ordered*. For ordered categorical data, the default palette is the sequential one.

``` r
    
library(tmap)
library(spData)

nz$ordered = factor(c(rep(1, 4), rep(2, 6), rep(3, 3), rep(4, 3)), ordered = TRUE)
nz$not_ordered = factor(c(rep(1, 4), rep(2, 6), rep(3, 3), rep(4, 3)), ordered = FALSE)

tm_shape(nz) +
    tm_polygons("ordered")
```

![](https://i.imgur.com/6NtlEak.png)

``` r

tm_shape(nz) +
    tm_polygons("not_ordered")
```

![](https://i.imgur.com/FVgNRQp.png)

<sup>Created on 2020-10-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Not sure what to do. I agree that the expectation for a numeric variable when style is set to `"cat"` is a categorical palette, but at the same time, I strongly believe ordered categorical data should be shown with a sequential palette by default.

Currently, when style is set to `"cat"` numerical data is factorized with `ordered = TRUE`, with the underlying assumption that it truly is numerical data, and not factor numbers.

We may decide to factorize numerical data with `ordered = FALSE`. In this way, we get the expected result, and still shown ordered categorical data with a sequential palette.

What do you think?

**Comment by Nowosad** [comment]
Hi @mtennekes - I would keep the current behaviour. I was not aware of this explanation. It makes a lot of sense!
