### ISSUE TITLE
Plotting irregular raster objects with tmap

### ISSUE THREAD

**Issue by jernejjevsenak** [mtennekes/tmap#525]
This issue is also related to the question [I posted on StackExhange](https://gis.stackexchange.com/questions/379047/plotting-irregular-raster-object-with-tmap). 

I would like to use tmap to plot irregular raster object, which is in fact not real spatial data, but rather climate space with temperature on x axis, precipitation on y axis and interpolated variable (z axis).  

```
> temp_object
class      : RasterStack 
dimensions : 400, 550, 220000, 1  (nrow, ncol, ncell, nlayers)
resolution : 0.1, 10  (x, y)
extent     : -20, 35, 0, 4000  (xmin, xmax, ymin, ymax)
crs        : NA 
names      :          X1 
min values : 0.001695915 
max values :   0.1038332
```

The problem is that in tmap I cannot control the ratio between x and y axis. Fore example in ggR, this can easily be controlled with the argument `coord_equal = FALSE`, but I haven’t found similar argument in tmap, while it would be extremely useful. 
I have tried the `asp` argument from `tm_layout`, but it does not effect the ratio between x and y.

Please refer to the question on StackExhange for more details. You can also download the »problematic« tif file from my my github account. https://github.com/jernejjevsenak/test_tiff/blob/main/example_surface.tif

Best,
Jernej

**Comment by Nowosad** [comment]
I do not know what is the best solution, but one possible way to solve your problem would be to create a new empty raster with new dimensions, and then fill it with the original values: 

``` r
library(raster)
#> Loading required package: sp
library(tmap)

tifile = "https://github.com/jernejjevsenak/test_tiff/blob/main/example_surface.tif?raw=true"
download.file(tifile, "example_surface.tif")

r = raster("example_surface.tif")
r
#> class      : RasterLayer 
#> dimensions : 400, 550, 220000  (nrow, ncol, ncell)
#> resolution : 0.1, 10  (x, y)
#> extent     : -20, 35, 0, 4000  (xmin, xmax, ymin, ymax)
#> crs        : NA 
#> source     : /tmp/RtmpN6MyNH/reprexeb09563bb80f6/example_surface.tif 
#> names      : example_surface 
#> values     : 0.006431331, 0.5273994  (min, max)

r2 = r
extent(r2) = c(0, 5500, 0, 4000)
res(r2) = c(10, 10)
values(r2) = values(r)

tm_shape(r2) + tm_raster()
#> Warning: The projection of the shape object r2 is not known, while it seems to
#> be projected.
#> Warning: Current projection of shape r2 unknown and cannot be determined.
```

![](https://i.imgur.com/2YfApyb.png)

<sup>Created on 2020-11-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jernejjevsenak** [comment]
Yes. That totally solves my problem. Thank you very much.
