### ISSUE TITLE
Plotting of non-spatial data with the same geometry

### ISSUE THREAD

**Issue by marz29** [mtennekes/tmap#530]
In order to create my tmap, I merge my spatial data (which includes State ZIP Codes, Cities and ZIP Codes Polygon Geometry) with my non-spatial data (Individual Personal Info, Individual's ZIP Code and other variables). In total I have 1500 individuals so as you can imagine, I have more than one individual per ZIP Code. 

Therefore by the time I plot the tmap for a specific variable (e.g weight) I am not sure whether it plots only one individual per polygon or plots a consensus (e.g if most individuals with the same polygon geometry weight 132 lb, the polygon color is one that reflects 132 lb). Can you tell me how can I checked that and what can I do in order to represent all the individuals per polygon? 

Thanks in advance!

**Comment by Nowosad** [comment]
@marz29 everything depends on how you merged your data. The role of **tmap** is to visualize the data you provide. For example, if you want to visualize average weight - you need to calculate it before making the map. 

If you need more help - please create a reproducible example, post it on https://gis.stackexchange.com/ and add let us know.

**Comment by marz29** [comment]
I have just post my reproducible example. 
You can find it in this link: Plotting of non-spatial data with the same geometry
https://gis.stackexchange.com/q/381441/173910?sem=2

The files I use are attach in the question of Stack Exchange. As you might see the variable I am plotting is categorical and in some cases I have more than one individual per ZIP code. So taking into account that some individuals will have the same polygon geometry due to the same ZIP code, my question is the same: how do I know if only one individual is represented by that polygon and how can I show that more individuals are in that polygon?
