### ISSUE TITLE
does not display correct legend, creates more legend -- when importing and plotting categorical raster

### ISSUE THREAD

**Issue by ffpinas** [mtennekes/tmap#535]
I imported a tiff file (see below) using the raster package and tried to plot this tmap (see attached image below). 
> each_tif
class      : RasterLayer 
dimensions : 7878, 11558, 91053924  (nrow, ncol, ncell)
resolution : 5, 5  (x, y)
extent     : 622655, 680445, 6204975, 6244365  (xmin, xmax, ymin, ymax)
crs        : +proj=utm +zone=33 +ellps=WGS84 +units=m +no_defs 
source     : M:/marin/nkp16/nmi18/arbetskataloger/habmod/r-project/data/outputs/predictions/classifications/natura2000/nmi18/v11/5m/natura2000_sgu_nmi18_v01_5m.tif
names      : natura2000_sgu_nmi18_v01_5m 
values     : 1, 3  (min, max)
attributes :
ID category
  0         
  1        1
  2        2
  3        3
 

The problem with my plot is that I get 4 categories instead of just three. – Looking at the attributes in my file, I see that there are four values in the “ID” (i.e., 0,1,2,3) while there are only three in the “Category”. Why is this?
 
Plotting them using tmap using a labels list of three because there are only three classes (below) would also result in in one extra category (a repeat of the first one) and I get a warning message: “number of legend labels should be 4

I tried to import using the stars package, unfortunately st_read does not support .tif files.

Any thoughts on these would be welcome. Thanks.

![problem with legend](https://user-images.githubusercontent.com/76095337/102353920-11c44e00-3faa-11eb-9642-53e85d272686.png)

**Comment by Nowosad** [comment]
Just a side note: to read this file using the **stars** package, you need to use the `read_stars()` function.

**Comment by ffpinas** [comment]
Yes, thanks for this... importing using the stars package also led to the same issue as the picture above, i.e., extra legend is added (same as the first one).

**Comment by mtennekes** [comment]
@ffpinas Could you share the tif file so that I can reproduce it? A cropped version is also fine.

**Comment by ffpinas** [comment]
attached is the file that I used for the map
[natura2000_sgu_nmi18_v01_5m.zip](https://github.com/mtennekes/tmap/files/5707887/natura2000_sgu_nmi18_v01_5m.zip)

**Comment by mtennekes** [comment]
Thanks. I do not see the categories when reading the tif file. I've tried both stars::read_stars and raster::raster. Either I don't have the correct drivers, or there are some auxiliary files missing.

**Comment by ffpinas** [comment]
yes, the categories came from the dbf file also attached (i.e., natura2000_sgu_nmi18_v01_5m.tif.vat.dbf) which I exported using the code below;
rat <- read.dbf("M:/marin/nkp16/nmi18/arbetskataloger/habmod/r-project/data/outputs/predictions/classifications/natura2000/nmi18/v11/5m/natura2000_sgu_nmi18_v01_5m.tif.vat.dbf").

this is the code I used to plot the map in tmap;

tm_shape(each_tif)+ 
     tm_raster(n = NROW(rat), title=paste("Natura2000", "Classes"), labels = paste(as.vector(rat$Class_Name), " ", as.numeric(rat$Class_perc), "%", sep = ""))

**Comment by mtennekes** [comment]
I get this map after running the code:

![image](https://user-images.githubusercontent.com/2444081/102600147-be274100-411e-11eb-85b7-5b16f497683d.png)

**Comment by ffpinas** [comment]
I also had a look at the files that was sent--- I think I made a mistake with the dbf file that I sent, it was for another raster file. the correct one is below; I am sorry for that.
[natura2000_sgu_nmi18_v01_5m.tif.vat.zip](https://github.com/mtennekes/tmap/files/5715265/natura2000_sgu_nmi18_v01_5m.tif.vat.zip)
using plot() to plot the raster file would show that there are only three classes

This mistake made me realize that when plotting with tmap, using a list of legend that has more classes than what is specified in the raster file would still output a map with the specified legends, which in this case was ten class even if the raster had only three class (this would show if it was plotted using plot()).  If using a legend list that has less the number of classes than what is specified in the raster file, tmap would plot the raster and add a legend to compensate for the number of classes.

**Comment by mtennekes** [comment]
Hope this helps:

```r
tm_shape(each_tif)+
	tm_raster(n = NROW(rat), title=paste("Natura2000", "Classes"), labels = paste(as.vector(rat$Class_Name), " ", as.numeric(rat$Class_perc), "%", sep = ""))

# uses the same color classes as:
tm_shape(each_tif)+
	tm_raster(n = 3)

# using categories instead of the default color classes:
tm_shape(each_tif)+
	tm_raster(n = 3, style = "cat")

# with meta
tm_shape(each_tif)+
	tm_raster(n = NROW(rat), style = "cat", title=paste("Natura2000", "Classes"), labels = paste(as.vector(rat$Class_Name), " ", as.numeric(rat$Class_perc), "%", sep = ""))
```

**Comment by ffpinas** [comment]
Yes, this is the solution I was looking for!!! thanks so much!!!
