### ISSUE TITLE
Support for terra?

### ISSUE THREAD

**Issue by Nowosad** [mtennekes/tmap#536]
I think it would be great for tmap to support terra objects as well as raster and stars. 
For example, terra is used by a great package maptiles (https://github.com/riatelab/maptiles) by @rCarto:

``` r
library(sf)
#> Linking to GEOS 3.8.1, GDAL 3.0.4, PROJ 6.3.2
library(raster)
#> Loading required package: sp
library(maptiles)
library(tmap)
vector_filepath = system.file("vector/zion.gpkg", package = "spDataLarge")
zion = read_sf(vector_filepath)
zion_osm = get_tiles(zion, crop = TRUE, zoom = 11, provider = "Stamen.Toner")
zion_osm2 = stack(zion_osm)
#> Warning in showSRID(uprojargs, format = "PROJ", multiline = "NO", prefer_proj =
#> prefer_proj): Discarded datum Unknown based on GRS80 ellipsoid in CRS definition

tm_shape(zion_osm2) + 
  tm_rgb() + 
  tm_shape(zion) +
  tm_borders(lwd = 5, col = "gray95") +
  tm_credits(get_credit("Stamen.Toner"),
             position = c("RIGHT", "BOTTOM"))
```

![](https://i.imgur.com/pa090Ti.png)

<sup>Created on 2020-12-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mtennekes** [comment]
Yes, that would be great indeed!

@edzer and @rhijmans Currently, the conversion methods between `sf`/`stars` and `terra` do not work. For `terra`'s `SpatRaster` class, I need `st_bbox`, `st_crs`, and `st_as_stars`. The latter works, but not well:

``` r
library(sf)
#> Linking to GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1
library(raster)
#> Loading required package: sp
library(maptiles)
vector_filepath = system.file("vector/zion.gpkg", package = "spDataLarge")
zion = read_sf(vector_filepath)
zion_osm_terra = get_tiles(zion, crop = TRUE, zoom = 11, provider = "Stamen.Watercolor")

# convert to raster stack
zion_osm_raster = stack(zion_osm_terra)
#> Warning in showSRID(uprojargs, format = "PROJ", multiline = "NO"): Discarded datum Unknown based on GRS80 ellipsoid in CRS definition,
#>  but +towgs84= values preserved

# convert to stars object
(zion_osm_stars = stars::st_as_stars(zion_osm_terra))
#> stars object with 3 dimensions and 1 attribute
#> attribute(s), summary of first 1e+05 cells:
#>       A1                NA              NA       
#>  Min.   : 51.22   Min.   : 77.2   Min.   :  0.0  
#>  1st Qu.:234.23   1st Qu.:220.6   1st Qu.:180.7  
#>  Median :245.98   Median :226.4   Median :207.9  
#>  Mean   :230.19   Mean   :224.0   Mean   :186.3  
#>  3rd Qu.:249.32   3rd Qu.:230.7   3rd Qu.:213.5  
#>  Max.   :255.00   Max.   :255.0   Max.   :255.0  
#>  NA's   :316      NA's   :316     NA's   :316    
#> dimension(s):
#>    from  to offset delta refsys point values x/y
#> X1    1 728      0     1     NA FALSE   NULL [x]
#> X2    1 579      0     1     NA FALSE   NULL [y]
#> X3    1   3      0     1     NA FALSE   NULL

# however, the data of the first attribute is still a SpatRaster:
zion_osm_stars[[1]]
#> class       : SpatRaster 
#> dimensions  : 728, 579, 3  (nrow, ncol, nlyr)
#> resolution  : 60.71488, 60.71488  (x, y)
#> extent      : 301244.7, 336398.6, 4110569, 4154769  (xmin, xmax, ymin, ymax)
#> coord. ref. : +proj=utm +zone=12 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs 
#> source      : memory 
#> names       :    Sta_1,    Sta_2,    Sta_3 
#> min values  :  0.00000, 77.20142,  0.00000 
#> max values  :      255,      255,      255
```

<sup>Created on 2021-01-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


@Nowosad and @tim-salabim Probably, we have discussed this before, but this example is a reminder: what is the best approach to get static map tiles directly into tmap? Obviously, `maptiles` works very well, but the downsides are 1) it is a bit slow and 2) the list of import packages is growing again (with `maptiles`, `terra`, `raster`, etc.).

**Comment by edzer** [comment]
There is no conversion method for `terra` to stars, but you could try
```r
st_as_stars(as(zion_osm_terra, "Raster"))
```
which seems to produce something useful.

**Comment by tim-salabim** [comment]
@mtennekes I am not sure what the best approach for static map tiles is. `maptiles` looks very convenient though. You could only suggest `maptiles` for the case when someone wants background tiles, maybe?

**Comment by rCarto** [comment]
I think you should also consider the fact that `maptiles` uses functions from `terra` that need GDAL >= 3.0.4. (`sf` only needs 2.0.1)

**Comment by Nowosad** [comment]
@mtennekes many alternatives are mentioned at https://github.com/riatelab/maptiles#alternatives, but **maptiles** looks the most complete.

**Comment by rhijmans** [comment]
For `st_bbox` and `st_crs` you could do something like the below . I am not trying to match exactly what these do for sf objects, but like this them may extract the info you need; and if that is the case and you do not export them no harm is done.

```
st_bbox.SpatRaster = function(obj, ...) {
	as.vector(ext(obj))[c(1,3,2,4)]
}

st_crs.SpatRaster = function(x, ...) {
	crs(x)
}	

st_bbox(zion_osm_terra)
#     xmin      ymin      xmax      ymax 
# 301244.7 4110568.7  336398.6 4154769.1 
st_crs(zion_osm_terra)
#[1] "BOUNDCRS[\n    SOURCECRS[\n        PROJCRS[\"UTM Zone 12, Northern Hemisphere\",\n ... 

```

**Comment by edzer** [comment]
Thanks! these even return the properly classed objects when defined as
```r
st_bbox.SpatRaster = function(obj, ...) {
    bb = as.vector(terra::ext(obj))[c(1,3,2,4)]
    names(bb) = c("xmin", "ymin", "xmax", "ymax")
    st_bbox(bb, crs = st_crs(obj))
}

st_crs.SpatRaster = function(x, ...) {
    st_crs(crs(x))
}   
```
I now added these along with the `st_as_stars()` method to stars in https://github.com/r-spatial/stars/commit/85154cc7438baeb6105e9ac5d8888a998772ef4c

**Comment by rhijmans** [comment]
Very good. Much better.  Perhaps these are of interest as well for `tmap`

```
st_bbox.SpatVector = function(obj, ...) {
    bb = as.vector(terra::ext(obj))[c(1,3,2,4)]
    names(bb) = c("xmin", "ymin", "xmax", "ymax")
    st_bbox(bb, crs = st_crs(obj))
}

st_crs.SpatVector = function(x, ...) {
    st_crs(crs(x))
} 
```

**Comment by edzer** [comment]
thanks, @rhijmans - added to stars.

**Comment by t-wojciech** [comment]
@mtennekes, @rhijmans, @edzer, best crossover ever.

**Comment by edzer** [comment]
The dutch trinity!

**Comment by ailich** [comment]
@edzer `st_as_stars` is no longer working for SpatRasters, likely due to this change in terra/raster (rspatial/terra#432)

```
library(terra)
library(stars)

packageVersion("terra") # ‘1.5.1’
packageVersion("stars") #‘0.5.5’
packageVersion("raster") # ‘3.5.7’

r<- rast(volcano)
st_as_stars(r)
#Error: $ operator is invalid for atomic vectors
```

**Comment by Nowosad** [comment]
@ailich see https://github.com/r-spatial/stars/pull/484
