### ISSUE TITLE
Anchorpoints for positioning legend and  tm_text labels

### ISSUE THREAD

**Issue by sjewo** [mtennekes/tmap#54]
Hi Martijn,
I produced a lot of figures with your package and it's working really well!
If I look back at my workflow, it would be a great enhancement, if the positioning achor points ("top left corner", "center" and so on) could be explicitly defined.

In my usecase this had been useful in an specific situation:
I produced multiple maps for the same shapefile with different variables. The automatic legend placement wasn't optimal, so I had to position the legend manually. For different legends I had to change the position argument, because the size of the legend changed. An anchor point for positioning the legend at the top left corner (i put the legend on the right side of the plot) would fix this problem and makes reusing the positioning for many plots usable.

An similar problem occured while using xmod and ymod with 'tm_text'. After printing a map into a grid-viewport, the automatic positioning of the labels was wrong (to much space between point coordinates and label), so I set them manually via the `xmod` and `ymod` option. This was somehow time consuming, because I wanted the label left from the coordinates and the position anchor was in the center of the label and had to set different values for labels of different length.

Here is an example for `tm_text`:
```
library(tmap)
data(NLD_muni, NLD_prov)

# autoplacement
tm_shape(NLD_prov) + 	tm_fill("population", style="quantile") + tm_borders() + tm_shape(NLD_muni[c(114,30,50,200),]) + tm_dots("green") + tm_text("name", auto.placement=T)

# static xmod an ymod
tm_shape(NLD_prov) + 	tm_fill("population", style="quantile") + tm_borders() + tm_shape(NLD_muni[c(114,30,50,200),]) + tm_dots("green") + tm_text("name", auto.placement=F, xmod=2.5, ymod=0.1)

# mimimc the autoplacement with xmod an ymod - manual adjustment needed for every entry
tm_shape(NLD_prov) + 	tm_fill("population", style="quantile") + tm_borders() + tm_shape(NLD_muni[c(114,30,50,200),]) + tm_dots("green") + tm_text("name", auto.placement=F, xmod=c(1.7,3.5,2.5,2.2), ymod=0.3)
```

**Comment by mtennekes** [comment]
Hi Sebastian,

Thanks for your suggestion! These two problems are different:

With respect to the legend, the values "left", "top" etc. will snap the legend to the corners. I don't see how to place the legend when `legend.position = c("right", "top")`, and `legend.anchor = c("left", "top")`. I think anchor points for legend position may indeed be handy when the legend.position is numeric. Now, the anchor points are (implicitly) defined by the grid coordinate system as left bottom:

```
data(land)
tm_shape(land) +
	tm_raster("trees") +
	tm_legend(position=c(.7, .02), frame=TRUE)

tm_shape(land) +
	tm_raster("cover") +
	tm_legend(position=c(.7, .02), frame=TRUE)
```

So it would be nice to have legend.anchor argument at this point. Is this what you mean?

The text labels are automatically placed with this function: https://github.com/mtennekes/tmap/blob/master/pkg/R/pointLabelGrid.R, where I do not have control over the anchor position. I'm also not always satisfied with the outcome positions, so any ideas are welcome. Also, feel free to cooperate.

**Comment by sjewo** [comment]
Hi Martijn,

your example shows an nice usage situation for a legend.anchor argument I had in mind. And it would also be handy for manual adjustment of tm_text plots. One just needs to make the `just` parameter in `plot_text` an option. If you think this is useful, I could take some time and dig into the code. Looks like an pretty newbie task ;)

I understand most of the individual function, but I didn't get, how the different functions for setting styles, process them and plot thing fit together.

**Comment by mtennekes** [comment]
It's difficult to explain the interaction of all functions, but I'll have some comments in https://github.com/mtennekes/tmap/blob/master/pkg/R/print_tmap.R#L64-L89. 

For this specific task, you'll need to pass on `just` in `process_text`. The placement of labels is done in https://github.com/mtennekes/tmap/blob/master/pkg/R/plot_misc_functions.R#L345. If `auto.placement` is enabled, it is processed afterwards in https://github.com/mtennekes/tmap/blob/master/pkg/R/plot_map.R#L91-L245, which is a pretty ugly and tedious chuck of code.

Let me know if you're stuck somewhere. I'll try to write some co-authoring-tmap instructions.

**Comment by sjewo** [comment]
Hi and thanks for the explanations.
I tried to add the justification option and its working as i had in mind.  Maybe you want to take a look on the commit 7a1c7ec4b5d36b55ae15ba84db12f1b8891d2a2e before make an pull request. 

```
tm_shape(NLD_prov) +    tm_fill("population", style="quantile") + 
tm_borders() + tm_shape(NLD_muni[c(114,30,50,200),]) + 
tm_dots("green") + tm_text("name", auto.placement=F, just=c("left", "top"))
```
I will look into the auto.placement code next.

**Comment by mtennekes** [comment]
Well done! 

PS: In which branch did you commit this? I cannot find the commit in github's gui menus.

**Comment by sjewo** [comment]
Thanks for adding me to you repo! Should I create an branch in this repo for the positiong modifications or do you prefer a pull request?

**Comment by mtennekes** [comment]
I think another branch would be better, because then we can also improve the legend anchor, and maybe also the auto.placement algorithm. Moreover, when we improved the anchor/auto placement for text labels, we can also use this for inset graphics (https://github.com/mtennekes/tmap/issues/52).

**Comment by sjewo** [comment]
Just commited an justification argument for legends b587d9c

So the current state of this branch is
- [x] justification of tm_text labels
- [x] justification of legends
- [ ] justification of inset graphics
- [ ] improved auto placement

In regards of auto placement i'll take a look in the code of the directlabels package.

**Comment by mtennekes** [comment]
Thanks! I made some changes. Both legend.position and legend.just should accept a mixture of character and numeric values, for instance `legend.position=c("left", .8)`. I'll test the code this weekend.

**Comment by mtennekes** [comment]
Here is some example code of the new legend positioning. It should be working 100% now.

```
data(land)

tm_shape(land) +
	tm_raster("trees") +
	tm_layout(legend.position=c("left", "top"),
			  legend.frame=TRUE)

tm_shape(land) +
	tm_raster("cover") +
	tm_layout(legend.position=c("left", "top"), 
			  legend.frame=TRUE)

tm_shape(land) +
	tm_raster("trees") +
	tm_layout(legend.position=c("right", "bottom"),
			  legend.frame=TRUE)

tm_shape(land) +
	tm_raster("cover") +
	tm_layout(legend.position=c("right", "bottom"), 
			  legend.frame=TRUE)

tm_shape(land) +
	tm_raster("trees") +
	tm_layout(legend.position=c(.9, "bottom"), 
			  legend.just=c("right", "top"),
			  legend.frame=TRUE)

tm_shape(land) +
	tm_raster("cover") +
	tm_layout(legend.position=c(.9, "bottom"), 
			  legend.just=c("right", "top"),
			  legend.frame=TRUE)

tm_shape(land) +
	tm_raster("trees") +
	tm_layout(legend.position=c(.95, .5), 
			  legend.just=c("right", .5),
			  legend.frame=TRUE)

tm_shape(land) +
	tm_raster("cover") +
	tm_layout(legend.position=c(.95, .5), 
			  legend.just=c("right", .5),
			  legend.frame=TRUE)


tm_shape(land) +
	tm_raster("trees") +
	tm_layout(legend.position=c(.5, .5), 
			  legend.just=c(.5, .5),
			  legend.frame=TRUE)

tm_shape(land) +
	tm_raster("cover") +
	tm_layout(legend.position=c("center", "center"), 
			  legend.just=c(.5, .5),
			  legend.frame=TRUE)
```

FYI: the branches positioning and master and now leveled. @sjewo: we can use the positioning branch to improve the other positioning items.
