### ISSUE TITLE
A couple of tmap_arrange() feature requests

### ISSUE THREAD

**Issue by francisbarton** [mtennekes/tmap#540]
Just two things I've noticed today. Thought I would post for your consideration.
Thank you!

### 1. Sorry this one is already addressed [here](https://github.com/mtennekes/tmap/issues/511#issuecomment-709919403) <strike>**For `tmap_arrange()` to be able to have a main banner title running across the top of all component maps, as you have with faceted maps.**</strike>

``` r
library(tmap)

data("NLD_prov")

map1 <- qtm(NLD_prov) + tm_layout(main.title = "Two separate maps with tmap_arrange")
map2 <- qtm(NLD_prov)

tmap_arrange(map1, map2, ncol = 2)
```

![](https://i.imgur.com/dU7AMIY.png)

``` r
tmap_arrange(map2, map2, ncol = 2, main.title = "Two maps")
#> Error in tmap_arrange(map2, map2, ncol = 2, main.title = "Two maps"): Not all arguments are tmap objects.

tm_shape(NLD_prov) +
  tm_fill(c("grey75", "grey75")) +
  tm_layout(main.title = "Two faceted maps with running main.title")
```

![](https://i.imgur.com/5KuemKp.png)

The faceting trick works great, but I don't think it works if you want to arrange two different maps (different `tm_shape`s).

### 2.  **For tmap\_arrange() objects to be accessible via tmap\_last()**

``` r
tmap_arrange(map1, map2, ncol = 2)
```

![](https://i.imgur.com/LQLbRsg.png)

``` r
tmap_save(tm = tmap_last(), "~/tmp_out.png")
#> Error in `+.tmap`(e1 = tm, e2 = tml): object 'tm' not found

arr_out <- tmap_arrange(map1, map2, ncol = 2)
tmap_save(tm = arr_out, "~/tmp_out.png")
#> Map saved to C:\Users\Francis\tmp_out.png
#> Resolution: 2100 by 2100 pixels
#> Size: 7 by 7 inches (300 dpi)
```

<sup>Created on 2021-01-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Nowosad** [comment]
Hi @francisbarton , due to a very recent enhancement, you can convert tmap objects into grobs, and then arrange them using **gridExtra** or **cowplot**:

``` r
library(tmap)

data("NLD_prov")

map1 <- qtm(NLD_prov) 
map2 <- qtm(NLD_prov)

map1_grob <- tmap_grob(map1)
#> Note that the aspect ratio for which the grob has been generated is 1.4
```

![](https://i.imgur.com/Rc58Ipz.png)

``` r
map2_grob <- tmap_grob(map2)
#> Note that the aspect ratio for which the grob has been generated is 1.4
```

![](https://i.imgur.com/kSosVfT.png)

``` r
# 1
library(gridExtra)
grid.arrange(map1_grob, map2_grob, top = "Two separate maps with tmap_arrange", nrow = 1)
```

![](https://i.imgur.com/CbhKZj1.png)

``` r
# 2
library(cowplot)

title = ggdraw() + 
  draw_label("Two separate maps with tmap_arrange", fontface = "bold", x = 0, hjust = 0)

plot_grid(title, ggdraw(), map1_grob, map2_grob, nrow = 2, rel_heights = c(0.1, 1))
```

![](https://i.imgur.com/1lfW4tZ.png)

<sup>Created on 2021-01-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by francisbarton** [comment]
This is great! Thanks @Nowosad and @mtennekes .
I will update tmap and have a play with those other tools - I guess they will give some additional useful customisation options to help with the presentation of maps.

_(Getting map layouts to look nice and having more control over the arrangement of elements is the only thing I find difficult about using tmap)._
