### ISSUE TITLE
Incorporate inset map with tmap_arrange

### ISSUE THREAD

**Issue by nekronaut** [mtennekes/tmap#541]
I would like to merge several `tmap` objects into one file, including a map with an insert, using `tmap_arrange`. To my understanding, the way inset maps are created in `tmap` involves using `grid::viewport`, which plots additional objects on top of an existing plot. Unfortunately, this method does not seem to enable creating a named `tmap` object which could be used in the `tmap_arrange` command. Is this just me, or did I miss something?

    library(sf)
    library(tidyverse)
    library(tmaptools)
    library(tmap)
    library(grid)
    library(raster)

    DE <- getData('GADM', country='DE', level=0) %>% 
      st_as_sf() %>% 
      tm_shape + 
      tm_polygons()

    BAV <- getData('GADM', country='DE', level=1) %>% 
      st_as_sf() %>% 
      filter(NAME_1 == "Bayern") %>% 
      tm_shape + 
      tm_polygons()

    map_joined <- tmap_arrange(DE, BAV, ncol = 2)

    BAV
    print(DE, vp = viewport(0.85, 0.8, width = 0.2, height = 0.2)) 

    #map_inset_joined <- tmap_arrange(???, DE, ncol = 2) does not work!

**Comment by Nowosad** [comment]
Hi @nekronaut, `tmap_arrange()` does not allow for creating inset maps. However, you can make them converting your maps to grobs with `tmap_grob()` and then arranging the maps with **cowplot**:

``` r
library(sf)
#> Linking to GEOS 3.8.1, GDAL 3.1.4, PROJ 6.3.2
library(dplyr)
library(tmap)
library(raster)

DE <- getData('GADM', country='DE', level=0) %>% 
  st_as_sf() %>% 
  tm_shape + 
  tm_polygons()

BAV <- getData('GADM', country='DE', level=1) %>% 
  st_as_sf() %>% 
  filter(NAME_1 == "Bayern") %>% 
  tm_shape + 
  tm_polygons()

DE_grob <- tmap_grob(DE)
#> Note that the aspect ratio for which the grob has been generated is 1.4
BAV_grob <- tmap_grob(BAV)
#> Note that the aspect ratio for which the grob has been generated is 1.4
```

``` r
library(cowplot)
ggdraw() +
  draw_plot(BAV_grob) +
  draw_plot(DE_grob,
            width = 0.2, height = 0.2,
            x = 0.65, y = 0.75)
```

![](https://i.imgur.com/AI3SK0a.png)

<sup>Created on 2021-01-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by nekronaut** [comment]
Thanks - that works!
