### ISSUE TITLE
Anyone else using tmap with conda?

### ISSUE THREAD

**Issue by spittssj** [mtennekes/tmap#543]
For about nine months, I've been working on my first python GIS project. Recently, after battling some hairy GDAL library issues involving Homebrew, I successfully set up a GIS environment with conda for my python GIS workflow. It has Postgresql + PostGIS + geopandas. 

The reason I switched to conda is that it can successfully manage C library dependencies as well like gdal and libspatialite. In my case it manages my postgresql + postgis development server as well. The whole toolchain is linked against the same GDAL and plays well together. 

Lately our team wants to generate some static maps with RMarkdown on our data set (based on spatial statistics we are computing with R), so I'm trying to do something similar for my R environment. 

But the problem I run into is that the conda-forge tmap (via lwgeom) is trying to link to an old version of proj.

I've written about these issues on the tmap feedstock
https://github.com/conda-forge/r-tmap-feedstock/issues/10

and the lwgeom feedstock
https://github.com/conda-forge/r-lwgeom-feedstock/issues/12

But I haven't gotten a reply, so I'm asking here. Is anyone else doing this? 

I'd be happy to help. I'm new to conda and R but I have a moderate amount of python and Unix development experience, so I'm willing to learn, so I can contribute to the R geospatial ecosystem instead of simply taking advantage of it. 

Thanks.

**Comment by izahn** [comment]
This stems from lack of updates to the lwgeom package in the conda ecosystem. You can work-around it by installing everything that doesn't depend on lwgeom via conda, and then the rest via install.packages:

```
conda create -n sftest -c conda-forge r-base r-rcolorbrewer r-classint r-htmltools r-htmlwidgets r-leaflet r-leafsync r-raster r-sf r-units r-viridislite r-leafem
```
```
conda activate sftest
mkdir -p ~/.conda/envs/sftest/lib/R/site-library ## optional but recommended
Rscript -e "install.packages('tmap', repos='https://cran.rstudio.com')"
```

**Comment by izahn** [comment]
This issue is being tracked at https://github.com/conda-forge/r-lwgeom-feedstock/issues/12. There is nothing to be done from the tmap side, this issue can be closed.
