### ISSUE TITLE
tm_fill get outer coordinates 

### ISSUE THREAD

**Issue by yasineahmed** [mtennekes/tmap#544]
Would it be possible to extract the outer boarder coordinates (lng , lat)? cannot find a way to do this. 

`tm_shape(territory) + tm_fill() `
![image](https://user-images.githubusercontent.com/34150701/106543583-db3f8580-64ba-11eb-9df9-36ed277ae331.png)

**Comment by mtennekes** [comment]
Not sure if I completely understand what you want to achieve, but there are two ways to do that:

1. Get the bounding box

```r
sf::st_bbox(territory)
```

2. Draw graticules

```r
tm_shape(territory) + tm_fill() + tm_graticules()
```
