### ISSUE TITLE
Figure 4 cannot be reproduced with the JSS code

### ISSUE THREAD

**Issue by Nico-Rojas** [mtennekes/tmap#549]
In Figure 4 of the JSS article, there is a tm_facet syntax to reproduce Figure 4 that does not generate the same figure. The code can also be found in the reproduction code [here](https://rdrr.io/cran/tmap/f/vignettes/tmap-JSS-code.Rmd). 

County polygons are dropped while running the code while in the example country polygons are not dropped. 

What is the code necessary to reproduce Figure 4?

```{r}
# The code from the article
library(tm)
data("World", package = "tmap")
tm_shape(World) + tm_polygons("red") + tm_facets(by = "continent", free.coords = FALSE, free.scales = F)
```
How it should look like: 
![fig1](https://user-images.githubusercontent.com/43378796/108750513-1871c300-750f-11eb-86d4-e84afc11090d.JPG)

How it looks like:
![fig2](https://user-images.githubusercontent.com/43378796/108750597-37705500-750f-11eb-8a2e-f37c8b39027d.JPG)

**Comment by mtennekes** [comment]
Since v2, there is an additional argument that controls the 'out-of-selection' units, namely `drop.units`.

```r
tm_shape(World) + tm_polygons("red") + 
tm_facets(by = "continent", free.coords = FALSE, free.scales = F, drop.units = FALSE)
```

**Comment by Nico-Rojas** [comment]
Thank you so much!
