### ISSUE TITLE
Subtitles per facet in interactive map

### ISSUE THREAD

**Issue by PieterjanVerhelst** [mtennekes/tmap#550]
When creating an interactive HTML plot/view, I don't get a subtitle per facet anymore. This used to be the case. Specifically, the subtitles were the levels in the object stated after the argument `by =` in the function `tm_facet`. Did something change in the recent version of `tmap`?

**Comment by mtennekes** [comment]
Probably I've disabled them because they didn't always work.
I re-enabled them, so now it should work as normal again.
