### ISSUE TITLE
How can I see the leaflet map on a mobile?

### ISSUE THREAD

**Issue by JaeyounRyoo** [mtennekes/tmap#552]
I want to see the leaflet map on the web.
I can see the map on PC, but I can't see it on the phone.
I can see all of markers, labels on grey map on the phone.
I am coding r shiny.

p <- leaflet(plot.data) %>%
        setView(lng = x.lon, lat = y.lat, zoom = z.size) %>% 
        addTiles() %>%

        addCircleMarkers(lng = ~lng, lat = ~lat,
                         color = ~conc_color(plot.data[, input$item]),
                         radius = 7,
                         stroke = FALSE,
                         fillOpacity = 0.8,
                         label = ~str_c(plot.data$road.name, ", ", input$item, " : ",
                                        format(round(plot.data[ , input$item], digits = n_digit), nsmall = n_small))) %>%

        addLegend(position = "topright",
                  colors = lbl_palette,
                  labels = lbl_conc)

**Comment by Nowosad** [comment]
__
