### ISSUE TITLE
I've got error message "File does not exist" when I download with write.csv in shiny

### ISSUE THREAD

**Issue by JaeyounRyoo** [mtennekes/tmap#554]
I've got error message "File does not exist" when I download with write.csv in shiny

I didn't have any error like that in my PC, but I've got error message after I copied the code in Laptop.
I don't have any idea.
When I click download button, I can see the all path and filename made in code in save file window.
But I got error message.
How could I solve it.

Error Message
File does not exist: C:\users\adminitrator\AppData\Local\Temp\RtmpaQipxd\file647ed493a.csv

  #==================================================================
  output$save.the.table.summary <- downloadHandler(  
    
    filename = function() {
      if(str_sub(input$obs_file$name, -3, -1) == "MDB"){
        paste(getwd(), "/tables/TSI_", 
              substr(input$obs_file$name, 17, 18), "_", 
              substr(input$obs_file$name, 1, 8), "_summary.csv", sep = "")
      } else {
        if(substr(input$obs_file$name, 1, 3) == "TSI") {
          paste(getwd(), "/tables/", 
                substr(input$obs_file$name, 1, 3), "_", 
                substr(input$obs_file$name, 5, 6), "_", 
                substr(input$obs_file$name, 8, 15), "_summary.csv", sep = "")
        } else {
          paste(getwd(), "/tables/", 
                substr(input$obs_file$name, 1, 3), "_", 
                substr(input$obs_file$name, 5, 8), "_", 
                substr(input$obs_file$name, 10, 17), "_summary.csv", sep = "")
        }
      }
    },

    content = function(file) {
      write.csv(road.data.summary(), file, row.names = FALSE)
    }
  )

**Comment by Nowosad** [comment]
Dear @JaeyounRyoo - this issue seems not to be related to the tmap package. If it is - please create a reproducible example.
