### ISSUE TITLE
Issue with popup.format now requiring html.escape

### ISSUE THREAD

**Issue by kforeman** [mtennekes/tmap#556]
The latest release (both `3.3.1` from CRAN and installing https://github.com/mtennekes/tmap/commit/10aa8b099f9d93c0235a05779287798242cc538e from source) adding `html.escape` to `popup.format` is causing errors for me.

E.g.

```
library(tmap)
library(leaflet)
tmap_mode("view")

data(World, metro)
metro$growth <- (metro$pop2020 - metro$pop2010) / (metro$pop2010 * 10) * 100

tm_shape(metro) +
  tm_bubbles("pop2010", col = "growth", 
             border.col = "black", border.alpha = .5, 
             style="fixed", breaks=c(-Inf, seq(0, 6, by=2), Inf),
             palette="-RdYlBu", contrast=1, 
             title.size="Metro population", 
             title.col="Growth rate (%)", id="name", 
             popup.vars=c("Population (2010)"="pop2010", "Population (2020)"="pop2020", "Growth (%)"="growth"),
             popup.format=list(growth=list(digits=4)))
```

now throws an error that `Error in if (format$html.escape) { : argument is of length zero`.

I've tried changing the last line to 
```
popup.format=list(growth=list(digits=4, html.escape=FALSE))
```

but receive the same error.

Removing `popup.format` from the call to `tm_bubbles` (or `tm_fill`, etc) fixes the issue.

**Comment by mtennekes** [comment]
Thanks @kforeman It should work again.

**Comment by kforeman** [comment]
Works again - thanks!
