### ISSUE TITLE
Incorrect map in "plot" mode

### ISSUE THREAD

**Issue by SunsetBlvd** [mtennekes/tmap#563]
I am trying to plot a map with this code:
```
library(tmap)
data("World")
tm_shape(World) + tm_polygons("HPI")
```
but I get this:
[map](https://ibb.co/ZWQ02NJ)
About one month ago everything worked fine. For the last month I probably updated some libraries (my versions of tmap and tmaptools are now 3.3-1. Version of R is 3.5.3) and installed QGIS 3.16.5.
In interactive mode I get correct map:
```
tmap_mode("view")
tm_shape(World) + tm_polygons("HPI")
```
Can somebody advice how to fix this problem in "plot" mode?

**Comment by mtennekes** [comment]
Very strange.

Does this work?

```r
library(sf)
plot(World[, "HPI"])
```

Could you share your `devtools::session_info()` results?

**Comment by SunsetBlvd** [comment]
```r
library(sf)
plot(World[, "HPI"])
```
map:
[link](https://ibb.co/wQrYvcP)
session_info:
[1](https://ibb.co/1mMPDng)
[2](https://ibb.co/9ZLvMZG)

**Comment by mtennekes** [comment]
If you're able to upgrade R to 4.x, please do so. It may be a unlucky combinations of package/R versions that causes this bug.

**Comment by SunsetBlvd** [comment]
Ok, thank you.

**Comment by SunsetBlvd** [comment]
Update of R to 4.0.5 solved the problem.
