### ISSUE TITLE
Legend title ignores system locale

### ISSUE THREAD

**Issue by KHrehova** [mtennekes/tmap#567]
When I run the following:

```
Sys.setlocale("LC_ALL","Slovak")
distance_map<-qtm(skmap_c, "annual_dist_2017", fill.palette=isp_pal,
                    fill.title = "Vzdialenosť od CPP, 2017")
tmap_save(distance_map, filename="empirical/3_output/1_4_prepare_data_stage2/distance_map_2017.png")

``` 
The saved file has in the legend title something like **VzdialenosĹA** od CPP, 2017. Any ideas on how to solve this?

**Comment by mtennekes** [comment]
I don't know; My experience with special characters is very limited. @Nowosad any ideas?

**Comment by Nowosad** [comment]
I can reproduce this problem:

```r
Sys.setlocale("LC_ALL","Slovak")
library(tmap)
data("World")
distance_map = qtm(World, fill = "life_exp", fill.title = "vzdialenosť")
tmap_save(distance_map, filename = "my_map.png")
```
![my_map](https://user-images.githubusercontent.com/3457131/122106668-8291d900-ce1a-11eb-8fca-3ecba3687063.png)

It happens also when I render the map in R.

**Comment by Nowosad** [comment]
The issue seems to be much broader - this problem also happens for **ggplot2**:

```r
Sys.setlocale("LC_ALL","Slovak")
library(ggplot2)
library(tmap)
data("World")
ggplot(World) +
  geom_point(aes(life_exp, well_being)) +
  ggtitle("vzdialenosť")
```

Sadly, I do not have any solutions (except using UTF-8 everywhere if possible)...
