### ISSUE TITLE
x-axis line in histogram legend doesn't get the color specified in attr.color from tm_layout()

### ISSUE THREAD

**Issue by EduardoFernandezC** [mtennekes/tmap#569]
I am new to `tmap` and I am currently struggling to get the color of the x-axis line of the histogram legend in the color specified in the `attr.color` argument. Did not find help in stackoverflow or elsewhere. Here is a reprex that shows the issue:

```
library(tmap)
data("World")

tm_shape(World) +
  tm_polygons("HPI", legend.hist = TRUE) +
  tm_layout(bg.color = "black",
                    attr.color = "red",
                    legend.bg.color = "grey")
```

**Comment by mtennekes** [comment]
Easiest bug fix so far.
