### ISSUE TITLE
RGB raster map in tmap

### ISSUE THREAD

**Issue by marionowak** [mtennekes/tmap#57]
Hello
Is it possible to add RGB rasterstacks to a map with tmap?
This could be used to add satellite imagery to a map. And is it possible to resample raster(stack) data to a smaller resolution?

Thanks, Mario

**Comment by mtennekes** [comment]
It's easy to do, but the confusing thing is: how to recognize a RGB raster stack/brick object? I mean, a raster stack/brick could also be a three-layer-data file. Does anyone knows this? We could assume all 3-band raster bricks with values between 0 and 255 are RGB stacks.

For testing, I downloaded a tiff of SF bay from http://www.terracolor.net/sample_imagery.html

```
library(raster)
x <- brick("TC_NG_SFBay_US_Geo.tif")

qtm(x)

tmap_mode("view")
qtm(x)
```

Now, what happens is that the layers are seen as data rather than RGB values:
![rplot05](https://cloud.githubusercontent.com/assets/2444081/14586346/75c13120-0495-11e6-80fd-ec8d66db735e.png)


Aggregation to a smaller resolution is quite straightforward:

```
y <- aggregate(x, fact=4)
qtm(y)
```

So, we could check whether `nbands(x) == 0`, `minValue(x)>=0` and `maxValue(x)<=255`, but any other suggestions are welcome.

**Comment by marionowak** [comment]
souds good so far and would be nice if implemented.
but why not `nbands(x) == 3` ?

**Comment by sjewo** [comment]
Maybe a more manual approach would be sufficient? What if the detection goes wrong or the user just wants to plot one band?

To plot a raster correctly we could use an dedicated  object class, to define whether the values are data or color values.  A user could use a function like `as.RasterRGB()` to define an RasterRGB object and tmap would handle it as an RGB image.

Unfortunately the raster package doesn't define a class like `rasterBrickRGB`, but a simple helper function could be written for tmap (or we could ask the raster developer to alter their package functions `plotRGB()` and `RGB` to define an own subclass).

**Comment by mtennekes** [comment]
@marionowak: it should indeed be `nbands(x)==3`.

I agree with @sjewo that the user should have control over what to plot. The approach that I'm working on is:

* If `tm_raster()` is called, so without defining `col`, then I'll check in `preprocess_shapes` whether the raster contains colors or 3 bands between 0 and 255. If so, the shape object is flagged as RGB. Notice that `read_osm` also returns a flagged raster object by defining an attribute `is.OpenStreetMap=TRUE` (which I renamed it to `is.RGB`). So, if the user wants to plot one band, no problem, just define `col` in `tm_raster`.
* For the RGB to color procedure, I'll use the (r)gdal function `SGDF2PCT`. It creates a 256 color palette. I store the colors as factor levels (just as I did in `read_osm`).
* The tedious think about the whole raster/data management is whether to use `Raster` objects or `SpatialGridDataFrame`s. Raster contains much more methods, but the data is not as easy accessible as in `SpatialGridDataFrame`, especially thinks like factor levels. I already did have some workaround functions like `get_raster_data`. In `preprocess_shapes`, I split the shapes from the data, and store the raster shapes as `Raster` objects.
* `SGDF2PCT` only takes `SpatialGridDataFrames`. I also tried to apply `rgb` to the 3 bands, but it was much slower.

**Comment by mtennekes** [comment]
It's working d1f5f41. Large rasters, which are fromDisk, are processed slowly, especially compared to `plotRGB`. It takes some seconds to get the rgb data into memory, a second calculate colors, etc.

See my test script https://github.com/mtennekes/tmap/blob/master/test/test_raster.R.
If you have some time, please test this, and other raster objects. Feedback is welcome.

**Comment by marionowak** [comment]
cool, seems to be working for me:

and it's quicker than plotRGB()
```
> system.time({
   plotRGB(x)
})
       User      System verstrichen 
      3.142       0.469       3.667 
 
> system.time({
  print(qtm(x))
})
       User      System verstrichen 
      1.886       0.311       2.261 
> 
```

I tested this map here: [swissimage](http://www.toposhop.admin.ch/en/shop/products/images/ortho/swissimage25_1), aggregated with factor 10.

very nice!

**Comment by marionowak** [comment]
thanks again :-)

**Comment by ratnanil** [comment]
for the record, plotting a RasterBrick with RGB can be achieved with `tm_rbg()` (if `qtm()` is not an option).
