### ISSUE TITLE
Add arrows to plot?

### ISSUE THREAD

**Issue by forstem6** [mtennekes/tmap#574]
First of all, thank you for this great package. 
I am totally new to plotting geospatial data, but the package made it really easy to quickly get going.

I am however stuck at a specific point, where I am unsure whether it is ( or will soon be) possible in tmap.
I have a map with NUTS-3 regions and want to display movement between the regions with directional arrows. 
Is there any way I can accomplish this in tmap? 
I can plot the NUTS-3 map with sf functions and add curved arrows with the [curvedarrow() ](https://www.rdocumentation.org/packages/diagram/versions/1.6.5/topics/curvedarrow) function from the [diagram package ](https://www.rdocumentation.org/packages/diagram/versions/1.6.5). But with this I do not have the nice layer features of tmap.
AFAIK I cannot just add the curved arrows to the tmap plot. Any suggestions?

Thank you so much in advance.

**Comment by mtennekes** [comment]
If it will be included in tmap, it will be in the next major update, v4. In the meantime, there are a few options:

* https://github.com/mtennekes/odf
Contains a function to create curved arcs (unfortunately without arrow heads). These can be plotted with tmap. See its vignette: https://github.com/mtennekes/odf/blob/master/vignettes/od.Rmd
* @Robinlovelace created a similar package called `od`, which can also draw curved (?) arcs. See https://github.com/ITSLeeds/od
* What is the output of `curvedarrow()`? You may want to try to convert that to an `sf` object and plot it with `tmap`.
* Not curved arcs, but these new doughnut maps may be useful for your application: https://github.com/mtennekes/donutmaps

**Comment by forstem6** [comment]
Thank you so much, that is really helpful.
I looked at all the options and the donutmaps look promising.
(I however ran into an issue there, but I will post this in the repo of donutmap)
Thanks again.
