### ISSUE TITLE
Enable adding xlab and ylab to the figure frame

### ISSUE THREAD

**Issue by Martin-Jung** [mtennekes/tmap#58]
Just a minor thing, but I would like to write "_Longitude (°)_" and latitude respectively below/beside the frame of the following plot and I do not think that is possible currently.

```
library(tmap)
data(World)
tm_shape(World, projection="longlat") + 
  tm_grid(projection="longlat",n.x = 20, n.y = 20, labels.size = .5) +
  tm_polygons(col="#FFF8DC",alpha = .75,border.alpha = .25,border.col = "black") 
```

**Comment by mtennekes** [comment]
Working! See https://github.com/mtennekes/tmap/blob/master/examples/tm_lab.R
