### ISSUE TITLE
I cannot install v4

### ISSUE THREAD

**Issue by Nowosad** [mtennekes/tmap#591]
@mtennekes - I cannot install the v4 branch, getting the below message:

```
─  installing *source* package ‘tmap’ ...
   ** using staged installation
   ** R
   ** data
   ** demo
   ** inst
   ** byte-compile and prepare package for lazy loading
   Error in split(.tmap_pals$label, list(.tmap_pals$package, .tmap_pals$series)) : 
     object '.tmap_pals' not found
   Error: unable to load R code in package ‘tmap’
   Execution halted
   ERROR: lazy loading failed for package ‘tmap’
─  removing ‘/tmp/RtmpwVaInN/Rinst448ce25e9e0e4/tmap’
```

**Comment by mtennekes** [comment]
You should be able to install it now. If not, let me know.

I'm almost ready with the 'sneak peek' vignette (the rmd is inside the vignette folder).

**Comment by Nowosad** [comment]
@mtennekes One more thing to discuss - you use the new pipe operator. 
We also plan to use it for the second edition of geocompr, but it could be slightly to soon (in my opinion) to expect most users to have R version 4.1+. For example, I use Fedora 34 (the current version) which has R 4.0.5 available. 

I will test tmap v4 on my other Red Hat server with R 4.1 later today.
