### ISSUE TITLE
possibility of including an OSM layer

### ISSUE THREAD

**Issue by joelgombin** [mtennekes/tmap#6]

**Comment by mtennekes** [comment]
I played with osmar with some nice results:

![rplot](https://cloud.githubusercontent.com/assets/2444081/7357126/ecafc2fa-ed2c-11e4-8d7b-6c8925325ca8.png)

See [https://github.com/mtennekes/tmap/blob/master/test/test_osm.R]

We could try to integrate osmar into some a tm_osm layer function. Any ideas what parameters such a tm_osm function could/should have? From the code above, I could imagine something like this:

```R
tm_osm(poly="building", line=c("highway", "bus"), point="busstop", bb=my_bounding_box)
```
where bb is only required when there is no preceeding shape loaded with tm_shape. If poly, line or point is not specified, then all polygons, lines, points from OSM within the bounding box are drawn.

Any other suggestions are welcome. Also other routes to including an OSM layer.

**Comment by joelgombin** [comment]
Maybe it's better to have something similar to `read_shape`, maybe `get_osm` or something, that produces a regular `sp`object which can then be dealt with with regular `tmap` functions. Something like:

```r
buildings <- get_osm(mybbox, poly="building")
tm_shape(buildings) +
  tm_fill()
```
etc.

That way, the user has the maximal control over the way the shapes are rendered.

The function could also pull a raster through the `OpenStreetMap` package, maybe with a syntax like `get_osm(mybbox, raster = TRUE)` which could then be plotted using the usual raster functions. What do you think?

**Comment by mtennekes** [comment]
Fully agree with your first remark: it takes some time to query osm, and its better to put that in a separate function, like get_osm.

It's also nice to have a osm raster. Does an osm raster contain any data values, or just colors? In the latter case, those colors could be the first data column, so that 
```r
mymap <- get_osm(mybbox, raster=TRUE)
tm_shape(mymap) +
  tm_raster()
```
works.

**Comment by joelgombin** [comment]
I think it's just colors.

**Comment by joelgombin** [comment]
Actually not `get_osm`, `osmar` uses that. `fetch_osm`? ìmport_osm`?

**Comment by mtennekes** [comment]
or `read_osm` in line with `read_shape`  (although it may suggest some local osm file)

**Comment by mtennekes** [comment]
Your options are both fine, by the way.

**Comment by joelgombin** [comment]
Yeah I thaught of that too and had the same hesitation. Let's settle for that now, for the sake of consistency.

**Comment by mtennekes** [comment]
It's working. Of course the code is not frozen, so any suggestions or improvements are welcome.
I'm still struggling a bit with the dependencies of OpenStreetMap. Somehow it doesn't work without require statements.

**Comment by mtennekes** [comment]
OSM search query is working, as argument q of bb:

```{r}
data(land)
data(World)
tm_shape(land, bbox = bb(q="Canada", ext=1.2)) + tm_raster("trees") + qtm(World, fill = NULL)
```
Examples and docs to be updated.

**Comment by joelgombin** [comment]
\o/
