### ISSUE TITLE
[reproducibility] vignette code do not grey-out non-european countries

### ISSUE THREAD

**Issue by yipcma** [mtennekes/tmap#61]
a reproducibility issue:

`qtm(Europe, fill="well_being", text="iso_a3", text.size="AREA", root=5, fill.title="Well-Being Index", 
    fill.textNA="Non-European countries", 
    format="Europe", style="gray")`

produces 

![image](https://cloud.githubusercontent.com/assets/6114333/15646600/35919326-2667-11e6-9077-4014e2cc816d.png)

instead of the vignette image

![image](https://cloud.githubusercontent.com/assets/6114333/15646632/578265e6-2667-11e6-8367-63c57adb0a20.png)

**Comment by yipcma** [comment]
re-checked on latest version, all work as expected. closing this issue.

**Comment by mtennekes** [comment]
thanks for checking!
