### ISSUE TITLE
common legend for multiple variables of same unit in a rasterstack

### ISSUE THREAD

**Issue by yipcma** [mtennekes/tmap#62]
`library(tmap)`
`data(Europe)`
`tm_shape(Europe) +
    tm_polygons(c("pop_est_dens", "gdp_cap_est"), style="kmeans", 
        title=c("Population density", "GDP per capita")) +
tm_format_Europe() + 
tm_style_grey()`

Assume we have two variables of the same units (say, different seasonal values of temperature in a rasterstack), how should one specify a common legend at same scale instead of the automatic one legend each small multiple with its own legend?

Thanks.

**Comment by mtennekes** [comment]
`+ tm_facets(free.scales = FALSE)` should work

**Comment by yipcma** [comment]
Thank you @mtennekes, but how exactly to do so when `tm_facets` is not actually called? (the multiples are created by calling multiple variables in `tm_raster` or `tm_polygons`

**Comment by mtennekes** [comment]
You can call `tm_facets` just to set `free.scales=FALSE`, without specifying a `by` argument:

```
library(tmap)
data(Europe)
tm_shape(Europe) + tm_polygons(c("pop_est_dens", "gdp_cap_est"), style="kmeans", title=c("Population density", "GDP per capita")) + tm_format_Europe() + tm_style_grey() +
tm_facets(free.scales = FALSE)
```
