### ISSUE TITLE
Animation in tmap not showing variable name

### ISSUE THREAD

**Issue by Robinlovelace** [mtennekes/tmap#64]
The name of the variable does not change when `, free.scales = F` is set in the `tm_facets` function:

![animation_vnames](https://cloud.githubusercontent.com/assets/1825120/16077634/0243af08-32f2-11e6-8b45-ec1651b09699.gif)

Reproducible example:

```r
popvars = c("pop_est", "pop_est_dens", "gdp_md_est")
m <- tm_shape(Europe) + 
  tm_fill(popvars) + 
  tm_borders() + 
  tm_facets(nrow=1,ncol=1, free.scales = F)
animation_tmap(m, "animation_vnames.gif")
animation_tmap(m, "animation_vnames.gif")
```

**Comment by Robinlovelace** [comment]
Apologies, it does work, as shown in the updated map above!

**Comment by Robinlovelace** [comment]
Ah, found that the issue is linked to `free.scales`.

**Comment by Robinlovelace** [comment]
Another update: an easy work-around is to set the bins manually:

```r
b = quantile(Europe$pop_est, na.rm = T)
m <- tm_shape(Europe) + 
  tm_fill(popvars, breaks = b) + 
  tm_borders() + 
  tm_facets(nrow=1, ncol=1)
animation_tmap(m, "animation_vnames.gif")
```

![animation_vnames](https://cloud.githubusercontent.com/assets/1825120/16077895/7927da6c-32f3-11e6-8cea-440dbe9f5981.gif)

**Comment by Robinlovelace** [comment]
Same bug seems to apply with `legend.outside = T`

**Comment by mtennekes** [comment]
It's not a bug, but by design. When `free.scales=F`, it assumes that there is only one legend (for each aesthetic). This legend is therefore placed outside the map by default (argument `legend.outside` in `tm_layout`). It has nothing to do with the animation itself. You can see this when creating small multiples:

```
data(Europe)
popvars = c("pop_est", "pop_est_dens", "gdp_md_est")

tm_shape(Europe) + 
	tm_fill(popvars) + 
	tm_borders() + 
	tm_facets(free.scales = T)
```
![rplot09](https://cloud.githubusercontent.com/assets/2444081/16086698/c00ace9e-3320-11e6-964d-21759216234d.png)

```
tm_shape(Europe) + 
	tm_fill(popvars) + 
	tm_borders() + 
	tm_facets(free.scales = F)
```
![rplot10](https://cloud.githubusercontent.com/assets/2444081/16086720/cdcd28a6-3320-11e6-8142-325e83ae6e60.png)

For animations, when both `ncol` and `nrow` are 1, the legend is still placed outside the map by default, as in your opining post.

```
tm_shape(Europe) + 
	tm_fill(popvars) + 
	tm_borders() + 
	tm_facets(free.scales = T) +
	tm_layout(legend.outside = FALSE)
```
![rplot12](https://cloud.githubusercontent.com/assets/2444081/16087217/885b06a6-3322-11e6-8b81-5584a5a06fe0.png)

Let me know it this works as expected. If not, you can reopen the issue again.

**Comment by Robinlovelace** [comment]
Many thanks for the fast feedback - yes I see it's not a bug. My question, then, is how would one show the time variable iterate (1801, 1811, ..., 2001) while keeping the scale constant or placing the legend outside the mapping window? [Reproducible example](https://github.com/Robinlovelace/Creating-maps-in-R/blob/master/R/gganimate.R) I've been using to teach map animation methods:

```r
m = tm_shape(lnd) +
  tm_borders() +
  tm_fill(popvars, breaks = seq(0, 5e5, by = 1e5)) +
  tm_facets(ncol = 1, nrow = 1)
animation_tmap(m, filename = "figure/tmap_animation.gif", width=1200, delay=100)
```

**Comment by Robinlovelace** [comment]
This is the output:

![tmap_animation](https://cloud.githubusercontent.com/assets/1825120/16091294/f19d0648-332a-11e6-82b1-6837e190df7d.gif)

**Comment by Robinlovelace** [comment]
Further clarification: I'm not suggesting that the entire legend should change, only the legend title, as above.

**Comment by mtennekes** [comment]
It should be working now! I split the legend (one for each new page), and also the attributes, e.g. the credits:

```
m <- tm_shape(Europe) + 
	tm_fill(popvars) + 
	tm_borders() + 
	tm_facets(ncol=1,nrow=1) +
	tm_layout(legend.outside=T) + tm_credits(c("A", "B", "C"))

animation_tmap(m, filename = "test_animation.gif", delay=100)
```

![test_animation](https://cloud.githubusercontent.com/assets/2444081/16172278/aaf9ec94-3585-11e6-92df-8fef7732fc5c.gif)

**Comment by Robinlovelace** [comment]
Fantastic work sir. Thanks so much for taking the time to implement this fix - make **tmap** the best package the best available way to make animated maps (in addition to static maps). The results for London are below and they look awesome!

![tmap_animation](https://cloud.githubusercontent.com/assets/1825120/16174336/45a96cea-35b5-11e6-8c49-ec56e43c78f0.gif)
