### ISSUE TITLE
Formatting numbers in legends

### ISSUE THREAD

**Issue by rbubley** [mtennekes/tmap#67]
It would be nice to be able to format numbers in the legend more flexibly:
For example, I might want want "19% to 35%" instead of "0.19 to 0.35".

Perhaps this would best be accomplished by being able to pass in a formatting function?

**Comment by mtennekes** [comment]
Thanks for the great suggestion! It's implemented now:

```
data(World)

tm_shape(World) +
	tm_polygons(c("well_being"), legend.format=list(fun=function(x) paste0(formatC(x, digits=1, format="f"), "%")))

# legend.format can also be defined per small multiple:
tm_shape(World) +
	tm_fill(c("well_being", "life_exp"), legend.format=list(list(digits=3), list(fun=function(x) paste(x, "year"))))
```

Let me know if it works as expected.

**Comment by rbubley** [comment]
That's great. Thanks!
