### ISSUE TITLE
easier insets

### ISSUE THREAD

**Issue by joelgombin** [mtennekes/tmap#7]

**Comment by joelgombin** [comment]
I've tried using the viewports and it can indeed make nice things. The challenge though is to allow the reader to understand which parts are insetted (?) where (in the case when the insets are small parts of the larger map, e.g. zoom on cities), and possibly to label them.

**Comment by mtennekes** [comment]
For now, the reader has to create a new tmap to be insetted, and assign it to a viewport.
See [example](http://www.von-tijn.nl/tijn/research/presentations/tmap_user2015.pdf#17).

I agree that we could help the user. How would you like the output?

Maybe something like this, where I want an inset for the Benelux:

    tm_shape(World) + 
    tm_polygons("income_grp") +
    tm_inset(id="iso_a3", selection=c("NLD", "BEL", "LUX"), vp=myViewport)

**Comment by joelgombin** [comment]
Yep, someting along these lines, with maybe a sensible default value for `vp`.

**Comment by mtennekes** [comment]
Started a new branch for this. Not easy, especially regarding small multiples:-)

**Comment by timelyportfolio** [comment]
What about a case where we want to overlap two `tmap`, such as #24 with a different `SpatialPointsDataFrame` of points/symbols?

**Comment by joelgombin** [comment]
Things might have got easier thanks to https://github.com/riatelab/mapinsetr/ (I haven't tested it myself yet though).

**Comment by Nowosad** [comment]
Some new **tmap** ideas of adding inset maps are at https://github.com/mtennekes/tmap/issues/541 (WIP).
