### ISSUE TITLE
tm_layout() documentation

### ISSUE THREAD

**Issue by odelaigue** [mtennekes/tmap#70]
I've just seen 2 little mistakes in the tm_layout() documentation page

Details

Predefined styles:
>>tm_style_grey/_grey	 Grey background, useful to highlight sequential palettes (e.g. in choropleths)
tm_style_ **gray**/_grey	 Grey background, useful to highlight sequential palettes (e.g. in choropleths)

>> tm_style_albatross	 Inspired by latex beamer style cobalt
tm_style_albatross	 Inspired by latex beamer style **albatross**

**Comment by mtennekes** [comment]
tnx for reporting!
