### ISSUE TITLE
Changing the symbol of points

### ISSUE THREAD

**Issue by Geopsychty** [mtennekes/tmap#71]
Hi,

First, thanks for tmap, its the best package I've found for mapping in R so far. I was wondering if there are any plans to be able to change the marker symbol (such as using R base pch symbols).

The tm_dot function is great, and I can change the colours to demark different types of a variable (for example I'm plotting three different categories of buildings and would like to be able to show one type as dots, one as squares and one as triangles. I can't see that this is possible currently but apologies if I have missed it.

Thanks so much.
Rich

**Comment by mtennekes** [comment]
Thanks! This one is on top of my to do list. The plan I had is to create a base function for proportional symbols, which should serve not only tm_bubbles, tm_dots, but also tm_symbol, and tm_graph for small ggplot insets (see https://github.com/mtennekes/tmap/issues/52).

**Comment by Geopsychty** [comment]
That's great, i look forward to it!

**Comment by mtennekes** [comment]
Working, e.g.:

```
data(metro)
tm_shape(metro) +
	tm_symbols(size = "pop2010", col="pop2010", shape="pop2010") +
tm_layout(legend.outside = TRUE, legend.outside.position = "bottom", legend.stack = "horizontal")
```
