### ISSUE TITLE
Strange behaviour with read_osm

### ISSUE THREAD

**Issue by Robinlovelace** [mtennekes/tmap#72]
Not sure if this is a bug but I'm getting strange behaviour after entering this:

```r
library(tmap)
p = geocode_OSM("plaza mayor, sevilla")
p = SpatialPoints(matrix(p$coords, ncol = 2))
r1 = read_osm(x = p)
```

Please try to reproduce.

If you get a sensible response I'll try to find out what's wrong with my installation.

If you strange behaviour it may be worth exploring.

Hope this is useful and not a pain due to unconventional use of the `read_osm()`.

**Comment by mtennekes** [comment]
In the third code line, the projection is not set. However, you can just do this:

```
p <- geocode_OSM("plaza mayor, sevilla")
r1 <- read_osm(p$bbox)
```

Then, I get the error `Error in .local(x, y, ...) : extents do not overlap`. Is this what you get as well?

This works:

```
p < geocode_OSM("Sevilla")
r1 < read_osm(p$bbox)
qtm(r1)
````

Maybe, the error is caused by a bounding box that is too small.

**Comment by Robinlovelace** [comment]
Yes - as I suspected it wasn't really a bug but just my use of it.
Also, your creation of the following functionality is very useful:
```r
b = bb("plaza mayor, sevilla", ext = 20)
```
Thanks for the fast response.
