### ISSUE TITLE
Error in tmap using continuous scale?

### ISSUE THREAD

**Issue by oharac** [mtennekes/tmap#74]
Hi,

I am working with the tmap package and encountered an error that I cannot figure out...

I created a basic map using a SpatialPolygonsDataFrame object, and all seemed well.  Then I changed the `style` in the `tm_polygons()` function to be `style = 'cont'` and got this error (and no map):

```
Error in seq.default(i - floor(id_step/2), i + ceiling(id_step/2), length.out = 11) :
  'from' cannot be NA, NaN or infinite
```

It seems like it might be coming from the num2pal function (https://github.com/mtennekes/tmap/blob/master/pkg/R/num2pal.R#L178) but not totally sure.

Using the World data from `tmap`, I created a small subset to work with; it works fine with sample code from the `tm_polygons` manual page, acting on the "HPI" variable within the World dataframe.

```
### Load package and data; truncate to a small subset for easy manipulation
library(tmap)
data(World)

World1 <- World[1:10, ]

### Sample code from tmap package: this chunk is what I have modified for testing
# tm_shape(World1) +
#   tm_polygons("HPI",
#               palette="RdYlGn",
#               style="cont",
#               auto.palette.mapping=FALSE,
#               title="Happy Planet Index")
### Works with built-in data:
# World1@data$HPI
# [1] 36.75366 33.20143 54.05118 31.77827 54.05504 46.00319       NA       NA 41.97981 47.08514
```

Next I created a new column with data from my own dataset, and modified the `tm_polygons` call to use the new "score" variable instead of "HPI" - and I get an error.

```
### Try it with my own data and get an error
World1@data$score <- c(NA, 20, 27, NA, 20, 20, NA, NA, 70, 70)

tm_shape(World1) +
  tm_polygons("score",
              palette="RdYlGn",
              style="cont",
              auto.palette.mapping = FALSE,
              title="tmap continuous variable")
# Error in seq.default(i - floor(id_step/2), i + ceiling(id_step/2), length.out = 11) :
#   'from' cannot be NA, NaN or infinite
```

Here are a few hypotheses I tested:

```
### Hypothesis: something weird with my own data?
### try random numbers:
# World1@data$score <- round(runif(10) * 100)
World1@data$score <- c(66, 67, 65, 89, 21, 66, 49, 72, 73, 26)
### (then run the above lines with this new set of "score" values)
### Not a problem with these particular numbers, though I did get the
### error one time with a randomly generated dataset as well.

### Hypothesis: NAs are causing the problem?
### assign a few NAs to the random scores
World1@data$score <- c(NA, 67, 65, 89, NA, 66, 49, NA, 73, 26)
### NAs don't seem to be a problem...

### Hypothesis: Too few unique values?
### overwrite some scores to be same as other existing scores
World1@data$score <- c(66, 66, 26, 49, 26, 66, 49, 72, 72, 26)
length(unique(World1@data$score))
### Only 4 unique values, still doesn't seem to be a problem.

### Try some other permutations?
World1@data$score <- rep(1:3, times = 4, length.out = 10)
# [1] 1 2 3 1 2 3 1 2 3 1
# Error in seq.default(i - floor(id_step/2), i + ceiling(id_step/2), length.out = 11) :
#   'from' cannot be NA, NaN or infinite
```

Thanks for considering it, and helping me figure it out.

**Comment by mtennekes** [comment]
Solved! Thanks for finding this bug, and for the testing.

**Comment by oharac** [comment]
sweet, thanks - I appreciate the super fast fix.  It seems to work fine on
my end too.  I presume it's not updated on CRAN yet?  (I used
devtools::install_github)




~~
Casey O'Hara
Project Scientist, Ocean Health Index <http://www.oceanhealthindex.org>
National Center for Ecological Analysis and Synthesis
<http://www.nceas.ucsb.edu>
735 State Street, Suite 300, Santa Barbara  CA  93101
