### ISSUE TITLE
Not clear how to add facet titles

### ISSUE THREAD

**Issue by Robinlovelace** [mtennekes/tmap#76]
Not sure if this is an issue of documentation or code, but it seems tricky to add titles to each facet of a plot with a common legend: all the 'title' arguments seem to be consumed by the legend title, not the title of the plotting panel used by each facet.

Reproducible example building on https://github.com/mtennekes/tmap/blob/master/examples/tm_facets.R : 

```r
tm_shape(Europe) +
  tm_polygons(c("well_being", "life_exp")) +
  tm_layout(legend.outside = T)
```
I tried various solutions including the following but none seem to work and I don't think the solution (if there is one) is well documented. The resulting image is pasted below - not what I was expecting!

```r
tm_shape(Europe) +
  tm_polygons(c("well_being", "life_exp")) +
  tm_layout(legend.outside = T, title = c("well_being", "life_exp"))
```
![facet-title](https://cloud.githubusercontent.com/assets/1825120/19264693/a6cac972-8f99-11e6-9585-65f5bac32961.png)

Thanks for an amazing package in any case. You may be interested in my description of it for a workshop at the eRum conference - any feedback on its accuracy/usefulness appreciate here: https://github.com/Robinlovelace/Creating-maps-in-R/blob/master/vignettes/vspd-base-shiny.Rmd if you have a free moment.

Robin

**Comment by mtennekes** [comment]
Should be working now! 

I like this one better:

```
tm_shape(Europe) +
	tm_polygons(c("well_being", "life_exp"), title="") +
	tm_layout(panel.show = TRUE,
			  panel.labels = c("well_being", "life_exp"),
			  legend.outside = T)
```

although the map is not correct since the second multiple has other classes (thank god the life expectancy of European countries is not in the range 4-8;-))

I'll take a look at your tutorial (and post a link on the homepage of this repo).

**Comment by Robinlovelace** [comment]
Thanks - I think an example made possible by your fix may go into the tutorial, just in time for its delivery tomorrow!
