### ISSUE TITLE
Add logos?

### ISSUE THREAD

**Issue by mbacou** [mtennekes/tmap#77]
Hi,
I need to recreate a large series of maps as below, and wondering if there's an easy way to add the logos in the lower right corner?

![map](http://spam05.harvestchoice.org/v2r0/png/harvested-area/spam2005v2r0_harvested-area_banana_total.png)

**Comment by mtennekes** [comment]
It's possible now! Thanks for the good suggestion. Could you test it and tell me if it works as expected?
This will be the last new feature of version 1.6, which will be send to CRAN soon.

**Comment by mbacou** [comment]
Martijn,
Thanks a million for implementing `tm_logo()` so quickly! Seems to work well -- however I'm struggling trying to place the legend below the map but above the other credits elements as in the example above. Also would like to stretch the legend to the width of the inner frame, but that seems hard as well!

My current code looks like:

```r
    m <- tm_shape(World) +
    tm_fill("white", border.col="grey70", lwd=.2) +

    tm_grid(n.x=7, n.y=6, projection="longlat", lwd=.2, col="grey70",
      labels.col="grey50", labels.size=.5) +

    tm_shape(r, is.master=T, projection="eck4") +
    tm_raster(n=8, style="cont", palette="YlOrRd", title="", legend.is.portrait=F, legend.z=0) +

    tm_shape(World) +
    tm_borders("grey70", lwd=.2) +

    tm_credits(str_wrap(vi[var, varDesc], 100), size=.6, position=c("center", "top")) +
    tm_credits(str_wrap(vi[var, citation], 60), size=.5, position=c("left", "bottom")) +
    tm_logo("./SPAM/aux/logo.png", height=2,
      position=c("RIGHT", "bottom"), margin=0, just=c("RIGHT", "top")) +

    tm_layout(
      title=vi[var, varTitle],
      title.size=1,
      title.snap.to.legend=T,
      bg.color="#AEDFE5",
      outer.bg.color="white",
      earth.boundary=c(-180, 180, -90, 90),
      earth.boundary.color="grey70",
      earth.boundary.lwd=.4,
      #earth.datum="eck4",
      space.color="white",
      frame=F,
      #legend.position=c("center", "top"),
      legend.width=-1,
      legend.outside=T,
      legend.outside.position="top",
      #legend.outside.size=1,
      legend.text.size=.6,
      attr.outside=T)

  save_tmap(m,
    paste0("./SPAM/2005v3r0/png/SPAM2005v3r0-", var, ".png"),
    width=6, height=4.5, units="in", dpi=600)
```

![file_show](https://cloud.githubusercontent.com/assets/260325/19881345/4ab24e60-9fdb-11e6-848e-de5592d47119.png)

**Comment by mtennekes** [comment]
One option would be to increase the inner margins:

```{r}
data(World)
tm_shape(World) +
	tm_polygons("HPI", palette="RdYlGn", auto.palette.mapping=FALSE, legend.is.portrait=FALSE, title="", style="cont") +
	tm_logo(rep(system.file("img/tmap.png", package="tmap"), 3), position=c("right", "bottom")) +
	tm_credits("Credits", position=c("left", "bottom"), size = 1) +
	tm_grid(x=seq(-160,160, by=20), y=seq(-80, 80, by=20), projection="longlat", lwd=.2, col="grey70",
			labels.col="grey50", labels.size=0) +
	tm_style_natural() +
	tm_legend(width=.9,
			  position=c("center", .25),
			  frame=FALSE,
			  bg.color="white") +
	tm_layout(title="Title", inner.margins=c(.4, .05, .15, .05))
```

which results in 
![x](https://cloud.githubusercontent.com/assets/2444081/19906372/cc8563a6-a07a-11e6-885c-dd47b7ebfa32.png)

One downside is that the grid labels are placed tight to the frame, so in this case below the credits and logo. Therefore, I ignored them with `labels.size=0`.

Another option is to set both `legend.outside.position` and `attr.outside.position` to `bottom`. However, I found that that this does not work very well yet.

**Comment by mtennekes** [comment]
To stretch the legend across the full width of the map is indeed not easy. `legend.width` only defines the maximum width (you can see this with `design.mode` enabled). The legend is designed such that all labels and legend items (color boxes etc) fit well. So if you really want, you could stretch the legend with wide labels (i.e. that contain white space).

**Comment by mbacou** [comment]
OK I see, will try that hack for the legend width, and also try a different layout placing legend and histogram over the map instead. Else re-use the python code that produced the original...

**Comment by mbacou** [comment]
I had to simplify the layout quite a bit, but think it's "acceptable". I could stretch the legend in horizontal mode using `legend.format=list(fun=function(x) str_pad(prettyNum(x, big.mark=","), 10))` but could not place it adequately below the map.

```r
m <- tm_shape(World) +
    tm_fill("white", border.col="grey70", lwd=.2) +
    tm_grid(n.x=7, n.y=6, projection="longlat", lwd=.1, col="grey70", labels.size=0) +
    tm_shape(r, is.master=T, projection="eck4") +
    tm_raster(title=vi[var, paste(unit, 2005, sep=", ")], n=9, style="cont", palette="YlOrRd") +
    tm_shape(World) + tm_borders("grey70", lwd=.2) +

    tm_credits(str_wrap(vi[var, varDesc], 80),
      position=c(.5, 1.04), just=c("center", "top"), size=.55) +
    tm_logo("./SPAM/aux/logo.png", height=2,
      position=c(.5, .5), just=c("center", "center")) +
    tm_credits(str_wrap(vi[var, citation], 116),
      position=c(.5, .08), just=c("center", "bottom"), size=.45) +

    tm_layout(
      title=vi[var, varTitle],
      title.size=.7,
      title.snap.to.legend=F,
      title.position=c("center", "top"),
      bg.color="#AEDFE5",
      outer.bg.color="white",
      earth.boundary=c(-180, 180, -70, 90),
      earth.boundary.color="white",
      earth.boundary.lwd=.4,
      space.color="white",
      frame=F,
      legend.position=c(.1, .2),
      legend.text.size=.45,
      legend.title.size=.6,
      attr.outside=T,
      attr.color="grey20",
      legend.text.color="grey40",
      inner.margins=c(.04, .01, .08, .01),
      outer.margins=c(0, 0, 0, 0),
      asp=6/3.3)

  save_tmap(m, file, width=6, height=4, units="in", dpi=600)

```
![file_show](https://cloud.githubusercontent.com/assets/260325/19918206/c4d88870-a09f-11e6-80c0-dd7cbee3e807.png)

**Comment by mtennekes** [comment]
NIce!

FYI, the second option is also available now, i.e. to place both legend and attributes below the map frame. The order can be determined with upper case letters for attr.outside.position:

```{r}
data(World)
tm_shape(World) +
	tm_polygons("HPI", palette="RdYlGn", auto.palette.mapping=FALSE, legend.is.portrait=FALSE, title="", style="cont") +
	tm_logo(rep(system.file("img/tmap.png", package="tmap"), 3), position=c("right", "bottom")) +
	tm_credits("Credits", position=c("left", "bottom"), size = 1) +
	tm_grid(x=seq(-160,160, by=20), y=seq(-80, 80, by=20), projection="longlat", lwd=.2, col="grey70",
			labels.col="grey50", labels.size=.5) +
	tm_style_natural() +
	tm_legend(width=.9,
			  position=c("center", .25),
			  frame=FALSE,
			  bg.color="white") +
	tm_layout(title="Title", 
			  inner.margins=c(.05, .05, .15, .05),
			  legend.outside = TRUE,
			  legend.outside.position = "bottom",
			  legend.outside.size=.15,
			  attr.outside = TRUE,
			  attr.outside.position = "BOTTOM",
			  attr.outside.size=.15)
```

**Comment by mbacou** [comment]
Reopening this thread as I'm really struggling positioning annotations and logos. Would it be feasible to pass numeric values to `tm_logo()` and `tm_credits()` `position=c(x, y)` argument that are all relative to the map frame's lower left corner, with possible `x, y` values between `-1, 1` (negative values would position elements outside the frame, and positive inside the frame) all relative to the frame's height and width -- instead of the current combination of `*.outside.position` and `position`?

**Comment by mtennekes** [comment]
Thanks for the suggestion, but it doesn't work like that since outside legend /attributes are placed in extra viewports. I've made a demo script https://github.com/mtennekes/tmap/blob/master/demo/legend_and_attributes_placement.R which explains this. If you still have a particular question about the placement of logos (and other attributes), could you provide a working example?
