### ISSUE TITLE
inconsistent legend behaviour

### ISSUE THREAD

**Issue by joelgombin** [mtennekes/tmap#8]
Whether subtitles are used in the legend is not completely consistent. 

Compare:

```r
data(World)

rivers$constant <- factor("Rivers")
tm_shape(World) +
    tm_fill() +
tm_shape(rivers) +
    tm_lines(col="constant", palette="dodgerblue3") +
tm_layout_World("World map")
```

and 

```r
rivers$constant <- factor("Rivers")
tm_shape(World) +
    tm_fill() +
tm_shape(rivers) +
    tm_lines(col="constant", palette="dodgerblue3") 
```

Maybe this is desired, but it can actually become a problem when there is more than one legend item:

```r
data(cities)
cities$constant <- factor("Cities")

tm_shape(World) +
    tm_fill() +
tm_shape(rivers) +
    tm_lines(col="constant", palette="dodgerblue3") +
tm_shape(cities) +
    tm_bubbles(size=1, col = "constant") +
tm_layout("A map")
```

**Comment by mtennekes** [comment]
This was indeed desired, but I'm open to change it if it's counter intuitive.
The background idea is that the main title replaces the title of the first legend element.

In this example, the main title is set to the fill variable, "pop_est_dens":
    tm_shape(World) + tm_fill("pop_est_dens") + tm_bubbles("gdp_md_est", col = "economy")

Now, the main title is specified:
    tm_shape(World) + tm_fill("pop_est_dens") + tm_bubbles("gdp_md_est", col = "economy") +
    tm_layout("Main title")

Now the main title is specified, as well as the legend title for fill: 
    tm_shape(World) + tm_fill("pop_est_dens") + tm_bubbles("gdp_md_est", col = "economy") +
    tm_layout("Main title", legend.titles=c(fill="population density"))

**Comment by mtennekes** [comment]
A problem may arise when multiple legend items will be supported [https://github.com/mtennekes/tmap/issues/2]

The reason for this behavior was that most thematic maps will probably have only one legend element. For that element, it's overkill to have two titles (a main title and a legend title).

A logical improvement could be that a legend title is only overruled by the main title if there is one legend element.

**Comment by joelgombin** [comment]
OK, I didn't see there a `legend.titles` argument, my bad!

**Comment by mtennekes** [comment]
Still a useful issue!

I'll change it to make it more intuitive: in the next update, there will be a title argument for each aesthetic in each layer, and maybe other legend options as well. Only layout settings that are not legend-item-specific will be processed in tm_layout.

**Comment by mtennekes** [comment]
Just started a "legends" branch for this.

**Comment by mtennekes** [comment]
Done! Legend titles are now specified inside the layer functions, and the main title in tm_layout.
