### ISSUE TITLE
Data variable contains color values - not working?

### ISSUE THREAD

**Issue by marionowak** [mtennekes/tmap#80]
I have a SpatialPolygonsDataFrame with columns containing hex-color values. 
I want to draw them like this:
tm_shape(full.shp) + tm_fill(col="konf1900")
But then it is treated as categorial variable, resulting in this:
![screenshot 2016-11-01 10 15 53](https://cloud.githubusercontent.com/assets/9657746/19884917/4031df96-a01c-11e6-86dd-63e8f41c1706.png)
I am not sure how to tell tmap that it should plot the color values directly on the map...

Can anyone help on this?

Thanks a lot

**Comment by sjewo** [comment]
Hi,
is your color vector an factor? 
Try this:
```
full.shp$konf1900char <- as.character(full.shp$konf1900)
tm_shape(full.shp) + tm_fill(col="konf1900char")
```

**Comment by marionowak** [comment]
wow, thanks a lot, that was the problem!
it is also important not have any NA values in the column.
