### ISSUE TITLE
Update to 'Crimes in London' demo

### ISSUE THREAD

**Issue by keevee09** [mtennekes/tmap#81]
Applies to demo code at:

https://github.com/mtennekes/tmap/blob/master/demo/crimes_in_Greater_London.R

To get the code to run I made two small changes:

* changed

```R
crimes <- rbind(read.csv(file.path(tmpdir, "2015-10-city-of-london-street.csv")),
```

to

```R
crimes <- rbind(read.csv(file.path(tmpdir, "2016-08/2016-08-city-of-london-street.csv")),
```

specifically, updated to latest data and found that `unzip` placed the data into a sub-folder `2016-08/` rather than in the root of the `tmpdir` directory.

The `crime_densities$dasy` doesn't exist so changed

```R
tm_shape(crime_densities$dasy) +
```

to

```R
tm_shape(crime_densities$polygons) +
```

Here is a gist link to my edit: [crimes_in_Greater_London.R](https://gist.github.com/keevee09/99de7f541e13407e46d1094f99610fd9)

**Comment by mtennekes** [comment]
Thanks for noticing! I have made some other updates in that example as well. It will probably also appear in a JSS paper (currently in review). Therefore, I have not updated the data itself.
