### ISSUE TITLE
border color of bubbles not working (yields black border)

### ISSUE THREAD

**Issue by mapMakingActuary** [mtennekes/tmap#82]
border color variable seems to have stopped working for bubbles -  I haven't tested it on other symbols.   

data(metro)
t <- tm_shape(metro)+tm_bubbles(border.col = "red")

t$tm_symbols$border.col
[1] "black"

Thanks for the build/maintenance of the package!
-Pete

**Comment by mtennekes** [comment]
Tnx for the bug report!
