### ISSUE TITLE
Adding Polylines from JSON to map

### ISSUE THREAD

**Issue by methodds** [mtennekes/tmap#86]
Hi,

first of all thanks for creating this nice package! =) With the help of your vignette I managed to draw a map of German federal states filled with observation data from another dataset. In addition, I need to add several polylines to the map which I have stored in a [JSON-file](https://www.dropbox.com/s/unnqsrgw9dmciz7/polyroutes.json?dl=1). These polylines are autobahn routes between several cities.
Is there an easy way to directly read the polylines from this file and plot it with ``tm_lines()``? I did not manage to read the file with ``rgdal``. The keys in the JSON-file are not related to variables in  the federal states dataframe.

**Comment by methodds** [comment]
Just for clarification my code at the moment looks like this:

```
library(rgdal)
library(readxl)
library(tmap)

states <- read_excel('states_events.xlsx')
geo <- jsonlite::fromJSON("3_mittel.geojson", FALSE)

main <- readOGR("3_mittel.geojson", "OGRGeoJSON")
main <- append_data(main, states)
tm_shape(test) +  tm_borders() + tm_fill('Observations')
```
which produces the following map on which I want to draw the polylines:

![image](https://cloud.githubusercontent.com/assets/7460499/20237727/daf38b8a-a8da-11e6-96e0-54b3ef669531.png)

**Comment by mtennekes** [comment]
For lines, a SpatialLines(DataFrame) object is required. Maybe it's possible to convert geojson with the `geojsonio` package?
