### ISSUE TITLE
Does tmap know the units of area?

### ISSUE THREAD

**Issue by edzer** [mtennekes/tmap#91]
In your [example](http://von-tijn.nl/tijn/research/presentations/tmap_user2015.pdf) you plot units of density with unit km-2, for data that (I believe) have coordinates in m. Does `convert2density` make hard assumptions, and does it check for the CRS? 

I'm interested because `sf::st_area` now returns values with units attached when the CRS was set; these can be m^2, feet^2 or US feet^2, and follow from the CRS. For long/lat data, it uses geosphere::areaPolygon with the ellipsoid parameters of the CRS used.

**Comment by mtennekes** [comment]
Yes, it makes the assumption that the projected coordinates are in meters, and that the projection has the equal-area property. For long-lat data (or when CRS is missing), is throws a warning that areas cannot be determined.

Good to hear that it is possible to obtain 'real' areas values. It will certainly be useful for tmap. How to you cope with a CRS without equal-area property?

**Comment by edzer** [comment]
Good point: they are simply wrong, but at least wrong in the right units! We now assume the user understands the consequences of working with a particular CRS.

**Comment by mtennekes** [comment]
Just to be a little more precise how it is done in `tmap`: the units can be specified (argument `unit`), and the number of coordinate points per unit (`unit.size`). By default these are set to `km2` and `1000` meaning that the assumption is made that the CRS is in meters and the desired densities are in `km2`. It is certainly a good idea to get this information directly from the CRS, and to inform the users to be careful with areas.

**Comment by mtennekes** [comment]
Not relevant anymore, since `tmap` and `tmaptools` will soon rely on `units` and functions like `st_area`
