### ISSUE TITLE
Invert order of legend items in tm_raster

### ISSUE THREAD

**Issue by jlehtoma** [mtennekes/tmap#97]
Is there currently a way to invert the order of legend items in `tm_raster`? For example, following the example fro [tmap in a nutshell](https://cran.r-project.org/web/packages/tmap/vignettes/tmap-nutshell.html):

```r
data(land)
tm_shape(land, projection="eck4") +
  tm_raster("elevation", breaks=c(-Inf, 250, 500, 1000, 1500, 2000, 2500, 3000, 4000, Inf),  
            palette = terrain.colors(9), title="Elevation", auto.palette.mapping=FALSE) +
  tm_shape(World) +
  tm_borders("grey20") +
  tm_style_white(legend.position = c("left", "center"))
```

produces the following map

![world_elev](https://cloud.githubusercontent.com/assets/525495/22065921/b2899aba-dd8a-11e6-9d28-e6f59448b2f0.png)

What I would like to have is the same thing, but with a legend with an inverted order of items (most labels omitted here):

![world_elev_invert](https://cloud.githubusercontent.com/assets/525495/22065940/ce9ce874-dd8a-11e6-96fd-a483623e1ce8.png)

**Comment by mtennekes** [comment]
You can do this by manually creating the levels:

    land$elevation_cat <- cut(land$elevation, breaks=c(-Inf, 250, 500, 1000, 1500, 2000, 2500, 3000, 4000, Inf))
    land$elevation_cat <- factor(land$elevation_cat, levels = rev(levels(land$elevation_cat)))

    tm_shape(land, projection="eck4") +
	tm_raster("elevation_cat",  
			  palette = rev(terrain.colors(9)), title="Elevation", auto.palette.mapping=FALSE) +
	tm_shape(World) +
	tm_borders("grey20") +
	tm_style_white(legend.position = c("left", "center"))

There is no other way to do this, yet. However, it should easy to implement. Do you have any idea how a user should be able to specify this, preferably without having to introduce another argument like `reverse.legend`?

**Comment by jlehtoma** [comment]
Thanks, the manually level creation should do the trick!

> There is no other way to do this, yet. However, it should easy to implement. Do you have any idea how a user should be able to specify this, preferably without having to introduce another argument like reverse.legend?

Additional argument to e.g. `tm_layout` (and thus `tm_legend`) *would* have been my first suggestion. If that's not preferable, I don't have any great ideas for now.

**Comment by mtennekes** [comment]
Thanks for the suggestion. I think it would make more sense to set this in the layer function, since it should be layer/aesthetic-specific, like `legend.is.portrait`. Maybe something like `legend.reverse`?

I think I leave this for now, unless there is more demand for this feature.

**Comment by yipcma** [comment]
legend.is.portrait = F gives error in tm_raster.

**Comment by jlehtoma** [comment]
@yipcma : AFAIK, this was never implemented. Hence the error.

**Comment by johnbaums** [comment]
A vertically flipped (portrait) legend would be a vast improvement for continuous rasters (assuming we don't want to bin values), since for these we definitely expect low values at the bottom of the legend.

fwiw I have a hacky, relatively untested workaround as a gist, [here](https://gist.github.com/johnbaums/77a3a838d309d0356a8d2cba7f5de69f).

```R
 flip_legend <- function(m) {
    # m: a `mapview` or `leaflet` object
    if(methods::is(m, 'mapview')) {
      calls <- methods::slot(m, 'map')$x$calls
    } else if((methods::is(m, 'leaflet'))) {
      calls <- m$x$calls
    } else {
      stop('m must be a mapview or leaflet object.')    
    }
    i <- grep('addLegend', sapply(calls, '[[', 'method'))
    clr <- calls[[i]]$args[[1]]$colors
    h <- strsplit(gsub('(#\\S+)[^#]+', '\\1 ', clr), ' ')[[1]]
    p <- paste0(rev(
      100 - as.numeric(strsplit(gsub('#\\S+[ ,]+|%', '', clr), ', ')[[1]])
    ), '%')
    clr2 <- paste0(do.call(paste, list(rev(h), c('', p, ''))), collapse=', ')
    calls[[i]]$args[[1]]$colors <- clr2
    calls[[i]]$args[[1]]$labels <- rev(calls[[i]]$args[[1]]$labels)
    extra <- calls[[i]]$args[[1]]$extra 
    calls[[i]]$args[[1]]$extra$p_1 <- 1 - extra$p_n
    calls[[i]]$args[[1]]$extra$p_n <- 1 - extra$p_1
    if(methods::is(m, 'mapview')) {
      methods::slot(m, 'map')$x$calls <- calls
    } else if((methods::is(m, 'leaflet'))) {
      m$x$calls <- calls
    }
    m
  }
```

**Comment by johnbaums** [comment]
... although [this](https://stackoverflow.com/a/56334156/489704) also seems to work.
